### ISSUE TITLE
Settings defaultZoneName doesn't seem to apply.

### ISSUE THREAD

**Issue by AdamBlade** [moment/luxon#1003]
DefaultZoneNome doesn't seem to apply new timezone to new instances of DateTime.

I'm building an angular application in which I want the user to specify his timezone and apply that zone across the app for all the dates.
For example in my main component

```
import { Settings } from 'luxon';
 export class AppComponent {
  constructor() {
    Settings.defaultZoneName = "Europe/Paris";
  }

 testZone() {
   console.log(DateTime.now()); // It should be 1h behind my current time. I've also tried with dates imported from the database and it doesn't apply.
  console.log(DateTime.now().setZone('Europe/Paris')); //This displays how I expected the above statement to work.
}
}


```
I was expecting it to apply the new timezone and not use my local timezone. I'm sorry if I'm missing something obvious but I couldn't find a clear answer.

- OS: Windows 10
- Browser Chome Version 92.0.4515.131
- Angular 11
- Luxon version [e.g. 2.0.1]
- Your timezone [e.g. "Europe/Bucharest"]

**Comment by dasa** [comment]
Try `Settings.defaultZone = "Europe/Paris";`. This is a 2.0 breaking change: https://moment.github.io/luxon/#/upgrading?id=default-zone

**Comment by AdamBlade** [comment]
I've tried that but Typescript says it's readonly.

**Comment by dasa** [comment]
The types are still for 1.x. The 2.0 version is pending at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54595

**Comment by icambron** [comment]
Thanks @dasa. I've updated the upgrade guide to clarify this a bit more
