### ISSUE TITLE
ETC timezones are converted to fixed timezone

### ISSUE THREAD

**Issue by KurtGokhan** [moment/luxon#1007]
**Describe the bug**
When a timezone like `Etc/GMT-3` is passed to luxon, it is detected as a fixed timezone. This is practically fine until you want to take the timezone name from luxon and pass it to somewhere which accepts only IANA timezones.

**To Reproduce**
`luxon.DateTime.local().setZone('Etc/GMT+3').zone.name`

**Actual vs Expected behavior**
The above code outputs `UTC-3` while `Etc/GMT+3` was excepted.

**Desktop (please complete the following information):**

- OS: All OS
- Browser: All browsers & Node
- Luxon version: 2.0.2
- Your timezone: "Europe/Istanbul"

**Additional context**

I know there are workarounds but it seems illogical to me that luxon takes in a standard timezone and outputs a non-standard timezone. Even native JS does not accept the `UTC+` format. 

![image](https://user-images.githubusercontent.com/6034931/129328867-192fccf1-94b9-43a5-b080-282a91d1ee17.png)

**Comment by ties-s** [comment]
This does what you want:

`luxon.DateTime.local().setZone(luxon.IANAZone.create('Etc/GMT+3')).zone.name`

**Comment by KurtGokhan** [comment]
Thanks, I did not know that. I will try it when I have a chance.

**Comment by icambron** [comment]
I was able to determine that these zone identifiers now work everywhere, including Node 12+. Fixed in 7eca41f2 and will go into Luxon 2.1
