### ISSUE TITLE
dur.toString()

### ISSUE THREAD

**Issue by zeroprofit** [moment/luxon#1011]
Hi,

const dur = Duration.fromObject({milliseconds: 384 * 1000});
console.log(dur.toString())  //  PT384S

I was expecting '00:06:25.8' or '6m 25s 800ms'.  It is odd to produce "PT384S".  Not friendly at all.  If we cannot change toString().  Can we add a toStringFriendly() to produce output like '00:06:25.8' or '6m 25s 800ms'?

**Comment by icambron** [comment]
It's not odd at all; it's an ISO 8601 duration string. Using that as the `toString` is consistent with DateTime's behavior, and avoids creating an ad hoc duration format. Remember that durations can also contain weeks, months, and so on, so the specific formats you suggested aren't great anyway.

You might be interested in `toObject` which provides an output more along the lines of what you expect
