### ISSUE TITLE
Can't create datetime object in Safari Technology Preview

### ISSUE THREAD

**Issue by ceviche-lyres** [moment/luxon#1013]
**Describe the bug**
After downloading luxon.js, and inserting "<script src="luxon.js"></script>" into my html code, I try to create a date time using: var mydate = DateTime.local();

I get the following error in javascript console: 
Cannot load file://null/Users/xxxx/luxon.js.map due to access control checks.

I have other .js files linked in my html code and they work.

**To Reproduce**
<html>
<head>
<script src="luxon.js"></script>
<script>
var mydate = DateTime.local();
</script>
</head><body/></html>

The luxon.js file is stored in the same directory as the test file above.

**Actual vs Expected behavior**
I expected to get a luxon date time object.

**Desktop (please complete the following information):**

- OS: mac os 12.0 beta
- Browser [Safari Technology Preview: Release 130 (Safari 15.0, WebKit 17612.1.26.1.5)]
- Luxon version [e.g. downloaded from website 20/8/2021]

**Additional context**

**Comment by dasa** [comment]
Deleting `//# sourceMappingURL=luxon.js.map` from `luxon.js` might be a workaround.

**Comment by ceviche-lyres** [comment]
Thanks for the reply. 
No it didn't work. Now the error is "ReferenceError: Can't find variable: DateTime".
I edited the luxon.js file directly to make sure that the browser is seeing it - and it can. For example, if I create a test() function in luxon.js (function test(){alert("hello");}), I can access it with no problem from my HTML file.

e.g.,: <html>
<head>
<script src="luxon.js"></script>
<script>
	 test();
	 var mydate = DateTime.local(); 
</script>
</head><body/></html>

Shows my alert message, but then gives the error above.

**Comment by dasa** [comment]
Try `luxon.DateTime.local()`

See: https://moment.github.io/luxon/#/install?id=basic-browser-setup

**Comment by ceviche-lyres** [comment]
Thanks very much - that does work. I put the line "//# sourceMappingURL=luxon.js.map" back into luxon.js, and using "luxon.DateTime.local()" - I still get a datetime object - (along with the error above) - so the error I was receiving above was not the cause of the problem.
Finally, thanks for the link to "https://moment.github.io/luxon/#/install?id=basic-browser-setup" - I was using that and it doesn't reference luxon.DateTime.local(). 

Thanks again and would you like me to close this report?

**Comment by dasa** [comment]
> Thanks again and would you like me to close this report?

If you'd like, but this might be good feedback to the repo owners.

**Comment by ceviche-lyres** [comment]
I'll leave it for them then. Thanks very much dasa.

**Comment by icambron** [comment]
Yeah, Luxon is creating the fewest globals it can, so everything is added to the `luxon` global. It certainly makes usage a little less consistent, which I don't love, but I also don't want to create a zillion globals, so I'm going to leave this as-is.

I do think this is reasonably well documented, though of course I'd accept documentation enhancements that prevent this confusion.
