### ISSUE TITLE
Duration.fromMillis doesn't work

### ISSUE THREAD

**Issue by Aloso** [moment/luxon#1014]
`Duration.fromMillis(1800000)` creates a Duration object `{ milliseconds: 1800000 }`, but it should be `{ minutes: 30 }`:

```js
const duration = Duration.fromMillis(1800000)

console.log(duration.milliseconds) // 1800000
console.log(duration.seconds)      // 0
console.log(duration.minutes)      // 0
```

- OS: Manjaro Linux
- Browser: Firefox 90.0.2
- Luxon version: 2.0.2
- Your timezone: "Europe/Berlin"

**Comment by icambron** [comment]
No, that's not how Durations work. Those accessors just echo back the units you set. Try `duration.as("minutes")`
