### ISSUE TITLE
Polyfills for AMD (require.js)

### ISSUE THREAD

**Issue by Roseidon** [moment/luxon#102]
Will there be a release of the polyfills version for require.js?
Or how can I insert the polyfills to require.js?

**Comment by icambron** [comment]
I can definitely add one, was really just waiting to make sure it was needed. You can also use polyfill.io.

**Comment by icambron** [comment]
I went ahead and added it: http://moment.github.io/luxon/docs/manual/install.html#amd--system-js--requirejs--etc-

I also added some clarifications to the IE section higher up in the doc that might be worth looking at.
