### ISSUE TITLE
toFormat( 't ZZZZ')  returns null timezone sometimes

### ISSUE THREAD

**Issue by satya-imaginea** [moment/luxon#1021]
**Describe the bug**

```
let datetime = DateTime.fromMillis(<passing dynamic date in millis>);
datetime.toFormat( 't ZZZZ',) 
```

datetime.toFormat( 't ZZZZ',) is giving **null** in the part of output response sometimes, whatever the input, at least the **null** value should not be printed in the middle of output. 

**Actual vs Expected behavior**

Actual: Error output with null:
![image](https://user-images.githubusercontent.com/76739349/131317793-87d9e006-3c0e-43a8-8c4d-fbb554d2aae5.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/76739349/131318022-9ea2c21a-d6e0-457a-a740-b54f8cb80da5.png)

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [Chrome 92]
- Your timezone [Time zone in Kolkata, West Bengal (GMT+5:30)]

**Comment by icambron** [comment]
Thanks. Do you have a reproduceable example?

**Comment by satya-imaginea** [comment]
@icambron, Yes. This is my observation, when I test it using jest -> printing **UTC**, on Xcode(ios)/android emulator -> printing **GMT+5:30**, on real device -> printing **null**, the timestamp I used - 1630411227881

**Comment by icambron** [comment]
@satya-imaginea The way this works is that you're trying to help me solve this problem. So you want to give me an easy way to see the issue. What I'm asking for is an easy way to reproduce the issue myself
