### ISSUE TITLE
Website Docs has incorrect return value in comments

### ISSUE THREAD

**Issue by darrinmn9** [moment/luxon#1024]
**Describe the bug**
In the docs https://moment.github.io/luxon/#/math?id=diffs, I am fairly certain this is incorrect:

Docs example:
> var end = DateTime.fromISO('2017-03-13');
var start = DateTime.fromISO('2017-02-15');
end.diff(start, ['months', 'days']) //=> { months: 1, days: 2 }

Actual:
`end.diff(start, ['months', 'days']).toObject() // {months: 0, days: 26}`

(`1` month `2` days vs `0` months `26` days)

**Comment by icambron** [comment]
Thanks, fixed in https://github.com/moment/luxon/commit/f4e06053b27e0737be50d9569feb86cf91d5fb80
