### ISSUE TITLE
fromFormat() doesn't parse 1-digit milliseconds correctly

### ISSUE THREAD

**Issue by rbehzadan** [moment/luxon#1025]
**Describe the bug**
When parsing strings with millisecond part that has 1 digit (or 2 digits starting with zero), `fromFormat` treats the millisecond as a whole number not as a decimal part.

**To Reproduce**
```js
let t = luxon.DateTime.fromFormat('3:14:15.9', 'H:m:s.S')
console.log(t.millisecond)   //  --> 9 (should be 900)

let t = luxon.DateTime.fromFormat('3:14:15.09', 'H:m:s.S')
console.log(t.millisecond)   // --> 9 (should be 90)
```

**Actual vs Expected behavior**
I expected milliseconds to be treated as decimal parts not whole numbers.

**Desktop (please complete the following information):**

- OS: linux
- Browser: Firefox 91
- Luxon version: 2.0.2
- Your timezone: Asia/Tehran

**Comment by icambron** [comment]
It's not, like, contextually aware of the `.` there; it's just parsing the number of milliseconds. Imagine, for example, that you were trying to parse the string `"It has been 7 milliseconds"`; you certainly wouldn't want `S` to interpret that as 700 milliseconds.

You want a different token, with different semantics, namely `u`:

```js
luxon.DateTime.fromFormat('3:14:15.09', 'H:m:s.u').millisecond //=> 90
luxon.DateTime.fromFormat('3:14:15.9', 'H:m:s.u').millisecond //=> 900
```
