### ISSUE TITLE
Donate/sponsor Luxon?

### ISSUE THREAD

**Issue by abhikp** [moment/luxon#1028]
Hey 👋🏾 ! We love Luxon at our company (Ashby) and we'd be interested in donating/sponsoring.  Any plans to set that up?

**Comment by abhikp** [comment]
Apologies for creating an issue. Wasn't sure how else to ask (and seems like it hasn't been asked before)

**Comment by icambron** [comment]
No problem about creating the issue, but I've long since determined that administering such a system would be more work than it's worth, and further I wish to feel no obligations. I genuinely appreciate the thought though.
