### ISSUE TITLE
Access to previous API docs

### ISSUE THREAD

**Issue by nijk** [moment/luxon#1032]
**Is your feature request related to a problem? Please describe.**
I am using `v1.26` of Luxon and need to access the API documentation for this version to use the library correctly

**Describe the solution you'd like**
I'd like to access API documentation prior to `v2.x.x`

**Describe alternatives you've considered**

- Searching the internet for alternative links
- Using google cached pages
- trying links in the `README.md` on the `v1.26` tag in GitHub

**Additional context**
I may have missed something, but a link to older versions of the documentation would be most helpful

**Comment by icambron** [comment]
I don't have that hosted anywhere, but you can check out the tag in git and build the docs via `npm run docs` to generate the docs yourself.

Alternatively, there's this: https://web.archive.org/web/20201214214108/https://moment.github.io/luxon/docs/identifiers.html
