### ISSUE TITLE
Cannot parse using fromFormat()

### ISSUE THREAD

**Issue by hardysabs2** [moment/luxon#1033]
I am using static method DateTime.fromFormat().

I am getting cannot parse - I have tried amongst others, the following:

the input "2021-10-04T17:23:00" can't be parsed as format yyyy-MM-ddT:HH:mm:ss
the input "2021-10-04T16:21:00" can't be parsed as format yyyy-LL-ddT:HH:mm:ss

I am looking here https://github.com/moment/luxon/blob/master/docs/formatting.md

I would be very grateful of some advice as to why this may not be working.

Thank you.

**Comment by dasa** [comment]
This doc is better: https://moment.github.io/luxon/#/parsing?id=ad-hoc-parsing

**Comment by hardysabs2** [comment]
the table of tokens look the same

**Comment by dasa** [comment]
For those values, I think you can use `fromISO` instead: https://moment.github.io/luxon/#/parsing?id=iso-8601

**Comment by icambron** [comment]
@dasa is correct that the best way to do this is with the dedicated ISO parser.

The specific problems with the parsing you did are:
1. The colon between the T and the H shouldn't be there
2. `T` is a formatting token, so you need to quote it

```js
DateTime.fromFormat("2021-10-04T17:23:00", "yyyy-MM-dd'T'HH:mm:ss").toObject() 
// => { year: 2021, month: 10, day: 4, hour: 17, minute: 23, second: 0, millisecond: 0 }
```
