### ISSUE TITLE
Please add `DateTime.today()`

### ISSUE THREAD

**Issue by alvipeo** [moment/luxon#1036]
People do use it very often.
Thanks.

**Comment by icambron** [comment]
Meaning, a shortcut for `DateTime.now().startOf("day")` or something else?

**Comment by alvipeo** [comment]
Yes, the shortcut for `DateTime.now().startOf("day")`. Btw, I had a hard time finding this!

**Comment by Isaac-alencar** [comment]
According contributing guides, we shouldn't be doing that. I think is a better idea callers create your own abstractions (shortcuts) to this king of nested methods

**Comment by icambron** [comment]
I agree. I'll add another reason: `DateTime.today()` is deceptive, because it implies that Luxon supports a Date type, whereas it's actually returning a DateTime of first millisecond of the day, whereas `DateTime.now().startOf("day")` is explicit.
