### ISSUE TITLE
setting zone in firefox giving Invalid DateTime

### ISSUE THREAD

**Issue by praveen7557** [moment/luxon#1039]
**Describe the bug**
When setting a zone in `fromMillis` is giving `Invalid DateTime` in firefox

```
DateTime.fromMillis(1632980664445, { zone: "PST" }).toFormat(
    "MMM dd yyyy hh:mm a ZZZZ",
    {
      locale: "en-US"
    }
  )
```

**To Reproduce**
CodeSandbox URL [https://codesandbox.io/s/luxon-playground-forked-mo6m2?file=/src/App.js:270-401](url)

**Actual vs Expected behavior**
Actual: Giving `Invalid DateTime`
Expected:  Should give the date in the specified timezone

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Browser: Firefox 92.0.1 
- Luxon version 1.25.0
- Your timezone PST

**Comment by icambron** [comment]
`PST` is not a supported zone. Luxon uses IANA identifiers for zones, so you want `America/Los_Angeles`
