### ISSUE TITLE
Wrong offset when specifing a time zone in NestJs

### ISSUE THREAD

**Issue by AndresHalliday** [moment/luxon#1056]
**Describe the bug**
I ran the same code in Angular and in NodeJs (NestJs) and it gave me different offsets for the same time zone.

**To Reproduce**
let date = DateTime.fromISO('2021-10-16T14:30:00.000Z').setZone('Europe/Paris');
console.log('zoneName', date.zoneName);
console.log('offset', date.offset);
console.log('valueOf', date.valueOf());

**Actual vs Expected behavior**
In Angular it printed this:
      zoneName Europe/Paris
      offset 120
      valueOf 1634394600000

And in Nestjs in printed this:
      zoneName Europe/Paris
      offset -600
      valueOf 1634394600000
It is the same timestamp and time zone name but the offset is different. I think the one from Angular is correct.

**Desktop (please complete the following information):**

- OS: windows
- Browser: Edge
- Luxon version 2.0.2
- Your timezone "America/Bogota"

**Comment by icambron** [comment]
This is probably #1073. Can you try the latest version of Luxon?

**Comment by AndresHalliday** [comment]
Hi, thank you.

I updated Luxon and it worked fine. But I try it also without the update and it worked fine too, so I'm not sure if that was what fixed it, or if it is somthing random or it has something to do with the date. Anyway, after that I haven't found any other date that has that problem.

Thanks
