### ISSUE TITLE
In Next.js fromISO does not parse correctly with zone specified in the options

### ISSUE THREAD

**Issue by kracas** [moment/luxon#1064]
**Describe the bug**
In backend of Next.js (API route), parsing ISO 8601 string with fromISO and zone specified in the options gives an incorrect result

**To Reproduce**
API route code:

```
import { DateTime } from "luxon";
export default function handler(req, res) {
  console.log(DateTime.fromISO(`2022-02-21T16:00:00`, {zone: 'Europe/Vilnius'}).toString())
  res.status(200).send('OK')
}
```

**Actual vs Expected behavior**
The console logs 2022-02-22T04:00:00.000+02:00. 
It should actually log 2022-02-21T16:00:00.000+02:00, so it seems it's adding 12 hours.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Framework: Next.js
- Luxon version 2.0.2
- My timezone: 'Europe/Vilnius'

**Additional context**
The string is parsed correctly if the zone is not specified in the options (i.e. system zone is used).
This bug is not present in Luxon v1.28.

**Comment by icambron** [comment]
This is probably #1073. Can you try the latest version of Luxon?
