### ISSUE TITLE
`DateTime.fromObject(..., zone)` does not set the zone to the created instance when using Chrome

### ISSUE THREAD

**Issue by khanhhuy** [moment/luxon#1072]
**Describe the bug**
`DateTime.fromObject(..., zone)` does set the zone to the newly created instance when using with Chrome. But it does set the zone when using with NodeJS

**To Reproduce**
- OS: MacOS Big Sur 11.4 (M1 chip)
- Browser: Chrome Version 95.0.4638.69 (Official Build) (arm64)
- Luxon version: `luxon@^2.0.2`
- Your timezone: `Asia/Saigon`

```javascript
Intl.DateTimeFormat().resolvedOptions().timeZone
// 'Asia/Saigon'
window.H.DateTime.fromObject({ year: 2021, month: 11, day: 4 }, { zone: "Europe/Paris" }).zoneName;
// 'Asia/Saigon'
```

**Actual vs Expected behavior**
- The expected `zoneName` should be `Europe/Paris`
- But the actual is `Asia/Saigon`

**Additional context**
Do the same test using NodeJS, and the zone name is set correctly.
- NodeJS: v12.20.0

```javascript
// Command to run: env TZ='Asia/Saigon' node .

luxon2 = DateTime.fromObject({ year: 2021, month: 11, day: 4 }, { zone: 'Europe/Paris' })
console.log(luxon2.zoneName);
// Europe/Paris

```

**Comment by icambron** [comment]
How confident are you that the version of Luxon you have having on your window var is 2.0.2?

**Comment by khanhhuy** [comment]
Hi @icambron, thank you for your reply. You're totally correct, my browser version is `^1.2.6`. I'm having some other libraries that use luxon `2.0.2` and I wasn't aware of these inconsistencies.
Thanks again for your help on this, I'll close this issue.
