### ISSUE TITLE
Changing system timezone shows wrong date.

### ISSUE THREAD

**Issue by broomfn** [moment/luxon#1075]
**Describe the bug**
Changing the system time zone (e.g. in Windows) on a running ionic application causes Luxon to incorrectly display the wrong date (e.g. It adds or removes a day)

**To Reproduce**
$ npm install -g @ionic/cli
$ ionic start luxontest tabs --capacitor
$ npm i luxon
$ ionic serve

In tab1.page.html add the following line above `<app-explore-container>`:

`  <h1>Date = {{getFormated("2021-11-12")}}</h1> <!-- Add this line -->`
`  <app-explore-container name="Tab 1 page"></app-explore-container>`

In tabs1.page.ts add the following function:

`  public getFormated(date) {`
`    const strangeDate = DateTime.fromISO(date);`
`    console.log(strangeDate.toISO(), strangeDate);`
`    return DateTime.fromISO(date).toLocaleString(DateTime.DATE_SHORT);`
`  }`

Open a browser to http://localhost:8100 and the date shown on tab1 should be 12/11/2021, which is correct, now change the system time zone in windows Date & Time settings to +14 or -12 and switch the ionic application to tab3 and then back to tab1 (this force the html to redraw and the getFormated function to be recalled) and the date is now shown incorrect, typically either the 13/11/2021 or 11/11/2021 (moved by a day).  What's stranger still if you now refresh the browser the date fixes itself and shows 12/11/2021.  It's almost as if there is some strange caching going on or something.

**Actual vs Expected behaviour**
I would expect a date of "12/11/2021" not to change when moving the system time zone, if for some reason (I can't think of) this was correct behaviour, I would expect the behaviour to be consistent and refreshing the browser not to change the date back.

**Desktop (please complete the following information):**

- OS: Windows 10 
- Browser Chrome: 95.0.4638.69
- Luxon version: tried 2.1.1 and 1.28.0
- Your timezone: "Europe/London"

**Additional context**

**Comment by icambron** [comment]
Yes, Luxon caches instances of the Intl.DateTimeFormat objects it creates. That object in turn seems to cache the local zone: https://jsfiddle.net/Lcq098ms/

Last time I benchmarked, it made a huge perf difference to cache these objects. But it certainly has the downside that it can't handle "live" changes to the system zone.

**Comment by broomfn** [comment]
Many thanks for the quick response, is there anyway within Luxon to disable this caching or force a cache refresh?

**Comment by icambron** [comment]
Try out `Settings.resetCaches()`
