### ISSUE TITLE
keepLocalTime applies day light savings

### ISSUE THREAD

**Issue by End-S** [moment/luxon#1079]
**Describe the bug**
I have recently begun using Luxon and I'm really enjoying it so far. Apologies if I have misunderstood the purpose of the `keepLocalTime` option. As I understood it, it should return a local time with a different offset but the same date and time. But what I am seeing is day light savings being applied.

**To Reproduce**
```JavaScript
const ny = DateTime.fromISO('2021-03-28T23:59:00.000Z')
  .setZone('America/New_York', { keepLocalTime: true })

ny.toFormat('DDDD HH:mm')
// "Monday, 29 March 2021 00:59"  (Actual - Unexpected)
// "Monday, 28 March 2021 23:59" (Expected)

const ny2 = luxon.DateTime.fromISO('2021-02-28T23:59:00.000Z')
  .setZone('America/New_York', { keepLocalTime: true })

ny2.toFormat('DDDD HH:mm')
// "Sunday, 28 February 2021 23:59" (Expected)
```

**Actual vs Expected behavior**
I would have expected `ny.toFormat('DDDD HH:mm')` to have given me `"Sunday, 28 March 2021 23:59"` but instead it appears to apply DST and prints `"Monday, 29 March 2021 00:59"`

**Desktop:**

- OS: Linux Kubuntu
- Browser: Firefox 94.0
- Luxon version: `2.1.1`
- Your timezone: Europe/London

Again apologies if I have misunderstood the purpose of the `keepLocalTime` and this is actually intentional behaviour.

**Comment by icambron** [comment]
I agree. Not sure what's happening in there to cause that

**Comment by icambron** [comment]
Oh, I see. No, this is not a bug. What's happening is this:

```js
// parse a UTC date string and convert to local time (which for you is BST)
const aLocalDt =  DateTime.fromISO('2021-03-28T23:59:00.000Z');

aLocalDt.toISO() // pretty sure this produces 00:59+1:00 for you

// convert to US EDT but holding the 00:59 constant
aLocalDt.setZone("America/New_York", { keepLocalTime: true });
```

In other words, the DST shift comes from your local zone _before_ the `setZone()` has ever been called.

What you meant was to keep the offset from the string. You can do that one of a few ways:

1. Explicitly keep the zone in UTC, like `DateTime.fromISO(s, { zone: "UTC"})`
2. Accept the offset from the string as not _just_ the zone to interpret the string in, but _also_ keep the resulting DateTime in: `DateTime.fromISO(s, { setZone: true })`
3. Run your whole environment in UTC instead of Europe/London

**Comment by End-S** [comment]
That makes a lot of sense. Thank you for taking the time to explain it.

**Comment by icambron** [comment]
I'll add one more fix: set the default zone to utc, like:

```js
Settings.defaultZone = 'utc';
```

**Comment by d4g0** [comment]
This issue has save me from goin nuts. Thanks for it guys.  Im on Cuba, a DTS present zone, was getting a shift off `1h` on non local time zone convertions with `keepLocalTime`. Setted the defaultZone setting to utc as adviced avobe and Boom no problema any more.
