### ISSUE TITLE
Etc/GMT+/-X backwards

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [moment/luxon#1081]
So this is a bit confusing. The ETC/GMT+/-X are by definition backwards in most systems. That is, The Etc/GMT+1 timezone value actually corresponds to GMT-1. While that's confusing, it is an established standard: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones . Furthermore, it's an established standard followed by the Javascript Date library. 

Here's a quick example: https://fv8es.csb.app/

Or some basic code

```javascript
const isoString = `${new Date().toIsoString()`
const luxonDate = `${DateTime.fromISO(isoString).setZone("Etc/GMT-4").toString()}`
const javascriptDate = `${new Date(isoString).toLocaleString("en-Us", {
            timeZone: "Etc/GMT-4"
          })}`
```

You can clearly see that Luxon is behaving in a non standard way. Ideally, it would work as expected under the established standard.

**Comment by icambron** [comment]
Your sandbox is using Luxon 1.2.0. This issue was #327 -- you can see it by upgrading to any newer version.

**Comment by JustAnotherSoftwareDeveloper** [comment]
My bad. I should have double checked the version. Thanks for clearing that up and sorry for wasting your time.
