### ISSUE TITLE
How to customise locale?

### ISSUE THREAD

**Issue by sergej-s** [moment/luxon#1084]
Hello!

Im migrating momentjs to luxon and stuck on how to update locale as it was done in momentjs:
```
moment.updateLocale('fr', {
    months: 'Janvier_Février_Mars_Avril_Mai_Juin_Juillet_Août_Septembre_Octobre_Novembre_Décembre'.split('_'),
    monthsShort: 'Janv._Févr._Mars_Avr._Mai_Juin_Juil._Août_Sept._Oct._Nov._Déc.'.split('_'),
    weekdays: 'Dimanche_Lundi_Mardi_Mercredi_Jeudi_Vendredi_Samedi'.split('_'),
    weekdaysShort: 'Dim._Lun._Mar._Mer._Jeu._Ven._Sam.'.split('_'),
    weekdaysMin: 'Di_Lu_Ma_Me_Je_Ve_Sa'.split('_'),
    ...
```
Could you explain me what is the approach to change localised output in luxon on formatting?

**Comment by icambron** [comment]
Internationalization is provided by the browser through the Intl API. There's no way to customize it.

**Comment by jalite1991** [comment]
Is it possible to add this as a feature request?
