### ISSUE TITLE
Duration wrong output using toFormat with HH

### ISSUE THREAD

**Issue by BulatSa** [moment/luxon#1085]
**Describe the bug**
Creating a duration using a milliseconds then using toFormat produces an incorrect result

**To Reproduce**
`Duration.fromObject({hours: 0, minutes: 10}).toFormat('HH:mm')` returns `"HH:10"`
`Duration.fromMillis(600000).toFormat('HH:mm')` returns `"HH:10"`

**Actual vs Expected behavior**
Duration of 10 minutes format to 00:10
Duration of 600000 milliseconds format to 00:10

**Desktop (please complete the following information):**

- OS: Win 10
- Browser: Chrome 95
- Luxon version: 1.28.0, 2.1.1
- Your timezone: "Europe/Moscow"

**Comment by icambron** [comment]
Per the [API docs](https://moment.github.io/luxon/api-docs/index.html#durationtoformat), use `hh` for hours, not `HH`
