### ISSUE TITLE
bug: creating a fixed DateTime inside DST boundary depends on client's time

### ISSUE THREAD

**Issue by jorroll** [moment/luxon#1089]
**Describe the bug**
When creating a `DateTime` for `2021-10-31T01:45:00.000[Europe/London]` (which exists inside the BST->GMT daylight savings boundary) the result is dependent on the client's current local time.

Put another way, the DateTime created by this code is different depending on if the client executing the code is before or after the DST change.

```ts
const date = DateTime.fromObject({
  year: 2021,
  month: 10,
  day: 31,
  hour: 1,
  minute: 45,
}, {
  zone: 'Europe/London',
});
```

**To Reproduce**
[See this repo for a reproduction](https://gitlab.com/john.carroll.p/luxon-rschedule-bug). Note, if you use `.devcontainer.json` files in VSCode, the repo contains one.

```ts
import MockDate from 'mockdate'; // method for mocking client's local time
import { DateTime } from 'luxon';

describe('create a date in the BST->GMT boundary', () => {
  function runLuxonTest() {
    const date = DateTime.fromObject({
      year: 2021,
      month: 10,
      day: 31,
      hour: 1,
      minute: 45,
    }, {
      zone: 'Europe/London',
    });

    expect(date.toJSDate().toISOString()).toEqual('2021-10-31T00:45:00.000Z');
  }

  it('when the local time is before the DST change', () => {
    MockDate.set(new Date(2021, 9, 29));
    runLuxonTest();
    MockDate.reset();
  });

  it('when the local time is after the DST change', () => {
    MockDate.set(new Date(2021, 10, 4));
    runLuxonTest();
    MockDate.reset();
  });
});

```

**Actual vs Expected behavior**
The generated `DateTime` should be the same regardless of the current client time.

**Desktop (please complete the following information):**

- OS: macOS
- Browser Chrome 96
- Luxon version 2.0.7 (the bug also exists in version 1.x)
- Your timezone "America/Los_Angeles"

**Additional context**
I maintain a javascript recurring event library called [rSchedule](https://gitlab.com/john.carroll.p/rschedule). This bug was [originally reported there](https://gitlab.com/john.carroll.p/rschedule/-/issues/66). Note that both [MomentJS](https://momentjs.com/) and [js-joda](https://js-joda.github.io/js-joda/) don't seem to experience this issue. 

I'll also note that the bug was originally reported in the context of the [ical spec](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.5) which states

```
If, based on the definition of the referenced time zone, the local
      time described occurs more than once (when changing from daylight
      to standard time), the DATE-TIME value refers to the first
      occurrence of the referenced time.  Thus, TZID=America/
      New_York:20071104T013000 indicates November 4, 2007 at 1:30 A.M.
      EDT (UTC-04:00).  If the local time described does not occur (when
      changing from standard to daylight time), the DATE-TIME value is
      interpreted using the UTC offset before the gap in local times.
      Thus, TZID=America/New_York:20070311T023000 indicates March 11,
      2007 at 3:30 A.M. EDT (UTC-04:00), one hour after 1:30 A.M. EST
      (UTC-05:00).
```

Since the ical spec isn't directly related to Luxon, the bug in Luxon is simply that the provided test is dependent on the client's date and Luxon could "fix" this bug by simply ensuring that the produced DateTime is consistent. So Luxon could fix this by either ensuring that the generated date behaves like the current "before" time or it could fix the bug by ensuring that the generated date behaves like the current "after" time.

If it makes no difference to the Luxon maintainers though, I'd strongly prefer that Luxon follows the behavior established by Momentjs and js-joda and the ical spec.

**Comment by icambron** [comment]
Luxon converts the parsed time to the default zone (the system zone, or whatever's specified in Settings.defaultZone). This is to allow consistent behavior in the face of strings outside the program's control If you want to use the zone from the string, use the setZone option. See https://moment.github.io/luxon/#/zones?id=strings-that-specify-an-offset

**Comment by icambron** [comment]
Luxon is very explicit about this: https://moment.github.io/luxon/#/zones?id=ambiguous-times

**Comment by jorroll** [comment]
Gotcha. I don't actually use Luxon myself (other than maintain a library that allows people to use Luxon). I'm not that familiar with the library and it never occurred to me that this behavior would be known and accepted. Thanks for the info.
