### ISSUE TITLE
weeksInWeekYear returns wrong results

### ISSUE THREAD

**Issue by Sebi2020** [moment/luxon#1090]
**Describe the bug**
The year 2021 has 52 ISO Weeks (compare with Google Calendar), but luxon returns 53 for the year 2021. This must be wrong, because Week 52 goes from 27.12.21 to 02.01.22. After this the first week of 2022 must follow, cause it always contains 4th january (see ISO 8601 for reference)

**To Reproduce**
```javascript
console.log(DateTime.fromISO("2021").weeksInWeekYear) // returns 53
```

**Actual vs Expected behavior**
Should return right number of weeks.

**Workaround**
```javascript
function weeksInYear(year) {
 return DateTime.fromISO(year + "-12-28").weekNumber;
}
```

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. Chrome 84, safari 14.0] Chrome 96
- Luxon version [e.g. 1.25.0] 2.2.1
- Your timezone [e.g. "America/New_York"] Europe/Berlin

**Comment by icambron** [comment]
No, `fromISO("2021")` returns a DateTime representing 2021-01-01T00:00:00. That's in the 2020 ISO week year, so `weeksInWeekYear` is answering about then, i.e. 2020.

**Comment by Sebi2020** [comment]
@icambron So what's the difference between DateTime.weekNumber and DateTime.weeksInWeekYear (in my opinion a misleading name...). You're description sounds like it give you the exact same value as you would get with DateTime.weekNumber

**Comment by icambron** [comment]
weekNumber gives the week number of the current date. weeksInWeekYear gives the number of weeks in the current week year. That's what you expected it to do, but I'm pointing out that "current week year" isn't the week year you assumed it was

**Comment by Sebi2020** [comment]
Just for reference, the documentation states:
> weeksInWeekYear returns the number of weeks in this DateTime's [maybe add "iso"] year

"This" DateTime year was 2021 and it has 52 weeks, not 53. I'm not sure if week year is the same as "iso year", but i so the description should say "number off weeks in DateTime's week/iso year and not "DateTime's year".

**Comment by icambron** [comment]
DateTime's are specific instants in time. `fromISO` returns such an instant. That instant is in the 2021 _Gregorian_ year but not the 2021 ISO year. Thus weeksInWeekYear is returning the number of weeks I'm the iso week year your datetime is actually in

**Comment by icambron** [comment]
I think I can guess the confusion. The "ISO" in "fromISO" doesn't refer to the ISO week calendar; it refers to the ISO 8601 string format. When parsing a just alone year, that refers to the Gregorian year. Does that help?
