### ISSUE TITLE
format tokens differ from momentjs. Is there a way to fix this?

### ISSUE THREAD

**Issue by Antonimo** [moment/luxon#1106]
this makes migrating to the new library extra difficult, especially if the old tokens are saved in a database.

'DD/MM/YYYY HH:mm:ss'  

results in

9 Sept 49213/09/YYYY 07:06:40

**Comment by icambron** [comment]
No, we're not going to change the tokens. That would be a huge breaking change for thousands of Luxon users

**Comment by Antonimo** [comment]
who was asking to change anything? a backwards compatibility to moment js
tokens would be nice through some specialized method / addon / lib

**Comment by icambron** [comment]
In your example, "DD" means "localized date with abbreviated month", whereas in Moment it means "2-digit day". Making that token compatible with Moment would break that token.
