### ISSUE TITLE
Duration.weeks returns zero but Duration.as('weeks') works

### ISSUE THREAD

**Issue by ctsstc** [moment/luxon#1110]
**Describe the bug**
I would expect calling the `weeks` property on a duration to be the same as calling `as('weeks')`, but I get `0` when I call the `weeks` property on this duration.

**To Reproduce**
```javascript
const createdDate = DateTime.fromISO('2021-12-15')
const today = DateTime.fromISO('2022-01-03') // DateTime.now()
const dateDiff = today.diff(createdDate)
console.log('DateDiff `weeks`', dateDiff.weeks)
console.log('DateDiff `as`', dateDiff.as('weeks'))
```
> DateDiff \`weeks\` 0
> DateDiff \`as\` 2.7142857142857144

**Actual vs Expected behavior**
I would expect them to be the same or at least `.weeks` to be non-zero.

Maybe this is a misunderstanding on my part?

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome: `Version 96.0.4664.110 (Official Build) (x86_64)`
- Luxon version: `2.1.1`
- Your timezone: PST/LA

**Comment by icambron** [comment]
A duration is a bag of unit values, and diff creates one of those bags of units based on how you took the diff:

```js
today.diff(createdDate).toObject() //=> { milliseconds: 1641600000 }
today.diff(createdDate, "weeks").toObject() //=> { weeks: 2.7142857142857144 }
today.diff(createdDate, ["days", "hours", "minutes"]).toObject() //=> , days: 19, hours: 0, minutes: 0 }
today.diff(createdDate, ["weeks", "days"]).toObject() // => { weeks: 2, days: 5 }
```

You took the diff in milliseconds (the default), so the `weeks` component is 0, where as `as` _converts_ to weeks.
