### ISSUE TITLE
Missing Locale: 'af'

### ISSUE THREAD

**Issue by jojukin** [moment/luxon#1111]
When I use the locale code for [French](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry#:~:text=%25%25%0AType%3A%20language%0ASubtag%3A%20fr%0ADescription%3A%20French%0AAdded%3A%202005%2D10%2D16%0ASuppress%2DScript%3A%20Latn%0A%25%25),
```
const dateOutput = DateTime.fromFormat("18/07/2021", "dd/MM/yyyy", { locale: "fr" });
console.log(dateOutput.toLocaleString(DateTime.DATE_MED_WITH_WEEKDAY));
```
Output = dim. 18 juil. 2021 (As expected)

When I try with the code for [Afrikaans](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry#:~:text=%25%25%0AType%3A%20language%0ASubtag%3A%20af%0ADescription%3A%20Afrikaans%0AAdded%3A%202005%2D10%2D16%0ASuppress%2DScript%3A%20Latn%0A%25%25)
```
const dateOutput = DateTime.fromFormat("18/07/2021", "dd/MM/yyyy", { locale: "af" });
console.log(dateOutput.toLocaleString(DateTime.DATE_MED_WITH_WEEKDAY));
```
Output = Sun, Jul 18, 2021 (Which is English)

What do I need to do to get the output in Afrikaans? Is it supported?

**Comment by icambron** [comment]
Internationalization support comes from the JS runtime (e.g. the browser), not from Luxon itself. And Afrikaans doesn't seem to be supported, at least in Chrome. So to get Afrikaans support, you'd need to wait until the browser supports the `af` locale. I'm honestly a little surprised it's not in there, but I confirmed that I don't see it either. At any rate, there's not much Luxon can do.

The only workaround I can offer is to use Dutch instead, but there are enough differences in the strings that it might not be a real option.

**Comment by jojukin** [comment]
> Internationalization support comes from the JS runtime (e.g. the browser), not from Luxon itself. And Afrikaans doesn't seem to be supported, at least in Chrome. So to get Afrikaans support, you'd need to wait until the browser supports the `af` locale. I'm honestly a little surprised it's not in there, but I confirmed that I don't see it either. At any rate, there's not much Luxon can do.
> 
> The only workaround I can offer is to use Dutch instead, but there are enough differences in the strings that it might not be a real option.

Thanks so much for this information. Where can I look to find the languages that are currently supported in Chrome? I would like to periodically check on this.

**Comment by icambron** [comment]
The easiest way is to just try it in the Chrome dev console:

```
new Intl.DateTimeFormat("af").resolvedOptions().locale
```

If it were supported, that would return `"af"` of perhaps `"af-ZA"`  instead of your default locale.

**Comment by fwiwDev** [comment]
Hello,

This locale is now supported in the Chrome browser but not in Luxon.

```
new Intl.DateTimeFormat("af").resolvedOptions
```

Returns af but in Luxon, I get English

**Comment by icambron** [comment]
@fwiwDev can you open a fresh issue?
