### ISSUE TITLE
abutsStart, abutsEnd and merge is not correct

### ISSUE THREAD

**Issue by likern** [moment/luxon#1112]
I have **adjacent intervals** and tried to merge them to **get one interval** using `Interval.merge()`.
But intervals **haven't gotten merged**.

These two intervals are:
```bash
 LOG  Merged Interval: [start: 2022-01-09T21:00:00.000Z] - [end: 2022-01-15T20:59:59.999Z]
 LOG  Merged Interval: [start: 2022-01-15T21:00:00.000Z] - [end: 2022-01-16T20:59:59.999Z]
```
They are **adjacent**  with the max precision allowed, **but not overlapping**.

After looking at `merge` and `abutsStart` functions
https://github.com/moment/luxon/blob/d1372798e253f29ac000f988ad7c7c707d88a173/src/interval.js#L466

https://github.com/moment/luxon/blob/d1372798e253f29ac000f988ad7c7c707d88a173/src/interval.js#L382

I see that `abutsStart` doesn't really check for "abuts start", **but for overlapping**.

**To Reproduce**
Create two intervals with followed time ranges and merge them using `Interval.merge()`.

**Actual vs Expected behavior**
I expect that adjacent intervals get merged into one interval.

**Desktop (please complete the following information):**

- OS: Android
- Browser: React Native
- Luxon version: 2.3.0
- Your timezone: UTC

**Comment by hamishjohnson** [comment]
An interval ending at 2022-01-15T21:00:00.000Z and another one starting at 2022-01-15T21:00:00.000Z don't overlap, they just share a common boundary.

The way I think of it is that an interval starts at `start`, and ends up to but not including `end`.
