### ISSUE TITLE
Duration.minus() returns the wrong value

### ISSUE THREAD

**Issue by J0ck3rul** [moment/luxon#1115]
**Describe the bug**
> Difference of duration between 31st December and 1st January next year is of 6 days.

**To Reproduce**
```js
const startDuration = Duration.fromObject({
  years: 2021,
  months: 12,
  days: 30
});
const endDuration = Duration.fromObject({ years: 2022, months: 1, days: 1 });
const durationResult = endDuration.minus(startDuration);

console.log(durationResult.days); // returns -29
console.log(durationResult.shiftTo("days").days); // returns 6
```

**Actual vs Expected behavior**
It should return 1

**Desktop (please complete the following information):**

- Here I tested the code: [Code sandbox](https://codesandbox.io/s/luxon-playground-forked-18chr?file=/src/index.js:269-302)
- Browser Chrome 96.0.4664
- Luxon version 2.3.0
- Your timezone Romania GMT+2

**Comment by icambron** [comment]
I think you wanted to use `DateTime`, not `Duration`

```js
const start = DateTime.fromObject({....});
const end = DateTime.fromObject({....});

end.diff(start, "days")
```
