### ISSUE TITLE
Date conversion with RU locale not working

### ISSUE THREAD

**Issue by lordent** [moment/luxon#1123]
**Describe the bug**
I trying to convert user input to date and it doesn't work in case of word month

**To Reproduce**
For example
```javascript
const mask = "dd MMM yyyy HH:mm:ss"
const initial = "2021-12-24T21:52:23"
const isodatetime = luxon.DateTime.fromISO(initial)  // Ok, it datetime with RU locale
console.log(isodatetime)

const value = isodatetime.setLocale("default").toFormat(mask)  // without setLocale locale is US??! wtf?
console.log(value)

const valuedatetime = luxon.DateTime.fromFormat(value, mask)  // the input \"24 дек. 2021 21:52:23\" can't be parsed as format dd MMM yyyy HH:mm:ss
console.log(valuedatetime)
```

**Actual vs Expected behavior**
I just want it to work

**Desktop (please complete the following information):**

- OS: [any]
- Browser [any]
- Luxon version [2.3.0]
- Your timezone ["Europe/Moscow"]

**Comment by icambron** [comment]
It's just a string; Luxon doesn't know it's in Russian. But you can just tell it that:

```js
luxon.DateTime.fromFormat(value, mask, { locale: "ru" }) //=> works fine
````
