### ISSUE TITLE
Make API available in browser console on doc pages

### ISSUE THREAD

**Issue by slobo** [moment/luxon#1124]
It would be great that we could just open browser console on https://moment.github.io/luxon/ and https://moment.github.io/luxon/api-docs/ and have access to all of Luxon API. Presumably it's just a matter of `<script src="path/to/latest/luxon/on/cdn"...`, and it would help immensly

An example of this is https://lodash.com/. If you open console you can type for example `_.compact([0, 1, false, 2, '', 3])` to try out said API. On Luxon documentation pages things like `DateTime` are not defined.

Thanks for a great library in any case!

**Comment by icambron** [comment]
This is done now
