### ISSUE TITLE
fromMillis(0) does not start with the Epoch

### ISSUE THREAD

**Issue by matthiasg** [moment/luxon#113]
`DateTime,fromMillis(1)` returns 1970-01-01 and 1 milliseconds, but `DateTime,fromMillis(0)` returns the current time. Is this a bug or does it have a reason ?

**Comment by icambron** [comment]
Sounds like a bug; I bet it's `0` being falsy causing a problem.

**Comment by icambron** [comment]
Fixed in 8e20a4e, will release soon.

**Comment by icambron** [comment]
Released in 0.2.7

**Comment by ecoronadosc** [comment]
Tested in 0.2.8
.. stil broken

because of this line
https://github.com/moment/luxon/blob/master/src/datetime.js#L331

**Comment by icambron** [comment]
Hmm, yeah, i'll clean that up

**Comment by icambron** [comment]
Fixed in c7a76ce4, released in 0.2.9

**Comment by paddingtonsbear** [comment]
Looks like this is back in `0.5.8`
```js
import { DateTime } from 'luxon';

const date = DateTime.fromMillis(1521250121);
console.log('DateTime', date); // DateTime 1970-01-18T08:34:10.121-06:00
```
https://codesandbox.io/s/lrxovkjx4m

**Comment by icambron** [comment]
@paddingtonsbear I don't think you saved the codesandobx example; I just see the boilerplate at that link. But I looked at the example you pasted in and that looks fine. What did you expect the result of that to be?

**Comment by paddingtonsbear** [comment]
I believe I might be using the package incorrectly, I was trying to format the unix time `1521250121` to `yyyy/mm/dd` but the `fromMillis` function keeps returning `1970-01-18` and not the correct date which is suppose to be `2018-03-06`.

**Comment by icambron** [comment]
Unix timestamps are in seconds, not milliseconds. Try this:

```js
luxon.DateTime.fromMillis(1521250121 * 1000).toFormat("yyyy/MM/dd") //=> "2018/03/16"
```

**Comment by paddingtonsbear** [comment]
Of cos it is 😞 , thanks @icambron 👍
