### ISSUE TITLE
Convert timezone offset to IANA timezone name

### ISSUE THREAD

**Issue by noahw3** [moment/luxon#1133]
**Is your feature request related to a problem? Please describe.**
Given an arbitrary timestamp string I have two requirements:
1) Be able to parse it into a JS Date in ISO 8601 and do any timezone conversions necessary.
2) Be able to extract the IANA timezone name

Luxon can absolutely do the former without problem. However as far as I can tell there's no good way to do the latter when the timetamp string specifies a timezone offset. For example "2021-11-04T19:00:00-05:00" returns a timezone name of "UTC-5" and not "America/New_York."

**Describe the solution you'd like**
I'm aware that timezone != offset. However for my purposes I only care about the timezone name _at the time of conversion_, not necessarily across all time.

I'm also aware that offset to timezone name is a 1:many mapping. It would be nice to have predetermined "preferred" timezones (eg. "America/New_York" over "America/Detroit"). I imagine that something along these lines may be possible by having different preference sets by locale. However if this was extraordinarily complicated it's not strictly necessary, and any valid timezone name matching the offset could be used.

**Describe alternatives you've considered**
The most reasonable alternative seems to be to create my own mapping/search (which would itself need to use a list of timezones from an external source - see https://github.com/moment/luxon/issues/353) from offset to IANA name. While functional, it seems quite clunky. Including any sort of locale data would also make it unnecessarily complex.

**Comment by icambron** [comment]
See #447, which has a description of why Luxon won't support this directly, but how to handle it in userspace. Though definitely read Matt's note about unresolvable ambiguities as the DST change rolls across the country.

For additional color specific to your questions:

>  It would be nice to have predetermined "preferred" timezones

This is much harder than it sounds. The rules are on the zone side -- the mapping is really many:many, so we'd have to poll a list of candidates. For example, whether -5 means EST or CDT depends on what time it is, and that rule is part of the zone, so we'd have to ask both America/New_York and America/Chicago if that zone is right. Second, remember that Luxon doesn't store any per-zone or per-locale information; it merely uses the available JS APIs to use them. So this kind of thing is a non-starter.
