### ISSUE TITLE
Cannot read property 'now()' of undefined

### ISSUE THREAD

**Issue by ngoding-bro** [moment/luxon#1139]
**Describe the bug**
Why is 'now()' undefined?

**To Reproduce**
```
const { dateTime } = require("luxon")
console.log(dateTime.now().toString())
```
**Actual vs Expected behavior**
Hoping to fix the 'Undefined' issue

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [Chrome 98]
- Luxon version [2.3.0]
- Your timezone ["Asia/Jakarta"]

**Additional context**
No more problems

**Comment by lekoaf** [comment]
Is it not because you should use `DateTime` not `dateTime`?
