### ISSUE TITLE
Provide a data type representing a date with no time and no time zone (LocalDate)

### ISSUE THREAD

**Issue by scic** [moment/luxon#1141]
We often send "dates" with no time part such as 2007-12-24 over the REST API to the JS client. Right now if we convert this to a Luxon DateTime it causes the date to have a time and time zone meaning. This has the effect that calculations now need be be done carefully and it is semantically not clear that this date has no time.
It would be great if the type system and API could enforce a type with no time and time zone part.

As a workaround we defined a data type which sets the time part to 00:00:00.0000 but it would be nice to have a proper concept integrated.

js-joda has this concept and it is named LocalDate (as in Java): [https://js-joda.github.io/js-joda/manual/LocalDate.html](https://js-joda.github.io/js-joda/manual/LocalDate.html)

> A LocalDate represents a date with no time and no time zone in the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) calendar system, such as 2007-12-24.

Perhaps this is a similiar issue as #843, but i would still love this integrated.

**Comment by icambron** [comment]
This is a totally valid feature request but Luxon just isn't going to do it, sorry. I totally understand the need and why the workaround isn't great, but it's just a lot more mass to support.
