### ISSUE TITLE
Welsh locale

### ISSUE THREAD

**Issue by DamianGlowala** [moment/luxon#1149]
**Is your feature request related to a problem? Please describe.**
I'd like to provide a Welsh locale. It does not seem to be covered by Intl.

**Describe the solution you'd like**
Is there an API to provide locale strings to Luxon? Could there be one for cases like this one? Is it feasible?

**Comment by icambron** [comment]
No, there's no API for strings. We just get whatever we get from Intl. I suppose you could try polyfilling Intl, but that sounds pretty painful.

I'm actually pretty surprised Welsh isn't available; there seems to be rich CLDR data for it...it would be interesting to track down what happened there, but in any case nothing Luxon can do, sorry

**Comment by wozzo** [comment]
@DamianGlowala just wondering if you ever found a solution to this?
My first time doing internationalisation and ofcourse it's for an unsupported language, lol.

**Comment by wozzo** [comment]
@DamianGlowala I found a solution
Add the `@formatjs/intl-datetimeformat` package
Then add the following code and make sure it gets run as part of your site initialisation
```javascript
// Adds Welsh to the Intl API for date formatting etc.
import { shouldPolyfill } from "@formatjs/intl-datetimeformat/should-polyfill"

async function polyfill(locale) {
	const unsupportedLocale = shouldPolyfill(locale)
	// This locale is supported
	if (!unsupportedLocale) {
		return
	}
	// Load the polyfill 1st BEFORE loading data
	await import("@formatjs/intl-datetimeformat/polyfill-force")

	// Parallelize CLDR data loading
	const dataPolyfills = [
		import("@formatjs/intl-datetimeformat/add-all-tz"),
		import(`@formatjs/intl-datetimeformat/locale-data/${unsupportedLocale}`)
	]
	await Promise.all(dataPolyfills)
}

polyfill("cy")
```
After that code such as 
```javascript
DateTime.now().toFormat(
    msg.formatMessage("dd MMM yyyy"),
    { locale: "cy" }
)
```
Should correctly translate to Welsh, e.g. "21 Ebr 22" for 21st April 2022

**Comment by wozzo** [comment]
@icambron fyi ⬆️

**Comment by DamianGlowala** [comment]
Thanks @wozzo for sharing the above snippet! I will try it out shortly - exciting that you found a solution to this pretty frustrating problem :)

**Comment by wozzo** [comment]
Started getting a weird build error after including the above.
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

Try this if you get the same.
```javascript
import "@formatjs/intl-datetimeformat/polyfill-force"
import "@formatjs/intl-datetimeformat/add-all-tz"
import "@formatjs/intl-datetimeformat/locale-data/cy"
```
