### ISSUE TITLE
Supporting macro tokens in the parser

### ISSUE THREAD

**Issue by icambron** [moment/luxon#115]
`DateTime#toFormat` supports "macro tokens" like `DD` or `TTT`. See the bottom of the table [here](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens) to see them. In principle, these could be supported by the parser too, but it's a bunch of work and I don't feel like doing it. I'm also not willing to let the library grow much bigger and more complex unless there's a lot of interest in the feature. Anyway, this is an outline of how I think it *could* work.

The goal is to take a format like `D` and "expand" it to something like `MM/dd/yy` or `dd/MM/yy` based on the locale. The steps below work though that process, though I'm not saying each intermediate object must really be generated.

Step 1: Look up the token in the `Formats` class and pull out the Intl opts the correspond to it. So we get something like

```js
{
  year: 'numeric',
  month: 'numeric',
  day: 'numeric'
}
```

Step 2: use `formatToParts` with a dummy date to generate a list of tokens using those opts. 

```js
new Intl.DateTimeFormat('fr', fmt).formatToParts()
[ { type: 'day', value: '06' },
  { type: 'literal', value: '/' },
  { type: 'month', value: '12' },
  { type: 'literal', value: '/' },
  { type: 'year', value: '2017' } ]
```

Step 3:  We can map that back the input to get a list of almost-tokens. In the example below, note the new style key, which I've injected from looking up each unit in the original object. Also note that I've removed `value`; we don't care about that, just the ordering.

```js
[ { type: 'day', style: 'numeric'},
  { type: 'literal', value: '/'},
  { type: 'month', style: 'numeric'},
  { type: 'literal', value: '/' },
  { type: 'year', style: 'numeric' } ]
```

Step 4: Next, we need to know the tokens these correspond to. The inverse of this mapping is in the `TokenFormatter` class already as `unitForToken`, but we need `tokenForUnit` that takes in the unit ('day', etc) and the style ('numeric', 'short', etc) and returns a token like 'MM'. Now you know what token goes which each piece of the format. And you can glue that all together:

```js
'dd/MM/yy'
```

Step 5: This all needs wrapped into a function for expanding the string before the main parsing steps in, with a name like `expandMacroTokens`. It should return the string as-is if there are no macro tokens in it. It should process the string one token at a time; there might be other tokens, other literals, and even multiple macros in it. It should be called by the parsing code in a way that `fromStringExplain()` can return it explicitly as one of the fields.

**Comment by kshukost** [comment]
i was really surprised that this lib can format to 'D', but cannot parse it :((((
will just leave my small workaround here:

```
export const getLocalizedShortDateFormat = () => {
    const tokens = DateTime.fromObject({ year: 2018, month: 1, day: 1 }).toLocaleParts();

    const formats = tokens.map(token => {
        switch (token.type) {
            case 'day':
                return token.value.length === 1 ? 'd' : 'dd';
            case 'month':
                return token.value.length === 1 ? 'M' : 'MM';
            case 'year':
                return 'yyyy';
            default:
                return token.value;
        }
    });

    return formats.join('');
};
```
