### ISSUE TITLE
Unable to parse 7 digit milliseconds

### ISSUE THREAD

**Issue by w-a-b** [moment/luxon#1156]
**Describe the bug**
We have timestamps like '2022-01-25 00:06:30.1590000', but we are unable to parse them.

**To Reproduce**
We have tried different combinations:
DateTime.fromFormat('2022-01-25 00:06:30.1590000', 'yyyy-MM-dd HH:mm:ss.S')
DateTime.fromFormat('2022-01-25 00:06:30.1590000', 'yyyy-MM-dd HH:mm:ss.SSSSSS')

**Actual vs Expected behavior**
Expected successful parsing with 7 digit milliseconds, similar to https://github.com/moment/luxon/issues/757

**Desktop (please complete the following information):**
- Luxon version [e.g. 2.3.0]

**Comment by nahueldiazz** [comment]
hi, could you give me information on how to participate in this issues

**Comment by jmai00** [comment]
I'm having this issue also. Will there be support for longer than 3 digit milliseconds? I've only successfully converted up to 3 digit milliseconds.

**Comment by diesieben07** [comment]
The difference compared to `fromISO` is that `S` and `SSS` parse actual milliseconds. `fromISO` operates on _fractional seconds_. What does this mean? Adding more digits to fractional seconds means more precision (you can represent things shorter than milliseconds by adding more than 3 digits past the decimal point). While Luxon uses milliseconds internally, it makes sense to accept such formats.
But `S` and `SSS` parse the number of milliseconds. Adding more digits here means _a bigger number_. As such a millisecond value above 999 does not make sense, those would just be seconds.
If you want fractional seconds like in `fromISO`, use the `u` token, which supports up to 9 fractional digits.

**Comment by acierto** [comment]
What do you mean with does not make any sense? 

BigQuery format is:  `2024-03-27T00:00:00.001000` and luxon can't parse it, by closing this issue second time instead of fixing it
