### ISSUE TITLE
More robust performance testing

### ISSUE THREAD

**Issue by icambron** [moment/luxon#116]
See the comments at the top of: https://github.com/moment/luxon/blob/master/benchmarks/benchmark.js

**Comment by mannanali413** [comment]
@icambron i can take this up.

**Comment by mannanali413** [comment]
@icambron please have a look at the above PR. I hope it addresses the requirements you had listed earlier. Presently I have added the benchmark tests only for DateTime . 
Should I create a separate issue for the benchmark tests for other modules and raise another PR addressing the same?

**Comment by icambron** [comment]
Fixed in 8445647

@mannanali413 It's always fine for people to add more benchmarks, but I don't think there needs to be an explicit issue.
