### ISSUE TITLE
`Duration#toFormat` should support a formatting token for `week`

### ISSUE THREAD

**Issue by jsejcksn** [moment/luxon#1164]
I'm surprised that `Duration#toFormat` doesn't support a token for `week` (7 days). (e.g. `w`)

Is there a reason this unit token was omitted for Duration specifically?

Current release tag source ref: https://github.com/moment/luxon/blob/2.3.1/src/duration.js#L397-L426

**Comment by icambron** [comment]
No reason, just needs added. Would accept a PR

**Comment by jsejcksn** [comment]
@icambron I'm not familiar with the luxon source, but I can see that the unit needs to be added to this switch statement here:

https://github.com/moment/luxon/blob/2.3.1/src/impl/formatter.js#L355-L372

Are more modifications necessary besides updating the JSDoc?

**Comment by icambron** [comment]
@jsejcksn needs a test too, but that should be all
