### ISSUE TITLE
Directory build/es6/ needs a package.json file containing '"type":"module" or node won't be able to load it

### ISSUE THREAD

**Issue by mercmobily** [moment/luxon#1166]
**Describe the bug**
the package.json file is missing "type":"module" in it

**To Reproduce**
npm install :D

**Actual vs Expected behavior**

Right now, trying to import luxon gives this result in node:

````
import { DateTime } from 'luxon/build/es6/luxon.js'
         ^^^^^^^^
SyntaxError: Named export 'DateTime' not found. The requested module 'luxon/build/es6/luxon.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'luxon/build/es6/luxon.js';
const { DateTime } = pkg;
````

At the moment I am working around the problem by having this in my package.json:

````
"postinstall": "echo '{\"type\":\"module\"}' > node_modules/luxon/build/es6/package.json",
````

**Comment by icambron** [comment]
I mean, sure, we can add that.

But can I ask why you're using the ES6 one instead of just

```
import { DateTime } from "luxon"
```

**Comment by mercmobily** [comment]
> But can I ask why you're using the ES6 one instead of just `import { DateTime } from "luxon"`

Oh sure. I mean, the answer is easy. Very easy.
Because I am a brain dead, incompetent, useless cretin.

Sorry. Close.
