### ISSUE TITLE
Incorrect weekday for dates in first century

### ISSUE THREAD

**Issue by fwdekker** [moment/luxon#1167]
**Describe the bug**
Luxon returns incorrect weekdays for all dates starting from 0001-01-01 until 0099-12-31.

**To reproduce**
```javascript
DateTime.fromObject({year: 43, month: 4, day: 4}).weekdayLong  // "Sunday" (incorrect, should be "Saturday")
```

You can verify that `Saturday` is the correct answer by looking at the [Gregorian calendar](https://www.timeanddate.com/calendar/?year=43&country=22). Interestingly, Luxon's answer also does not correspond to the [Julian calendar](https://www.timeanddate.com/calendar/custom.html?year=43&country=23), since 0043-04-04 was a Thursday in the Julian calendar.

You can also verify that `Saturday` is the correct answer by looking at the date for the year 443, since the Gregorian calendar repeats exactly every 400 years:
```javascript
DateTime.fromObject({year: 443, month: 4, day: 4}).weekdayLong  // "Saturday" (correct)
```

**Actual vs expected behavior**
Luxon makes a calculation error when asked for the weekday of a date in the first century AD. Note that the given weekdays do not correspond to the Gregorian calendar nor to the Julian calendar (which was used in my country in the first century).

**Desktop (please complete the following information):**

- OS: Debian 12 (testing)
- Browser: Firefox 96.0.3
- Luxon version: v2.3.1
- Your timezone: "Europe/Amsterdam"

**Comment by FWDekker** [comment]
Luxon's answers correspond exactly to using interpreting two-digit years as being years in the 20th century. That is, it looks like the weekday calculation interprets `43` as being `1943`. Even when using `year: 0043`, the weekday calculation's answers correspond to years in the 20th century. Confusingly, the `year` field of a `DateTime` is parsed as being a year in the 1st century:
```javascript
DateTime.fromObject({year: "0043", month: 4, day: 4}).year  // 43 (a number, not a string)
```

I think there is a mismatch between how `weekday` interprets a two-digit year and how the remainder of the code interpret a two-digit year.
