### ISSUE TITLE
`luxon` global not available in dev console on API pages

### ISSUE THREAD

**Issue by h-h-h-h** [moment/luxon#1174]
**Describe the bug**
On the Luxon website, on all pages I checked, it says in the dev console: ``You can try Luxon right here using the `luxon` global, like `luxon.DateTime.now()` ``. [On the front page](https://moment.github.io/luxon/#/), this works. On the [API pages](https://moment.github.io/luxon/api-docs/index.html), it doesn't.

**To Reproduce**
- Visit [API page](https://moment.github.io/luxon/api-docs/index.html) and type `luxon` into dev console.

**Actual vs Expected behavior**
- The browser responds: `<h3 class="mb0 no-anchor" id="luxon">...</h3>`. This isn't the correct `luxon` global, but a DOM element.

**Desktop (please complete the following information):**

- OS: Windows
- Browser: I tested it in Firefox and Brave.
- Luxon version: N/A
- Your timezone: N/A

**Additional context**
The front page, like an API page, also has an HTML header element with `id="luxon"` (`<h2>`, [linked to in read-me](https://github.com/moment/luxon/blob/c9ded3019194af7fadcecc2072a59296e781471a/README.md?plain=1#L27)), but it doesn't trigger the same problem.

**Comment by icambron** [comment]
It seems to work now
