### ISSUE TITLE
Add docs section about missing leap second support

### ISSUE THREAD

**Issue by h-h-h-h** [moment/luxon#1176]
You can use the following draft I wrote or edit it before insertion (I have no idea *where* in the docs to insert it):

    # Leap Seconds

    Luxon doesn't take [leap seconds](https://en.wikipedia.org/wiki/Leap_second) into account, because it's a wrapper of JavaScript's `Date` and *it*, by specification, explicitly [ignores leap seconds](https://262.ecma-international.org/5.1/#sec-15.9.1.1). Admittedly, Luxon could correct for past leaps, relative to a version's release date, but future leaps are unpredictable and not every IANA time zone and their jurisdictions can be expected to follow the leaps exactly when they occur or at all.

    This means that, if you view a `DateTime` like `DateTime.now()`, that gives you the same time representation as an atomic clock accounting for leap seconds, as representing the current moment in time, a `DateTime` that reports `"1970-01-01T00:00:00.000+00:00"` is 27 seconds off (as of April 2022) toward the moment in time that string *actually* points to.

    When logging timestamps and later referencing them, the reported duration since an earlier timestamp can be slightly off when a leap second was involved. E.g., `DateTime.fromISO("2017-01-01T00:01:00.000+00:00").diff(DateTime.fromISO("2016-12-31T23:59:00.000+00:00")).toISOTime()` reports `"00:02:00.000"`, even though it *really* was `"00:02:01.000"`.

    `DateTime.utc(2016, 12, 31, 23, 59, 60).isValid` returns `false`, even though that second existed.

For reading:

> # Leap Seconds
>
> Luxon doesn't take [leap seconds](https://en.wikipedia.org/wiki/Leap_second) into account, because it's a wrapper of JavaScript's `Date` and *it*, by specification, explicitly [ignores leap seconds](https://262.ecma-international.org/5.1/#sec-15.9.1.1). Admittedly, Luxon could correct for past leaps, relative to a version's release date, but future leaps are unpredictable and not every IANA time zone and their jurisdictions can be expected to follow the leaps exactly when they occur or at all.
>
> This means that, if you view a `DateTime` like `DateTime.now()`, that gives you the same time representation as an atomic clock accounting for leap seconds, as representing the current moment in time, a `DateTime` that reports `"1970-01-01T00:00:00.000+00:00"` is 27 seconds off (as of April 2022) toward the moment in time that string *actually* points to.
>
> When logging timestamps and later referencing them, the reported duration since an earlier timestamp can be slightly off when a leap second was involved. E.g., `DateTime.fromISO("2017-01-01T00:01:00.000+00:00").diff(DateTime.fromISO("2016-12-31T23:59:00.000+00:00")).toISOTime()` reports `"00:02:00.000"`, even though it *really* was `"00:02:01.000"`.
>
> `DateTime.utc(2016, 12, 31, 23, 59, 60).isValid` returns `false`, even though that second existed.

---

> The POSIX way of basically making leap seconds disappear **except for when the actual leap second itself happens** kind of minimizes the impact for most common timekeeping situations.

(https://web.archive.org/web/20150112115749/https://www.wired.com/2015/01/torvalds_leapsecond/)

Is there anything about that that should be added to the text?

**Comment by icambron** [comment]
> Admittedly, Luxon could correct for past leaps, relative to a version's release date, but future leaps are unpredictable and not every IANA time zone and their jurisdictions can be expected to follow the leaps exactly when they occur or at all.

Meaning adjust diff calculations to include the extra seconds? I would leave that sentence out, not just because it's impractical for the reasons you state, but also because if we _were_ to do that, it would confuse everyone. 

>  a DateTime that reports "1970-01-01T00:00:00.000+00:00" is 27 seconds off (as of April 2022) toward the moment in time that string actually points to.

Either I have misunderstood you, or I think this is incorrect. It may be that 27 leap seconds have accumulated since the beginning of 1970, but it doesn't follow that the DateTime doesn't represent that time, or that it points to some other time. It represents that time just fine, because it's what it says it does. Unless, we are using Luxon to, like, calibrate a real-life time machine, it's unfalsifiable and sort of meaningless to say it represents a different time.

>  E.g., `DateTime.fromISO("2017-01-01T00:01:00.000+00:00").diff(DateTime.fromISO("2016-12-31T23:59:00.000+00:00")).toISOTime()` reports `"00:02:00.000"`, even though it *really* was `"00:02:01.000"`.

This the relevant practical point: that slightly more time has passed in the outside world than Luxon computes. This has a very limited set of circumstances in which it matters, but it's real enough.

> `DateTime.utc(2016, 12, 31, 23, 59, 60).isValid` returns `false`, even though that second existed.

Fair enough, this is a point worth making. Luxon doesn't allow you to represent that moment in time.

However, zooming out a bit: in general, with docs, the right thing to do is to focus on the impact to the developer. With leap seconds, like you point out, it's very minimal. They may be even more minimal than you think: NTP systems increasingly use a smear and distribute the discontinuity over 24 hours.

Nevertheless, I think we can expand that section, which currently looks like this:

> Don't worry about leap seconds. JavaScript and most other programming environments don't account for them; they just happen as abrupt, invisible changes to the underlying system's time.

(from [here](https://github.com/moment/luxon/blob/master/docs/math.md)).

Perhaps something like:

> Luxon (and JavaScript in general) doesn't account for leap seconds; as in most programming environments, leap seconds happen as invisible changes to the underlying system's time. In practice, this has no effect on the vast majority of applications, and my sincere advice is ignore leap seconds altogether. 

> The practical effect of leaps seconds is:

> 1. you can't represent the leap second itself (i.e. `DateTime.utc(2016, 12, 31, 23, 59, 60).isValid` returns `false`)
> 2. a  Luxon diff calculation that crosses a leap second will not exactly match the number of seconds that passed in the outside world. This can come up in rare situations where it matters to your application exactly what happened in the last N seconds. Even this is increasingly mitigated by [Leap Smear](https://developers.google.com/time/smear).

**Comment by h-h-h-h** [comment]
The [Wikipedia article](https://en.wikipedia.org/wiki/Leap_second) should still be linked.

---

> > a DateTime that reports "1970-01-01T00:00:00.000+00:00" is 27 seconds off (as of April 2022) toward the moment in time that string actually points to.
> 
> Either I have misunderstood you, or I think this is incorrect. It may be that 27 leap seconds have accumulated since the beginning of 1970, but it doesn't follow that the DateTime doesn't represent that time, or that it points to some other time. It represents that time just fine, because it's what it says it does. Unless, we are using Luxon to, like, calibrate a real-life time machine, it's unfalsifiable and sort of meaningless to say it represents a different time.

My view is that there is a timeline Luxon's logic is connected to, and that timeline doesn't know about leap seconds. The library as a whole presents its own universe with its own timeline, so to speak, because its capable of duration calculations. Who says it's the duration that's wrong? It's a matter of viewpoint. It can also be the points in time that are wrong (or just one), while the duration is viewed as correct -- especially when your source data is a point in time and a duration, and the target data is a point in time. (That's why I wrote "if you view a DateTime like DateTime.now() [...] as representing the current moment in time".) Should this be added as point 3?

---

Do NTP syncs happen frequently enough in the context of leap smear, so individual machines rarely encounter double-seconds (only on internet outages)? If a sync happens, say every 48 hours, there's a double-second again and it's not necessarily invisible.

**Comment by icambron** [comment]
NTP syncs on most systems defaults to every 64 seconds, so if you're hooked up to a leap smear system, you're good. Of course, maybe you just powered on your computer or came online and you'll still see the double second. So it's not perfect, but it's pretty good.

> My view is that there is a timeline Luxon's logic is connected to, and that timeline doesn't know about leap seconds. The library as a whole presents its own universe with its own timeline, so to speak, because its capable of duration calculations. Who says it's the duration that's wrong? It's a matter of viewpoint. It can also be the points in time that are wrong (or just one), while the duration is viewed as correct -- especially when your source data is a point in time and a duration, and the target data is a point in time. (That's why I wrote "if you view a DateTime like DateTime.now() [...] as representing the current moment in time".) Should this be added as point 3?

I think I see what you mean, and I roughly agree, but I don't think it has much practical utility and veers into sort of philosophical territory. It's really the same point as 2, but with a bit of "what is time anyway?" added. For practical purposes, and again in the absence of time machines, all the developer really wants to know is "what behavior does Luxon have that I might not be expecting?"
