### ISSUE TITLE
support for n-th token?

### ISSUE THREAD

**Issue by dnalborczyk** [moment/luxon#118]
Is there an equivalent for 1st, 2nd, 3rd etc. for luxon?  I was looking through the documentation, but couldn't find anything regarding this topic.

compare to:
http://momentjs.com/docs/#/displaying/format/   e.g. DDDo, Do, Mo, wo etc.

**Comment by icambron** [comment]
No, there's nothing for that. Luxon relies on [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) to handle numbers, and it would need to support for nd, rd, th, etc in arbitrary locales, which it does not. When (and if) that API gains that capability, I will be able to add to Luxon too.

**Comment by zposten** [comment]
This function should do the trick (for English at least)

```js
function getNumberSuffix(num) {
  const th = 'th'
  const rd = 'rd'
  const nd = 'nd'
  const st = 'st'

  if (num === 11 || num === 12 || num === 13) return th

  let strNum = num.toString()
  let lastDigit = Number(strNum[strNum.length - 1])

  switch (lastDigit) {
    case 1:
      return st
    case 2:
      return nd
    case 3:
      return rd
    default:
      return th
  }
}
```

**Comment by Ciboulette** [comment]
Or you can do this 😬

```js
function ordinal(n) {
  var s = ["th", "st", "nd", "rd"];
  var v = n%100;
  return n + (s[(v-20)%10] || s[v] || s[0]);
}
```

**Comment by SlyDave** [comment]
This is supported via Intl.PluralRules setting it to mode: ordinal ?
example for n-th token: https://v8.dev/features/intl-pluralrules

**Comment by icambron** [comment]
Nifty. Yeah, I would take a PR that uses that to implement some new formatting/parsing tokens

**Comment by cjolif** [comment]
FYI I'll try to issue a PR about this in the coming weeks. So if someone else works on that, let me know :)

**Comment by cjolif** [comment]
Hmm actually `Intl.PluralRules` does give us the rule to apply based on the locale but not the actual formatting based on the rule. So this would still mean adding to luxon a map from the plural rules to the different languages formats. I suspect this is not what you had in mind @icambron? So we still have to wait on that?

**Comment by SlyDave** [comment]
> Hmm actually `Intl.PluralRules` does give us the rule to apply based on the locale but not the actual formatting based on the rule.

True, but you have Intl available so all that needs to happen is to pass the result to that to change local afterwards, no?

First work out the resulting rule from PluralRules, map to English st, nd, rd, th. Then plug into Intl. Or see if the Intl already contains the mapping for the one/two/many/other for each language

**Comment by cjolif** [comment]
>  map to English st, nd, rd, th.

That's where the issue is? Luxon would have to contain that mapping code for "all" locales? (Intl does not have that mapping as far as I can see but would be happy to be proved wrong!).

**Comment by icambron** [comment]
OK, I spent some more time here. @cjolif is correct. The PluralRules would let us figure out which of the strings to use in what situation, but not what the strings actually are. Maintaining those strings is ICU's job, not Luxon's. We're not going to add scores of these:

```js
const suffixes = new Map([
  ['one',   'st'],
  ['two',   'nd'],
  ['few',   'rd'],
  ['other', 'th'],
]);
```

I believe `Intl.NumberFormat` should add an option for this...
