### ISSUE TITLE
setZone('system') is using the Timezone in Settings.defaultZone, not the browser Timezone

### ISSUE THREAD

**Issue by benjaminpick** [moment/luxon#1182]
**Describe the bug**
When using an explicit value in Settings.defaultZone (e.g. 'Asia/Kolkata'), the method `setZone('system')` is not changing the timezone - because 'system' appears to mean "whatever is set in Settings.defaultZone, or, if this is set to 'system', then use the Browser Timezone."

**To Reproduce**
https://codesandbox.io/s/modest-haze-s766q6?file=/src/index.js
```js
const LOCAL_TIMEZONE = "Asia/Kolkata";

Settings.defaultZone = LOCAL_TIMEZONE;
const dt = DateTime.now(); // 2022-04-14T21:56:54.028+05:30 (LOCAL_TIMEZONE)
const zoned = dt.setZone("system", { keepLocalTime: true }); // 2022-04-14T21:56:54.028+05:30 (actual: LOCAL_TIMEZONE, expected: Browser Timezone)

Settings.defaultZone = "system";
const zoned2 = dt.setZone("system", { keepLocalTime: true }); // 2022-04-14T21:56:54.028+02:00 (Browser Timezone)
```

**Actual vs Expected behavior**
I would have expected `zoned` to be in the same timezone as `zoned`. As far as I see it, there is no other possibility to access the "system" timezone without changing the defaultZone. 

I find this confusing because the documentation says: 
`By default, Luxon creates DateTimes in the system's zone. However, you can override this behavior globally:`
Also, the keyword 'system' means something else in `setZone('system')` and in Settings.defaultZone

For backwards compatibility, we probably can't change the meaning of the 'system' timezone now. So I suggest to add a new keyword 'browser':

```js
Settings.defaultZone = LOCAL_TIMEZONE;
const dt = DateTime.now(); // 2022-04-14T21:56:54.028+05:30 (LOCAL_TIMEZONE)
const zoned = dt.setZone("browser", { keepLocalTime: true }); // should be 2022-04-14T21:56:54.028+02:00 (Browser Timezone)
Settings.defaultZone = 'browser'; // should be an alias of 'system'
```
and clean up the wording in the documentation accordingly.

**Use-Case**
In my case, all datetimes are in a certain defaultZone (of a local event), because the times need to be shown in local time. However, a datepicker library expects the dates to be in browser time, so I need to create a "zoned" Date object via 'keepLocalTime'.

**Comment by icambron** [comment]
Yeah, I agree:

- "system" should always mean system
- "default" should mean "whatever is in Settings.defaultZone, which may or may not be "system""

**Comment by davkub** [comment]
Hello @icambron I would like to take a look into this issue. Is this issue free to work on?

**Comment by icambron** [comment]
@davkub yup!
