### ISSUE TITLE
make DateTime object available through the dev console in the docs site

### ISSUE THREAD

**Issue by iamzapata** [moment/luxon#1183]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to play with the api while on the docs site

**Describe the solution you'd like**
Similar to what [moment's site](https://momentjs.com/) does, you can play with the moment object in the dev console.

**Additional context**
I haven't gone through all of the docs, but if this is already available (through something different than DateTime), it would be nice to have it somewhere in the docs.

**Comment by icambron** [comment]
This currently works on the "main" site, but doesn't seem to work in the generated API docs, because a DOM node with id=luxon overrides the global. Would take a fix

**Comment by huilibaba** [comment]
Hey @icambron, 

I have tested the API docs page and the DateTime object is now available through dev console as expected ✔️

This issue has been resolved and can be closed.
