### ISSUE TITLE
fromISO method is not able to parse time if hour is less than 10.

### ISSUE THREAD

**Issue by nikhilece2011** [moment/luxon#1185]
**Describe the bug**
fromISO method is not able to parse time if hour is less than 10. while it is able to parse if I pass hour greater than 10 for instance 11 or 12. 

I am passing time to get ISO 8601 format and it is a string like "06:51" where 6 indicates to hour and 51 indicates minutes. 
When I passing anything greater than 10:00 than it is able to parse time and not working for less than 10:00. Any idea ?

**To Reproduce**
Using the something like this - DateTime.fromISO(this.timeValue);

**Actual vs Expected behavior**
I am expecting to parse any time from this method.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] - Windows 10
- Browser [e.g. Chrome 84, safari 14.0] - Chrome 100.0.4896.127 64 Bit
- Luxon version [e.g. 1.25.0] - 1.26.0
- Your timezone - EST

**Comment by icambron** [comment]
@nikhilece2011 You're going to have to make something directly reproduceable, like a JSFiddle or similar. Certainly seems to work for me:

```
// today at 11:34
DateTime.fromISO("11:34").toISO()   //=> '2022-04-21T11:34:00.000-04:00'

// august 6 at 11:34
DateTime.fromISO("2022-08-06T11:34").toISO()  //=> '2022-08-06T11:34:00.000-04:00'  
```

**Comment by nikhilece2011** [comment]
@icambron  Did you try with `DateTime.fromISO("1:34")` ? and do I also need to add `toISO()`  along with `fromISO()` ?

**Comment by nikhilece2011** [comment]
@icambron check this screenshot 

![image](https://user-images.githubusercontent.com/77094088/164434337-c4be68b0-0fc7-48a0-bfd0-e153d67cc73f.png)

**Comment by nikhilece2011** [comment]
@icambron  It is strange but it works when I pass 06:51 but failing on 6:51.

**Comment by icambron** [comment]
Ah, I misread your original. Well, right, "6:51" isn't a valid ISO 8601 string, which require two digits for the hour; that's just how the format works. You can parse that string with Luxon's `fromFormat()` if you'd like: 

```
DateTime.fromFormat("6:51", "H:mm").toISO()                                                                                                                                                                                                                                                                                                                                                 
'2022-04-21T06:51:00.000-04:00'   
```

The `toISO()` is just me turning the Luxon object back into a string so it's easier to read the result.
