### ISSUE TITLE
NodeJS issues with `weekdayLong`

### ISSUE THREAD

**Issue by marcalj** [moment/luxon#1187]
I have NodeJS v16 installed in two linux systems. In one those tests are passing, and in the other one are failing since one is returning `Friday` and the other `Fri`.

Tests:

```
 it('test', () => {
    const sessionDay = DateTime.fromJSDate(new Date(), { zone: 'utc' });
    expect(sessionDay.weekday).toEqual(5); // Works on both
    expect(sessionDay.toFormat('cccc')).toEqual('Friday'); // Works on both
    expect(sessionDay.weekdayLong).toEqual('Friday'); // Fails
    expect(sessionDay.toLocaleString({ weekday: 'long' })).toEqual('Friday'); // Fails
 });
```
Luxon version: v2.3.2

Which could be the issue? Thanks!

PD: I've implemented a simple mapping function since I've read `weekdayLong` is slow: https://github.com/moment/luxon/issues/775

Thanks!

**Comment by icambron** [comment]
Not sure, but it's always good test what the Intl API thinks the answer is. Like so:

```js
> new Intl.DateTimeFormat("en-US", { weekday: "long" }).format(new Date(2022, 4, 6))   //=> 'Friday'    
```

If that gives you "Fri" instead of Friday, there's something wrong with your installation of Node. Perhaps the ICU data is installed in some funny way? OTOH, if that gives "Friday" but Luxon still uses "Fri", then it's a Luxon bug. The latter seems unlikely, since it works on one of your systems.

**Comment by marcalj** [comment]
Thanks Isaac, I guess it would be something related to NodeJS ICU data since I manually installed NodeJS from the official site in the system which the tests are failing.

Would be nice to have some check for NodeJS projects, so it's esier to find the root cause if fails.

Have a great day!

**Comment by icambron** [comment]
Luxon only interacts with ICU through the Intl API. The ICU data is just affecting the implementation of that API in your environment, so anything weird there is effectively invisible to Luxon.

FWIW, recent Node releases come with all the ICU data in place, and I run all tests in an unaltered Node 17 installation, both on both Linux and OSX. Node is the environment where Luxon the best test coverage.
