### ISSUE TITLE
DateTime.fromFormat does not handle zone correctly

### ISSUE THREAD

**Issue by gquittet** [moment/luxon#1198]
**Describe the bug**

DateTime.fromFormat does not handle zone correctly.

Only UTC zone is working as expected.

**To Reproduce**
Please share a minimal code example that triggers the problem:

```javascript
// You can also use: Intl.DateTimeFormat().resolvedOptions().timeZone
console.log("My timezone", DateTime.local().zoneName)

const brussels = DateTime.fromFormat("Friday 23:00", "cccc HH:mm", { zone: "Europe/Brussels" });
console.log(brussels.zoneName, brussels.toString())

const newYork = DateTime.fromFormat("Friday 23:00", "cccc HH:mm", { zone: "America/New_York" });
console.log(newYork.zoneName, newYork.toString())

const utc = DateTime.fromFormat("Friday 23:00", "cccc HH:mm", { zone: "UTC" })
console.log(utc.zoneName, utc.toString())
```

Result:

![image](https://user-images.githubusercontent.com/11082739/166707843-a70a137e-d18e-42f1-b405-a01b9584cada.png)

You can also try the example from: https://github.com/moment/luxon/blob/master/docs/zones.md#creating-datetimes-in-a-zone

```javascript
var overrideZone = DateTime.fromISO("2017-05-15T09:10:23", { zone: "Europe/Paris" });

overrideZone.zoneName; //=> 'Europe/Paris'
overrideZone.toString(); //=> '2017-05-15T09:10:23.000+02:00'
```

Output:

![image](https://user-images.githubusercontent.com/11082739/166727367-b8d5430f-f8e2-4950-bcd4-c2069537b667.png)

**Actual vs Expected behavior**

Normally, the test date should be +02:00, not +13:00. +13:00 is my local timezone.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows
- Browser [e.g. Chrome 84, safari 14.0] Chrome 101.0.4951.41
- Luxon version [e.g. 1.25.0] 2.3.2
- Your timezone [e.g. "America/New_York"] Pacific/Apia

**Comment by gquittet** [comment]
Temporary we can use `Intl.DateTimeFormat` as an alternative:

```javascript
Intl.DateTimeFormat("en-GB", { weekday: "long", timeZone: "Europe/Brussels" }).format(new Date("2022-05-06 23:00:00"));
````

instead of 

```javascript
DateTime.fromFormat("Friday 23:00", "cccc HH:mm", { zone: "Europe/Brussels" });
```

I choose 6th May 2022 just because it's Friday.

**Comment by icambron** [comment]
Are you on the latest Luxon? What browser are you using? Because this is the output I get on Chrome:

```js
My timezone America/New_York
Europe/Brussels 2022-05-06T23:00:00.000+02:00
America/New_York 2022-05-06T23:00:00.000-04:00
UTC 2022-05-06T23:00:00.000Z
```

**Comment by gquittet** [comment]
I'm using the latest version of luxon with Angular built with Node 16.

As you read in the issue, I'm using the latest version of Chrome running on Windows 10.

**Comment by gquittet** [comment]
Sorry, it's working fine when I'm using the `Sensors` tab from the Chrome Developer Tools.

I was using this Chrome extension that was the issue: https://chrome.google.com/webstore/detail/change-timezone-for-googl/cejckpjfigehbeecbbfhangbknpidcnh

I close it.
