### ISSUE TITLE
Documentation specifies wrong object format for some DateTime methods

### ISSUE THREAD

**Issue by OliverJAsh** [moment/luxon#120]
Hey! First of all, thanks for your work on this project. :-)

The documentation for math methods like `plus` and `minus` specify the argument can be:

> the object argument to Duration.fromObject()

However, this object has type:

``` ts
{
  day?: number;
  …
}
```

… whereas math methods receive a delta:

``` ts
{
  days?: number
  …
}
```

Perhaps this is a `Duration`?

Can we correct the documentation? Or am I mislead?

**Comment by OliverJAsh** [comment]
Apologies, I misread. It does say it can receive a `Duration`:

> Either a Luxon Duration,

**Comment by icambron** [comment]
@OliverJAsh `Duration.fromObject()` accepts `day` or `days`, whereas the Duration itself only has `days`. I'm glad you sorted this out, but I'm also not sure what you meant: where is the type for the `fromObject` arg specified like that? The only place I know of is [here](https://moment.github.io/luxon/docs/class/src/duration.js~Duration.html#static-method-fromObject) which specifies `days` to match Duration itself.

**Comment by icambron** [comment]
Oh, you meant some third party Flow or TS types...Those should use the plurals for periods of time even though Luxon is also willing to take the singular versions.
