### ISSUE TITLE
Multiple string date formats for "fromString" method

### ISSUE THREAD

**Issue by adwinang** [moment/luxon#1202]
**Is your feature request related to a problem? Please describe.**
I am dealing with a data set where the date string values are not consistent throughout due to data coming from many sources. I had to create many if else statements to test whether the datetime is valid and it resulted in many lines of code just for the if else statement.

**Describe the solution you'd like**
Instead of just accepting a single format string in the "fromString" method, accept an array of string formats.

**Describe alternatives you've considered**
Many if else statement is the only solution that I know of

**Comment by icambron** [comment]
I don't understand; why not just make a list the formats you support and iterate through them?

**Comment by adwinang** [comment]
Geez, my brain fart, for some reason I didn't think of that
