### ISSUE TITLE
Add optional argument to DateTime#toJSDate() to preserve timezone or time offset

### ISSUE THREAD

**Issue by ksze** [moment/luxon#1203]
**Is your feature request related to a problem? Please describe.**
Right now, `DateTime#toJSDate()` will always return a JavaScript `Date` object converted to UTC (in Node.js anyway). That behaviour is not explained in the documentation and is a little unintuitive/surprising. If I have a luxon `DateTime` object in "Asia/Tokyo" timezone and I call `toJSDate()`, I expect the resulting JavaScript `Date` object to be in that timezone as well.

**Describe the solution you'd like**
In order to not break existing code, I would suggest adding an optional argument (which defaults to false), to control whether the resulting JS `Date` object is in UTC or in the original timezone.

**Comment by ties-s** [comment]
@ksze is this fixed or do you just don't need it anymore?

**Comment by icambron** [comment]
As written, this issue doesn't make sense. JS Dates don't support time zones. A date is always "in" the local zone of the computer it's running on. That's a limitation of the JS date API, not Luxon.

So anyone finding themselves here should think carefully about what behavior they expect to get out of Luxon, and once you have that nailed down, you can create a new issue detailing that, though I suspect you'll find Luxon already has what you need.
