### ISSUE TITLE
Asia/Tokyo timezone offsetNameShort is wrong

### ISSUE THREAD

**Issue by phatcatmatt** [moment/luxon#1208]
**Describe the bug**
The offsetNameShort for the 'Asia/Tokyo' timezone is "GMT+9" instead of "JST" even though the offsetNameLong is correctly returned as 'Japan Standard Time'

**To Reproduce**
`DateTime.fromMillis(Date.now() {zone: 'Asia/Tokyo}).offsetNameShort` returns `GMT+9`

**Actual vs Expected behavior**
`DateTime.fromMillis(Date.now() {zone: 'Asia/Tokyo}).offsetNameShort` returns `JST`

**Comment by icambron** [comment]
Luxon gets the strings from the built-in Intl API, which pulls them from ICU. And unfortunately they don't have every offset name in every language.

```js
new Intl.DateTimeFormat("en", { timeZoneName: "short", timeZone: "Asia/Tokyo" }).format() //=> '5/19/2022, GMT+9'
new Intl.DateTimeFormat("en", { timeZoneName: "long", timeZone: "Asia/Tokyo" }).format() //=> '5/19/2022, Japan Standard Time'
```

So that's unfortunate, but there's nothing Luxon can do about it.

**Comment by phatcatmatt** [comment]
Fair enough. Might be worth mentioning in the documentation. Thanks!
