### ISSUE TITLE
DateTime.FromISO broken using browserify

### ISSUE THREAD

**Issue by Inkata** [moment/luxon#121]
I installed luxon vía npm, then bundled using browserify,

Datetime.local() works, but not much more. 

Datetime.fromISO() and some math comparisons do not work. I haven't tested thoroughly.

```
luxon.DateTime.local()
> {ts: 1512859181236, zone: t, loc: e, invalid: null, weekData: null, …}

luxon.DateTime.fromISO('2017-05-15')
node_modules.js:1 Uncaught TypeError: Invalid attempt to destructure non-iterable instance

```

I know it's not listed in the docs as a supported installation procedure, but wanted you to know.

Thanks!

**Comment by icambron** [comment]
Interesting. I'd like to fix this but I don't know anything about Browserify.

Also, what browser did you end up running this on?

**Comment by Inkata** [comment]
Firefox 57 and chromium 62,  both fail. 

If loaded via script tag, both work. It's just the bundling from node to the browser that's broken.

**Comment by icambron** [comment]
Well, those two cases use different builds so I was checking whether the targeting was right. But those are nice new browsers, so that's not the problem. So, yeah, I have no idea why it's not working.

**Comment by tswaters** [comment]
Seems to work fine for me -- latest chrome/firefox.

See following repo:  https://github.com/tswaters/luxon-issue-121 -- visiting `index.html` doesn't raise an error and the output is logged properly to the console.

Can you provide a reduced test case (repo) or possibly send a PR to that repo that highlights the problem?

**Comment by icambron** [comment]
I'm going to close this for age. @Inkata if you can provide more info, I'll reopen.
