### ISSUE TITLE
Feature request: Introduce an option in diff() for excluding hours(e.g. non-working hours, weekend hours), days e.t.c from the calculation

### ISSUE THREAD

**Issue by ghuser** [moment/luxon#1210]
**Is your feature request related to a problem? Please describe.**

One feature we often need is to be able to calculate the difference between two dates (e.g. in hours) but excluding non-working hours  and weekends. One example case of this is to be able to report the hours it took for an issue to be resolved  but calculated in working hours (or SLA support hours).

**Describe the solution you'd like**

One way (api-wise) to achieve this would be to introduce an extra `DateTime.diff()` option `excludedWeekHours` whose value is a 7-positions array (one for each day of the week) containing hour arrays with values `0-23` on each position. Since `DateTime` contains a timezone these hours would by default be considered on that timezone.

example
```js
//exclude hours outside weekdays `8.00-18.00`.
let excludedWeekendHours = [...Array(24).keys()] //[0, 1, 2, 3, 4, 5, 6, 7, 19, 20, 21, 22, 23]
let excludedWeekdayHours = [...Array(8).keys()].concat([...Array(5).keys()].map(v=>v+19))   //[0, 1, 2, 3, 4, 5, 6, 7, 19, 20, 21, 22, 23]
let excludedWeekHours = [excludedWeekendHours, ...Array(5).fill(excludedWeekdayHours),  excludedWeekendHours]


dt.diff(otherDateTime, {excludedWeekHours});

```

The above feature could be expanded also to `excludedMonthDays` or `excludedMonthHours` e.t.c.

**Describe alternatives you've considered**

An alternative solution could be to provide a callback function in options like `{hoursFilter: (dateTime)=>workingHoursFilter(dateTime) }` which would execute for each hour of the given range. One implementation option would be to not change the current implementation for diff calculation. Just to append one step at the end, which would "walk" the hours from startDate to endDate and subtract the excluded ones from the already calculated result. 
Other filters could be `daysFilter`, `minutesFilter` (being executed for each minute or day in the range)

**Additional context**

**Comment by icambron** [comment]
I think we're very unlikely to add this. It's not that I don't think it's useful, it's just a big piece of scope, and I don't want to add big features to Luxon. I think it would be better off in another library.

I don't think this is quite what you're looking for, but here's something similar: https://github.com/amaidah/luxon-business-days
