### ISSUE TITLE
Zone option not working on `DateTime.fromObject`

### ISSUE THREAD

**Issue by hs737** [moment/luxon#1217]
**Describe the bug**
I have been trying to use luxon's `DateTime.fromObject` constructor for some time now with a timezone option in Typescript. For some reason, no matter how I try to use the `zone` attribute of the DateTime options, I don't see the zone applied. I would expect that with different timezone's interpretations, I would see different ISO times outputted. 

According to the documentation in these links, I would have expected the following to work.
* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/datetime.d.ts#L585
* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/datetime.d.ts#L314
* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/datetime.d.ts#L306

This seems like a bug to me, but let me know if I'm misunderstanding or misusing the API. 

**To Reproduce**
I am able to see this in my command line node interpreter
```js
$ node
Welcome to Node.js v16.14.0.
Type ".help" for more information.
> let luxon = require('luxon')
undefined
> let a = luxon.DateTime.fromObject({hour:12}, {zone:luxon.IANAZone.create('Asia/Tokyo')})
undefined
> let b = luxon.DateTime.fromObject({hour:12}, {zone:luxon.IANAZone.create('America/New_York')})
undefined
> let c = luxon.DateTime.fromObject({hour:12}, {zone:luxon.IANAZone.create('America/Anchorage')})
undefined
> a.toISO()
'2022-06-07T12:00:00.000-04:00'
> b.toISO()
'2022-06-07T12:00:00.000-04:00'
> c.toISO()
'2022-06-07T12:00:00.000-04:00'
> a.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
> b.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
> c.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
```

```js
> let x = luxon.DateTime.fromObject({hour:12}, {zone:'Asia/Tokyo'})
undefined
> let y = luxon.DateTime.fromObject({hour:12}, {zone:'America/New_York'})
undefined
> let z = luxon.DateTime.fromObject({hour:12}, {zone:'America/Anchorage'})
undefined
> x.toISO()
'2022-06-07T12:00:00.000-04:00'
> y.toISO()
'2022-06-07T12:00:00.000-04:00'
> z.toISO()
'2022-06-07T12:00:00.000-04:00'
> x.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
> y.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
> z.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
```

```js
> let m = luxon.DateTime.fromObject({hour:12}, {zone:'utc'})
undefined
> let n = luxon.DateTime.fromObject({hour:12}, {zone:'local'})
undefined
> m.toISO()
'2022-06-07T12:00:00.000-04:00'
> n.toISO()
'2022-06-07T12:00:00.000-04:00'
> m.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
> n.toUTC().toISO()
'2022-06-07T16:00:00.000Z'
```

**Actual vs Expected behavior**
I would imagine that the same time interpreted in different timezones would have different underlying times, even if the input hour is the same. 

**Desktop (please complete the following information):**

- OS: macOS 12.3.1
- Environment: NodeJS
- Luxon version: 
-- "luxon": "1.28.0"
-- "@types/luxon": "2.3.0",
- My timezone: "America/New_York"

Thanks for any comments and help!

**Comment by icambron** [comment]
Luxon 1.x had the zone key as part of the first arg. In 2.0, we moved it to a second arg that contains config options, so that's what's documented now. So you're just using the wrong parameterization for the version you're on. I recommend upgrading, but that's up to you.

**Comment by hs737** [comment]
Thank you! This was very helpful 🙏
