### ISSUE TITLE
Partial shiftTo() in durations like in moment.js

### ISSUE THREAD

**Issue by feralheart** [moment/luxon#1226]
I have a duration millisecond what I want to cast to human readable form. 
This duration can be just a few seconds or days as well. It would be good if the zero values would be optional. 
For example if it's only 30 seconds the output should be '30seconds' and not '0days 0hours 0minutes 30seconds'

Before migrating to Luxon, I could achieve this in moment like this:
`moment.duration(value).format(' D [days], H [hrs], m [mins], s [secs]')`

**Comment by icambron** [comment]
See [duration.toFormat](https://moment.github.io/luxon/api-docs/index.html#durationtoformat). You might also consider [duration.toHuman](https://moment.github.io/luxon/api-docs/index.html#durationtohuman)
