### ISSUE TITLE
`Duration#normalize` has trouble with negative milliseconds

### ISSUE THREAD

**Issue by elliott-king** [moment/luxon#1233]
**Describe the bug**
Fails to normalize a Duration with negative milliseconds.

**To Reproduce**
I was able to repro this in the playground in the docs:
```javascript
> luxon.VERSION
'2.4.0'

> let d = luxon.Duration.fromObject({seconds: -44, milliseconds: -100, minutes: 1})

> d.normalize()
Duration {values: {…}, loc: Locale, conversionAccuracy: 'casual', invalid: null, matrix: {…}, …}
...
values: {seconds: 16, milliseconds: -100, minutes: 0}
```

I would expect the above to be {seconds: 15, milliseconds: 900, minutes: 0}

Out of curiosity, I tried the initializing the "right" duration, and it has no issues normalizing:

```javascript
> let m = luxon.Duration.fromObject({seconds: 15, milliseconds: 900})

> m.normalize()
Duration {values: {…}, loc: Locale, conversionAccuracy: 'casual', invalid: null, matrix: {…}, …}
...
values: {seconds: 15, milliseconds: 900}
```

**Actual vs Expected behavior**
Since the overall duration is greater than zero, I expect all normalized fields to be greater than zero.

**Desktop (please complete the following information):**

- OS: MacOS 11.6.5
- Browser: Chrome Version 102.0.5005.115 (Official Build) (x86_64)
- Luxon version: 2.4.0 (used your playground)
- Your timezone "America/New_York"

**Additional context**
This library is excellent, by the way!

**Comment by elliott-king** [comment]
Possibly unrelated: I would also expect `normalize` to change 66 seconds into a combination of seconds & minutes:
```javascript
> luxon.Duration.fromObject({days: 777}).normalize()
...
values: {days: 777}

> luxon.Duration.fromObject({milliseconds: 15900}).normalize()
...
values: {milliseconds: 15900}
```

**Comment by icambron** [comment]
Yeah, that could definitely use some improvements

**Comment by CristiMacovei** [comment]
@icambron Can I solve this issue?

**Comment by ZainGulbaz** [comment]
@icambron Can you please assign this to me? Thanks.

**Comment by thomassth** [comment]
Hi @icambron , would you mind checking out #1467 ? I've included a test that'd fail in current builds, but passing after PR.
