### ISSUE TITLE
Convert date to specific locale, without changing language

### ISSUE THREAD

**Issue by syllith** [moment/luxon#1235]
` return DateTime.fromISO(date).toRelativeCalendar({ locale: navigator.language });`

Take this code for example. If my clients browser navigator.language is set to "en", it will say something like "yesterday"

However, if I change it to say "es", it will comeback with the correct date, but, it also comes back in Spanish. I'd like it to calculate the date the same way, but report back to me in english. Is this possible?

**Comment by icambron** [comment]
I'm confused on what you're trying to accomplish. The _only_ thing `locale` controls is the language. So if you want it be in English, you can just pass "en" there.

**Comment by syllith** [comment]
Oh? I think I was just misunderstanding something. It seems you are correct. So just so I know for future reference, how exactly does Luxon get the users current time zone? If locale only controls language, what method does it use to determine the timezone it needs to convert the provided date to?

**Comment by syllith** [comment]
Sorry, I definitely misunderstood something. The locale would of course change the language only. Locale doesn't specify time zone. That was just a brain fart on my end. I'd still like to know what method it uses to determine time zone, just so I know for future reference. How does it know what timezone the user is in?

**Comment by icambron** [comment]
Luxon automatically uses the user's current time zone -- it's the default for everything. You only need to set the zone on a DateTime if you want to work with times in some _other_ zone. To do that, use `setZone()`, and read https://moment.github.io/luxon/#/zones

And while you don't need to specify it directly (in the vast majority of cases), the user's zone is

```js
Info.normalizeZone("system").name //=> "America/New_York"
```

**Comment by syllith** [comment]
Cool, thank you so much. You answered my question and my codes all working as intended now. Appreciate it!
