### ISSUE TITLE
Pod install fails with react-native build which includes luxon

### ISSUE THREAD

**Issue by ajp8164** [moment/luxon#1238]
**Describe the bug**
For a react-native project; can't install luxon and `pod install`. Reported error is..

```
[!] Invalid `Podfile` file: 783: unexpected token at 'Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/Andy/Development/ajp/AwesomeProject/node_modules/luxon/package.json

    at new NodeError (node:internal/errors:388:5)

    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)

    at packageExportsResolve (node:internal/modules/esm/resolve:719:3)

    at resolveExports (node:internal/modules/cjs/loader:488:36)

    at Module._findPath (node:internal/modules/cjs/loader:528:31)

    at Module._resolveFilename (node:internal/modules/cjs/loader:932:27)

    at Function.resolve (node:internal/modules/cjs/helpers:108:19)

    at resolveNodeModuleDir (/Users/Andy/Development/ajp/AwesomeProject/node_modules/@react-native-community/cli-tools/build/resolveNodeModuleDir.js:24:42)

    at /Users/Andy/Development/ajp/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:93:76

    at Array.reduce (<anonymous>)

info Run CLI with --verbose flag for more details.
'.
```

**To Reproduce**
1. Create new react native project using `npx react-native init AwesomeProject`
2. `cd AwesomeProject && npm i && cd ios && pod install && cd ..`
3. `npm i luxon`
4. `cd ios && pod install` => produces error stated above

Works => `npm uninstall luxon && cd ios && pod install`

**Actual vs Expected behavior**
Expect the project to build.

**Desktop (please complete the following information):**

- Node 18.4.0
- Luxon version 3.0.1
- Ruby 2.7.5
- Cocoapods 1.11.3

**Additional context**
React native project uses react 18 and RN 0.69.1

**Comment by hatem-72** [comment]
Good catch.
Personally I had no reference to luxon in my error logs when running pod install.
So it took me a while to catch the culprit. But indeed `luxon v3.0.1` caused an error on pod install for RN projects.

```bash
[!] Invalid `Podfile` file: source is not valid JSON!

 #  from /path-to-my-project/ios/Podfile:8
 #  -------------------------------------------
 #  target 'Inshallah' do
 >    config = use_native_modules!
 #
 #  -------------------------------------------
```

**Comment by hatem-72** [comment]
In fact problem did not appears in `v3.0.1` but in `v2.5.0`.
You can check [changes here](https://github.com/moment/luxon/compare/2.4.0...2.5.0).
I guess it comes from the `Support for ESM-style node imports` part.

**Comment by hatem-72** [comment]
Exporting `./package.json` inside luxon `package.json` seems to fix the issue. I will submit a PR.

```diff
  "exports": {
+   "./package.json": "./package.json",
    ".": {
      "import": "./src/luxon.js",
      "require": "./build/node/luxon.js"
    }
  },
```
