### ISSUE TITLE
Add human durations from an object besides the provided object properties.

### ISSUE THREAD

**Issue by ricardocastanho** [moment/luxon#1241]
It would be nice if Luxon users can transform objects into a describing date, besides the provided object properties.

I would suggest a new property in ToHumanDurationOptions interface.

Actual behavior:
```javascript
const obj = { minutes: 125 };

const duration = Duration.fromObject(obj).toHuman();

console.log(duration); // => "125 minutes"
```

Feature suggestion:
```javascript
const obj = { minutes: 125 };

const opt = { style: "complete" };

const duration = Duration.fromObject(obj).toHuman(opt);

console.log(duration); // => "2 hours, 5 minutes"
```

Currently I did this:
```javascript
const obj = { minutes: 125 };

const raw = Duration.fromObject(obj).toFormat('dd-hh-mm');
const [days, hours, minutes] = raw.split('-');

const dayLabel = days > 1 ? 'days' : 'day';
const dayText = days > 0 && `${parseInt(days)} ${dayLabel}`;

const hourLabel = hours > 1 ? 'hours' : 'hour';
const hourText = hours > 0 && `${parseInt(hours)} ${hourLabel}`;

const minutesLabel = minutes > 1 ? 'minutes' : 'minute';
const minutesText = minutes > 0 && `${parseInt(minutes)} ${minutesLabel}`;

const duration = [dayText, hourText, minuteText].filter(text => !!text).join(', ');

console.log(duration); // => "2 hours, 5 minutes"
```

**Comment by KikoCosmetics** [comment]
@ricardocastanho thanks for the workaround. `toFormat` saved my bacon!!

**Comment by linda-rian** [comment]
@ricardocastanho [`shiftTo`](https://moment.github.io/luxon/api-docs/index.html#durationshiftto) method allows to achieve the same result:
```js
const duration = Duration.fromObject({ seconds: 1236836 }).shiftTo("days", "hours", "minutes", "seconds");
    
console.log(duration); // => "14 days, 7 hours, 33 minutes, 56 seconds"
```

**Comment by KikoCosmetics** [comment]
If someone interested, in **ts-luxon** the humanize has been recently fixed...
v4.0.0 is about to be released (Luxon 3)

**Comment by ricardocastanho** [comment]
> @ricardocastanho [`shiftTo`](https://moment.github.io/luxon/api-docs/index.html#durationshiftto) method allows to achieve the same result:
> 
> ```js
> const duration = Duration.fromObject({ seconds: 1236836 }).shiftTo("days", "hours", "minutes", "seconds");
>     
> console.log(duration); // => "14 days, 7 hours, 33 minutes, 56 seconds"
> ```
> 
> But you would still need to filter out false values.

Thanks! I didn't know this method 🤝

**Comment by icambron** [comment]
I'd support adding a method to remove 0-valued units
