### ISSUE TITLE
Circular dependency building with rollup

### ISSUE THREAD

**Issue by RafaelGB** [moment/luxon#1249]
**Describe the bug**
There is a circular dependency with building with rollup

**To Reproduce**
build a node project with 3.0.1 & `@types` 3.0.0

**Actual vs Expected behavior**
Not a circular dependency

**Desktop (please complete the following information):**

- OS: MacOS 12.4
- Browser: N/A
- Luxon version: 3.0.1
- Your timezone : N/A

**Additional context**
Log of the build
```bash
Building development

src/main.ts → dist...
(!) Circular dependencies
node_modules/luxon/src/impl/locale.js -> node_modules/luxon/src/settings.js -> node_modules/luxon/src/impl/locale.js
node_modules/luxon/src/datetime.js -> node_modules/luxon/src/duration.js -> node_modules/luxon/src/impl/locale.js -> node_modules/luxon/src/datetime.js
node_modules/luxon/src/datetime.js -> node_modules/luxon/src/interval.js -> node_modules/luxon/src/datetime.js
node_modules/luxon/src/datetime.js -> node_modules/luxon/src/info.js -> node_modules/luxon/src/datetime.js
node_modules/luxon/src/datetime.js -> node_modules/luxon/src/impl/tokenParser.js -> node_modules/luxon/src/datetime.js
```

BTW: Thanks for this fantastic library

**Comment by icambron** [comment]
Yeah, unfortunately, Luxon simply has internal circular dependencies. Not much to be done here, without a significant refactor of Luxon. You can suppress Rollup from complaining about them, which is what we do in Luxon itself: https://github.com/moment/luxon/blob/c0302f0ee50de4858deeacf82633151ad9b18d86/tasks/build.js#L27

**Comment by RafaelGB** [comment]
thanks for your quick response and the snippet. If its a controlled warning 100% trust on your work :)

**Comment by agrohs** [comment]
Why would someone close out these issues if the actual fix has never been made - it is not good practice to write code w/ circular dependencies and these have now been in the codebase for years on end without resolving [#193](https://github.com/moment/luxon/issues/193)
