### ISSUE TITLE
Issue with latest luxon (2.5.0) and Webpack 5

### ISSUE THREAD

**Issue by feardarkness** [moment/luxon#1252]
**Describe the bug**
When I'm trying to run my project with webpack, I'm getting an error:

`No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file /path/to/project/node_modules/luxon/src/package.json, or manually specify version in shared config.
`

**Actual vs Expected behavior**
The error shouldn't be thrown

** Fix **

I was able to fix the problem deleting the package.json file inside the src folder in luxon but it will affect builds of other people too. Also, it is really complicated trying to update node_modules in the yarn cache (with workspaces).
The problem was introduced here: https://github.com/moment/luxon/pull/1218

**Comment by dasa** [comment]
How are you importing it? This seems to work fine: `import { DateTime } from "luxon";`

**Comment by feardarkness** [comment]
I've fixed the problem updating webpack to 5.74.0

Thank you a lot!
