### ISSUE TITLE
Issue with latest luxon (2.5.0), Webpack 5 and Module Federation

### ISSUE THREAD

**Issue by feardarkness** [moment/luxon#1253]
**Describe the bug**
(Had to re-open #1252) When I'm trying to run my project with webpack and module federation, I'm getting an error:

`No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file /path/to/project/node_modules/luxon/src/package.json, or manually specify version in shared config.
`

**To Reproduce**
Install the dependencies and run the project with yarn.
Repository: https://github.com/feardarkness/luxon-module-federation-issue

**Actual vs Expected behavior**
The error shouldn't be thrown

** Fix **

I was able to fix the problem deleting the package.json file inside the src folder in luxon but it will affect builds of other people too. Also, it is really complicated trying to update node_modules in the yarn cache (without node_modules).

The problem was introduced here: https://github.com/moment/luxon/pull/1218

**Comment by badboyku** [comment]
I think the proper way to fix this is to add the version `"version": "3.0.1"` to the `/src/package.json` file

**Comment by erkanisuf** [comment]
Any updates on this ? I got same issue

**Comment by bandman0226** [comment]
I also am having this exact issue. Any updates yet?

**Comment by badboyku** [comment]
This is an ongoing issue since Aug 2022. Any chance we can get the latest version `"version": "3.2.1" added to the `/src/package.json` file?

I am getting dependabot high warnings about being on luxon 2.4.0. I would love to be able to upgrade to the latest luxon.

**Comment by DiviBretschneider** [comment]
I made a PR with the necessary adjustment of src/package.json. Rfc.

https://github.com/moment/luxon/pull/1385

**Comment by bandman0226** [comment]
@DiviBretschneider thanks for getting that PR! Can't wait to update!

**Comment by icambron** [comment]
This has been released in 3.3.0
