### ISSUE TITLE
Creating an isToday() function

### ISSUE THREAD

**Issue by Brandon-Ritchie** [moment/luxon#1258]
**Is your feature request related to a problem? Please describe.**
I have created a function that checks that the passed in DateTime has the same Day, Month, and Year as DateTime.now(), as I was surprised one did not exist.

**Describe the solution you'd like**
A built in isToday() function.

**Describe alternatives you've considered**
Creating my own function that creates said function that takes the DateTime you would like to compare as a parameter.

**Additional context**
My current implementation in TypeScript. Happy to take suggestions.

```
import { DateTime } from 'luxon';

export const isToday = (dateTime: DateTime) => {
  const now = DateTime.utc();
  return (
    now.hasSame(dateTime, 'year') &&
    now.hasSame(dateTime, 'month') &&
    now.hasSame(dateTime, 'day')
  );
}; 
```

I am unsure if I should explicitly convert the passed in DateTime to utc as well, or if it would be better to check the locale of the passed in DateTime and set now related to the parameter.

**Comment by icambron** [comment]
`now.hasSame(dateTime, 'day')` doesn't just check the day property, it means like the actual same day.

```js
// actually today
DateTime.now().hasSame(DateTime.now(), "day"). // => true

// same date but last month
DateTime.now().hasSame(DateTime.now().minus({months: 1}), "day") // => false
```


So I think all you need is `DateTime.hasSame(yourInputDT, "day")`.

**Comment by Brandon-Ritchie** [comment]
Oh really? That's great, I must have misread that somewhere.

**Comment by icambron** [comment]
Also, `foo.hasSame(bar, "day")` coverts `bar` to `foo`'s zone before comparing them.

You might find the implementation helpful in understanding it:

```js
  hasSame(otherDateTime, unit) {
    if (!this.isValid) return false;

    const inputMs = otherDateTime.valueOf();
    const adjustedToZone = this.setZone(otherDateTime.zone, { keepLocalTime: true });
    return adjustedToZone.startOf(unit) <= inputMs && inputMs <= adjustedToZone.endOf(unit);
  }
```

**Comment by Brandon-Ritchie** [comment]
@icambron 

I ran some tests against this, and it doesn't seem to work as expected:

```

  for (let hour = 0; hour < 24; hour++) {
    for (let minute = 0; minute < 59; minute++) {
      tests.push([
        DateTime.utc(2022, 9, 30, hour, minute),
        DateTime.local(2022, 9, 30, 9, 0),
      ]);
    }
  }

  test.each(tests)('isToday %j to %j', (passedDateTime, currentDateTime) => {
    // WHEN
    const result = passedDateTime.toLocal().hasSame(currentDateTime, 'day')
    // THEN
    expect(result).toEqual(true);
  });
```

This test should fail for the first four hours worth of `passedDateTime`s, since I am in EST.

**Comment by Brandon-Ritchie** [comment]
```  
const tests: DateTime[][] = [];

  for (let hour = Mat.abs(DateTime.local().offset / 60); hour < 24; hour++) {
    for (let minute = 0; minute < 59; minute++) {
      tests.push([
        DateTime.utc(2022, 9, 30, hour, minute),
        DateTime.local(2022, 9, 30, 9, 0),
      ]);
    }
  }

  test.each(tests)('isToday %j to %j', (passedDateTime, currentDateTime) => {
    // WHEN
    const result = dateTimeToCompare.setZone(DateTime.local().zone).hasSame(DateTime.local(), 'day');

    // THEN
    expect(result).toEqual(true);
  });
```

This test passes, as far as I can tell.

I am wondering if in the source code that you sent me, is the `{ keepLocalTime: true }` supposed to be included in this instance? I would think that it wouldn't be, because it wouldn't adjust the time.

If hasSame(..., 'day') is working as intended, then I would like to re-open the suggestion for an isToday() function.
