### ISSUE TITLE
Webpack Source-Map-Loader cannot find Source Map

### ISSUE THREAD

**Issue by joshuajung** [moment/luxon#126]
Trying to bundle Luxon 0.2.7 with Webpack 3.6.0 and Source-Map-Loader 0.2.2 results in the following warning:

`Cannot find SourceMap 'luxon.js.map': Error: Can't resolve './luxon.js.map' in '/my-project/node_modules/luxon/build/node'`

This seems to result from line 7184 in luxon/build/node/luxon.js resp. luxon/build/cjs-browser/luxon.js:

`//# sourceMappingURL=luxon.js.map`

I'm no source mapping expert, so this may easily be a configuration issue on my side, but it seems odd that Luxon refers to source map files that do not seem to be part of the package.

**Comment by icambron** [comment]
Yeah, there are a couple problems here:

 1. Luxon builds the map file but doesn't include it in the package
 2. It's called [luxon.map](http://moment.github.io/luxon/node/luxon.map) instead of `luxon.js.map` 

I'll see if I can clean that up
