### ISSUE TITLE
Recreating a datetime object from a different datetime object

### ISSUE THREAD

**Issue by sksallaj82** [moment/luxon#1260]
**Is your feature request related to a problem? Please describe.**
In a way. I'm saving a DateTime object into indexDb (or localStorage), so I can use it as a timestamp for later comparison checks. When I retrieve the object, it's the object without the function. So if I do something like:

    const a = localStorage.getItem('myTimestamp', ... )
    a.plus( ... )   // this does not work
    DateTime.isDateTime(a)  // this returns true

    the object 'a' looks like this:

        {
           c: {year: 2022, month: 8, day: 5, hour: 0, minute: 42, …}
           invalid: null
           isLuxonDateTime: true
           loc: {locale: 'en-US', numberingSystem: null, outputCalendar: null, intl: 'en-US', weekdaysCache: {…}, …}
           o: -420
           ts: 1659685339135
           weekData: null
           _zone: {}
        }

**Describe the solution you'd like**
It could be possible to either do something like 

    DateTime.recreateFrom(a)  // returns a DateTime
    
Or, add an accessor to internal properties to DateTime like DateTime.val.c  or DateTime.val.invalid, so that when I get my object I can do

    DateTime.fromObject(a.c)

**Describe alternatives you've considered**

    Definitely could work if I converted to milliseconds and saved that to the local storage

**Additional context**

I think that's pretty much it

**Comment by icambron** [comment]
See #1125
