### ISSUE TITLE
JobDonePT: any = DateTime.local().setZone("America/Los_Angeles"); makee null date in Firfox

### ISSUE THREAD

**Issue by Ofer-Gal** [moment/luxon#1261]
Every now and then users report that the date coming from my app is empty.

**To Reproduce**
JobDonePT: any = DateTime.local().setZone("America/Los_Angeles");

run few times with Firfox and some will make the date null

Windows- Browser [Fire fox]
- Luxon version [2.4]
- Your timezone [e.g. "America/Los_Angeles"]

This does not happen all the time.

Help

**Comment by icambron** [comment]
I would need a reproducible scenario for this. I suspect there's something weird with Firefox here, but it's tough to say. I've certainly never seen this.

**Comment by Ofer-Gal** [comment]
Just create a DateTime object in JS and show in Firefox.
I managed to prevent users from using Firefox.  I am good for now
