### ISSUE TITLE
`DateTime.diff` produces wrong results with unit `quarter`

### ISSUE THREAD

**Issue by Cameramorphic** [moment/luxon#1266]
**Describe the bug**
When diffing two dates using a `unit` combined with `'milliseconds'`, where the duration between the dates is a multiple of this `unit`, the resulting duration has unexpected values if the `unit` is `'quarter'`.
As far as I can tell, this happens if the year of the two dates is different.
It works as expected for the units 'month' and 'year'.

The `'milliseconds'` of the duration act as the remainder, if it is `0` the duration is a multiple of `unit`.

**To Reproduce**
```ts
const d = DateTime.fromISO('2023-01-01').diff(DateTime.fromISO('2022-01-01'), ['quarter', 'milliseconds']);
const d2 = DateTime.fromISO('2023-05-01').diff(DateTime.fromISO('2022-02-01'), ['quarter', 'milliseconds']);
```
**Actual vs Expected behavior**
Actual: `d` is `{ quarters: 0, milliseconds: 31536000000 }` (a year in ms).
Expected: `d` should be `{ quarters: 4, milliseconds: 0 }`.

Actual: `d2` is `{ quarters: 1, milliseconds: 31536000000 }` (a year in ms).
Expected: `d2` should be `{ quarters: 5, milliseconds: 0 }`.

My current workaround: 
I check if the unit is `'quarter'` and use `'month'` instead.
Afterwards I additionally have to check if `duration.quarters % 3 === 0`.

**Desktop:**
- OS: Ubuntu 20.04 LTS
- Browser: Chrome 104
- Luxon version: 3.0.1
- Your timezone "Europe/Berlin"

**Comment by Cameramorphic** [comment]
I just managed to reproduce another (even more confusing) variant of this bug with negative values, even though the 'end' date is still after the 'start' date:
```ts
const d3 = DateTime.fromISO('2023-01-01').diff(DateTime.fromISO('2022-10-01'), ['quarter', 'milliseconds']);
const d4 = DateTime.fromISO('2023-07-01').diff(DateTime.fromISO('2022-10-01'), ['quarter', 'milliseconds']);
```
**Actual vs Expected**
Actual: `d3` is `{ quarters: -3, milliseconds: 31536000000 }`.
Expected: `d3` should be `{ quarters: 1, milliseconds: 0 }`.

Actual: `d4` is `{ quarters: -1, milliseconds: 31536000000 }`.
Expected: `d4` should be `{ quarters: 3, milliseconds: 0 }`.

**Comment by icambron** [comment]
Yeah, sounds like a bug. Would take a fix for this.

**Comment by ajinkyac03** [comment]
@icambron anything more needed from my side or can be merged?

**Comment by icambron** [comment]
@ajinkyac03 i merged your fix and will release it soon
