### ISSUE TITLE
.toLocaleString() returning US formatting for non-US locales, even though Intl seems to be available

### ISSUE THREAD

**Issue by Sweater-Baron** [moment/luxon#1267]
I'm trying to use Luxon.toLocaleString to format dates for different locales. I'm on Luxon version 3.0.1.

I'm following this example from the [luxon documentation][1]:
```
DateTime.now().toLocaleString({ locale: 'en-gb' }); //=> '20/04/2017'
```

My code:
```
import { DateTime } from 'luxon';
console.log(DateTime.fromISO('2017-04-20').toLocaleString({ locale: 'en-gb' }));
```
Running this gives me: `4/20/2017`, but the documentation linked above says it should be returning `20/04/2017`. It similarly is incorrectly returning the US format for other locales that I've tried.

The cause of my issue seems to be different than the one described in [this stackoverflow question][2] (missing Intl implementation), because running the following code produces results that are consistent with having a proper Intl installation:

```
const df = new Intl.DateTimeFormat('de', {day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC'});
console.log(df.format(new Date("2018-08-13T04:00:00.000Z")));
```
gives: `13. August 2018` as expected.

This is running in a React app (create-react-app), if that matters. (And the React app is served from Node 14, which I understand is supposed to come with `full-icu` installed by default - although since this is running in the browser, I'm not sure if that should matter)

  [1]: https://moment.github.io/luxon/api-docs/index.html#datetimetolocalestring
  [2]: https://stackoverflow.com/a/58010987/5602521

**Comment by icambron** [comment]
Yeah, something is up there. I'll take a look. In the meantime, you can do this:

```js
DateTime.fromISO(...).setLocale("en-gb").toLocaleString()
```

**Comment by Sweater-Baron** [comment]
FYI, I also made a Stackoverflow post about this, and someone left a comment saying it looks like .toLocaleString({}, {locale: 'en-gb'}) should work. I haven't had a chance to try it out yet though. Maybe a breaking change was made to the interface since the documentation was written?

https://stackoverflow.com/q/73478040/5602521

**Comment by icambron** [comment]
I took a closer look. Looks like we dropped support for passing in the the opts as the first arg in 2.0 and then just didn't get the docstring updates. Adding support for the overload would add a bunch of complexity and if we did, we'd have to do it on other functions too, just for consistency. So instead I updated the docstring.

So you can just do: `toLocaleString(DateTime.DATE_SHORT, { locale: 'en-gb' })`. DATE_SHORT is the default, but you have to provide it in order to provide the second arg.
