### ISSUE TITLE
INT localization doesn't support well on Node with full-icu

### ISSUE THREAD

**Issue by xunuoi** [moment/luxon#127]
Hi, I found the `toFormat` API of Luxon doesn't work well with Node. Node version: v6.10.3

I installed the `full-icu-npm` to get icu data for Node, https://github.com/unicode-org/full-icu-npm

And then run Node by `node --icu-data-dir=node_modules/full-icu`. I'm pretty sure it loaded icu-data well.

```js
const dt = DateTime.fromISO('2017-09-24', { locale: 'fr' });
const dateStr2 = dt.setLocale('fr').toFormat('MMMM dd, yyyy GG');

// output is normal en-us: September 24, 2017 Anno Domini
```

The return value is `September 24, 2017 Anno Domini` which is not localized text.
But the `toLocaleString` works well which can return the localized string.

So is there something wrong with this part ?

Thank you very much!

**Comment by xunuoi** [comment]
I also built the Node 6.12.1 with icu-full by `configure --with-intl=full-icu`, got the same result as `icu-full-npm`. The `toFormat` API just return the normal `en-US` string, which is different with Browser Client.

**Comment by icambron** [comment]
Yeah, `toFormat` requires not just full-icu but also [formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts) support, which is in Node 8 but not Node 6. Here's what it looks like in Node 8:

```js
dt.setLocale('fr').toFormat('MMMM dd, yyyy GG');
'septembre 24, 2017 après Jésus-Christ'
```

I have that [documented incorrectly](http://moment.github.io/luxon/docs/manual/matrix.html), so I'll fix that.

**Comment by icambron** [comment]
Also, fwiw, the preferred human-readable Intl feature `toLocaleString` should work fine in Node 6.

**Comment by icambron** [comment]
I fixed the Node 6 doc issue, so I'm closing this
