### ISSUE TITLE
Calculating wrong timezone offsets for BC timestamps in FF

### ISSUE THREAD

**Issue by adamszigeti** [moment/luxon#1283]
**Describe the bug**
In Firefox 104.0.2, `Intl.DateTimeFormat().formatToParts()` returns values for `"era"` as either `A` (for "AD"), or `B` (for "BC") - this makes [this check](https://github.com/moment/luxon/blob/74803401d453ae5b21583b2c49e991dc99f6900c/src/zones/IANAZone.js#L157) a false negative, leading Luxon to calculate the wrong timezone offset in Firefox.

**To Reproduce**
Any code that queries BC dates' offsets triggers this, but as an example, here is a fiddle that returns different offsets in v8 (edge) and SpiderMonkey (FF): http://jsfiddle.net/90sp614f/

Here is the userspace code I used if you just want to skim it through:

```js
luxon.DateTime.fromObject({year:-1234, month:9, day:25}).setZone('Europe/Budapest').offset
```

Results:
```
v8:           76.33333333333333
SpiderMonkey: 1298569036.3333333
```

**Actual vs Expected behavior**
They both should print `76.33333333333333` (as I guess v8 is correct).

**Desktop (please complete the following information):**

- OS: Windows
- Browser Edge 105.0.1343.33, Firefox 104.0.2
- Luxon version 3.0.3
- Your timezone "Europe/Budapest"

**Additional context**
\-

**Comment by icambron** [comment]
Ok, sure, I'd take a fix making that line check for `B`

**Comment by diesieben07** [comment]
This was fixed in [Firefox 106](https://bugzilla.mozilla.org/show_bug.cgi?id=1752253). But because the workaround is so simple, I will submit a quick PR.
