### ISSUE TITLE
parseFormatForOpts with option [year: 'numeric'] returns 5-digit year

### ISSUE THREAD

**Issue by loukacodes** [moment/luxon#1286]
**Describe the bug**
I was using this `parseFormatForOpts` to produce format string like this:

```
DateTime.parseFormatForOpts({
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
})
```

However, instead of receving `MM/dd/yyyy`, it actually returned this `MM/dd/yyyyy` with 5-digit year. Not sure if this is intentional or a bug.

I can see that this is how it is defined:

```
year: {
"2-digit": "yy",
numeric: "yyyyy",
},
```

I needed this string to pass to my calendar, and the string is localized according to chosen locale. So with the 5-digit year string, it renders `02022` instead of just `2022`. So that's a bit weird. Of course, I could just use Regex to remove the extra digit, but would be nice to have it work out of the box.

If this is intentional (I guess it is), then why is it so? 🤔 

**To Reproduce**
```
DateTime.parseFormatForOpts({
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
})
```

**Actual vs Expected behavior**
Expected returned string: `MM/dd/yyyy`
Actual returned string: `MM/dd/yyyyy` with 5-digit year

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome 84
- Luxon version `3.0.1`
- Your timezone "Europe/Helsinki"

**Additional context**

**Comment by icambron** [comment]
Yeah, unfortunately if we make it yyyy, then it won't support years outside of the four-digit range, because the yyyy is strict, but `year: "numeric"` is not. This has come up before and I agree it's a real issue, but I'm not sure what the right answer is

**Comment by loukacodes** [comment]
Thanks for the quick response! Now I understand. And also it's good to have the Y10K-compliance already in place! Closing this..

**Comment by loukacodes** [comment]
Have you considered to add another option for year @icambron? So something like:

```
year: {
  "2-digit": "yy",
  "4-digit": "yyyy",
  numeric: "yyyyy",
}
```
