### ISSUE TITLE
Incorrect hour formatting on Firefox

### ISSUE THREAD

**Issue by ricardopieper** [moment/luxon#1287]
**Describe the bug**

"h" and "H" (as well as hh and HH) formatting options are broken on Firefox, but work fine on Chrome. On my machine, they display the hour with a -2 offset from what it should be.

**To Reproduce**
On Firefox, go to https://moment.github.io/luxon/#/formatting
On the console, enter:

```
var date = luxon.DateTime.fromISO("2014-08-06T13:07:04.054Z")
date.setLocale("en-US").setZone("America/New_York").toFormat("hh:mm ZZZZ")
```

**Actual vs Expected behavior**

Expected behavior: Prints 09:07 EDT
Actual behavior: Prints 07:07 EDT

This works correctly on Chrome.

If you format "t ZZZZ" it works correctly, and shows the expected value 09:07 AM EDT. 

Also, h and H are wrong too.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Firefox 104, Chrome 105
- Luxon version: 3.0.3
- Your timezone: "America/New_York" [other timezones end up exhibiting the same wrong behavior]

**Additional context**
N/A

**Comment by icambron** [comment]
@ricardopieper I wasn't able to reproduce this (outputs 9:07 for me), and I'm also on a Mac and running FF 104 (I also updated FF and tried in 105). Do you perhaps have some strange extensions?

**Comment by ricardopieper** [comment]
@icambron actually yes, you're right.
I was using https://addons.mozilla.org/en-US/firefox/addon/change-timezone-time-shift/ to change the browser timezone, perhaps it is not setting some configuration appropriately. 

It didn't cross my mind that the extension could cause this because on Chrome I'm also using an extension, albeit a different one, to change the timezone and it works. 

Removing/disabling the extension solves the problem. I'm glad this is not a problem with Luxon and Firefox :) 
Closing the issue!

**Comment by icambron** [comment]
That is strange, but without knowing exactly what the extension is doing, it's hard to say. It may be interfering with the Intl.DateTimeFormat API in an inconsistent way
