### ISSUE TITLE
Unused param in tokenForPart (tokenParser.js)

### ISSUE THREAD

**Issue by tonysamperi** [moment/luxon#1288]
**Describe the bug**
I just noticed that the signature for `tokenForPart` has a `locale` param, but it's unused.
So you've been passing locale everywhere for nothing.
Not really a bug but still, could make code more clear.

**To Reproduce**
Just in the code

**Actual vs Expected behavior**
It doesn't cause behaviours

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: irrelevant
- Browser [e.g. Chrome 84, safari 14.0]: irrelevant
- Luxon version [e.g. 1.25.0]: luxon >= 2.5.0,
- Your timezone [e.g. "America/New_York"]: irrelevant

**Additional context**
If you need I can make a pull request removing the param from everywhere

**Comment by vlad-tred** [comment]
Hi Tony, I have also noticed there is an unused parameter in `tokenForPart`. In luxon v3.1.0, however, I can see `tokenForPart` declared in luxon/src/impl/tokenParser.js and called only once at the very bottom of the same file. It also appears to me there is no need to pass the `locale` parameter. Are you planning to create a pull request for this issue?

**Comment by icambron** [comment]
Fixed in d607d8fb, will be released in 3.2.0. Thanks guys!
