### ISSUE TITLE
Add support for Europe/Kyiv timezone

### ISSUE THREAD

**Issue by artemkanaki** [moment/luxon#1289]
**Is your feature request related to a problem? Please describe.**
Hi Luxon Team,

Please add support for Europe/Kyiv timezone. The current version of luxon does not count it as valid.

**Describe the solution you'd like**
```
import { DateTime } from 'luxon';

DateTime.local().setZone("Europe/Kyiv").isValid; // should return true, currently it returns false
```

**Describe alternatives you've considered**
I can use the mapper to convert `Europe/Kiev` to `Europe/Kyiv`, but it would be more convenient if luxon supported it out of the box

**Comment by icambron** [comment]
The time zones and their names are supported directly by the JS runtime. They're not something Luxon itself maintains. You'll need to take it up with Chrome, Firefox, Nodejs, etc

**Comment by artemkanaki** [comment]
@icambron oh, I see. thanks for the quick response. In this case, I'll close this issue
