### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by cristearazvanh** [moment/luxon#1294]
With Luxon from https://cdnjs.cloudflare.com/ajax/libs/luxon/3.0.4/luxon.min.js
simple DateTime.now() **not working!** (DateTime is not defined)

**Comment by icambron** [comment]
That's the globals build, which exports everything under an object called `luxon`, so use `luxon.DateTime.now()`

**Comment by cristearazvanh** [comment]
So documentation is incomplete!
