### ISSUE TITLE
Converting to js Date object the result has different date than the original DateTime

### ISSUE THREAD

**Issue by jira-zz** [moment/luxon#1300]
**Describe the bug**
After converting to js Date object the result has different date than the original DateTime.

**To Reproduce**
const dt = DateTime.fromISO("2022-01-01");
console.log(dt.toISODate());
const d = dt.toJSDate();
console.log(d.toISOString().split("T")[0]);

**Actual vs Expected behavior**
Actual:
2022-01-01
2021-12-31

Expected:
2022-01-01
2022-01-01

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Ubuntu 22.04 WSL
- Luxon version: 3.0.4
- Your timezone: Europe/Prague
- Node: 18.5.0

**Comment by icambron** [comment]
This is correct, and is the result of the native JS Date object displaying ISO strings in UTC, whereas Luxon provides an ISO string with the local offset. When it's midnight in Prague, it's still the day before in UTC.

```js
const dt = DateTime.fromISO("2022-01-01"); // => Local midnight on the 1st
dt.toISODate() // => 2022-01-01 because that's what day it is
dt.toISO() //=> '2022-01-01T00:00:00.000+01:00' is the longer version
 
const d = dt.toJSDate(); // => still represents local midnight
d.toISOString() // => '2021-12-31T23:00:00.000Z'. The JS wrapper shows the string UTC, where it is still 23:00 the day before
```

If you want Luxon to match the JS date, you can covert it to UTC first:

```js
dt.toUTC().toISODate() //=> '2021-12-31'                                                                                                                                                                                                                                                                                                                                            
dt.toUTC().toISO() //=> '2021-12-31T23:00:00.000Z' 
```

You can't make the native JS date print an ISO string using the local offset. That's just not a feature of the JS Date object, as far as I know. That's part of why libraries like Luxon exist. The important thing from Luxon's perspective is that the JS date it produced also represents the same moment in time, which it does.

**Comment by jira-zz** [comment]
Thanks for the answer.

One thing is still not completely clear to me:
local time zone is currently UTC + 2 due to daylight saving time, but the JS date which is supposed to be in UTC is in fact local timezone - 1.

**Comment by icambron** [comment]
@jira-zz currently, yes, but Jan 1 it wasn't...
