### ISSUE TITLE
Better support for Hebrew calendar output

### ISSUE THREAD

**Issue by ladyisak** [moment/luxon#1302]
**Is your feature request related to a problem? Please describe.**
The Hebrew calendar does not align with the Georgian calendar in more than one way: besides the year and month misalignment, for cultural and ritual purposes the Jewish day starts at sunset; in the higher latitudes (say, Edinburgh, where I live), this can be up to nine/ten hours earlier than the gentile day in the winter, and sometimes up to an hour _after_ midnight in midsummer. Luxon currently does not take account of this, providing the incorrect date for evening times. 

**Describe the solution you'd like**
I'd like some way of taking into account whether the time of day is before or after an idealised sunset I can set by default, so I can put the correct Hebrew date on my blog posts. I realise the ideal scenario (taking into account sunrise/sunset times based on locale/latitude and season) may be non-trivial to implement, so I'm willing to settle for something "good enough".

**Describe alternatives you've considered**
[HebCal ](https://www.hebcal.com/home/developer-apis) has numerous API solutions for just this eventuality; however, that'd require me to use both HebCal and Luxon, and it'd be something of a headache; I prefer to limit the amount of libraries I use in my projects, as far as possible. As I do in fact need the other functionalities Luxon provides, I'd prefer a way to either bridge the two functionalities or stick to Luxon only.

**Comment by icambron** [comment]
Luxon uses the Intl API built into the JS runtime to do its calendar computations. It doesn't actually know anything about how Hebrew dates work, just how to use that API. And as far as I know, there's no way to provide parameters about latitude or sunset. So implementing this isn't really an option.
