### ISSUE TITLE
Wrong time zone information when parsing any date from 2022-11-06 and up

### ISSUE THREAD

**Issue by eliashdezr** [moment/luxon#1303]
**Describe the bug**
The output when parsing a date `fromISO` or `fromRFC2822` are adding the wrong timezone information for a certain dates

**To Reproduce**
`luxon.DateTime.fromISO('2022-11-25T15:00:00.000-04:00').setZone('America/New_York').toISO()` (Black Friday)

**Actual vs Expected behavior**
output
`2022-11-25T14:00:00.000-05:00`

expected
`2022-11-25T15:00:00.000-04:00`

This happens for any date starting `2022-11-06`, if I do this:
`luxon.DateTime.fromISO('2022-11-05T15:00:00.000-04:00').setZone('America/New_York').toISO()`

the output is the expected one:
`2022-11-05T15:00:00.000-04:00`

I am missing something? Is there an error on my parsing strategy?

Link to reproduce in the browser.
https://codesandbox.io/s/loving-jang-fpwfxu?file=/src/index.js

**Desktop (please complete the following information):**

- OS: `Windows / MacOS`
- Browser `Chrome and Node.js as well`
- Luxon version `3.0.4`
- Your timezone: `America/Monterrey`

**Additional context**
I have made the tests in Windows and MacOS.

**Comment by icambron** [comment]
Yes. Daylight Saving Time ends November 6, changing the offset for eastern time from -4 to -5.
