### ISSUE TITLE
issue with migrating from moment to luxon

### ISSUE THREAD

**Issue by codershona** [moment/luxon#1307]
Hello guys, can anyone help me, how can I convert this line into Luxon. I am working on migrating moment into Luxon. 

```
    moment.duration(moment().diff(object)).asMinutes();
    moment(luxon.DateTime.fromISO(object, { zone: “Europe/Spain” }).toJSDate());
    moment().isBetween(m1.object, m1.object2)
    moment().isBefore(m1.object)
    moment().isAfter(m1.object2)
```

I don’t know how can I make this line into Luxon. Here I want to totally remove the moment.

**Comment by icambron** [comment]
Sorry, this is more of an item for StackOverflow or the discussions forum. Luxon can do everything you need; you can look at the docs to see all the relevant APIs and you might find the [comparing datetimes section](https://moment.github.io/luxon/#/math?id=comparing-datetimes) especially useful
