### ISSUE TITLE
fromISO with options setZone and zone, does not work as expected

### ISSUE THREAD

**Issue by eliashdezr** [moment/luxon#1310]
**Describe the bug**
When passing the following string `2022-09-30T16:51:49Z` it does not set the zone in the output. And does not change the time to match the zone selected. If I remove the `Z`, it does set the zone.

**To Reproduce**
`luxon.DateTime.fromISO('2022-09-30T16:51:49Z', { setZone: true, zone: 'America/New_York' }).toISO()`

**Actual vs Expected behavior**
Actual:
`2022-09-30T16:51:49.000Z`

Expected:
`2022-09-30T12:51:49.000-04:00`

If I use this code:
``luxon.DateTime.fromISO('2022-09-30T16:51:49Z').setZone('America/New_York').toISO()``

it outputs the desired expected format: `2022-09-30T12:51:49.000-04:00`

Test link
https://codesandbox.io/s/pedantic-wiles-vsl4od?file=/src/index.js

**Desktop (please complete the following information):**
- Windows and MacOS
- Node.js and Chrome
- Luxon version 3.0.4
- America/Monterrey

**Comment by dasa** [comment]
The `setZone` parameter is a bit confusing. See: https://github.com/moment/luxon/issues/1012

I think `zone` is ignored when `setZone` is `true`: https://moment.github.io/luxon/api-docs/index.html#datetimefromiso

**Comment by eliashdezr** [comment]
@dasa thanks! resolved my issue.
