### ISSUE TITLE
IANAZone.isValidZone fails validation

### ISSUE THREAD

**Issue by gumurzhi** [moment/luxon#1313]
IANAZone.isValidZone("Europe/Kyiv") return false, but for "Europe/Kiev" it returns true. Not sure what Kiev is, but the capital of Ukraine is Kyiv.
Versions tested: 1.23.0, 3.0.0 and 3.0.4 .

**Comment by dasa** [comment]
This seems similar to #1289

**Comment by gumurzhi** [comment]
Sorry, didn't see those one. Thanks for the answer.
