### ISSUE TITLE
Luxon Date with Timezone Fails in Jest Tests

### ISSUE THREAD

**Issue by Lori-Becker** [moment/luxon#1314]
**Describe the bug**
I have some code that takes a timestamp (in millis) and a timezone (string) to create a DateTime object. When I run my React application, the DateTime object is successfully created without any errors. However, in my Jest test, that same line of code fails, stating that the timezone is unsupported. I've tried "America/Chicago", "America/New_York", and "America/Denver." These are all acceptable timezones and even appear in Luxon's documentation.

**To Reproduce**
Please share a minimal code example that triggers the problem:

Main code:
```
const currentValue = { timestamp: 1672525015000, timezone: 'America/Chicago' };
const date = DateTime.fromMillis(currentValue.timestamp)
        .setZone(currentValue.timezone)
        .toISO({ includeOffset: false });  // returns null ONLY in test suite because timezone is unsupported
return (<div>{date}</div>);
```

Test (using react-testing-library):
```
test('<Timestamp /> loads with previous value on edit', () => {
  const todayPlusOneDay = DateTime.now().plus({ days: 1 }).toMillis();
  const currentValue = { timestamp: todayPlusOneDay, timezone: 'America/Chicago' };

  render(<Timestamp currentValue={currentValue} />);
  const dateInIso = DateTime.fromMillis(currentValue.timestamp)
        .setZone(currentValue.timezone)
        .toISO({ includeOffset: false });
  expect(screen.getByText(dateInIso)).toBeInTheDocument(); // FAILS, due to main code returning date = null.
});

```

**Actual vs Expected behavior**
I expect to see a date like '2022-12-31T16:16:55.000' returned.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome 106.0.5249.119
- Luxon version: 2.0.2 (though I did briefly upgrade to the latest, 3.0.4. I got the same error)
- Your timezone: "America/New_York"

**Comment by icambron** [comment]
What version of Node are you running Jest in?

**Comment by Lori-Becker** [comment]
Node version is 14.17.1

**Comment by icambron** [comment]
Node 14 is new enough that I think it supports everything. But just in case, try this in your Node repl:

```js
new Intl.DateTimeFormat("en", {timeZone: "America/Chicago"}).format()
```

**Comment by diesieben07** [comment]
I could not reproduce this on Node 14.17.1. Please reopen this ticket with additional details if you still have this issue.
