### ISSUE TITLE
Feature request: Add 'T' character if needed to ISO-8601 strings 

### ISSUE THREAD

**Issue by jamesexplo** [moment/luxon#1325]
When trying to use `DateTime.fromISO` for an ISO-8601 string that contains a space instead of a `T` character (aka, instead of `2022-11-14T19:56:20`, a string like `2022-11-14 19:56:20`, Luxon should handle this alternative format or should provide an option to allow the `T` to be added.

**Comment by dasa** [comment]
Related to #990

**Comment by jamesexplo** [comment]
@dasa what was the solution for this? I don't see any relevant commits around the time 990 was closed and no option such as `allowSpaceSeparator` but maybe I am missing something.

**Comment by dasa** [comment]
I closed #990 since it seemed to be rejected, but here's my own workaround:

```ts
  // ISO 8601 time extension starts with T and then two digits.
  // Moment and RFC 3339 also allow the use of a space char instead.
  // https://github.com/moment/luxon/issues/990
  const re = / (\d\d)/;
  let dateTime = DateTime.fromISO(v);
  if (dateTime.isValid) {
    return dateTime;
  } else if (re.test(v)) {
    // replace space with a T and try again
    v = v.replace(re, "T$1");
    dateTime = DateTime.fromISO(v);
    if (dateTime.isValid) {
      return dateTime;
    }
  }
```

**Comment by icambron** [comment]
As far as I understand it, the string with a space in it isn't an ISO 8601 string. I don't want to support it because a lot of people rely on Luxon's validations to (mostly) filter out bad ISO strings that other parsers downstream may choke on.

Note that `fromSQL` accepts a space there

**Comment by diesieben07** [comment]
Like @icambron said, only `T` is allowed as a separator in ISO 8601. You can use `fromSQL` or a custom format using `fromFormat` to parse formats that are not ISO 8601.
As such I am going to close this.
