### ISSUE TITLE
luxon.DateTime.parseFormatForOpts() returns wrong format token for "numeric" year

### ISSUE THREAD

**Issue by Rondomat** [moment/luxon#1332]
**Describe the bug**
Calling
`luxon.DateTime.parseFormatForOpts({year: 'numeric'}, {locale: 'en-US'});`
should produce `'yyyy'` according to the token format definition:
https://moment.github.io/luxon/#/formatting?id=table-of-tokens
But it produces `'yyyyy'`, i.e. on 'y' to much. The generated token is important for a postprocessing to be passed to a 3rd party UI component
**To Reproduce**
```
// passing the locale is irrelevant by the way
console.assert(luxon.DateTime.parseFormatForOpts({year: 'numeric'}, {locale: 'en-US'}) === 'yyyy');
// Assertion failed
```
**Actual vs Expected behavior**
```
// passing the locale is irrelevant by the way
console.assert(luxon.DateTime.parseFormatForOpts({year: 'numeric'}, {locale: 'en-US'}) === 'yyyy');
// Assertion passed
```
**Desktop (please complete the following information):**

- OS: Windows 10, 64 bit
- Browser: Chrome 107
- Luxon version 3.1.0 (also tested with luxon available on dev console on luxon website)
- Your timezone [e.g. "Germany/Berlin"]

**Additional context**
nothing

**Comment by diesieben07** [comment]
You are referencing the wrong table of tokens. `parseFormatForOpts` generates a _parsing format_, as such you should refer to [this table](https://moment.github.io/luxon/#/parsing?id=table-of-tokens).
As shown there `yyyyy` means "four- to six-digit years", which is exactly what you'd expect `D` to parse. `yyyy` would not allow years greater than `9999`.

What is your use-case for interacting with the 3rd party library? Maybe I can assist you in finding a different solution using Luxon.

**Comment by Rondomat** [comment]
Ahh, you are right: I thought it was a bug, but I was referring to wrong token table as you said. Please close the issue. ;-)

For the usecase: In order to have a per locale dynamic parsing handling I have to pass the format to a 3rd party DateTimePicker component which only accepts a 4 digit year format string for the year (i.e. 'yyyy'). That's not an issue: I patch it inside a transformation code by replacing 'yyyyy' coming out of uxon.DateTime.parseFormatForOpts({year: 'numeric'}, {locale: 'en-US'});
with 'yyyy' to suite the 3rd party DateTimePicker component.

Thanks!
