### ISSUE TITLE
defaultLocale not picked up by dependency using luxon

### ISSUE THREAD

**Issue by ernstmul** [moment/luxon#1334]
**Describe the bug**
I'm looking for some help with a Luxon related problem I'm facing, which might be a bug. If it's not a bug, I'm looking for a recommendation on how to tackle this as best supported by Luxon.

**To Reproduce**
My setup is an application using Luxon, and a component library (CL) (also maintained by me) which also uses Luxon. The CL has a component showing the date as 'ccc' ("mon", "tue" etc.). For my CL I use Storybook to preview the components. When using `Settings.defaultLocale = 'nl'` in the `preview.js`, the locale is picked up nicely. Works as intended. The CL itself doesn't set any locale, since it should be usable all over the world in all kind of languages.

In my applications, on app root level I also have `Settings.defaultLocale = 'nl'`, which works for the components directly written in my application. However when I embed a component from my CL it defaults back to `en-US` for those components, not respecting the locale set in the root of the application. The CL is published internally using NPM publish in combination with rollup.

**Actual vs Expected behavior**
The CL component picks up the locale specified by the application.

**Desktop:**

- OS: Windows
- Browser Chrome 107.0.5304.107
- Luxon version: application and CL both 3.1.0
- Your timezone "Europe/Amsterdam"

**Comment by diesieben07** [comment]
To me this sounds like the CL is bundling Luxon. If your application then also uses Luxon you basically have the entire Luxon code running twice, meaning there are also two Settings classes. The solution would be for your CL to not bundle Luxon, but leave bundling up to the application.

**Comment by ernstmul** [comment]
Thanks for the reply! You're absolutely right. That was the problem, makes sense! Moved Luxon in my CL to peerDependencies, which fixed the issue.
