### ISSUE TITLE
DateTime.toLocaleString returning 24:00 instead of 00:00

### ISSUE THREAD

**Issue by adahl5** [moment/luxon#1339]
**Describe the bug**
I've noticed calling toLocateString with a UTC time equivalent to 00:00 in my local timezone returns 24:00 instead of the expected 00:00. The date is correct, but the time is +24 hours. I was able to reproduce on a server with UTC as the timezone. I'm specifically converting from an ISO string, but it also happens with a Unix timestamp (and any other source, I assume). 

The arguments I'm using are  `{dateStyle: "medium", timeStyle: "short", hour12: false}`.

**To Reproduce**
Timezone is UTC
```javascript
const luxon = require('luxon');
console.log(luxon.VERSION) // '3.1.1'
const withDate = luxon.DateTime.fromISO("2022-05-02T00:00:00.000Z").toLocaleString({dateStyle: "medium", timeStyle: "short", hour12: false})
console.log(withDate) // 'May 2, 2022, 24:00'
const withoutDate = luxon.DateTime.fromISO("2022-05-02T00:00:00.000Z").toLocaleString({timeStyle: "short", hour12: false})
console.log(withoutDate) // '24:00'
const fromTimestamp = luxon.DateTime.fromMillis(1651449600000).toLocaleString({timeStyle: "short", hour12: false})
console.log(fromTimestamp) // '24:00'

```

**Actual vs Expected behavior**
My timezone is -7 UTC (MST).
I expect (07:00 UTC) to be returned as 00:00 but get 24:00 instead.
00:00 UTC is also returned as 24:00.

**Desktop (please complete the following information):**

- OS: Ubuntu 20.04
- Browser: NodeJS v16.14.0 (and Chrome 107.0.5304.110)
- Luxon version: 3.1.1
- Your timezone: America/Phoenix

**Comment by adahl5** [comment]
I've looked into it a bit more, and it's a bug(?) in Chrome and NodeJS. Running the vanilla JS equivalent of this in NodeJS and Chrome produce the same problem. Firefox returns the expected format.
```javascript
const date = new Date(Date.UTC(2022, 04, 02, 0, 0, 0));
const formatter = new Intl.DateTimeFormat("en-US", {dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC', hour12: false});
console.log(formatter.format(date));
// Chrome & NodeJS return 'May 2, 2022, 24:00'
// Firefox returns 'May 2, 2022, 00:00'
```

**Comment by dasa** [comment]
> I was not able to get the correct value using hourCycle:

Try removing `hour12` since it takes precedence.

**Comment by adahl5** [comment]
> Try removing `hour12` since it takes precedence.

That worked, thank you!
