### ISSUE TITLE
Getters in Duration doesn't work

### ISSUE THREAD

**Issue by FourwingsY** [moment/luxon#134]
```
const d = DateTime.local()
const diff = d.diffNow()
setInterval(() => console.log(diff.seconds), 1000)
```
This always returns `0`

I thinks changing getters as sugar for `as(unit)` is rational.

**Comment by FourwingsY** [comment]
Oh i miss read how it works Completely. Sorry.

**Comment by VitorHFLopes** [comment]
@FourwingsY May you please explain what did you missed?

**Comment by FourwingsY** [comment]
@VitorHFLopes duration[units] returns internal values, that may has been set initially.
If i created duration with `d = Duration.fromObject({months: 3, days: 13})`, and get `d.days` it returns 13, not 103. cause this is what unit getters intended to.
if I want to get duration as seconds, i should do `d.shiftTo('seconds').seconds`

Or this might be useful,
```
d = Duration.fromObject({days: 103})
d.normalize().days // 103 days -> 3 months and 13 days, returns 13.
```

**Comment by icambron** [comment]
That's correct. I'll just add that a shortcut for `d.shiftTo("seconds").seconds` is `d.as("seconds")`

**Comment by FourwingsY** [comment]
That would be great!

**Comment by icambron** [comment]
I'm saying it's already there. Try it :)
