### ISSUE TITLE
Weird behaviour with DateTime toLocaleString and DateTime fromFormat

### ISSUE THREAD

**Issue by tonysamperi** [moment/luxon#1342]
**Describe the bug**
We can generate a string with a certain locale, but we can't parse it.

**To Reproduce**
```
 luxon.DateTime.local().reconfigure({ locale: "es-ES"}).toLocaleString({
            ...luxon.DateTime.TIME_SIMPLE,
            hourCycle: "h12"
        });

// '7:42 p. m.'

luxon.DateTime.fromFormat("02:00 a. m.", "hh:mm a", {locale: "es-ES", numberingSystem: "latin"});

// Invalid date time with reason: the input \"02:00 a. m.\" can't be parsed as format [object Object]
```

**Actual vs Expected behavior**

I guess it would make sense it worked both ways

**Desktop (please complete the following information):**

- OS: Win 11
- Browser: Chrome 107.0.5304.122
- Luxon version: 3.1.1
- Your timezone: "Europe/Rome"

**Additional context**

**Comment by diesieben07** [comment]
You're looking for the `latn` numbering system. `latin` is not a valid option here. This input should probably be validated.

**Comment by tonysamperi** [comment]
@diesieben07 damn! You're right! 
Ok it works.
The fact is that the "latin" string theoretically is produced by Luxon itself.
Let me do some checks and I can update the issue properly...

**Comment by tonysamperi** [comment]
Ok false alarm! The problem was generating with locale "es-ES" and trying to parse with "en-US".
Sorry!

**Comment by diesieben07** [comment]
I would still be careful trying to parse the output of `toLocaleString` as it is not guaranteed to be consistent or in a particular format.

**Comment by tonysamperi** [comment]
@diesieben07 

Thanks! No worries, though! It's proven to work...I just have to deal with some legacy code which for no apparent reason defaults to parsing in us locale...
Btw before opening this, I bypassed the issue transforming any weird representation of the meridiem to AM or PM...
But I'll see if I can do something cleaner!
