### ISSUE TITLE
Vercel/ms support for Duration

### ISSUE THREAD

**Issue by rmanibus** [moment/luxon#1346]
**Is your feature request related to a problem? Please describe.**

[ms](https://www.npmjs.com/package/ms) is a lightweight duration parser which allow to convert durations in natural language ("3 hours") to milliseconds.

It could be practical to be able to directly create Duration from a natural language string (which is more user friendly than an iso date)

**Describe the solution you'd like**
Duration.fromNaturalLanguage("3 hours"));

**Describe alternatives you've considered**
Duration.fromMillis(ms("3 hours"));

**Additional context**

**Comment by icambron** [comment]
I know ms is small, but Luxon isn't going to take a dependency on it, for a couple reasons: it's English-only and Luxon has mostly avoided the feature creep that comes with natural language processing. What makes more sense to me is to make it easier to convert the output of ms (or other things like it) to a Luxon duration
