### ISSUE TITLE
Invalid Date Time When Using Date With Slash

### ISSUE THREAD

**Issue by Jbnado** [moment/luxon#1347]
I was trying to use DateTime.fromISO('YYYY/MM/DD') but using slash it returns an invalid date time, so I need to always find slash in the string and replace to hifen.

Could luxon allows this format of date using slash?

**Comment by dasa** [comment]
You may need to use `fromFormat` instead: https://moment.github.io/luxon/#/parsing?id=ad-hoc-parsing

**Comment by icambron** [comment]
Yeah, YYYY/MM/DD isn't an ISO format, so you can't provide it to `fromISO()`.

`fromFormat(yourString "yyyy/MM/dd")` is what you want
