### ISSUE TITLE
Worst documentation ever

### ISSUE THREAD

**Issue by uehlbran** [moment/luxon#1350]
I get it. As a developer,  writing documentation is hard but, come on. Your documentation is barely readable. You might as well have written it in hieroglyphics!

Why is it so difficult to take a time that is un UTC and display it in whatever timezone you want? It shouldn't be and maybe it's really not but, I can't decipher your documentation to figure it out and I highly doubt anyone else can. setZone doesn't do anything. Settings.defaultZone doesn't do anything either -- they all ignore the specified timezone and always default to whatever 'local' is. WHY?!?! The API is so inconsistent and poorly named I thought this was a PHP library at first.

**Comment by icambron** [comment]
Guy who can't even explain his complaint wants other people to write him new documentation. We'll get right on that!
