### ISSUE TITLE
First day of year shows as week number 52

### ISSUE THREAD

**Issue by eschaefer** [moment/luxon#1355]
**Describe the bug**

Jan 1 2023 `weekNumber` is 52.

**To Reproduce**

https://codesandbox.io/s/elastic-frost-95foq1?file=/src/index.js

**Actual vs Expected behavior**

Jan 1 2023 should be week 1 of the year. 

**Desktop (please complete the following information):**

MacOS 

- Browser [e.g. Chrome 84, safari 14.0]
FF 108

- Luxon version [e.g. 1.25.0]
3.2.0

- Your timezone [e.g. "America/New_York"]
CET

**Additional context**

**Comment by diesieben07** [comment]
This is now the ISO week number works.
https://en.wikipedia.org/wiki/ISO_week_date

**Comment by eschaefer** [comment]
While this may be technically true, it's practically useless if using the library to display week numbers to users on a calendar for planning.

Is there a mechanism/conversion in luxon to display week numbers in this context?

**Comment by diesieben07** [comment]
I am not aware of any other week numbering system. Google calendar as well as the calendar of my Ubuntu operating system classify Jan 1 2023 as Week 52:
![image](https://user-images.githubusercontent.com/1915984/210222465-62ea49e8-17af-42f6-adcc-0893491bc4fd.png)
![image](https://user-images.githubusercontent.com/1915984/210222509-0715c794-ba78-4c20-a421-794c11b9abe9.png)

**Comment by eschaefer** [comment]
Indeed you are right! I'll close this for now.

**Comment by diesieben07** [comment]
If you really want a non-standard "Jan 1 is always week 1" number, you'll have to do some of your own maths. `Math.floor(date.ordinal / 7)` is probably a good starting point, but then you'll have to adjust for what the week day of Jan 1 is for that year.

**Comment by angela-patino-yuli** [comment]
I still think there is a bug here, Now that we agreed that Jan 1 2023 weekNumber is 52,
when getting the year number its 2023, though it  must be 2022
<img width="942" alt="image" src="https://user-images.githubusercontent.com/108668515/214849240-ab0f79eb-86eb-4535-b292-80e68924043c.png">
