### ISSUE TITLE
Security Advisory for 1.x refers to non-existing version 1.38.1

### ISSUE THREAD

**Issue by carboneater** [moment/luxon#1359]
**Describe the bug**

Security Advisory https://github.com/moment/luxon/security/advisories/GHSA-3xq5-wjfh-ppjc refers to `1.38.1` as the patched version of the 1.x branch.

The version released 5 days ago on npm is `1.28.1`.

**To Reproduce**

> gfournier@L111251:~/test$ npm i luxon@1
> 
> added 1 package in 962ms
> gfournier@L111251:~/test$ npm audit
> # npm audit report
>
> luxon  1.0.0 - 1.28.1
> Severity: high
> Luxon Inefficient Regular Expression Complexity vulnerability - https://github.com/advisories/GHSA-3xq5-wjfh-ppjc
> fix available via `npm audit fix --force`
> Will install luxon@3.2.1, which is a breaking change
> node_modules/luxon
>
> 1 high severity vulnerability
> 
> To address all issues (including breaking changes), run:
>  npm audit fix --force

**Actual vs Expected behavior**
Advisory should refer to `1.28.1` as the patched version for the 1.x branch

**Desktop (please complete the following information):**

- OS: Windows / WSL (Also node:lts-alpine containers)
- Browser [e.g. Chrome 84, safari 14.0]: N/A
- Luxon version [e.g. 1.25.0]: 1.28.1
- Your timezone [e.g. "America/New_York"]: America/Montreal

**Additional context**

We're running `npm audit` as part of our pipelines, so our workflow is blocked.

Thanks

**Comment by canderson-activatecare** [comment]
Update to security advisory database is pending approval from maintainer:

https://github.com/github/advisory-database/pull/1589

@icambron

**Comment by icambron** [comment]
Yeah, the advisory is now updated (I think)

**Comment by carboneater** [comment]
Thanks!

Let's now wait aggressively for NPM to update its GHSA cache...
