### ISSUE TITLE
duration.negate() mutates duration

### ISSUE THREAD

**Issue by riwsky** [moment/luxon#136]
Is this intentional? Because duration.negate() ends up calling the `clone` with `clear=False`, the negated values end up `Object.assign`-ed to the original `dur.values`; this ends up making someDatetime.minus(someDuration) non-idempotent. As far as I can tell, the fix is to just pass `true` for the third arg to clone and add some tests.

Should I do that? Is this fixed in some other branch? Or am I misunderstanding how this should work?

Thanks y'all and have a happy new year.

**Comment by icambron** [comment]
Yikes. Definitely not on purpose. It's true that `negate()` can use clear (and might as well), but it shouldn't but that clone code is broken for the general case. I went ahead and fixed it in ecf7ca3 and released it as 0.2.10
