### ISSUE TITLE
Wrong Patch Version Shown in Github Advisory: Luxon Inefficient Regular Expression Complexity vulnerability

### ISSUE THREAD

**Issue by arealesramirez** [moment/luxon#1360]
**Describe the bug**
I have vulnerabilities shown in my project as it uses `"luxon": "1.25.0"`. 
![Screen Shot 2023-01-09 at 10 54 29 AM](https://user-images.githubusercontent.com/20869583/211363540-0a9d7184-b431-4975-b200-92b92c2af6c9.png)

To check more information, I opened the link https://www.npmjs.com/advisories/1087851.

There, it mentions the patch version for my specific scenario would be 1.38.1.
![Screen Shot 2023-01-09 at 10 55 43 AM](https://user-images.githubusercontent.com/20869583/211363716-d7f2b007-3b99-4d4a-9ad5-d6d94667ac54.png)

After trying to do a quick update `yarn add luxon@1.38.1`, I got the following message "Couldn't find any versions for "luxon" that matches "1.38.1"". 

After checking the list of active versions (https://www.npmjs.com/package/luxon?activeTab=versions), I confirmed 1.38.1 doesn't exist. I assume the patch to fix the vulnerability is version 1.28.1, the most recent update for version 1.x.x.
![Screen Shot 2023-01-09 at 10 56 42 AM](https://user-images.githubusercontent.com/20869583/211363902-928d8cb8-f74c-4f8a-9c27-831618a2459a.png)

**To Reproduce**
Vulnerabilities are shown on projects using luxon version 1.25.0

**Actual vs Expected behavior**
Actual behavior: Updating luxon from 1.25.0 to 1.38.1 doesn't work as version 1.38.1 doesn't exist.

Expected behavior: Update to version 1.38.1 should fix vulnerabilities.

**Desktop (please complete the following information):**

- OS: Mac
- Browser Version 108.0.5359.124 (Official Build) (arm64)
- Luxon version 1.25.0
- Your timezone Central Standard Time

**Additional context**
N/A

**Comment by canderson-activatecare** [comment]
Confirming that the maintainer advisory has the right version number 1.28.1, but the main GHSA has 1.38.1 typo.

Maintainer advisory:  https://github.com/moment/luxon/security/advisories/GHSA-3xq5-wjfh-ppjc
GHSA: https://github.com/advisories/GHSA-3xq5-wjfh-ppjc

**Comment by canderson-activatecare** [comment]
Update to security advisory database is pending approval from maintainer:  

https://github.com/github/advisory-database/pull/1589
