### ISSUE TITLE
string daye to any format using fromFormat

### ISSUE THREAD

**Issue by Bhupendersinghbisht** [moment/luxon#1361]
I am expecting some help where I have my date as string in mm/dd/yyyy Or m/d/yy Or m/dd/yyyy
Or mm-dd-yyyy like that. 

Now this format of date can change but I always want to ensure that I could use this dynamic format and pass that as 2nd argument to fromFormat('20/11/2022', 'MM/dd/yyyy) 
Or fromFormat('06-11-2022', 'dd-MM-yyyy') 

How this can be achieved.  Any suggestion?

**Comment by diesieben07** [comment]
`M/d/yy` can parse both `2/11/22` and also `02/11/2022`. To accept both `M/d/yy` and `mm-dd-yyyy` you can try both in order:

https://runkit.com/embed/mwq2tm5l9faw

**Comment by Bhupendersinghbisht** [comment]
Thanks for sharing this. 
So can I can add more format types to possibleFormats and use it?

**Comment by diesieben07** [comment]
As long as they are not ambiguous, yes. But if you have ambiguous formats this is not possible no matter what you do. For example if you have `d/M/yy` and `M/d/yy` then it's unclear how to parse `1/1/22`, as it fits both formats.
