### ISSUE TITLE
First day of year shows as same year 

### ISSUE THREAD

**Issue by angela-patino-yuli** [moment/luxon#1368]
**Describe the bug**
Jan 1 2023 weekNumber is 52 and year is 2023

**To Reproduce**
<img width="891" alt="image" src="https://user-images.githubusercontent.com/108668515/214849792-3c009c91-9909-4842-a25d-1da6c81cf4e3.png">

**Actual vs Expected behavior**
 year is 2022 and no 2023

**Desktop (please complete the following information):**

- Browser [e.g. Chrome 84, safari 14.0]
- Luxon version [e.g. 1.25.0]
- Your timezone [e.g. "America/New_York"]

**Additional context**
Related issue, context
https://github.com/moment/luxon/issues/1355
https://github.com/moment/luxon/issues/1355#issuecomment-1405019215

**Comment by icambron** [comment]
Please see the [ISO Week Calendar](https://en.m.wikipedia.org/wiki/ISO_week_date). Luxon's weekYear and weekNumber refer to that calendar. Jan 1 2023 is in in the 52nd week of the 2022 week year.
