### ISSUE TITLE
Cannot parse date with meridiem

### ISSUE THREAD

**Issue by chincheta** [moment/luxon#1373]
**Describe the bug**
An error "Invalid DateTime" is raised when parsing a date with AM in it and the a token in the format.

**To Reproduce**
`DateTime.fromFormat("Nov 08, 2022, 2 AM Europe/Berlin", "MMM dd, yyyy, h a z", {locale: "en-US"}).toString()`

**Actual vs Expected behavior**
"Invalid DateTime" vs the date being parsed.

**Desktop (please complete the following information):**

- OS: Windows and Ubuntu.
- Browser Firefox.
- Luxon version 3.2.1
- Your timezone Europe/Brussels

**Additional context**
It fails in browser and in a node app.

**Comment by chincheta** [comment]
The error was a weird unicode character instead of a normal space.

**Comment by dasa** [comment]
This may be fixed by #1369
