### ISSUE TITLE
Full support of Persian Calander.

### ISSUE THREAD

**Issue by mostafabarmshory** [moment/luxon#1374]
In many cases, I need to manipulate dates based on another calendar, in my case Persian. I want to know if Luxon is designed to switch calendars easily. 

If there is an API for a calendar to be fully supported, then I can implement it in my own calendar system. 

If anyone knows about Luxon design, please help.

**Comment by icambron** [comment]
Luxon doesn't provide full support for other calendars, only the ability to format dates in those calendars. Adding such support--e.g. the ability parse dates in them, or add/subtract days from Persian dates--is out of scope for Luxon.

**Comment by mostafabarmshory** [comment]
Dear @icambron 

I`ve reviewed the code; the calendar (ISO) is hardcoded.
Think of the calendar as a service and inject it into the DateTime class. Thats all.
Then we can suggest a new calendar service to support the other one.
