### ISSUE TITLE
StartOf('month') on Hebrew calendar not pointing to 1st

### ISSUE THREAD

**Issue by tounsoo** [moment/luxon#1375]
**Describe the bug**
StartOf('month') is not correct when used with Hebrew Calendar.

**To Reproduce**
```
date // DateTime object of `02/07/2023`
      .reconfigure({ outputCalendar: "hebrew" }) // Change Calendar to Hebrew
      .startOf('month') // set date to start of the month (1st) of the Calendar
      .toLocaleString() // -> 10 Shevat 5783

```

**Actual vs Expected behavior**
Expect the `.toLocaleString()` to be `1 Shevat 5783`

**Desktop (please complete the following information):**

- OS: Mac m1
- Browser: Chrome109 + Safari16
- Luxon version: 3.2.1
- Your timezone:  "America/Los_Angeles"

**Additional context**

**Comment by tounsoo** [comment]
Also tried using `set` but didn't work as well.
```
date // DateTime object of `02/07/2023`
      .reconfigure({ outputCalendar: "hebrew" }) // Change Calendar to Hebrew
      .set({day: 1}) // set date to 1st of the Calendar
      .toLocaleString() // -> 10 Shevat 5783
```

**Comment by diesieben07** [comment]
As the name implies, `outputCalendar` sets the calendar only for _outputting_ dates. Anything else in Luxon always operates on either the Gregorian or ISO Week calendar. By using `startOf('month')` or `set({day: 1})` you are using the Gregorian calendar. `toLocaleString` then shows the date you have created using the output calendar that you have configured.
You can check the [documentation on calendar support](https://moment.github.io/luxon/#/calendars), too.

**Comment by icambron** [comment]
Luxon doesn't support other calendars in the sense you need. You'll want to use hebcal for that.

**Comment by tounsoo** [comment]
Gotcha. I was trying to draw a calendar(using table and data from luton) but when I started adding calendar option it was not working as expected but I guess luxon isn't going to support those scenarios yet.

Thank you for the feedbacks!
