### ISSUE TITLE
Timezone "America/Ciudad_Juarez" is not supported

### ISSUE THREAD

**Issue by miso-belica** [moment/luxon#1376]
Hallo, thank you for the library :)

**Describe the bug**
Exception is thrown for valid timezone name got from the user's phone. I found the zone name also at https://timezonedb.com/time-zones/America/Ciudad_Juarez.

**To Reproduce**
```ts
import {Settings} from 'luxon';

Settings.throwOnInvalid = true;
DateTime.fromISO('2023-01-01T00:00:00', {zone: 'America/Ciudad_Juarez'});
```

**Actual vs Expected behavior**
I expect to create a valid DateTime object for the valid timezone.

**Desktop (please complete the following information):**

- OS: Debian v10.13, Kernel 4.4.0
- Runtime: Node.js v16.19.0
- Luxon version: 3.2.1
- Your timezone: UTC

**Additional context**
Timezone is taken from the user's phone by react-native and sent to backend API running in Node.js.

**Comment by diesieben07** [comment]
This seems to be a fairly new timezone. IANA tzdata 2022g has it, but 2022a does not (I have not bothered checking all the ones in between to find where it was added). Node 14 ships with ICU version 70.1, which has tzdata 2021e. As such you can't expect it to know about this time zone. The same is true for Node 18, which has ICU 71.1, which has tzdata 2022a and thus also does not know about this time zone.
There isn't really anything Luxon can do here, as Luxon uses the timezone database of the underlying platform (Node.JS in this case).

**Comment by miso-belica** [comment]
Thank you. I try to update Node.js to the newest version and I hope that helps. Have a nice day 🙂
