### ISSUE TITLE
DateTime.fromFormat Fails to Parse Time

### ISSUE THREAD

**Issue by derekhubbard** [moment/luxon#1382]
**Describe the bug**
Using `DateFormat.fromFormat` to parse a time value fails to parse the time successfully, resulting in an invalid `DateTime` object.

This worked as expected until updating my browser from Chrome 109 to 110. 

Parsing the same time value in Safari 16.3 and Firefox 110 works as expected.

**To Reproduce**
```javascript
import { DateTime } from 'luxon';

const testTime = DateTime.fromFormat('1:07 AM', 't');

console.log('DateTime.isValid', testTime.isValid);
console.log('DateTime.invalidReason:', testTime.invalidReason);
console.log('DateTime.invalidExplanation:', testTime.invalidExplanation);
```

The output of the console logs above are: 
```
DateTime.isValid false
DateTime.invalidReason: unparsable
DateTime.invalidExplanation: the input "1:07 AM" can't be parsed as format t
```

**Actual vs Expected behavior**
The time format in the example above (`1:07 AM`) should be successfully parsed as a valid `DateTime` object. 

**Desktop (please complete the following information):**

- OS: OSX
- Browser: Chrome 109/110, Safari 16.3, Firefox 110
- Luxon version: 3.2.1
- Your timezone: "America/New_York"

**Additional context**
It's not clear yet whether this is Chrome bug or an issue with Luxon, but starting here in the hopes that you will be able to help me research it more. Thanks in advance!

**Comment by derekhubbard** [comment]
It sounds like others are experiencing this issue when updating to Node 18 as well: 
https://github.com/moment/luxon/issues/1364#issuecomment-1431156347

**Comment by shinnqy** [comment]
Same issue once upgrade browser.

Please check this output, very strange 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/15121888/220055515-fc1954cc-040d-4492-adf0-4d2fa1f9e68b.png">

**Comment by shinnqy** [comment]
Follow up: It turns out, Luxon only accept white space of ascii code 8239, not ascii code 32. Because Luxon use literal value to generate Regex value instead of using `\s`
<img width="302" alt="image" src="https://user-images.githubusercontent.com/15121888/220081344-20fbabd6-2099-46c8-8d2c-360feaf9318e.png">

**Comment by diesieben07** [comment]
This is behaving exactly as described in the documentation, imho.
`tt` is described as the "localized time with seconds". Localized meaning "whatever the current environment says it should look like according to the locale". If the environment (i.e. Chrome in this case) says there should be Unicode 8239 there, then Unicode 32 is not valid.
If you want a rigorous, specific format, you need to build it up yourself from non-localized tokens. `tt` and other localized tokens are _implementation dependent_.

This is also mentioned in the [documentation](https://moment.github.io/luxon/#/parsing?id=consider-alternatives):
> If the string is typed out by a human, it may not conform to the format you specify when asking Luxon to parse it. **Luxon is quite strict about the format matching the string exactly.**

**Comment by shinnqy** [comment]
Why code 32 is invalid? Remember this lib is for browser! So there is no reason not support code 32.

**Comment by diesieben07** [comment]
toLocaleString is specifically also dependent on the underlying implementation. That allows Luxon to be smaller in size than e.g. moment, which has to ship all the locale data.
If you rely on specific output from toLocaleString you are imho misusing the locale API. This also applies to using the locale-dependent format tokens like `tt`. If you want to parse a string like `10:30 pm`, you should be using the format `h:m a`, which specifically says "I want a space, not a narrow width space". The only use-case for parsing with `tt` is if you are parsing the output of `toLocaleString` from some horrible legacy API that does not use ISO format.

So: This is not something to be "handled". You are using the wrong tool.

**Comment by shinnqy** [comment]
@diesieben07 If you use `h:m a`, how to make sure to use correct regional format since even in same locale, some regions are different in format.

**Comment by diesieben07** [comment]
You can't have both. Either you want the local format, then you have to accept it as is from the underlying system (including the fact that ICU now says that a narrow space should be used) or you have to provide your own formats.

**Comment by shinnqy** [comment]
No, I don't agree. Locale and regional format can be supported at the same time.

**Comment by gBusato** [comment]
Didn't had the time to wait for a merge, there I have replace my string : `"9:23 AM".replace(/\s/g, '\u202F')` and now it work

**Comment by diesieben07** [comment]
@shinnqy @derekhubbard Would an option `looseWhitespace` to `DateTime.fromFormat` solve this issue for you? This option would replace any whitespace-literals given by the browser for the locale-dependent format with a `\s` in the regex (not quite, because we don't really want to allow `\n` or `\r`). In that case any whitespace in the input can stand-in for any whitespace in the required format.

**Comment by diesieben07** [comment]
That would be up to @icambron, I don't have permissions to do releases.

**Comment by ccmetz** [comment]
@diesieben07  I understand that this will be fixed once the next version is released but just out of curiosity, why does `DateTime.now().toFormat('t')` not return a string using the non-breaking space character that chrome expects? I would understand why this doesn't work on Chrome:

```
DateTime.fromFormat('1:30 AM', 't');
```

but why wouldn't this work?

```
let time = DateTime.now().toFormat('t');
let datetime = DateTime.fromFormat(time, 't');
```

I guess I would expect that since I formatted the datetime on Chrome, it would use that non-breaking space character that it is expecting when parsing the string using `fromFormat`?

**Comment by diesieben07** [comment]
@ccmetz My guess is that your browser is on a different locale than `en-US`. `fromFormat` defaults to `en-US` parsing, not the browser locale.
