### ISSUE TITLE
DateTime.fromFormat & regex match failed once upgrade to latest version of Edge and Chrome

### ISSUE THREAD

**Issue by shinnqy** [moment/luxon#1384]
**Describe the bug**
Once upgrade to the latest version of edge and chrome. DateTime.fromFormat failed, even the output generated by itself.

When I looked into this. I find the regex match failed.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/15121888/220056252-1b62da8b-012e-4808-b341-c39267e67375.png">

**To Reproduce**
<img width="475" alt="image" src="https://user-images.githubusercontent.com/15121888/220179041-c43d7a6d-ac8b-4a9a-8d5d-34df6a6a4cad.png">

**Actual vs Expected behavior**

**Desktop (please complete the following information):**

- Browser: latest version of edge and chrome
- Luxon version: 3.2.1
- Your timezone:  beijing/shanghai +8

**Additional context**

**Comment by shinnqy** [comment]
<img width="296" alt="image" src="https://user-images.githubusercontent.com/15121888/220064639-84f29d4b-3e3e-4762-9a2a-3ca75faf5a8e.png">

I think you also need to handle ascii code 32.

**Comment by tehamawirelessd4** [comment]
Same here. This was working:
     const opts={locale: 'en-US', zone: 'local'}
     result = DateTime.fromFormat(datetime, 'D tt', opts)

And now, it fails. There's an unprintable unicode character in the regex right before the AM/PM indicator. This makes the parse fail, returning invalid date with the same legacy date strings as last week. My legacy date strings look like this: '2/21/2023 11:01:28 PM'. 

As a workaround, I now use:
   result = DateTime.fromFormat(datetime, 'D hh:mm:ss a', opts)

Which does not put the unicode character into the regex

**Comment by dasa** [comment]
This may be fixed by #1369

**Comment by shinnqy** [comment]
@dasa  Thanks for the info. This PR created 3 weeks ago. Would you please help review it and merge it? I see you are contributor.

**Comment by dasa** [comment]
> I see you are contributor.

That just means I've had PRs merged in the past: https://github.com/moment/luxon/commits?author=dasa

I'm not able to merge any PRs myself.

**Comment by joepwijnhoven** [comment]
+1

**Comment by geertjansen** [comment]
+1

**Comment by diesieben07** [comment]
#1369 has been merged. The next version of Luxon will treat non-breaking white-space equally when parsing macro-tokens like `t`.

**Comment by RonNabuurs** [comment]
Just confirmed that this is also an issue in safari.
