### ISSUE TITLE
toLocaleString behaviour is not the same in different browser

### ISSUE THREAD

**Issue by shinnqy** [moment/luxon#1386]
**Describe the bug**
DateTime.toLocaleString has different behaviour in different browser.

Edge: Version 110.0.1587.50 (Official build) (64-bit)
<img width="437" alt="image" src="https://user-images.githubusercontent.com/15121888/220126781-bd7098ae-b84f-42ec-9cc3-65cfa512b767.png">
Chrome: Version 110.0.5481.78 (Official Build) (64-bit)
<img width="575" alt="image" src="https://user-images.githubusercontent.com/15121888/220126885-0d30d293-e77f-4d61-9220-47912886cfd4.png">

**To Reproduce**
Please share a minimal code example that triggers the problem:
```ts
const targetStr = DateTime.fromJSDate(new Date()).setLocale('en-US').toLocaleString(DateTime.TIME_WITH_SECONDS);
const charCode = targetStr.charCodeAt(7);
```

**Actual vs Expected behavior**

Expect: the output should be same in Edge and Chrome
Acutal: Edge is unicode 32, while Chrome is unicode 8239

**Desktop (please complete the following information):**

- Browser [e.g. Chrome 84, safari 14.0]
- Luxon version [e.g. 1.25.0]
- Your timezone [e.g. "America/New_York"]

**Additional context**

**Comment by diesieben07** [comment]
Luxon's localization abilities depend on the underlying browser and `toLocaleString` is specified to be system dependent. Most systems use Unicode ICU, but this is neither required nor specified. The output is consistent _most of the time_, but this can change as underlying systems update. What you are observing here is that your version of Chrome has an updated ICU and Edge does not (yet).

If you need a date / time format which must never change then `toLocaleString` is not the correct tool. Use `toFormat` for that circumstance.

You may also find the note on the [return value of toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString?retiredLocale=de#return_value) interesting:
> output variations are by design and allowed by the specification. You should not compare the results of toLocaleString() to static values.

**Comment by ngbrown** [comment]
Using `toFormat` also generates different behaviors:

```js
revisionCreateDate.toFormat("fff", { locale: "en-US" })
```

From Node 16 (on Debian):

```
encodeURIComponent("August 4, 2010 at 2:51 PM UTC");
'August%204%2C%202010%20at%202%3A51%20PM%20UTC'
```

From Chrome 113 on Windows 10:

```
encodeURIComponent("August 4, 2010 at 2:51 PM UTC");
'August%204%2C%202010%20at%202%3A51%E2%80%AFPM%20UTC'
```
