### ISSUE TITLE
Typo in type definition Info type. Incorrect UnitOptions type interface

### ISSUE THREAD

**Issue by maburdi94** [moment/luxon#141]
- Correct Info.weeksdays to Info.weekdays
- UnitOptions type does not allow exclusive use of InfoOptions interface but requires at least one other paramter. (eg {locale: "..."} is incompatible, but {locale: "...", outputCalendar: "..."} works). This  doesn't seem to fit the docs

**Comment by icambron** [comment]
The TS defs are community maintained [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/index.d.ts) so you'll have to file something over there. If you think the types are right and either the code or the documentation is right, I can help.
