### ISSUE TITLE
Mexico removed daylight savings

### ISSUE THREAD

**Issue by clivi-kj** [moment/luxon#1417]
**Describe the bug**
Mexico removed day light savings in the majority of the country. When will the database of timezones be updated?

Release 2022f - 2022-10-28 18:04:57 -0700

  Briefly:
    Mexico will no longer observe DST except near the US border.
    Chihuahua moves to year-round -06 on 2022-10-30.
    Fiji no longer observes DST.
    Move links to 'backward'.
    In vanguard form, GMT is now a Zone and Etc/GMT a link.
    zic now supports links to links, and vanguard form uses this.
    Simplify four Ontario zones.
    Fix a Y2438 bug when reading TZif data.
    Enable 64-bit time_t on 32-bit glibc platforms.
    Omit large-file support when no longer needed.
    In C code, use some C23 features if available.
    Remove no-longer-needed workaround for Qt bug 53071.

**Comment by diesieben07** [comment]
Luxon does not have its own time zone database. It uses the Intl API of the underlying platform (i.e. the browser, Node.js, etc.).
