### ISSUE TITLE
Asia/Singapore timezone offsetNameShort is wrong

### ISSUE THREAD

**Issue by puddinator** [moment/luxon#1422]
Hi all, thanks for this great library.

For Asia/Singapore time zone, ```offsetNameLong``` returns ```Singapore``` which is correct, but ```offsetNameShort``` remains ```GMT``` which is wrong. I get the same results from ```toResult('ZZZZZ')``` and ```toResult('ZZZZ')``` respectively.

I've read that Luxon gets the offsetName from Intl. Intl returns the correct output
```
new Intl.DateTimeFormat('en', {
            timeZoneName: 'short',
            timeZone: 'Asia/Singapore',
        }).format()
``` 
is GMT+8

**Comment by diesieben07** [comment]
Cannot reproduce: 
```
console.log(new Intl.DateTimeFormat('en', {timeZoneName: 'short', timeZone: 'Asia/Singapore',}).format());
console.log(DateTime.now().setZone('Asia/Singapore').toFormat('ZZZZZ'));
console.log(DateTime.now().setZone('Asia/Singapore').toFormat('ZZZZ'));
```
Outputs:
```
4/18/2023, GMT+8
Singapore Standard Time
GMT+8
```

I'm using Node 18.12 to test. What runtime are you using?

**Comment by puddinator** [comment]
Wow, you're spot on with the issue with version. My bad, I was using an older version of Luxon!
