### ISSUE TITLE
In Firefox DateTime.now() returns invalid value

### ISSUE THREAD

**Issue by jira-zz** [moment/luxon#1423]
In Firefox luxon.DateTime.now().isValid is false.

![image](https://user-images.githubusercontent.com/444428/233100904-f5e69c13-79da-492c-9ff3-9a7c61f462fb.png)

**Comment by diesieben07** [comment]
I cannot reproduce this in Firefox 112.0.1 with Luxon 3.3.0 using the following test:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Luxon test case</title>
  <script src="https://cdn.jsdelivr.net/npm/luxon@3.3.0/build/global/luxon.min.js"></script>
</head>
<body>
  <script>
    const dt = luxon.DateTime.now();
    console.log(dt.isValid);
  </script>
</body>
</html>
```

Can you please provide additional details?

**Comment by jira-zz** [comment]
I used [datejs](https://github.com/datejs/Datejs) on my page. removing it solved the problem.
Strange is it worked in Chrome but not in FF.
Anyway problem solved.
