### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by rodrigofariow** [moment/luxon#1431]
Hello,

Is something blocking a release to npm right now?
I'm not aware of any official schedule and it's been more than a month since the last change in master, so I'm asking.

Not sure how/where else to ask this so forgive me for opening an issue just for this.

Cheers!

**Comment by emilykl** [comment]
Would love an update on a new release as well! There's some new features since the last release that I'm very interested in using in production ([this one](https://github.com/moment/luxon/pull/1405) in particular).
