### ISSUE TITLE
U+20 vs U+202f space between time and meridian when using 'DATETIME_SHORT'

### ISSUE THREAD

**Issue by JasonFoglia** [moment/luxon#1439]
With code below the format of the output toLocalString has a Unicode Character white space between the time and meridian which is not consistent with the white space between the date and time. 

`

    static formatDate(value: DateTime | Date, format: string): string {

        let dateTimeToUse: DateTime;

        if (value instanceof Date) {
          dateTimeToUse = DateTime.fromJSDate(value);
        } else {
          dateTimeToUse = value;
        }

        return dateTimeToUse.toLocaleString((<any>DateTime)[format]);
    }
` 

Using these dates:
  const dateToFormat = '2023-05-22T12:00:00Z';
  const expectedDate = '5/22/2023, 12:00 PM'; 
  const actualDate = '5/22/2023, 12:00 PM';

This breaks tests using Jasmine. 

- OS: Windows 10
- Browser Chrome Version 112.0.5615.138
- Luxon version 3.3.0
- Your timezone All timezones

I've only tested with 'DATETIME_SHORT' formatter and no others.

**Comment by diesieben07** [comment]
The output of toLocaleString depends on the underlying platform and is not a defined and testable output.
