### ISSUE TITLE
Can't parse "Tue Jan 24 2023 23:59:39 GMT+0100 (Central European Standard Time)"

### ISSUE THREAD

**Issue by Kydlaw** [moment/luxon#1445]
**Describe the bug**

Parsing of the string "Tue Jan 24 2023 23:59:39 GMT+0100 (Central European Standard Time)" using "EEE MMM dd yyyy HH:mm:ss 'GMT'ZZ (ZZZZZ)" fails

**To Reproduce**
```js
const dateString = 'Tue Jan 24 2023 23:59:39 GMT+0100 (Central European Standard Time)'
const formatString = "EEE MMM dd yyyy HH:mm:ss 'GMT'ZZ (ZZZZZ)"

// Parse the date string using the Luxon format
const dateTime = DateTime.fromFormat(dateString, formatString)

// Format the date in the desired format
const formattedDate = dateTime.toFormat('dd-MM-yyyy')

// Output the formatted date
console.log(formattedDate)
```

**Actual vs Expected behavior**
Currently it returns an invalid DateTime
I expected the `.fromFormat()` function to return a DateTime object containing the information from the string.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge 114
- Luxon version 3.3.0
- Your timezone Europe/Paris

**Additional context**

**Comment by diesieben07** [comment]
As documented in the [table of tokens](https://moment.github.io/luxon/#/parsing?id=table-of-tokens), `ZZZZZ` is not a valid parsing token. Luxon can only parse time zones from their IANA names (or from an offset, like you are already doing), this uses the token `z`. The reason for this is that there is no browser API to parse "human readable" time zone names and those names are not even consistent or unique.

**Comment by icambron** [comment]
This specific limitation is also discussed here: https://moment.github.io/luxon/#/parsing?id=limitations

**Comment by diesieben07** [comment]
Unfortunately the only real option you have is to ship your own mapping of abbreviated zones to proper time zone names and do the replacement manually before passing it in to Luxon or otherwise. I'm not 100% sure where you'd find this, but most likely either in the IANA Time Zone Database or maybe in Unicode's ICU.
