### ISSUE TITLE
Can't create "negative" intervals

### ISSUE THREAD

**Issue by ericmorand** [moment/luxon#145]
It is impossible to create a "negative" interval, i.e. an interval where the end point is earlier than the start point:

```
let dateEarlier = new Date(2007, 5, 19);
let dateLater = new Date(2010, 9, 6);
let di = Interval.fromDateTimes(dateLater, dateEarlier);

console.warn(di);
```

`Interval { Invalid, reason: invalid endpoints }`

The source code explicitely check that the start point is earlier than the end point. Is this a bug or a deliberate move?

**Comment by kshukost** [comment]
according to docs that's an expected behaviour, but real life says it's very inconveniently(( it obliges users to create additional conditions((

**Comment by icambron** [comment]
Yeah, I'm not really against them in principle so much as they made implementing them harder, and some of the semantics are less obvious. There are roughly two options:

 1. Just flip them in `fromDateTimes`; all durations are "positive" but you can provide the endpoints in any order and they'll land as `start` and `end` appropriately.
 2. Fully support the idea of negative time.

2 is pretty complicated: are the lengths negative? How do overlaps work? Etc. So I'd accept a PR doing option 1.

**Comment by ericmorand** [comment]
> Just flip them in fromDateTimes; all durations are "positive" but you can provide the endpoints in any order and they'll land as start and end appropriately.

We would still need a way to know that the endpoints have been flipped - this would be useless without that. If you are a creating the Interval, you know the endpoints and it's easy to check if they've been inverted. But if you're only a consumer and receive an Interval from an opaque system, you can't guess that the original endpoints were inverted.

So,either length() would have to return a negative number or there should be a function available to check that the endpoints were inverted - for example isNegative()?

About option 2, can you calrify what would be tricky with overlaps? I would love to work on this solution but I don't want to if you thunk this is a lost cause.

**Comment by icambron** [comment]
What I mean is, what is the sign on the union of two intervals, one negative and one positive? Both negative? Similar questions for the other set-like methods. Besides making the API clean and obvious, I also worry there will have to be a lot of checks for interval sign sprinkled through the code.

What's your use case for negative intervals? In years of supporting Twix, I can't remember a single request for them.

**Comment by ericmorand** [comment]
My test case is very simple: I'm working on a lib that formats and Interval the same way PHP DateInterval ::format() works. I don't know how the Interval was constructed since I receive it as parameter to my formatting function:

let myFormattingFunction = function(interval: Interval) {
    // format the interval to return form example "2 days ago" or "in 2 days"
}

Currently, it's not possible to send to my function a negative interval and even if it was I have no way to know that it is a negative interval.

In PHP, you can write something like this to create a negative interval:

`$diff = DateInterval::createFromDateString('-1 day');`

Then formatting it with `$diff->format('%d minutes')` would result to `"-1 days"`.

**Comment by icambron** [comment]
@ericmorand I think there's a terminology issue here. In Luxon, those are durations, not intervals. Luxon supports negative durations. An interval in Luxon is something different; it's the span of time between two specific times. So for example, "2 days" and "negative 2 days" are durations, but "from today until the day after tomorrow" and "from two days ago until today" are intervals.

You can think of an interval as in some way the application of a duration to a specific time, resulting in a range. But note above that I still always expressed the interval as starting at the earlier time and finishing at the later time. Obviously the duration can be negative, but the interval... that's different.

**Comment by ericmorand** [comment]
I got your point: my library shoudl not format Intervals but Durations. That makes a lot of sense.

Thanks for your patience and support.

**Comment by sam-s4s** [comment]
Just for the record, having run into this problem myself, I think my solution will be...
a) wrapper "Interval.fromDateTimes(from, to)"
b) if they are around the wrong way, flip them
c) return a boolean "flipped" so the consumer knows that this has happened
d) in subsequent usages of this Interval object, I then make the .length() results negative if the boolean is true

It's a bit of extra work - in my opinion, it would be lovely if it worked like moment, and just allowed inverted values, and provided negative results by default :) I think that not only would this make sense, but would be "expected behaviour".

Also, as a bonus, because the inverted behavious is currently not allowed at all, to implement this would not result in any "breaking change" of exiting functionality.

But yes, would be a bit of work to implement. But then again, everyone currently has to do it themselves I suppose.
