### ISSUE TITLE
Set timezone on .now() options

### ISSUE THREAD

**Issue by DevboiDesigns** [moment/luxon#1462]
**Describe the bug**
When passing timezone options to the .now() method, the wrong time is shown.

**To Reproduce**
```js
const now = DateTime.now({ zone: 'America/New_York' })
console.log(now.minute, now.hour) // returns one hour off of what it should be
```

**Actual vs Expected behavior**
Give me the time it currently is in New York

**Desktop (please complete the following information):**

- Luxon version [e.g. 1.25.0]
   - 3.0.4
- Your timezone [e.g. "America/New_York"]
   - Asia/Bangkok

**Additional context**
Maybe this should be a feature but it seems like it would already be a feature. Let me know if I am mistaken. 

**Work Around**
I just used the fromJSDate() method and it worked correctly

**Comment by diesieben07** [comment]
[`DateTime.now`](https://moment.github.io/luxon/api-docs/index.html#datetimenow) does not take any parameters. From its documentation:
> Create a DateTime for the current instant, in the system's time zone.

For your use case you want [`DateTime.local`](https://moment.github.io/luxon/api-docs/index.html#datetimelocal), which allows you to set the zone, locale and many other options.
