### ISSUE TITLE
Timezone support property documentation inconsistent

### ISSUE THREAD

**Issue by patrickjuchli** [moment/luxon#147]
The result of `Info.features()` is documented here: https://moment.github.io/luxon/docs/class/src/info.js~Info.html#static-method-features

According to the documentation, the result should contain a property called `timezones`. The actual result contains a property called `zones`.

(Also the type definitions at `@types/luxon` expect `timezones` which is misleading)

**Comment by icambron** [comment]
Happy to take a PR cleaning that up

**Comment by patrickjuchli** [comment]
Happy to do it but which one should it be? I prefer `timezones`, is that okay?

**Comment by icambron** [comment]
Good question. I think it needs to be `zones`, given that the tz argument to other methods is `zone`.

**Comment by patrickjuchli** [comment]
Okay, that makes sense. PR coming soon.

**Comment by icambron** [comment]
Fixed in #148
