### ISSUE TITLE
Duration return 60 minutes instead of adding an hour

### ISSUE THREAD

**Issue by kl3sk** [moment/luxon#1480]
**Describe the bug**
Parsing ISO time return a weird result such as "60 minutes"

**To Reproduce**
[JS Fiddle](https://jsfiddle.net/klesk/a91k032m/)

**Actual vs Expected behavior**
returns `"6 hours, 60 minutes, 0 seconds"`
instead of `"7 hours, 0 minutes, 0 seconds"`

**Desktop (please complete the following information):**

- OS: Win10
- Browser firefox 116.0.2
- Luxon version 3.4.0
- Your timezone Europe/Paris

**Additional context**
Great library 👍

**Comment by kl3sk** [comment]
My bad with more tests I just realize that certainly intentional, Luxon add hours and minutes on each side.

If it's that fell free to close the issue.

Note: How coud I achieve what I want ?

**Comment by icambron** [comment]
you want `Duration#normalize()`. [Fiddle](https://jsfiddle.net/b0kuwLeq/).

**Comment by kl3sk** [comment]
Ho thanks I missed this one.
