### ISSUE TITLE
Info.months return null[] on iOS if locale format is 'en-GB'

### ISSUE THREAD

**Issue by FrancoTanzarella** [moment/luxon#1486]
**Describe the bug**
This happens on iOS only. `Info.months('long', {locale: 'en-GB'})` returns an array filled with `null` but replacing `en-GB` with just `en` returns the month names. I can't get around this by stripping of `-GB` since we support other languages  like `es-CA, es-ES` etc.

**To Reproduce**
[snack:](https://snack.expo.dev/@francot/luxon-locale-returns-null-with-en-gb)

**Actual vs Expected behavior**
expect the `en-GB` and other locales to work. 

**Desktop (please complete the following information):**

- OS: iOS
- Luxon version: 3.4.0
- Your timezone:  Europe/London

**Additional context**

**Comment by diesieben07** [comment]
This seems to be a problem with the implementation of `Intl.DateTimeFormat#formatToParts`. Take this code:
```js
const dtf = new Intl.DateTimeFormat('en-GB', {month: 'long'});
console.log(dtf.formatToParts(new Date()));
```

V8 (i.e. NodeJS, Chrome and related browsers) and Firefox report the following:
```json
[
  { "type": "month", "value": "August" }
]
```

In sandbox environment you shared, this code produces the following (incorrect, note the `type` key) result instead:
```json
[
  { "type": "literal", "value": "August" }
]
```

I currently do not have the ability to test this on an actual iOS device (or Safari on macOS). But it seems you'll have to open a bug report in whichever environment causes this wrong result.

**Comment by dasa** [comment]
Safari 16.6 returns `[{type: "month", value: "August"}]`

**Comment by diesieben07** [comment]
Thank you for testing, it sounds like this is yet another bug with [Hermes](https://reactnative.dev/docs/hermes).

**Comment by FrancoTanzarella** [comment]
Thanks for the feedback. I can get around this using globalize for the month and day names for now.

**Comment by diesieben07** [comment]
You could also use [this polyfill](https://formatjs.io/docs/polyfills/intl-datetimeformat/).
