### ISSUE TITLE
Setting Weekday

### ISSUE THREAD

**Issue by nbd9** [moment/luxon#149]
First of all, thank you for this library. From what I've seen it's looking great and I can't wait to use it in future projects.

On that note, I'm trying to add it to a project I'm currently working on and having a bit of a problem. I need to set a datetime object to the next Wednesday in the week. In Moment, I could use `moment().day(10);`, but there seems to be no substitute in luxon. I tried using `DateTime.set({ weekday: 'Wednesday'});`, but it didn't seem to work. Is this a planned feature, or am I missing something in the docs?

Thanks again for the library, looking forward to seeing where it goes.

**Comment by icambron** [comment]
Weekdays are numbers in Luxon, so:

```js
DateTime.local().set({weekday: 3});
```

returns a DateTime with on the Wednesday of the current week.
