### ISSUE TITLE
DateTime.now() returns null for Asia/Kolkata IANA zone

### ISSUE THREAD

**Issue by BurgerZ** [moment/luxon#1490]
**Describe the bug**
`DateTime.now()` returns `null` if you try to set the timezone of `Asia/Kolkata`. It's not throwing any errors, just returns `null`.

**To Reproduce**
```javascript
try {
    console.log("date:", DateTime.now().setZone("Asia/Kolkata"))
} catch (error) {
    console.log("error:", error)
}
```
Resulting log entry:  `date: null`

**Actual vs Expected behavior**
Expecting that it will result the actual date in selected time zone:
```javascript
try {
    console.log("date:", DateTime.now().setZone("Europe/Madrid"))
} catch (error) {
    console.log("error:", error)
}
```
Output should be something like:  `date "2023-08-17T18:09:09.866+02:00"`

**Desktop (please complete the following information):**

- OS: iOS 16.4 (Simulator)
- Browser 
- Luxon version 3.4.0
- Your timezone "Europe/Madrid"

**Additional context**
-

**Comment by diesieben07** [comment]
I cannot reproduce this in the iOS 16.4 simulator.

**Comment by BurgerZ** [comment]
> I cannot reproduce this in the iOS 16.4 simulator.

Try this Expo snack - https://snack.expo.dev/@burgerz/luxon-datetime-issue 

On web and Android it works well, but on iOS it shows just `null` instead of actual DateTime for `Asia/Kolkata`.

**Comment by diesieben07** [comment]
Luxon uses `Intl.DateTimeFormat` to provide its localization and time zone data.
React Native uses Hermes normally, not the default iOS WebView. Hermes' implementation of `Intl.DateTimeFormat` is unfortunately quite buggy and incomplete.
In this case, `new Intl.DateTimeFormat(undefined, { timeZone: 'Asia/Kolkata' })` throws under Hermes ("incorrect timeZone information provided"). You'll have to report a bug to Hermes.
