### ISSUE TITLE
luxon toRelative() returning different values while migrating from moment fromNow()

### ISSUE THREAD

**Issue by Gokulkannan08** [moment/luxon#1492]
**Describe the bug**
Migrating from moment to luxon:
In my case moment.fromNow() and luxon.DateTime.toRelative() return different value

**To Reproduce**
```
DateTime.fromISO(new Date('2023-08-07T12:54:56.886Z').toISOString()).toRelative()
```
`returns 16 days ago`

**Actual vs Expected behavior**
As expected should be 17 days ago
```
moment('2023-08-07T12:54:56.886Z').fromNow()
```
`returns 17 days ago`

- Browser - latest
- Luxon version - latest
- Your timezone - "Asia/calcutta"

**Comment by icambron** [comment]
You'll need to tell us what time it was when you ran this.

**Comment by Gokulkannan08** [comment]
Checked round 10.30 am in the morning and periodically after that
**timezone - "Asia/calcutta"**

**Comment by diesieben07** [comment]
I cannot reproduce this with the following code:
```js
const dummyNow = DateTime.fromISO('2023-08-25T10:30', {zone: 'Asia/Calcutta'}).toMillis();
Settings.now = () => dummyNow;
Settings.defaultZone = 'Asia/Calcutta';
Settings.defaultLocale = 'en-US';
console.log(DateTime.fromISO(new Date('2023-08-07T12:54:56.886Z').toISOString()).toRelative());
```

This produces "17 days ago" for me, both in Node.JS 18, Chrome and Firefox.

Please provide more details for how to reproduce this issue.

**Comment by Gokulkannan08** [comment]
I have attached the screenshot below.

**Luxon**
![Screenshot from 2023-08-27 11-33-52](https://github.com/moment/luxon/assets/73270375/d1df6a42-9a85-459a-ab6e-3975d448019b)

**Moment**
![Screenshot from 2023-08-27 11-33-41](https://github.com/moment/luxon/assets/73270375/05273d93-d9a5-4b87-ba90-0f264e50f81e)

**Comment by diesieben07** [comment]
Okay, so the date you're using is `2023-08-07T18:24:56` in your time zone. Since the current time in your time zone is `2023-08-27T11:33:00`, 19 days and a few hours have passed. As such the report "19 days ago" is entirely accurate.

Moment.js does [some funky rounding when you call `fromNow`](https://momentjs.com/docs/#/displaying/fromnow/) instead of giving you an accurate report.
In Luxon you can use the `padding` option of `toRelative` to round up to e.g. the nearest day.

**Comment by Gokulkannan08** [comment]
Thanks

**Comment by Gokulkannan08** [comment]
How to round up with the nearest day using `padding` in toRelative()?
