### ISSUE TITLE
Luxon weekdayShort giving null value for all dates | React native IOS real device only

### ISSUE THREAD

**Issue by ashishmangukiya** [moment/luxon#1500]
**Describe the bug**
I am using luxon library to manage dates in my iOS application which is developed using react-native. In android it is working fine but in iOS real device it is giving null value from any date.

**To Reproduce**
Install latest luxon library in React native application.
Start iOS application in real device.
Use `DateTime.now().weekdayShort` and console it, It will give `null` value

**Actual vs Expected behavior**
Expected output should be like 'Mon', 'Tue' etc

- OS: [iOS any version]
- Luxon version [3.4.3]

**Additional context**
It is working fine in iOS simulator but in real device it is giving `null` value for all dates

**Comment by diesieben07** [comment]
React Native uses Hermes as its JavaScript engine, which unfortunately has many shortcomings in terms of its Intl.DateTimeFormat API implementation.
However, I am unable to reproduce this in Expo: https://snack.expo.dev/dVh0QsfdD (I do not have access to a physical iOS device). Included in the code is a test to do the same thing Luxon does using the Intl.DateTimeFormat API. Please test, if this code reports the correct value on your device. If not, this is a problem with your runtime, not with Luxon.

**Comment by ashishmangukiya** [comment]
@diesieben07 I opened your expo link and run it on real iOS device. again same issue [Link](https://i.ibb.co/R6V4Vqp/IMG-5047.jpg).

**Comment by diesieben07** [comment]
I will test on a real device later today and try to debug the problem.

**Comment by ashishmangukiya** [comment]
Ok, If you need any help on debugging then let me know.

**Comment by diesieben07** [comment]
I have now confirmed that this indeed an issue with Hermes. Your statement that Hermes is only used on Android is incorrect. If I open the Expo link on a real iOS device, then `global.HermesInternal` is defined, [meaning Hermes is in use](https://reactnative.dev/docs/hermes#confirming-hermes-is-in-use).
Please verify again if you are _really_ not using Hermes.

The following code demonstrates the problem:
```js
const intl = new Intl.DateTimeFormat(undefined, { weekday: "short" });
console.log(intl.formatToParts());
```

In a correct implementation of `DateTimeFormat` (including in Safari on iOS) this produces the following:
```js
[{ type: "weekday", "value": "Thu" }]
```

Hermes instead produces:
```js
[{ type: "literal", "value": "Thu" }]
```

**Comment by AndrewKirkovski** [comment]
Is there a known work around for this issue except disabling hermes for IOS?

**Comment by diesieben07** [comment]
> Is there a known work around for this issue except disabling hermes for IOS?

You could install a Polyfill for the Intl API.

**Comment by krystiansliwa** [comment]
> > Is there a known work around for this issue except disabling hermes for IOS?
> 
> You could install a Polyfill for the Intl API.

I have the same issue. What polyfill you are referring to?

**Comment by diesieben07** [comment]
> I have the same issue. What polyfill you are referring to?

https://formatjs.io/docs/polyfills/intl-datetimeformat/

**Comment by krystiansliwa** [comment]
Tried now to do it but still don't have weekdays

polyfills 

```
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';
import '@formatjs/intl-numberformat/polyfill';
import '@formatjs/intl-numberformat/locale-data/en'; // locale-data for en
import '@formatjs/intl-datetimeformat/polyfill';
import '@formatjs/intl-datetimeformat/locale-data/en'; // locale-data for en
import '@formatjs/intl-datetimeformat/add-all-tz'; // Add ALL tz data
```

result for `toLocaleParts()`

```
[
    {
        "type": "month",
        "value": "5"
    },
    {
        "type": "literal",
        "value": "/"
    },
    {
        "type": "day",
        "value": "31"
    },
    {
        "type": "literal",
        "value": "/"
    },
    {
        "type": "year",
        "value": "2024"
    }
]
```

Any suggestions how to workaround this?

**Comment by SerSerch** [comment]
```js
export function dateFormat(fmt, date) {
  try {
    const regex = /(\w)\1+|\w/gi;
    const localDate = date || DateTime.local();

    return typeof fmt === 'string'
      ? fmt.replace(regex, function (match) {
          switch (match) {
            case 'EEE':
            case 'ccc':
              return localDate.toLocaleString({weekday: 'short'});
            case 'EEEE':
            case 'cccc':
              return localDate.toLocaleString({weekday: 'long'});
            case 'MMM':
            case 'LLL':
              return localDate.toLocaleString({month: 'short'});
            case 'MMMM':
            case 'LLLL':
              return localDate.toLocaleString({month: 'long'});
            default:
              return localDate.toFormat(match);
          }
        })
      : '';
  } catch (err) {
    console.log('ERROR[datetime] dateFormat', err);
  }
}
```
