### ISSUE TITLE
DateTime.hasSame(...) doesn't work with months

### ISSUE THREAD

**Issue by MSeeligHEC** [moment/luxon#1502]
**Describe the bug**
Using hasSame to check if two date times have the same month fails.

**To Reproduce**
```typescript
const monthMoment = DateTime.fromJSDate(new Date(1971, 8, 8, 0, 0, 0, 0))
monthMoment.hasSame(DateTime.fromJSDate(new Date(2023, 8, 8, 0, 0, 0, 0)), "month") -> returns false
```

**Actual vs Expected behavior**
Using hasSame to check month should work correctly. If the first date time has september as month and the date time it gets checked with is also in september it shloud return true.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome 114.0.5735.134
- Luxon version 3.4.0
- Your timezone "Europe/Berlin"

**Comment by MSeeligHEC** [comment]
Just updated to 3.4.3 and the Problem still exists.

**Comment by diesieben07** [comment]
`hasSame('month')` asks "do these dates have the same _calendar month_". September 1971 and September 2023 are not the same calendar month. Even though both are _a_ September, they are in different years and thus are different calendar months.
Another way to think about this is that `hasSame('month')` implies `hasSame('year')`.

If you want to check if the month is the same regardless of year, just check if the month property is the same:
```js
const a = DateTime.fromJSDate(new Date(1971, 8, 8, 0, 0, 0, 0));
const b = DateTime.fromJSDate(new Date(2023, 8, 8, 0, 0, 0, 0));
console.log(a.month === b.month); // true
```

**Comment by MSeeligHEC** [comment]
Just to be sure. If i check the day with hasSame it should also return false since they are not in the same year?

**Comment by diesieben07** [comment]
Correct. You can think of `hasSame(<unit>)` checking that unit _and all bigger units_.
