### ISSUE TITLE
Using luxon in react native Android, setZone returns null

### ISSUE THREAD

**Issue by pencilcheck** [moment/luxon#153]
I used "babel-polyfill" so luxon will work with the use of for (let ... of) however somehow .setZone returns null when DateTime.fromISO returns the correct timestamp.

Any idea why?

Example output:
`[exp] durationDisplay 2018-01-01T00:00:00 2018-01-09T21:25:17 America/New_York "2018-01-01T00:00:00.000-05:00" "2018-01-09T21:25:17.000-05:00" null null`

The first two are raw output of the timestamp in string, and the ones in quotes are the output of DateTime.fromISO, and the last two nulls are ones after running setZone.

**Comment by icambron** [comment]
Yeah, React Native for Android doesn't ship with Intl support, so `setZone` returns invalid instances. I have a note about this at the end of [this doc](https://moment.github.io/luxon/docs/manual/matrix.html) but maybe I'll move it to the Install guide. Anyway, use this thing to fix it: https://github.com/SoftwareMansion/jsc-android-buildscripts.

**Comment by pencilcheck** [comment]
Thanks, the intl variants does work.

**Comment by arys** [comment]
> Thanks, the intl variants does work.

how did you installed intl version of jsc-android, did you build your own version from source?
