### ISSUE TITLE
Luxon 3 not available on unpkg

### ISSUE THREAD

**Issue by Vadorequest** [moment/luxon#1533]
**Describe the bug**
https://unpkg.com/browse/luxon@3.4.3 returns a 404
Whereas https://www.jsdelivr.com/package/npm/luxon works well.
Also, it used to work, because https://unpkg.com/browse/luxon@1.3.0/ works well.

I'm not sure what's wrong with unpck CDN, but a fix would be greatly appreciated.

My motivation is to use Luxon in WeWeb (no-code tool), which only supports unpck.

**Related**
https://github.com/moment/luxon/issues/282

**Comment by dasa** [comment]
https://unpkg.com/browse/luxon@3.4.3/ is working for me (added trailing slash).

**Comment by Vadorequest** [comment]
Silly mistake on my end, then. Thank you! It's working indeed with the slash.
