### ISSUE TITLE
Interval splitAt produces an invalid interval during DST change

### ISSUE THREAD

**Issue by zub0r** [moment/luxon#1537]
**Describe the bug**
Interval splitAt produces an invalid interval during DST change 

**To Reproduce**
https://stackblitz.com/edit/luxon-demos-tpff1z?file=index.ts

**Actual vs Expected behavior**
Interval splitAt should produce valid intervals during DST change 

- OS: Ubuntu
- Browser Chrome 
- Luxon version 3.4.3
- Your timezone Europe/Bratislava

**Comment by diesieben07** [comment]
This was already fixed by https://github.com/moment/luxon/pull/1524, the fix will be in the next version of Luxon.
Until then you can work around this bug by converting all split-points to UTC:

```ts
const interval = Interval.fromISO('2023-10-29T01:00:00.000+02:00/2023-10-29T04:00:00.000+01:00');
const cutpoints = interval.splitBy({ hour: 1 }).map((i) => i.start.toUTC()); // <== Converting to UTC here
const cuts = interval.splitAt(...cutpoints);
```
