### ISSUE TITLE
fromFormat ZZZZ doesn't parse UTC, returns null

### ISSUE THREAD

**Issue by ozten** [moment/luxon#1552]
**Describe the bug**
I am trying to parse a string like `11/15/23 00:51 UTC`. I get `{ Invalid, reason: unparsable }`.

**To Reproduce**
These fail when added to `test/datetime/tokenParse.test.js`

```
 expect(DateTime.fromFormat("UTC", "ZZZZ").zoneName).toBe('UTC');  
 expect(DateTime.fromFormat('11/15/23 00:51 UTC', 'LL/dd/yy T ZZZZ').toMillis()).toBe(1700009460000);
```

These both fail.

**Actual vs Expected behavior**

DateTime.fromFormat should support `ZZZZ` [formatting](https://moment.github.io/luxon/#/formatting).

**Desktop (please complete the following information):**

Note: This is happening in NodeJS process as well as in the browser.

- OS: Mac OS X
- Browser Chrome 120.0.6099.62 (Official Build) (arm64)
- Luxon version 3.4.4
- Your timezone "America/Los_Angeles"

**Additional context**

**Comment by diesieben07** [comment]
Parsing has a [separate table of tokens](https://moment.github.io/luxon/#/parsing?id=table-of-tokens) from formatting. This is due to limitations of the Intl API that Luxon uses, this is explained [here](https://moment.github.io/luxon/#/parsing?id=limitations).
