### ISSUE TITLE
Info.weekdays returning null for different locale(de, ro) on iOS(simulator and real device)

### ISSUE THREAD

**Issue by BocanceaIonut** [moment/luxon#1556]
**Describe the bug**
Info.weekdays returns a list of 7 null elements. 

**To Reproduce**
```
import { Info } from 'luxon';
const weekdays = Info.weekdays('long', { locale: 'ro' });
console.log('---------------weekdays --------------', weekdays);
```
OR
```
import { Info } from 'luxon';
const weekdays = Info.weekdays('long', { locale: 'de' });
console.log('---------------weekdays --------------', weekdays);
```

**Actual vs Expected behavior**
Expected
`["luni", "marți", "miercuri", "joi", "vineri", "sâmbătă", "duminică"]`
OR
`["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"]`

Actual
`[null, null, null, null, null, null, null]`

**Desktop (please complete the following information):**

- OS: iOS
- Luxon version: 3.4.3
- Your timezone: Eastern European Standard Time

**Additional context**
I installed the following polyfill: 

```
"@formatjs/intl-datetimeformat": "^6.12.0",
"@formatjs/intl-locale": "^3.4.3",

```
and imported it in index.js like this

```
import '@formatjs/intl-datetimeformat/locale-data/de';
import '@formatjs/intl-datetimeformat/locale-data/ro';
```

and it's still not working.

**Comment by diesieben07** [comment]
Please post the output of the following snippet in your runtime:
```js
const intl = new Intl.DateTimeFormat('de', { weekday: 'long' });
console.log(intl.formatToParts(new Date()));
```

It should output something like this:
```js
[
  { "weekday": "Donnerstag" }
]
```

**Comment by BocanceaIonut** [comment]
The output 
```
const intl = new Intl.DateTimeFormat('de', { weekday: 'long' });
console.log('----------', intl.formatToParts(new Date()));
```
is 
`---------- [{"type": "literal", "value": "Donnerstag"}]`

**Comment by diesieben07** [comment]
That suggests you are using [Hermes](https://reactnative.dev/docs/hermes), which unfortunately has an incomplete and not spec-compliant implementation of `Intl.DateTimeFormat`. The output you posted is not correct, as you can see the value is marked as a literal, not a weekday. I suggest you report this bug to Hermes.
See also https://github.com/moment/luxon/issues/1500.
