### ISSUE TITLE
Incorrect short format for timezone offset names

### ISSUE THREAD

**Issue by jdconley** [moment/luxon#1560]
**Describe the bug**
Luxon returns a GMT-based offset for a formatted timezone when I expect a friendly short name.

**To Reproduce**

Create a React Native app targeting Android with Hermes enabled.

```ts
import { DateTime, IANAZone } from 'luxon';

console.log(IANAZone.create('America/New_York').offsetName(DateTime.utc().getTime(), { format: 'short' }));
```

**Actual vs Expected behavior**
On iOS this prints as expected (EST). On Android I see 'GMT-4' (as of posting).

**Mobile**

- OS: Android API 34
- Browser: react-native 0.72.6 Hermes
- Luxon version: ^3.4.4
- Your timezone: America/Los_Angeles

**Comment by diesieben07** [comment]
Luxon can only provide data as good as the underlying platform. Hermes' implementation of the Intl.DateTimeFormat is unfortunately not great.
If you check the output of the following snippet, you will see that it likely reports "GMT-4" for `timeZoneName` on Android when using Hermes:
```js
const intl = new Intl.DateTimeFormat(undefined, { hourCycle: 'h23', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', timeZone: 'America/New_York', timeZoneName: 'short' });
console.log(intl.formatToParts(new Date()));
```

You'll have to report this issue to Hermes.
