### ISSUE TITLE
`defaultWeekSettings` does not exist on type `typeof Settings`

### ISSUE THREAD

**Issue by hokwanhung** [moment/luxon#1561]
**Describe the bug**
I am trying to override the `defaultWeekSettings` for the MUI Date Calendar with TypeScript. However, it appears that `TypeScript` does not find the `type` in `Settings.js`.

**To Reproduce**
[![Edit luxon-defaultWeekSettings-error-with-TypeScript](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/luxon-defaultweeksettings-error-with-typescript-fsy4gm?embed=1&file=%2Fyarn.lock)

**Actual vs Expected behavior**
Actual behaviour: The below `TypeScript` error occurs.
```
TS2339: Property 'defaultWeekSettings' does not exist on type 'typeof Settings'.
```

Expected behaviour: Can successfully get the `defaultWeekSettings` without any errors.

**Desktop (please complete the following information):**

- OS: `Windows`
- Browser: `120.0.2210.91 (Official build) (64-bit)`
- Luxon version: `3.3.7`
- Your timezone: `en-US`

**Additional context**
Suspected related parts of code in [`Settings.js`](https://github.com/moment/luxon/blob/master/src/settings.js):
```javascript
  /**
   * @typedef {Object} WeekSettings
   * @property {number} firstDay
   * @property {number} minimalDays
   * @property {number[]} weekend
   */

  /**
   * @return {WeekSettings|null}
   */
  static get defaultWeekSettings() {
    return defaultWeekSettings;
  }
```

**Comment by diesieben07** [comment]
Do you have `@types/luxon` installed? Typescript types for Luxon are not part of this project, they are maintained by DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/luxon
They do not contain the `defaultWeekSettings` yet. I suggest you open an issue there.

**Comment by hokwanhung** [comment]
@diesieben07 Yes, I have `@types/luxon` installed; thank you for your comments, and I will transfer the issue there. Great thanks and hope you had a lovely New Year's Eve.
