### ISSUE TITLE
Create DateTime from timestamp?

### ISSUE THREAD

**Issue by Skyyrunner** [moment/luxon#157]
I looked through the documentation but I don't think I've found an option to simply create a DateTime object from a numerical timestamp, the representation that DateTime uses internally. I am using a Web Worker which passes messages to the main thread that include DateTimes, but the DateTime 'type' of the object is stripped when it's passed back to the main thread, so it lacks the prototype methods.

Of course, I can probably work around by converting DateTimes to a more serializable format when passing the data back, but I do still wonder if not having the option to create a date from a timestamp is intentional or oversight.

**Comment by Skyyrunner** [comment]
Never mind, I simply had to search *better*, it is `fromMillis`.

**Comment by samundra** [comment]
Whoever ends up here please check answer here https://stackoverflow.com/a/66553683, borrowed snippet directly here.

```
> let timestamp = 1615065599.426264
undefined
> new Date(timestamp).toJSON()
'1970-01-19T16:37:45.599Z'
> new Date(timestamp * 1000).toJSON()
'2021-03-06T21:19:59.426Z'
```
