### ISSUE TITLE
Fixed offset zones with missing Intl API

### ISSUE THREAD

**Issue by patrickjuchli** [moment/luxon#158]
I'm exploring Luxon's behaviour with a missing Intl API and found something I don't understand. If I use a fixed offset zone, it should still be possible to correctly display the time using this offset, shouldn't it? For example the following works as expected with existing Intl API:

```
// UTC is 9:33, the output of this example is correctly 10:33.
DateTime.utc().setZone("UTC+1").toLocaleString(DateTime.DATETIME_MED);
```

If I kill off the Intl API, the example doesn't work correctly anymore:

```
window.Intl = undefined;

// UTC is 9:33, the output of this example is now 11:33.
DateTime.utc().setZone("UTC+1").toLocaleString(DateTime.DATETIME_MED);
```

Is this expected behavior? Is maybe my way of removing the Intl API not entirely correct?

**Comment by patrickjuchli** [comment]
By the way, my local timezone is UTC+1. Maybe related?

**Comment by icambron** [comment]
Sounds like a bug to me.
