### ISSUE TITLE
Timezone 'CST' is unsupported in Firefox browser

### ISSUE THREAD

**Issue by ilia-butovskii** [moment/luxon#1593]
**Describe the bug**
Timezone 'CST' is unsupported in Firefox browser, but it works in Safari, Chrome and Node

**To Reproduce**
In Firefox

```typescript
DateTime.local().setZone('CST').toISODate()
```
_or_

```typescript
DateTime.fromISO('2024-02-09',  { zone: 'CST' }).toISODate()
```

**Actual**
Throws error `Error: Invalid DateTime: unsupported zone: the zone "CST" is not supported`

**Expected**
Set [UTC−06:00](https://en.wikipedia.org/wiki/UTC%E2%88%9206:00) timezone

**Desktop (please complete the following information):**

- OS: MacOS, Windows
- Browser: Firefox 121, Firefox 122
- Luxon version 3.3.0
- Your timezone: GMT+7

**Comment by diesieben07** [comment]
`new Intl.DateTimeFormat('de',  {timeZone: 'CST'}).format()` throws the same exception. You will have to speak to the Firefox developers about this.
