### ISSUE TITLE
Luxon fails to parse ISO 8601 date with 'Z' suffix as UTC

### ISSUE THREAD

**Issue by BenjaminHofstetter** [moment/luxon#1596]
**Describe the bug**
When using Luxon's DateTime.fromISO() function with the string '2023-12-04Z', the date is parsed as invalid.

**To Reproduce**
Minimal code example:

```typescript
const { DateTime } = require('luxon');
const date = DateTime.fromISO('2023-12-04Z');
console.log(date.isValid); // false
````

**Actual vs Expected behavior**
Expected behavior: The date '2023-12-04Z' should be parsed as a valid date.
Actual behavior: Luxon parses '2023-12-04Z' as an invalid date.

**Desktop (please complete the following information):**

- OS: MacOs
- Browser 122.0.6261.94 ( 
- Luxon version 3.4.4
- Your timezone CET

**Additional context**
This issue occurs when attempting to parse ISO 8601 dates with Luxon. The 'Z' suffix indicates that the date is in UTC time, and it should be parsed correctly.

**Comment by diesieben07** [comment]
You can only specify an offset if you also specify a time. Just a date plus offset is not valid in ISO 8601.
