### ISSUE TITLE
Wrong Time coming for Asia/Almaty timezone

### ISSUE THREAD

**Issue by tusharnaresh** [moment/luxon#1599]
On 1st March 2024 the offset for Asia/Almaty timezone was changed from UTC+6 to UTC+5. The same is not reflected via luxon.

```
import { DateTime } from 'luxon';
// DateTime.now() //=> '2017-09-14T03:20:34.091-04:00'

const dt = DateTime.now().setZone('Asia/Almaty');
console.log(dt);
```

The date time should be created with an offset of 300 instead of 360.

**Comment by ekolga** [comment]
Have the same issue on my node 18.19.1. Checked on 20.14.0 and it's fixed there
