### ISSUE TITLE
Using `diff` leads to incorrect minute-of-day calculation due to Daylight Savings Time transition

### ISSUE THREAD

**Issue by agrawal-rohit** [moment/luxon#1608]
**Describe the bug**
I'm using the `diff` function to calculate the minute-of-day through the `convertTimeToMinuteOfDay` method below, however, it fails to account for the hour skipped during the transition into Daylight Saving Time (DST), leading to incorrect minute-of-day calculations until the end of the day when DST begins.

```js
function convertTimeToMinuteOfDay(time) {
  const startOfDay = time.startOf("day");
  // Using ceiling here because an example time 15:23:23 (HH:MM:SS) is the 24th minute and not 23rd
  return Math.ceil(time.diff(startOfDay, ["minutes"]).minutes);
}
```

**To Reproduce**
- Create a `DateTime` object representing the time during the day when DST starts _(in 2024, the DST begins at 10 March 2024, 02:00:00 - [source](https://www.timeanddate.com/time/change/usa))_.
- Pass this `DateTime` object to the `convertTimeToMinuteOfDay` function to calculate the minute of the day.

```js
const { DateTime } = require("luxon");

function convertTimeToMinuteOfDay(time) {
  const startOfDay = time.startOf("day");
  // Using ceiling here because an example time 15:23:23 (HH:MM:SS) is the 24th minute and not 23rd
  return Math.ceil(time.diff(startOfDay, ["minutes"]).minutes);
}

const dstStartTime = DateTime.fromObject({ year: 2024, month: 3, day: 10, hour: 2 }, { zone: "America/New_York" });
const beforeDstStartTime = DateTime.fromObject({ year: 2024, month: 3, day: 10, hour: 1 }, { zone: "America/New_York" });
const afterDstStartTimeOne = DateTime.fromObject({ year: 2024, month: 3, day: 10, hour: 3 }, { zone: "America/New_York" });
const afterDstStartTimeTwo = DateTime.fromObject({ year: 2024, month: 3, day: 10, hour: 4 }, { zone: "America/New_York" });

console.log(`1:00AM (Before DST) - Minute of day: ${convertTimeToMinuteOfDay(beforeDstStartTime)}`);
console.log(`2:00AM (At DST) - Minute of day: ${convertTimeToMinuteOfDay(dstStartTime)}`);
console.log(`3:00AM (After DST) - Minute of day: ${convertTimeToMinuteOfDay(afterDstStartTimeOne)}`);
console.log(`4:00AM (After DST) - Minute of day: ${convertTimeToMinuteOfDay(afterDstStartTimeTwo)}`);
```

```
1:00AM (Before DST) - Minute of day: 60
2:00AM (At DST) - Minute of day: 120
3:00AM (After DST) - Minute of day: 120
4:00AM (After DST) - Minute of day: 180
```

**Actual vs Expected behavior**
The function should account for the DST transition, adjusting the calculation to include the skipped 60 minutes, thus providing an accurate minute-of-day value throughout the entire day when DST starts. The expected output should be as follows:

```
1:00AM (Before DST) - Minute of day: 60
2:00AM (At DST) - Minute of day: 180
3:00AM (After DST) - Minute of day: 180
4:00AM (After DST) - Minute of day: 240
```

**Environment:**

- OS: `MacOS Sonoma`
- Luxon version: `3.4.4`
- NodeJS version: `21.7.1`
- Your timezone: `America/New_York`

**Additional context**
This behaviour only occurs on the day DST begins, the calculation remains correct on the day DST ends.

**Comment by diesieben07** [comment]
Firstly, The time you label "2:00 AM (At DST)" _does not exist_ at this point. At DST, the clock jumps from 01:59:59 to 03:00:00. 02:XX:XX never happens.
Therefor `dstStartTime` and `afterDstStartTimeOne` are the same point in time: 03:00:00 at UTC-4.

`DateTime#diff` calculates the actual amount of time that has passed between two points in time, it does not care about "what the clock shows".
Between 00:00:00 at UTC-5 (start of the day) and 03:00:00 at UTC-4 it is 2 hours that has passed (from 00:00:00 until 01:00:00 and from 01:00:00 until 03:00:00), therefor the output you get is as expected.

If you want the minutes "as the clock shows it", you'll have to look at `DateTime#minutes` and `DateTime#hours` directly:
```js
function convertTimeToMinuteOfDay(time) {
  return time.hours * 60 + time.minutes + (time.seconds !== 0 || time.milliseconds !== 0 ? 1 : 0);
}
```

**Comment by agrawal-rohit** [comment]
@diesieben07 Thanks for the explanation - it helps a lot! I had to resort to a much uglier solution before (given below), you definitely saved me from that lmao.

```js
function convertTimeToMinuteOfDay(time) {
  // Get the start of the day for the given time
  const startOfDay = time.startOf("day");
  // Calculate the difference in minutes from the start of the day
  let minuteOfDay = Math.ceil(time.diff(startOfDay, ["minutes"]).minutes);

  // Check if Daylight Saving Time (DST) starts on this day
  const doesDSTStartOnThisDay =
    startOfDay.offset !== startOfDay.plus({ day: 1 }).offset;

  // Check if DST starts on this day
  if (doesDSTStartOnThisDay) {
    let dstTransitionHour = null;

    // Find the hour when DST start transition happens
    for (let hour = 0; hour < 24; hour++) {
      const dateTimeAtCurrHour = startOfDay.set({ hour: hour });
      const dateTimeAtNextHour = dateTimeAtCurrHour.plus({ hours: 1 });

      // Check for DST start transition
      if (dateTimeAtNextHour.offset > dateTimeAtCurrHour.offset) {
        dstTransitionHour = dateTimeAtCurrHour;
        break;
      }
    }

    // If given time occurs after DST has started, adjust the minute of day calculation
    if (dstTransitionHour && time.hour > dstTransitionHour.hour)
      minuteOfDay += 60;
  }

  return minuteOfDay;
}
```

**Comment by diesieben07** [comment]
Glad I could help!

**Comment by icambron** [comment]
Adding a quick note for anyone who lands here searching.

> The function should account for the DST transition, adjusting the calculation to include the skipped 60 minutes

One way to think about this is that `diff` _does_ account for the DST transition, and thus does _not_ include the skipped 60 minutes. `diff` is very much about how much time passed -- like how a stopwatch record it -- and this works _despite_ DSTs and leap years and so on messing with the clocks or calendars.
