### ISSUE TITLE
Any way to select next month?

### ISSUE THREAD

**Issue by julien-f** [moment/luxon#163]
**The problem:** I have a date I do not statically know, and I want to select the next April (the issue is similar for other units):

```js
DateTime.fromISO('2018-06-01').set({ month: 4 })
// → 2018-04-01
```

But this approach may result to a date in the past depending of the current date.
I can work around by checking if the date is correctly in the feature, and if that's not the case, adding a year.

But I'd like to do it in a unit-agnostic way but it's very tedious because I need to two which unit to adjust and of how much.

Is there a proper way to do this?

**Comment by icambron** [comment]
Well, there's not a completely unit-agnostic way to do that, but I'm not sure there needs to be. As far as I know the only cases where we do "next" like that is months and days of the week. So this is pretty clean:

```js
function nextify(unit, nextUnit) {
  return (dt, value) =>
   	(dt.get(unit) >= value ? dt.plus({[nextUnit]: 1}) : dt).set({[unit]: value });
}
 
const nextMonth = nextify("month", "year");
const nextWeekday = nextify("weekday", "week");

nextMonth(DateTime.local(2018, 3, 15), 4).toISODate() //=> "2018-04-15"
nextMonth(DateTime.local(2018, 5, 15), 4).toISODate() //=> "2019-04-15"

nextWeekday(DateTime.fromObject({weekYear: 2018, weekNumber: 20, weekday: 2 }), 4).toISOWeekDate() //=> "2018-W20-4"
nextWeekday(DateTime.fromObject({weekYear: 2018, weekNumber: 20, weekday: 5 }), 4).toISOWeekDate() //=> "2018-W21-4"
```

I hope that helps!

**Comment by julien-f** [comment]
Yes thank you.

I did something similar: https://github.com/vatesfr/xen-orchestra/blob/c0f70cb1f4990399d9f1d69c4ff329fb3dcf7fbf/%40xen-orchestra/cron/src/next.js#L25-L26

**Comment by adamreisnz** [comment]
I've added the following helpers to the prototype of DateTime to aid with these kind of conversions

```js
/**
 * Get specific next month
 */
DateTime.prototype.nextMonth = function(month) {
  const current = this.get('month')
  const base = (current >= month) ? this.plus({years: 1}) : this
  return base.set({month})
}

/**
 * Get specific previous month
 */
DateTime.prototype.prevMonth = function(month) {
  const current = this.get('month')
  const base = (current < month) ? this.minus({years: 1}) : this
  return base.set({month})
}
```
