### ISSUE TITLE
UTC dates can't be locale formatted on iOS in Expo 51

### ISSUE THREAD

**Issue by ntnp** [moment/luxon#1633]
**Describe the bug**
`toLocaleString()` stopped working for UTC dates on iOS in Expo 51.
There are 4 attempts of Intl formatting in the example below: 2 using Intl directly (local and UTC) and 2 using Luxon (local and UTC). The UTC Luxon attempt fails on iOS in Expo 51.
When `toLocaleString()` is called on a UTC date it apparently fails to instantiate `Intl.DateTimeFormat` correctly, throwing `this.dtf.formatToParts is not a function (it is undefined)`.

**To Reproduce**
[Expo Snack](https://snack.expo.dev/@ntnp/luxon-locale-formatting-fails-for-utc-dates-in-ios-with-sdk-51)
Uncomment the `<LuxonUtc />` component on SDK 50 and then on SDK 51.

**Actual vs Expected behavior**
**Expected:** Calling `toLocaleString()` on a UTC date formats it.
**Actual:** Calling `toLocaleString()` on a UTC date fails with an exception.

**Desktop (please complete the following information):**

- OS: iOS
- Browser: native
- Luxon version: latest
- Your timezone: UTC

**Additional context**
Kinda looks like it's on Expo, but idk? It's weird that it affects iOS but not Android or Web.

**Comment by ntnp** [comment]
RIP: [Hermes issue](https://github.com/facebook/hermes/issues/1172)

**Comment by cseelus** [comment]
It seems this works w/o the polyfill(s) now.
