### ISSUE TITLE
Undocumented `weekSettings` opt in `DateTime.fromObject(...)` 

### ISSUE THREAD

**Issue by angeloaltamiranom** [moment/luxon#1637]
Currently it is possible to pass in weekSettings to `fromObject` when creating a new DateTime. Similarly to how we can pass in `locale`, `numberingSystem` and `outputCalendar`, `weekSettings` is forwarded to the `Locale.fromObject` and can be used to set custom week settings in a datetime.

However, I noticed this is not documented in: https://moment.github.io/luxon/api-docs/index.html#datetimefromobject

Was this a documentation overlook, or is this behavior not intended?

**Comment by SaichandChowdary** [comment]
@diesieben07 
I'd like to work on this issue, can you please assign it to me. Thanks.

**Comment by SaichandChowdary** [comment]
PR: https://github.com/moment/luxon/pull/1640
