### ISSUE TITLE
Indicate which function can invalidate

### ISSUE THREAD

**Issue by pauldijou** [moment/luxon#164]
It would be awesome if the documentation could indicate which function/method can actually return an invalid date/duration/interval even if all arguments are valid and matching the function/method signature.

For example, if I understand it correctly, `DateTime.fromMillis` will always return a valid date (as long as first argument is a number) while `DateTime.fromFormat` can easily return an invalid one if format does not match text input. `DateTime.plus` should always succeed (if DateTime argument, should be a valid one of course).

Some are more tricky... `DateTime.endOf`, what happen if the `unit` is not a supported one? Does it invalidate the DateTime or do nothing?

I'm asking because I would like to add a layer on top of Luxon to prevent any invalid date by testing the result of any "invalid possible" calls before returning the result. Like using a `Result<DateTime,string>` for more typed languages like Elm or Reason.

**Comment by icambron** [comment]
Yeah, the docstrings should specify under what conditions they return invalid dates.

**Comment by icambron** [comment]
I'm removing invalid objects in 2.0, so closing this
