### ISSUE TITLE
Incorrect functionality of DateTime.fromJSDate in Chrome browser for years older than 1935

### ISSUE THREAD

**Issue by alimemz** [moment/luxon#1646]
**Describe the bug**
For years 1935 and before, luxon's `DateTime.fromJSDate` acts incorrectly on Chrome browser while it works correctly on Firefox.

**To Reproduce**
`DateTime.fromJSDate(new Date('1935-01-01 00:00:00')).toFormat('yyyy-MM-dd HH:mm:ss');`
// On Chrome it wrongly return `1934-12-31 23:59:16`
// On Firefox it correctly return `1935-01-01 00:00:00`

Important note is that the following return the same milliseconds on both browsers:
`DateTime.fromJSDate(new Date('1935-01-01 00:00:00')).valueOf();`
// On both Chrome and Firefox return `-1104549944000`

More examples in the attached screenshots:
![luxon issue Chrome](https://github.com/user-attachments/assets/61b0466b-f43b-40b6-8abf-2d63f2725f81)
![luxon firefox](https://github.com/user-attachments/assets/94015aa0-e955-4307-9b3c-d9901e508b6b)

**Actual vs Expected behavior**
DateTime.fromJSDate should work correctly and consistently across browsers for historical dates, so that on Chrome it parses the passed JS Date with the expected precision and doesn't jump back.

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.4 LTS
- Browser Chrome 126.0.6478.61, Firefox 128
- Luxon version: 3.4.4
- Your timezone: Asia/Tehran

**Additional context**
-

**Comment by diesieben07** [comment]
Unfortunately this is just down to a problem with fractional timezone offsets and how browsers handle them differently.
The following behaves differently in Chrome and Firefox (assuming timezone Asia/Tehran):
```js
console.log(new Date('1935-01-01 00:00:00').getTimezoneOffset());
 ```

In Chrome this returns `-205`, in Firefox it returns `-205.73333333333`. I am not sure if there is something that can be done to work around this.

**Comment by icambron** [comment]
We get a ton of reports about old timezones with this problem. Unfortunately, JS just doesn't have an API for returning the offset in seconds, and it makes it impossible for us to do the math correctly. We'd love to fix it, but we simply can't.

I think we need an issue label specifically for this. That would make it easier for us to link people back.
