### ISSUE TITLE
Add helpers for the format used by <input type="datetime-local">

### ISSUE THREAD

**Issue by dzfranklin** [moment/luxon#1649]
**Is your feature request related to a problem? Please describe.**

I have a form with an \<input type="datetime-local"\>. I want to default it to the current date and time.

**Describe the solution you'd like**

myInput.value = DateTime.now().toDatetimeLocalInputFormat()
const inputtedValue = DateTime.fromDatetimeLocalInputFormat(myInput.Value);

**Describe alternatives you've considered**

I can just manually specify the format string: "yyyy-MM-dd'T'HH:mm"

**Comment by diesieben07** [comment]
The datetime inputs use the ISO format, so you can just use the following:

```js
myInput.value = DateTime.now().toISO({ includeOffset: false })
const inputtedValue = DateTime.fromISO(myInput.value)
```
