### ISSUE TITLE
Can we expose `FixedOffsetZone.fixed` in the Typescript typings?

### ISSUE THREAD

**Issue by mceachen** [moment/luxon#1661]
The current typings don't include this field, but it'd be a huge help to expose a getter to the field.

If you're OK with the idea, I'm happy to submit a PR.

Thanks for Luxon!

**Comment by diesieben07** [comment]
The typings are not maintained by Luxon, they live in the https://github.com/DefinitelyTyped/DefinitelyTyped project.

That said, `FixedOffsetZone#fixed` is a private property. You should use `Zone#offset` to get a zone's offset, this works for any zone, including fixed ones.
