### ISSUE TITLE
resolvedLocaleOptions does not return like in documents

### ISSUE THREAD

**Issue by Mateusz19021996** [moment/luxon#1663]
**Describe the bug**
In docs there is an information that resolvedLocaleOptions() will return that effect for 'ar' code. It returns not 'arab' but 'latn':

This is problematic because I need arabic digits for my purposes but I cannot get name of numeric system by function.
```
var dt = DateTime.now().setLocale("ar");

dt.resolvedLocaleOptions(); //=> { locale: 'ar',
//     numberingSystem: 'arab',
//     outputCalendar: 'gregory' }

dt.toLocaleString(); //=> '٢٤‏/٩‏/٢٠١٧'
```

**To Reproduce**
Just run above code

**Actual vs Expected behavior**
Expected: numberingSystem: 'arab',
Actual: numberingSystem: 'latn',

- Luxon version [3.5.0]

**Comment by icambron** [comment]
The exact behavior of `setLocale` is platform dependent, but you can always call `dt.reconfigure({ numberingSystem: "arab" })`

**Comment by Mateusz19021996** [comment]
Hello @icambron 

I know that I can overwrite numberingSystem, but I have only codes of countries - that's why I need to programmatically get numberingSystems in my code. I can have walkaround that I will use big array of objects {countryCode: 'en-US', numberingSystem: 'latn'} and same for every country but I would like to avoid that

**Comment by diesieben07** [comment]
If you get `numberingSystem: 'latn'` from `resolvedLocaleOptions` then your platform (i.e. browser, Node.JS, etc.) said that's what it should be. You can check it like this:
```js
// returns latn for me in Chrome
new Intl.DateTimeFormat('ar').resolvedOptions().numberingSystem
```

Note also that if you are more specific with your locale, you'll get a better answer, too:
```js
// returns arab for me in Chrome
new Intl.DateTimeFormat('ar-SA').resolvedOptions().numberingSystem
```

You can also explicitly specify the numbering system in the locale string itself (this also works with Luxon's `setLocale`):
```js
// will always return arab
new Intl.DateTimeFormat('ar-u-nu-arab').resolvedOptions()
```

**Comment by icambron** [comment]
Perhaps we need to update the documentation to reflect what Chrome currently returns, since it must have changed. But either way it's just an example of what the browser can decide the resolution is, so there's nothing much to do here -- Luxon doesn't control what numbering system "ar" results in.
