### ISSUE TITLE
AP label for persian date

### ISSUE THREAD

**Issue by navidrashidian** [moment/luxon#1667]
I am using luxon to convert dates to persian calendar. In some situations the date is labeled as 'AP', e.g. "Aban 30, 1403 AP." The label AP is never actually used for the Persian calendar and should be omitted.

**Comment by diesieben07** [comment]
The formatting is not generated by Luxon, but by the underlying platform through [`Intl.DateTimeFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat).
You can observe the same output if you use that API directly:
```js
console.log(DateTime.local().toLocaleString(DateTime.DATE_FULL, {outputCalendar: 'persian'}));
console.log(new Intl.DateTimeFormat(undefined, {...DateTime.DATE_FULL, calendar: 'persian'}).format());
```

I am not familiar with the details of the persian calendar, so I cannot assess whether or not your statement about the "AP" label is correct. However in either case you would need to take this up with the browser/runtime vendors if you believe that this is incorrect.
