### ISSUE TITLE
Parse date from LDAP format

### ISSUE THREAD

**Issue by koocotte** [moment/luxon#1669]
LDAP use a standard DateTime format of `yyyyMMddhhmmss[.SSS]Z` Constant uppercase letter `Z`  for Zulu or UTC Timezone.

I suggest that DateTime.fromISO could parse thoses dates:

```
DateTime.fromISO("20160525092415.123Z");
DateTime.fromISO("20160525092415.0Z");
DateTime.fromISO("20160525092415Z");
```
(or another fromXXX if it create ambiguity)

Alternative with current version is to use `DateTime.fromFormat("20160525092415Z", "yyyyMMddhhmmss'Z'");`

**Comment by diesieben07** [comment]
> I suggest that DateTime.fromISO could parse thoses dates

But why? The dates you want to parse are not in [ISO format](https://en.wikipedia.org/wiki/ISO_8601).

> Alternative with current version is to use DateTime.fromFormat("20160525092415Z", "yyyyMMddhhmmss'Z'");

What's wrong with this? I don't think Luxon needs to add dedicated parse methods for _every_ date/time format that is out there.

**Comment by koocotte** [comment]
>> I suggest that DateTime.fromISO could parse thoses dates

> But why? The dates you want to parse are not in [ISO format](https://en.wikipedia.org/wiki/ISO_8601).

You are right, according to 
https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations, 

In ISO 8601:2004 it was permitted to omit the "T" character by mutual agreement as in "200704051430", but this provision was removed in ISO 8601-1:2019.

>>    Alternative with current version is to use DateTime.fromFormat("20160525092415Z", "yyyyMMddhhmmss'Z'");

> What's wrong with this?

It work great.

The documentation [discourages](https://moment.github.io/luxon/#/parsing?id=consider-alternatives) the use of custom parser and I think it also result in a much higher compute cost. But I'm OK if the projet think it's not that common and fromFormat() is the right solution.

**Comment by diesieben07** [comment]
The discouragement is for _using_ custom formats at all. As in: the discouragement tells you to use ISO instead. If you _must_ parse a custom format like this, `fromFormat` is the right tool.

As for the performance: Yes, in theory we could add `DateTime.createParser(format)` which would front-load the cost of parsing the format. If this becomes a performance bottleneck for you, please open a new issue and we can work on that.
