### ISSUE TITLE
Month math at the end of months

### ISSUE THREAD

**Issue by rogerioyuuki** [moment/luxon#167]
(assuming this is not a bug)
```
DateTime.local(2018, 3, 31).minus({months: 1}).toISO()
> "2018-03-03T00:00:00.000-03:00"
DateTime.local(2018, 1, 31).plus({months: 1}).toISO()
> "2018-03-03T00:00:00.000-03:00"
```

The only part of the documentation that can explain this behavior is:

> It's best not to think of calendar math as requiring arcane checks on the lengths of intervening periods. Instead, think of them as **adjusting that unit directly and keeping lower order date components constant.**

I think this could be more explicit, since it's different from other usual date manipulation implementations
[[1]](https://msdn.microsoft.com/library/system.datetime.addmonths(v=vs.110).aspx) [[2]](http://momentjs.com/docs/#special-considerations-for-months-and-years) [[3]](https://github.com/date-fns/date-fns/issues/17) [[4]](http://labix.org/python-dateutil#line-229)

**Comment by icambron** [comment]
I think I'd rather call that a bug.

**Comment by rogerioyuuki** [comment]
Both [moment ](https://github.com/moment/moment/blob/475d4c1/src/lib/units/month.js#L199) and [date-fns](https://github.com/date-fns/date-fns/pull/18/files#diff-fe1f53c4df058bc4ab9c8bc0978a8761R12) use the same approach when handling this case.

Maybe this can be implemented in `adjustTime` (using `Util.daysInMonth`) ?(https://github.com/moment/luxon/blob/20dac8d/src/datetime.js#L123)

I can try to work on this

**Comment by icambron** [comment]
@rogerioyuuki Yes, I think the Moment approach is what we want. And yes, `adjustTime` is the place to do it. Would love a PR!

**Comment by damianobarbati** [comment]
@icambron @rogerioyuuki what happens when you actually do minus "month" or "week"? 
Is not very clear.
Does "minus 1 week" mean minus 7 days?
Does "minus 1 month" mean minus 30 days? Or minus 31 days? Or does Luxon try to get the same day of the month before and if it does not exist falls back to previous/next day?

**Comment by icambron** [comment]
@damianobarbati see http://moment.github.io/luxon/docs/manual/math.html
