### ISSUE TITLE
Invalid DateTime for Asia/Kolkata on iOS app

### ISSUE THREAD

**Issue by Nonentity5565** [moment/luxon#1671]
**Describe the bug**
Setting the timezone to `Asia/Kolkata` on iOS emulator or devices logs out `Invalid DateTime`. Same code used on android simulator or devices works fine.

Setting the timezones to other IANA timezones works fine but for some reason only `Asia/Kolkata` breaks. 

**To Reproduce**
```
import { DateTime } from "luxon";

const newDate = DateTime.now();
const kolkata = newDate.setZone("Asia/Kolkata");
console.log(kolkata.toFormat("HH:mm");
```

**Actual vs Expected behavior**
Expected:
log out current time in Kolkata, India

Actual:
`Invalid DateTime`

- OS: iOS
- Luxon version: 3.5.0
- Your timezone: Asia/Kuala Lumpur

**Additional context**
Running on a React Native project. iOS device and emulator are on iOS 17.6.1 and 18.0.0 respectively.

**Comment by diesieben07** [comment]
React Native uses Hermes, and its Intl.DateTimeFormat implementation is unfortunately not great.
Please try to format a date in that time zone using `Intl.DateTimeFormat` and you'll likely run into an issue as well.

My guess is that it is this issue: https://github.com/facebook/hermes/issues/1100

**Comment by Nonentity5565** [comment]
Thank you so much @diesieben07. Guess I'll need to have a specific OS workaround for Kolkata on iOS 🤦 🤣. 

Closing this issue as it is not really an issue on Luxon side.
