### ISSUE TITLE
Issue with `toFormat` adding extra year

### ISSUE THREAD

**Issue by aidanmc95** [moment/luxon#1676]
**Describe the bug**
When using `toFormat` on a specific set of date ranges it adds an extra year to the date. These are the date ranges I found:
	- 12/30/2024 at 12:00:00 AM - 12/31/2024 at 11:59:00 PM
	- 12/29/2025 at 12:00:00 AM - 12/31/2025 at 11:59:00 PM
The end result turns a date like this `12/30/2024 at 12:00:00 AM` -> `12/30/2025 at 12:00:00 AM`.

The format that I was using was: `.toFormat("MM/dd/kkkk 'at' tt")`. There seems to be a work around by using `.toFormat("MM/dd/yyyy 'at' tt")`.

**To Reproduce**
Here is a test that can be added to `test/datetime/toFormat.test.js`
```
test("DateTime#toFormat('MM/dd/kkkk 'at' tt') returns the correct date: '12/30/2024 at 12:00:00 AM'", () => {
  const bigDt = DateTime.fromFormat(`12/30/2024 at 12:00:00 AM`, "MM/dd/yyyy 'at' tt");
  expect(bigDt.toFormat("MM/dd/kkkk 'at' tt")).toBe("12/30/2024 at 12:00:00 AM");
});
```
Then run: `./scripts/test`

**Actual vs Expected behavior**
The date should not shift up by a year it should stay the same as what was input.

**Desktop (please complete the following information):**

- OS: Ubuntu 22.04.5 LTS
- Browser: terminal
- Luxon version: 3.5.0
- Timezone: "America/New_York" (on Ubuntu)

**Comment by diesieben07** [comment]
The "kkkk" token outputs the [ISO week year](https://en.wikipedia.org/wiki/ISO_week_date). It is not always the same as the gregorian year. You want "yyyy".
