### ISSUE TITLE
Manual error, weekYear for moment users

### ISSUE THREAD

**Issue by janat08** [moment/luxon#168]
weekYear in for moment users section is described as access to weekNumber which in turn isn't referenced.

**Comment by icambron** [comment]
I'm not sure what you mean. Moment's `weekYear` is mapped to `weekYear` in that document; it's really the equivalent of Moment's `isoWeekYear`. What do you mean it isn't referenced? It is documented [here](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-get-weekYear)

Or are you pointing out that Moment's `week` and `isoWeek` are documented as being functionally equivalent to Luxon's `weekNumber`? Yes, I should add that row.

**Comment by janat08** [comment]
https://moment.github.io/luxon/docs/manual/moment.html in unit getters, I'm not sure what weekYear is but it just gives the year in luxon.

**Comment by icambron** [comment]
It does not give the Gregorian year in the exact sense that `weekYear `and `isoWeekYear` do not just give the Gregorian year in Moment. It gives the [ISO week year](https://en.wikipedia.org/wiki/ISO_week_date). It is the direct equivalent of `isoWeekYear` in Moment and the nearest equivalent of `weekYear` in Moment.

**Comment by janat08** [comment]
DT.local().weekYear
2018

**Comment by icambron** [comment]
That is correct...
