### ISSUE TITLE
Settings.defaultZoneName = 'Europe/London'

### ISSUE THREAD

**Issue by sissingclay** [moment/luxon#169]
Using the setting above, this breaks ie11 and ie10

**Comment by icambron** [comment]
Have you read this? https://moment.github.io/luxon/docs/manual/matrix.html#polyfills

**Comment by sissingclay** [comment]
Yes I have, it all works in all the browsers well until I add `Settings.defaultZoneName = 'Europe/London' `

**Comment by icambron** [comment]
Following those instructions worked fine for me in IE 11: https://jsfiddle.net/q37jzjL2/. Does that work for you? It doesn't work in IE 10 compat mode, but I think that's something about the compat mode, not about IE 10, though I haven't tested in the real IE 10 and am curious about it.

Incidentally, I did notice there's something wrong with the minified version of Luxon's global-filled build in IE 11; I'll look into that.

**Comment by icambron** [comment]
I've moved the two issues I encountered troubleshooting this to #189 and #190. I don't think either of them are your issue, though. I'm closing this, but I'd be happy to reopen if you give me more info.

**Comment by sissingclay** [comment]
https://stackblitz.com/edit/angular-5ftq6t?file=app%2Fpipe%2Ftime.pipe.ts

**Comment by sissingclay** [comment]
@icambron I've used this for the time being it seems to work.
'moment-timezone'
moment.tz(date, 'Europe/London').format('HH:mm')

**Comment by sissingclay** [comment]
Hi @icambron, have you had time to look at this?
