### ISSUE TITLE
Initialize local() with the base object?

### ISSUE THREAD

**Issue by windware** [moment/luxon#170]
Current initialization looks pretty verbose with when I assign the whole library with an import statement,

> import * as luxon from 'luxon'
> luxon.DateTime.local()

but is it possible to make it initialize with the current time with the object by itself just llike how momentjs is simple in doing so?

> luxon()

**Comment by icambron** [comment]
Normally you'd do

```js
import { DateTime } from 'luxon';
DateTime.local();
```

At least, that is how Luxon is designed to be used in ES6.

But you can always do 

```
const luxon = DateTime.local
```

I don't personally like that style, because it's not very clear to me what `luxon()` should do, so I won't support it directly, but of course you should do what you like.
