### ISSUE TITLE
Interval.difference returns an array of Intervals (docs say single interval)

### ISSUE THREAD

**Issue by codyzu** [moment/luxon#175]
While using luxon, we realized that `Interval.difference` returns an array of Intervals (which seems logical). However, the [documentation](https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html#instance-method-difference) states that it returns a single Interval (which does not make sense).

Seems like a documentation typo.

Thanks for the great library!

**Comment by icambron** [comment]
Yeah, sounds like a doc bug. Would take a PR

**Comment by icambron** [comment]
Fixed in 77c62e7
