### ISSUE TITLE
React Native with setZone.

### ISSUE THREAD

**Issue by oiojin831** [moment/luxon#176]
I read the Docs says I need to install jsc-android-buildscripts  to use international stuffs.
So to use  `setZone` do I have to isntall `jsc-android-buildscripts `.
Cause I am installing it for 2 days and still not done yet. was it supposed to take this long?

**Comment by icambron** [comment]
I don't know, but I strongly suspect that nothing should take two days to install. I think you should probably ask at their repository though.
