### ISSUE TITLE
Neither Interval.contains nor Interval.isBefore returns true for Interval end date 

### ISSUE THREAD

**Issue by jonahkagan** [moment/luxon#177]
I got a bit confused by this behavior:

```js
> i = luxon.Interval.fromDateTimes(luxon.DateTime.local(), luxon.DateTime.local().plus({ minutes: 1 }))
Interval {s: DateTime, e: DateTime, invalid: null}
> i.contains(i.end)
false
> i.isBefore(i.end)
false
```

I would expect the endpoint to either be contained by the interval (closed interval) or after the interval (open interval). Based on the output of `toString`, which seems to indicate that the end is not included, I would expect `i.isBefore(i.end)` to return true.

This came up for me because I was using `isBefore`, `contains`, and `isAfter` to bucket datetimes into three buckets (before, during, after), and some datetimes that were equal to the interval end date were not falling into any bucket!

I also noticed that this doesn't happen with the interval start point and `isAfter`.

**Comment by icambron** [comment]
It's half-open: includes the start but not the end. `isBefore` confusingly breaks this. I brought its behavior over from Twix:

```js
  isBefore(dateTime) {
    if (!this.isValid) return false;
    return this.e.plus(1) < dateTime;
  }
```

This has come up before in Twix and I never remember why it's so weird and I change it and it breaks people's intuitions. I'd like to change it because I value consistency, so I may try doing that again.

**Comment by icambron** [comment]
Looking at this closer, I realized the current code makes no sense at all, ambiguity about openness aside. I've fixed to be consisten with half-openness and will release it in 0.5.0

**Comment by icambron** [comment]
Released.
