### ISSUE TITLE
Wrong offset for America/Los_Angeles

### ISSUE THREAD

**Issue by benmccann** [moment/luxon#178]
```
<script src="https://moment.github.io/luxon/global/luxon.js"></script>
<script>
var DateTime = luxon.DateTime;
var iso = DateTime.fromISO('2014-10-25T13:46:20', { zone: 'America/Los_Angeles' });
console.log(iso.zoneName);
console.log(iso.toString());
</script>
```

Prints out:
>America/Los_Angeles
2014-10-25T13:46:20.000-07:00

I think this should be `-08:00`: https://www.zeitverschiebung.net/en/timezone/america--los_angeles

Seems like a daylight savings time bug

**Comment by icambron** [comment]
No, that's right; PDT lasts until sometime in early November (in 2014 it was Nov 2), so LA would have been at -7 on Oct 25.

**Comment by benmccann** [comment]
Thanks. You're right. I had a brain fart and was thinking of today's date and not the date entered there
