### ISSUE TITLE
Support for partial dates?

### ISSUE THREAD

**Issue by tremby** [moment/luxon#179]
Is there any plan to handle partial dates, such as 2018-02 meaning February 2018 (and no particular day)? It's a valid ISO date form but at present every date handling library I've found just assumes that it means the first day of that month.

**Comment by icambron** [comment]
And not just that; it assumes you mean the first millisecond of that day.

It's a reasonable request, but I decided pretty early not to support lower-granularity dates like that. They make sense (especially the day-level one), but they're a headache to make sure they work smoothly with all the different kinds of operations you could conceivably do on them. So going to close as out-of-scope.

**Comment by anantakrishna** [comment]
The [documentation](https://moment.github.io/luxon/docs/manual/parsing.html#iso-8601) says:

> Missing lower-order values are always set to the minimum possible value

Is there a way to find out which values were missing in the input ISO string and, thus, were set to the minimum possible value?
