### ISSUE TITLE
With React Native using setZone.

### ISSUE THREAD

**Issue by oiojin831** [moment/luxon#180]
So I am using luxon with react-native.
Everything works fine on ios.

But for Android I am keep getting `Invalid DateTime` 
I installed `jsc-android-buildscripts` on my project as document recommended

What I did is
```DateTime.fromISO(isoDateTime).setZone(timeZone).toFormat('yyyy LLL dd H:mm')```
and this gives me `InvalidDateTime`. If I don't use `setZone` like this
```DateTime.fromISO(isoDateTime).toFormat('yyyy LLL dd H:mm')```
This works fine. so At this point, I thought It is something to do with `jsc-android-buildscrips`

However, strange thing is if I turn on debug mode everything works fine, with and without the `jsc-android-buildscrips`

So now I suspect that `setZone` isn't related to `jsc-android-buildscripts`...
I am not sure what's going on.
Can someone give me a hint what to do?

Thanks

**Comment by icambron** [comment]
I know little about React Native, but some debugging pointers:

 1. For those invalid DateTimes, does `dt.invalidReason` return "Unsupported zone"? I'm going to assume yes
 2. Try testing your Intl support without Luxon at all. Does `new Intl.DateTimeFormat("en", { timeZone: "America/Los_Angeles" }).format()` work? If so, then Luxon should too. If not, it's an environment issue, which as far as I understand it, does point `jsc-android-buildscripts`

**Comment by oiojin831** [comment]
@icambron 
thanks for the fast reply.
I think `jsc-android-buildscripts` wasn't properly installed.
cause I couldn't call the `new Intl.DateTimeFormat("en", { timeZone: "America/Los_Angeles" }).format()`

Thank you for your help.
but I will just use moment for now

**Comment by ntelkedzhiev** [comment]
@oiojin831 I'm having a similar problem. How did you figure out that `jsc-android-buildscripts` wasn't properly installed?

**Comment by rob5408** [comment]
Same problem here. The date would actually parse just fine, so `invalidReason` was always undefined. It was upon using `format()` where `InvalidDateTime` would surface. `console.log`ging the DateTime object on each iOS and Android showed what looked like a Unix timestamp, but the Android one was zeveral zeroes longer as if maybe ms were being added or something.

In regards to the `jsc-android-buildscripts` installation steps here: https://github.com/react-native-community/jsc-android-buildscripts Although I was using RN 0.59, I also needed this from the RN 0.58- steps...

```
+configurations.all {
+    resolutionStrategy {
+        eachDependency { DependencyResolveDetails details ->
+            if (details.requested.name == 'android-jsc') {
+                details.useTarget group: details.requested.group, name: 'android-jsc-intl', version: 'r241213'
+            }
+        }
+    }
+}
```

I'm now holding my breath and slowly walking away from this bit of code.
