### ISSUE TITLE
Viewing DateTime using React Dev Tools

### ISSUE THREAD

**Issue by fruitraccoon** [moment/luxon#182]
When a Luxon DateTime is passed as a prop to a React component, viewing the component props in the React Dev Tools shows the DateTime as expandable - however when expanded an `Uncaught TypeError: Cannot read property 'locale' of undefined` error appears in the console, indicating [this line](https://github.com/moment/luxon/blob/d485b16ba0aef87d2a9b9956f6c2593e0cfda16c/src/datetime.js#L779).

Digging into the Dev Tool code, this appears to be being caused by [the code](https://github.com/facebook/react-devtools/blob/40f926dfab63051446e9b671c369c703f2e21c67/agent/Bridge.js#L450) executing the `locale` property on the _prototype_ of DateTime, which has a `loc` of undefined.

Would a change to the `locale` prop code (and similar properties) to protect against an undefined `this.loc` be considered? Or perhaps there's a better way to solve the issue?

Thanks for this great library!

**Comment by icambron** [comment]
Yeah, I'd take a PR checking if `loc` is undefined. I hadn't bothered because I didn't know of a scenario where it would matter.

**Comment by icambron** [comment]
Fixed in #206
