### ISSUE TITLE
ISO Duration parsing does not allow fractions

### ISSUE THREAD

**Issue by rockerest** [moment/luxon#183]
[This line](https://github.com/moment/luxon/blob/fb6458a83451ef2f68e4ed3c7c987b580d24c900/src/impl/regexParser.js#L111) only allows whole numbers for ISO Durations.

I'm not an ISO member, so I can't actually see the specification, but my understanding from the Wikipedia article is that the same fractional parts should be allowed for durations:

[Times](https://en.wikipedia.org/wiki/ISO_8601#Times)
> Decimal fractions may be added to any of the three time elements. However, a fraction may only be added to the lowest order time element in the representation.

and

[Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)
> The smallest value used may also have a decimal fraction, as in "P0.5Y" to indicate half a year. This decimal fraction may be specified with either a comma or a full stop, as in "P0,5Y" or "P0.5Y".

Is this a documented/intentional deviance from the ISO (as reported by Wikipedia, however accurate that may be) standard?

Additionally, this fails totally silently.
Take the following:

```
luxon.Duration.fromISO( "PT6H54M2.893S" );
```

This returns an object with `invalid` set to `null` (e.g. the assumption is that this object is not invalid), `.isValid` returns `true`, and the `values` object is empty. So the object is presumed to be valid but winds up always representing zero time.

**Comment by icambron** [comment]
Ok, yeah, two things:

 1. That the duration was considered valid was a bug. I think during development I introduced invalid durations kind of late, and didn't go back to make sure parsing did the right thing there. I just pushed a fix for that to the `master` branch and will deploy in the next couple days.
 2. As far as the deviance from the standard is concerned, I would take a PR implementing ISO parsing for fractional durations

**Comment by icambron** [comment]
Release part 1 in 0.5.0

**Comment by icambron** [comment]
Fixed in 310dfd9. Will release it in 0.5.6 shortly.

**Comment by icambron** [comment]
Fixed in 5a6256978, will release as part of 0.5.6 shortly

**Comment by icambron** [comment]
@flmg Can you create a separate issue for that?
