### ISSUE TITLE
Interval#splitBy can cause infinite loop

### ISSUE THREAD

**Issue by vlad-zhukov** [moment/luxon#186]
`Interval#splitBy` hangs the process with an infinite loop if `duration` argument is not valid. 

Repro: https://codesandbox.io/s/n469pm30o4 (WARNING: this will hang the tab).

```js
const dateStart = DateTime.local().startOf("day");
const dateEnd = dateStart.plus({ days: 6 }).endOf("day");
const dates = Interval.fromDateTimes(dateStart, dateEnd).splitBy(DateTime.local());
```

**Comment by icambron** [comment]
Yeah, we should fix that. Would make for a good first contribution!

**Comment by vlad-zhukov** [comment]
I'll take it!

**Comment by icambron** [comment]
@bogdanpolak Someone just needs to take #187 and finish the work. It needs passing tests.

**Comment by bogdanpolak** [comment]
@ichernev I need little support, how to start this work. Should I clone current master and copy @vlad-zhukov changes into current sorce code? Then creating new pull request?

**Comment by icambron** [comment]
Here's what I'd do:

1. Fork this repository and clone it
2. add vlad's fork as a remote and pull his branch
3. rebase it against master
4. push it to your fork
5. make a new PR

Does that make sense?

**Comment by bogdanpolak** [comment]
@icambron Thx Issac for you assistance. I'm newbie in OpenSource on GitHub, but trying my best. 
For sure you suggestions make sense.
> 1. Fork this repository and clone it
forked: https://github.com/bogdanpolak/luxon and cloned.
> 2. add vlad's fork as a remote and pull his branch
Problem: can't find Vlad's fork.
Maybe this is an issue: vlad-zhukov deleted the vlad-zhukov:duration-toobject  branch 27 days ago?

**Comment by icambron** [comment]
@bogdanpolak ah, right. Yes you'll have to make your own branch and integrate the changes manually then

**Comment by bogdanpolak** [comment]
I just run luxon unit test in the cloned current main brunch and received 80 failed test. Should it looks that way? After small investigation I found that some failed tests are dependent on the OS X locale, I'm working on pl-pl locale settings. Maybe with docker will be better?

**Comment by icambron** [comment]
Try `scripts/test`

**Comment by bogdanpolak** [comment]
Now a little better: 35 failed. Those based on en-US locales was passed, but sill those which switching locales into different languages was failed (French, 
. Example:
>DateTime#weekdayLong returns the human readable weekday for fr locale
    expect(received).toBe(expected)
    Expected value to be (using ===):
      "mardi"
    Received:
      "Tuesday"
      at Object.<anonymous> (test/datetime/getters.test.js:93:51)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by bogdanpolak** [comment]
Propobly I have to configure full-icu. I will try it and get back with the feedback

**Comment by bogdanpolak** [comment]
After upgrading to node 8.x and mounting NODE_ICU_DATA now is much more better :-) but still I'v got 3 failed tests. Two of them are connected with meridiem, and issue is described here #229. And one is something connect with TimeZone:
```javascript
FAIL test/info/zones.test.js
  ● Info.hasDST returns true for Africa/Windhoek
  Expected value to be (using ===): true  Received: false
```
As I see at: https://www.timeanddate.com/worldclock/namibia/windhoek there is no DST and found info: 
> DST is no longer in use. Clocks do not change in Windhoek, Namibia.The previous DST change in Windhoek was on 2nd April 2017.

After updating `icudt60l.dat` in the full-ICU package this test should expected false. Am I right?

**Comment by icambron** [comment]
Interesting. Yes, I suspect that the test was based on an older version of the ICU data. We find another zone to test there.

**Comment by bogdanpolak** [comment]
@icambron. I'm almost done with passing all tests, but ... with this patch we are expecting that Duration.fromObject({}) will raise the exception, but one of the tests expecting that Duration.fromObject({}) will construct zero Duration like Duration.fromMillis(0). What is better?

**Comment by bogdanpolak** [comment]
I've decided to change fromObject implementation. Now Duration.fromObject({}) is constructing zero duration object.
