### ISSUE TITLE
The zone-aware formatToParts polyfill breaks in Chrome

### ISSUE THREAD

**Issue by icambron** [moment/luxon#190]
See https://github.com/yahoo/date-time-format-timezone/issues/17. It means that if you've polyfilled to support zones in IE 11, the library breaks on Chrome (where it would have worked without the poly). So that is lame.

**Comment by rileytb** [comment]
Is there any workaround for this? 
I get `Invalid Date` w/out polyfill in IE, but with polyfill in Chrome the whole thing dies.

**Comment by icambron** [comment]
I haven't found one yet

**Comment by nbdn** [comment]
Any updates?

**Comment by martijnmelchers** [comment]
You could always check if the Zones API is already available and only load the polyfills if it is not available 👍 

This also speeds up page loads!

**Comment by nbdn** [comment]
But that is the "quick & dirty" solution of the problem (except if you're doing SSR). Imagine that you have other dependencies that use Zones API: you must check if the Zones API is available, then load the polyfill or not, then load the rest of your dependencies that need Zones API... In this case, you're just increasing your page load...

**Comment by martijnmelchers** [comment]
I am using this in Angular, when Angular is booting I check whether or not the Zones API is available if it is not I load the required polyfill(s) and if it is, there is no need for it to be loaded in.

**Comment by dmngu9** [comment]
sorry im a bit of a noob here. How can check if Zones API is available, please?
@martijnmelchers

**Comment by ericmorand** [comment]
Can't you build and serve a different bundle to browsers that needs the polyfill?

**Comment by dmngu9** [comment]
@ericmorand you mean webpack build? But it still need to know which browser to serve first
