### ISSUE TITLE
Shiftto issue

### ISSUE THREAD

**Issue by r1cs1** [moment/luxon#197]
Hi,

I believe the following code returns wrong result:

`console.log('Test:', Duration.fromObject({ hours: 0, minutes: 59, seconds: 183 }).shiftTo('hours', 'minutes', 'seconds').toObject())`

> Test: {hours: 0, minutes: 62, seconds: 3}

Expected result:

> Test: {hours: 1, minutes: 2, seconds: 3}

Version: 0.5.3

Thanks,
Richard

**Comment by icambron** [comment]
Hmm, yes, that is wrong

**Comment by icambron** [comment]
I took a closer look at this and it's going to require substantial work to `shiftTo`'s implementation. I'll get to this, but it'll be a few days.

**Comment by icambron** [comment]
Fixed in 7d02641fe5. Will release soon.
