### ISSUE TITLE
Consider limiting the maximum amount of characters per line

### ISSUE THREAD

**Issue by lazzzis** [moment/luxon#198]
https://github.com/moment/luxon/blob/e15ea3a3d57aabebf3e3d4dd9b87de7f9ad2aa1b/src/info.js#L8

Some comments are too long, and they hurt code readability. I have to scroll horizontally to read the code on browser. Breaking lone comments to multiple lines may help improve code readability.

Thanks!

**Comment by icambron** [comment]
Unfortunately, I need to keep that on one line to satisfy ESDoc, who won't otherwise parse that all as one bullet point. I recommend enabling word wrap in your editor.
