### ISSUE TITLE
Question / potential bug: difference between Moment and Luxon default ISO formats

### ISSUE THREAD

**Issue by trevordmiller** [moment/luxon#199]
I've noticed that Moment and Luxon use different ISO formats by default:

Moment:
`2018-02-27T19:41:00+01:00`

Luxon
`2018-02-27T19:41:00.000+01:00`

So Luxon has the additional `.###` milleseconds after the minutes. Does this make a difference? For example, if I were to convert this Moment code to Luxon, is the difference going to change the user's experience?

```javascript
// Moment
    moment()
      .tz( 'Europe/Paris')
      .add({
        minutes: 15
      })
      .seconds(0)
      .milliseconds(0)

// Luxon
    DateTime.local()
      .setZone('Europe/Paris')
      .plus({
        minutes: 15
      })
      .set({
        seconds: 0,
        milliseconds: 0,
      })
```

Thanks for the great project - I'm enjoying the explicit and functional approach of Luxon a lot more than Moment :)

**Comment by icambron** [comment]
Nope, those are equivalent, aside from the difference in mutability. Internally, both libraries maintain the time as a count of epoch milliseconds + some metadata. The difference you're seeing in ISO formatting is just in displaying a human-readable representation. It's all good.

**Comment by trevordmiller** [comment]
@icambron Ok cool, thanks!
