### ISSUE TITLE
weeksInYear

### ISSUE THREAD

**Issue by luke-unifymonitor** [moment/luxon#205]
Hi.

Would be handy to include a weeksInYear property

DateTime.local(2018, 1, 1).weeksInYear //=> 52 
DateTime.local(2019, 1, 1).weeksInYear //=> 52 
DateTime.local(2020, 1, 1).weeksInYear //=> 53 

Apologies if this already exists.

Many thanks,

Luke.

**Comment by icambron** [comment]
It doesn't exist, but I I think it's just `Math.floor(DateTime.local(...).daysInYear()/7)`, right?

**Comment by icambron** [comment]
Ah, I suspect you mean, "how many ISO weeks are in this ISO week year?" Yeah, that is a good question for this library to answer.

**Comment by icambron** [comment]
`weeksInWeekYear`

**Comment by kivlor** [comment]
I've had a go implementing `weeksInWeekYear` in PR #230. I follow the [Wikipedia](https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_year) article on how to calculate.

**Comment by icambron** [comment]
Released in 1.1.0
