### ISSUE TITLE
Support for 'YYYY-MM-DD HH:mm:ss' format

### ISSUE THREAD

**Issue by felamaslen** [moment/luxon#207]
MySQL DATETIME fields support input in the format 'YYYY-MM-DD HH:mm:ss'; as far as I can tell, there is no built in way to format a DateTime object like this.

**Comment by icambron** [comment]
See [fromSQL](http://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromSQL) and [toSQL](http://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toSQL)

**Comment by felamaslen** [comment]
Using `.toSQL()` results in:insert into `fund_cache_time` (`done`, `time`) values (false, '2018-03-10 15:23:33.677 +00:00') - Incorrect datetime value: '2018-03-10 15:23:33.677 +00:00' for column 'time' at row 1

**Comment by felamaslen** [comment]
Using `.toSQL()` results in the following: ```insert into `****` (`done`, `time`) values (false, '2018-03-10 15:23:33.677 +00:00') - Incorrect datetime value: '2018-03-10 15:23:33.677 +00:00' for column 'time' at row 1```

**Comment by felamaslen** [comment]
For future reference, MySQL doesn't seem to support offsets. Might want to make a note of this in the [docs](http://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toSQL). Solution in this case is to use `includeOffset: false`.

**Comment by icambron** [comment]
There are lots of database servers, and each one has several different formats, each of which may or may not support various strings. I don't think it's appropriate to document all that in Luxon.

It would be reasonable to suggest that `includeOffset` ought to default to `false`, though.
