### ISSUE TITLE
Low performance of formating

### ISSUE THREAD

**Issue by andre2** [moment/luxon#216]
Hello,

I noticed low performance on date formating in comparsion with `moment`.
Checkout this [fiddle](https://jsfiddle.net/pfpqqfuu/14/).

Here results:
```js
DateTime.local().toISO() // 15.958984375ms
moment().toISOString() // 1.282958984375ms

DateTime.local() // 1.98388671875ms
moment() // 0.572265625ms
```
I think is bug, formatter (probably formatDateTimeFromString) is very slow in comparsion to moment.

**Comment by icambron** [comment]
Yup, that sucks. There's probably more we could do, but here's a quick fix that makes formatting to ISO (or other "technical" formats) 85x faster: c18f014ace4

Before:

```
DateTime#toISO x 2,641 ops/sec ±4.62% (83 runs sampled)
```

After:

```
DateTime#toISO x 223,646 ops/sec ±0.40% (93 runs sampled)
```

This same fix could make `toFormat` faster if I do some extra work (detecting whether we need the number formatter). And there's probably a lot more perf we could squeeze out of it. But for now I've released this in 0.5.7. Hope that helps!
