### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by ansem78** [moment/luxon#218]
The documentation about installing and using Luxon on Node says:

const { DateTime } = require('luxon');

But this is wrong. It should be:

const luxon = require('luxon');
const d = luxon.DateTime.local(); // Uses the DateTime class to construct a Luxon object.

**Comment by icambron** [comment]
Hmm, it works for me.

```
-> node
> const { DateTime } = require("luxon")
undefined
> DateTime.local()
DateTime {
  ts: 2018-03-19T12:09:11.796-04:00,
  zone: undefined,
  locale: en-US }
```

**Comment by ansem78** [comment]
Hmm...yesterday I tried a few times using that syntax and Node gave me an error like "DateTime.fromSQL() is not a function". But luxon.DateTime.fromSQL() worked. I have tried again with the same syntax and now it works. Maybe I was wrong to digit the variable name or something else, but I am pretty sure because I check my code very carefully...anyway, thank you.

**Comment by icambron** [comment]
That syntax does require a relatively new version of Node, but if it didn't give a syntax error, it should have worked. Anyway, going to close this out.
