### ISSUE TITLE
Add default export of the module 

### ISSUE THREAD

**Issue by xujif** [moment/luxon#219]
the module did not export default yet.

**Comment by icambron** [comment]
I'm not sure it should. Why should it?

**Comment by xujif** [comment]
es6 module imports:

- import * as luxion from 'luxon' 
- import {DateTime}  from 'luxon' 
- import luxion from 'luxion'

the first two ways can get luxion correctly,
but without "export default", the third way will be undefined.

**Comment by icambron** [comment]
Right, do `import * as luxon from "luxon"`
