### ISSUE TITLE
IANAZone.isValidSpecifier should support more than 2 components in the name

### ISSUE THREAD

**Issue by emanuelegalbiati** [moment/luxon#220]
There are timezone names like "America/Argentina/Ushuaia" or "America/Indiana/Indianapolis".

I think the regexp should be 
`/^[a-z_+-]{1,256}(\/[a-z_+-]{1,256})+$/i `
or 
`/^[a-z_+-]{1,256}\/[a-z_+-]{1,256}(\/[a-z_+-]{1,256})?$/i`

at line https://github.com/moment/luxon/blob/e77f74f27fae1237a5b59b1df15e4114215f665c/src/zones/IANAZone.js#L57

**Comment by aadityakulkarni** [comment]
Hi @emanuelegalbiati I would like to take this up. I will create a PR for this.

**Comment by icambron** [comment]
Fixed in #234. Will release it soon.

**Comment by icambron** [comment]
Released in 1.1.0
