### ISSUE TITLE
Localization not working reliably

### ISSUE THREAD

**Issue by lookapanda** [moment/luxon#229]
https://repl.it/repls/HealthySolidBusinesssoftware

```javascript
const { DateTime, Info } = require('luxon');

const a = DateTime.fromJSDate(new Date(2018, 2));
console.log(a.setLocale('de').toFormat('yyyy LLL dd'));
// => 2018 M03 01 (expected: 2018 Mar 01; Also happens with MMM or MMMM instead of LLL)

console.log(Info.weekdaysFormat('narrow', { locale: 'de' }));
// => [ 'M', 'T', 'W', 'T', 'F', 'S', 'S' ] (expected: ['M', 'D', 'M', 'D', 'F', 'S', 'S'])

console.log(Info.meridiems({ locale: 'de' }));
// => [ 'AM', 'PM' ] (expected: [ 'vorm.', 'nachm.' ])

console.log(a.setLocale('de').toFormat('ccc, MMM d'))
// => Thu, M03 1 (expected: Do, März 1)
```

Apparently, this could be an issue with node `>= 9.x` since both the `repl.it` and my PC run that node version AND it is working correctly if I try it directly in Chrome on your website.

Opening a new issue in favor of https://github.com/moment/luxon/issues/204#issuecomment-379902233 since this seems to be a broader issue.

**Comment by icambron** [comment]
It's probably that the Intl locales aren't in your build of node. The installation on your computer probably came with it, so that's the difference, not the Node version. See the [install guide](https://moment.github.io/luxon/docs/manual/install.html#node). I'd be willing to add more instructions there, I think.

See also #225

**Comment by lookapanda** [comment]
Hello,

okay, that's good to know, although I still have issues even with using `NODE_ICU_DATA` and supplying `full-icu` to it.

I got this test from the official node docs: 
```javascript
const checkForFullICU = () => {
    try {
        const january = new Date(9e8);
        const spanish = new Intl.DateTimeFormat('es', { month: 'long' });
        return spanish.format(january) === 'enero';
    } catch (err) {
        return false;
    }
};
```

but still, if I check
```javascript
console.warn(this.locale, checkForFullICU(), Info.meridiems({ locale: this.locale }));
```
this, it returns:
```
de true [ 'AM', 'PM' ]
```

Which is incorrect, it should be `['vorm.', 'nachm.']`
What am I missing?

**Comment by icambron** [comment]
What is `this.locale` in that `console.warn` line? What if you just put "de" there?

**Comment by icambron** [comment]
This is still Node 9, yeah? Here are a few things to check

1. Double check that you have `formatToParts` available (can't imagine why you wouldn't):

```
-> node
> Intl.DateTimeFormat.prototype.formatToParts
[Function: formatToParts]
```

2. How are you mounting the full ICU data? It's possible that if you mounted it in userspace after having already tried `Info.meridiems({ locale: "de" })`, that Luxon has cached `["AM", "PM"]` and isn't letting go of that after it has the real ICU dat.a

FWIW, here's my computer doing this in Node 8:

```js
> const { Info } = require("luxon")
undefined
> Info.meridiems({ locale: "de" })
[ 'vorm.', 'nachm.' ]
```

**Comment by bogdanpolak** [comment]
@icambron I've got similar issue: full-icu working fine with Date, but not working with Luxon.  

```javascript
env NODE_ICU_DATA=./node_modules/full-icu/ node
> const spanish = new Intl.DateTimeFormat('es', { month: 'long' }), 
...   rusian = new Intl.DateTimeFormat('ru', { month: 'long' });
undefined
> spanish.format(new Date(9e8));
'enero'
> rusian.format(new Date(9e8));
'январь'
> const { DateTime } = require('luxon');
undefined
> const dt = DateTime.fromJSDate(new Date(9e8));
undefined
> dt.setLocale('ru').monthLong;
'January'
> dt.setLocale('es').monthLong;
'January'
> Intl.DateTimeFormat.prototype.formatToParts
undefined
```

as you see I don't have ```formatToParts```! Isaac do you have any idea how to test what is the issue?

**Comment by bogdanpolak** [comment]
1. About formatToParts: In my environment there was node version issue. `Intl.DateTimeFormat.formatToParts` was introduced in the node 8. After upgrading to node 8.x  `formatToParts` is working fine.
2. About Info.meridiems: Even after upgrade to node 8.x. I'm receiving just the same result as @lookapanda 
```javascript
env NODE_ICU_DATA=./node_modules/full-icu/ node
> const { Info } = require("luxon")
undefined
> Info.meridiems({ locale: "de" })
[ 'AM', 'PM' ]
```
