### ISSUE TITLE
Documentation for "fmt"

### ISSUE THREAD

**Issue by damianobarbati** [moment/luxon#236]
Is it correct to assume the format uses the same placeholders as momentjs? I can't find the format/placeholders we can use in the string.

https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromFormat

I see recently the documentation changed from "manually" generated to "automatically" generated from code and it's not very clear/readable/browsable now.

Great work as always, thanks!

**Comment by damianobarbati** [comment]
Never mind, just found! https://moment.github.io/luxon/docs/manual/parsing.html#fromformat

**Comment by icambron** [comment]
The docs haven't changed, so I'm not sure what you mean by that. I would like to link from the method-level documentation to the long-form docs, but I'm not sure how to do that in ESDoc
