### ISSUE TITLE
Invalid 12-hours US time

### ISSUE THREAD

**Issue by ValentinaV** [moment/luxon#242]
Hello

DateTime.fromFormat('00:30:00', 'hh:mm:ss', { locale: 'en-US' }).toLocaleString(DateTime.TIME_SIMPLE)
return 12:30 AM

I think it isn't  correct. I expacted 00:30 AM

**Comment by icambron** [comment]
No, that's just how US 12-hour time works. "12:30 AM" is correct.  Three different kinds of sources:

1.  [Wikipedia](https://en.wikipedia.org/wiki/12-hour_clock)
1. I'm American and my clocks say "12:30 AM" every day
1. Intl API: 

```js
new Intl.DateTimeFormat("en-us", { hour: "numeric", minute: "numeric"}).format(new Date(2018, 04, 25, 0, 30)) //=> "12:30 AM"
```
