### ISSUE TITLE
Intended pattern to check is A is before B

### ISSUE THREAD

**Issue by damianobarbati** [moment/luxon#244]
Currently using the following:
```
const a = DateTime.fromObject({ year: 2016 });
const b = DateTime.local();
const interval = Interval.fromDateTimes(a, b);
const a_IsBefore_b = interval.length('milliseconds') > 0;
```

Is this the indended way to check if a date occurs before another?

Because the following real scenario It's getting weird.
Let's suppose I need to check if now is before local 22:00.
I don't know if now know is going to be before or after before the check when I'll be checking this (of course).
I do the following:
```
const time22 = DateTime.fromObject({ hour: 22 });
const now = DateTime.local();
const before22 = Interval.fromDateTimes(now, time22).length() > 0;
```

Now, we have 2 cases:
- now is before time22: interval.length() returns a number so comparison works fine
- now is not before time22: interval.length() returns NaN so number comparison is going to fail but the result is not logically correct

Introducing another check for "NaN" result turns this "isBefore" into a very verbose way to know if a date occurs before another, doesn't it?

**Comment by damianobarbati** [comment]
Nevermind, found the https://github.com/moment/luxon/issues/108 and valueOf implementation.

AMAZED!

**Comment by icambron** [comment]
For anyone else who ends up here: https://moment.github.io/luxon/docs/manual/math.html#comparing-datetimes
