### ISSUE TITLE
Add DateTime#toMillis for consistency

### ISSUE THREAD

**Issue by icambron** [moment/luxon#246]
We have `#fromMillis` but not `#toMillis`. We have `#valueOf` (which does the same thing) to make numeric casting work magically, but we should alias `toMillis` to that

**Comment by maxymshg** [comment]
Hello @icambron,

**Comment by icambron** [comment]
Hi @maxymshg. See [contributing](https://github.com/moment/luxon/blob/master/contributing.md). Add the code to src/DateTime.js along with the docs. We don't have a great place to put the test, but maybe create a new file at test/datetime/transform.js and add the test there. Happy coding!

**Comment by icambron** [comment]
Fixed in #258
