### ISSUE TITLE
Not working with ESM on Node 10

### ISSUE THREAD

**Issue by damianobarbati** [moment/luxon#252]
Hey, any chance to have luxon work with Node ESM modules?

```
import { DateTime } from 'luxon';
           ^^^^^^^^
SyntaxError: The requested module 'luxon' does not provide an export named 'DateTime'
at ModuleJob._instantiate (internal/modules/esm/module_job.js:89:21)
```

**Comment by icambron** [comment]
I've never used ESM, so I am not sure. Pretty hard to imagine why it thinks that. E.g. see the end of http://moment.github.io/luxon/node/luxon.js

I'd take a fix to the toolchain that helped here, but I have no idea how to help myself

**Comment by ericmorand** [comment]
Aren't ESM modules an experimental feature on node 10?

**Comment by damianobarbati** [comment]
Yes, and soon moving to harmony flag. Let's be prepared! :)

NB: I've been using them for weeks by now and they work seamlessly (only pain in the ass is you can't import .json as you used to require .json ...).

**Comment by ericmorand** [comment]
>  (only pain in the ass is you can't import .json as you used to require .json ...)

That's actually a very good thing if you ask me. JSON files are not modules in any way and this was leading to a lot of potential problems when you were requiring modules in the blind.

Anyway, yes, ESM is just around the corner. Why is it not working? Isn't doing this enough to support ESM?


`export { DateTime, Duration, Interval, Info, Zone, FixedOffsetZone, IANAZone, LocalZone, Settings };
`

https://github.com/moment/luxon/blob/19b6c26063498806266ab8b00bfae4d6754e7569/src/luxon.js#L11

**Comment by ericmorand** [comment]
Oh yes, good one.

**Comment by icambron** [comment]
Yes, we link to the built one, where the relevant code is:

```js
exports.DateTime = DateTime;
exports.Duration = Duration;
exports.Interval = Interval;
exports.Info = Info;
exports.Zone = Zone;
exports.FixedOffsetZone = FixedOffsetZone;
exports.IANAZone = IANAZone;
exports.LocalZone = LocalZone;
exports.Settings = Settings;
```

**Comment by damianobarbati** [comment]
Maybe .mjs extension is required?

**Comment by icambron** [comment]
Well, even if that's true, I can't just export that or it will break versions of Node that don't support it. What we need is something like:

1. Make the build produce a separate file
 2. Point to it with a different key in package.json that Node will know to import from

No idea if 2 is possible, but I'm unclear on what the path forward is supposed to be otherwise. How are libraries expected to provide these modules?

**Comment by pho3nixf1re** [comment]
You can set the main to `index` and provide both an `index.js` and `index.mjs`. Then ESM will pick up the mjs one and the rest of use will use js.

**Comment by pho3nixf1re** [comment]
You might also consider using https://github.com/standard-things/esm to remove the need for duplication and some pre-publish build steps.

**Comment by icambron** [comment]
Ah, that's the kind of answer I was looking for. I'll get to this, but if someone wants to give it a shot, that would be great

**Comment by damianobarbati** [comment]
>> You can set the main to index and provide both an index.js and index.mjs. Then ESM will pick up the mjs one and the rest of us will use js.

@pho3nixf1re is that a default behaviour when esm is enabled? 
If I set `"main": "index"` without extensions thus it is going to look for `index.mjs` first, `index.js` second?
Any reference on it?

**Comment by jdalton** [comment]
Hi 👋!

Node core, Node Module WG member, and creator of `esm` here. I just wanted to pop in and say

> Yes, and soon moving to harmony flag.

That is not the case. There is no set time for Node to move from `--experimental-modules` to an unflagged implementation. There is also no guarantee on what the final implementation will look like. While the `.mjs` extension will be used to disambiguate. The extension may not be-the-only-way to disambiguate. There are several ongoing discussions in the working group about what ESM support will look like in Node. And many possible outcomes are incompatible with the current WIP implementation. 

The `esm` loader lets you use ESM syntax today and migrate over time to whatever the ESM of tomorrow will be. So you can use `esm` and ship just ESM syntax that is consumable by CJS modules and compatible with code coverage, APM, unit test, and mocking libraries. As the Node support story solidifies you can tweak, and migrate gradually over.

**Comment by Laaas** [comment]
FWIW, you can set `"type": "module"` in package.json, import src/luxon.js directly, and it will work fine

**Comment by AGBrown** [comment]
I'm on a later version of node, but I found that I had really strange intermittent issues with luxon, `import` and typescript. In some files the import was fine, in others it was not. The error was only ever at runtime (in node) and was along the lines of

```
import { Settings, Interval } from 'luxon';
                   ^^^^^^^^
SyntaxError: The requested module 'luxon' does not provide an export named 'Interval'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

or 

```
import { DateTime } from 'luxon';
         ^^^^^^^^
SyntaxError: The requested module 'luxon' does not provide an export named 'DateTime'
```

or (this time DateTime is fine, but Info is not)

```
import { DateTime, Info } from 'luxon';
                   ^^^^
SyntaxError: The requested module 'luxon' does not provide an export named 'Info'
```

I solved it in one file with:

```ts
import luxon from 'luxon';

const { DateTime, Settings } = luxon;
```

and yet in another file in the same project I have this, with no issues:

```
import { DateTime, Info } from 'luxon';
```

Versions are:

```
$ npm -v && node -v && npm list --depth=0 | grep luxon
6.14.5
v12.17.0
+-- @types/luxon@1.24.1
+-- luxon@1.24.1
```

relevant [package.json][package.json.txt] and [tsconfig.json][tsconfig.json.txt] attached.


[package.json.txt](https://github.com/moment/luxon/files/4944738/package.json.txt)
[tsconfig.json.txt](https://github.com/moment/luxon/files/4944739/tsconfig.json.txt)

**Comment by Darkle** [comment]
Any movement on this? I am getting the same errors. I tried @AGBrown suggestion but it didnt work for me.
Im on luxon version 2.0.2

@pho3nixf1re's suggestion seems like the simplest fix for luxon. Or alternatively you cold rename all the /src .js files to .mjs

Docs https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_package_json_and_file_extensions

**Comment by patriceo** [comment]
Hi same issue in my angular project using the 2.0.2 version (and also with the 1.27.0) while trying to import Duration, import of DateTime works fine:

`
import {Duration} from 'luxon'; 
`

`
"export 'Duration' (imported as 'Duration$2') was not found in 'luxon/src/duration'
`
