### ISSUE TITLE
Duration.toISO() doesn't include milliseconds

### ISSUE THREAD

**Issue by RikkiGibson** [moment/luxon#253]
moment.js includes the milliseconds part of the duration in the ISO representation.

```js
> moment.duration({milliseconds: 11}).toISOString()
'PT0.011S'
```

However, luxon.Duration doesn't do the same.

```js
> luxon.Duration.fromObject({ milliseconds: 11 }).toISO()
'PT'
```

Is this intended?

**Comment by icambron** [comment]
The ISO format for durations doesn't have milliseconds, unfortunately.  https://en.wikipedia.org/wiki/ISO_8601#Durations

**Comment by RikkiGibson** [comment]
This handling seems a little off to me considering that fractional seconds are part of the ISO 8601 spec. Lots of time libraries convert to ISO format by including any sub-second components as a fractional part of the seconds. Are you sure there isn't some kind of normalization that should be happening before converting to ISO format? Is that some convenience which is out of scope for luxon?

```js
> luxon.Duration.fromObject({ seconds: 0.011 }).toISO()
'PT0.011S'

> luxon.Duration.fromMillis(10000).toISO()
'PT'

> luxon.Duration.fromObject({seconds: 1, milliseconds: 2000}).toISO()
'PT3S'
```

**Comment by icambron** [comment]
Hmm, you may be right that milliseconds should be upconverted to fractional seconds while `toISO`ing them. The reason I didn't do it is that it's not symmetrical for parsing, but I suppose if we're dropping the millis on the floor, it's not symmetrical as is either. So sure, I'd take a PR for that.

I'm actually not sure why your third example behaves that way. I'd have guess it would produce "PT1S". Not sure what's up with that.

**Comment by bogdanpolak** [comment]
I can take it

**Comment by bogdanpolak** [comment]
@icambron it can be closed
