### ISSUE TITLE
How should I be writing tests for code that depends on Luxon?

### ISSUE THREAD

**Issue by joshhepworth** [moment/luxon#254]
For example lets say I have this function:

```
import DateTime from 'luxon';

export default function renderDate() {
  return DateTime.local().toFormat('s');
}
```

And I want to write a test:

```
import renderDate from 'renderDate';

describe('renderDate', () => {
  beforeEach(() => {
    // Do something to freeze/mock/whatever the time so that it has 4 seconds
  });

  afterEach(() => {
    // Cleanup
  });

  test('gives me the seconds', () => {
    expect(renderDate()).toBe('4');
  });
});
```

I've tried some of the time mocking libraries I've found, like `mockdate` with no success. I've also tried overriding various methods on `Date`, also with no success.

I'm currently running tests with `TZ=utc jest`.

Also, if there is a better place to ask this question, please let me know.

**Comment by icambron** [comment]
Luxon allows you to specify the function that provides the current time:

```js
// it's always May 25
import { Settings, DateTime } from "luxon";
Settings.now = () => new Date(2018, 4, 25).valueOf();
DateTime.local().toISO(); //=> "2018-05-25T00:00:00.000-04:00"
```

Does that answer your question?

**Comment by joshhepworth** [comment]
Turns out a detail of my implementation caused the issue – my `renderDate` was closer to this:

```js
import DateTime from 'luxon';

const CURRENT_DATE = DateTime.local();

export default function renderDate() {
  return CURRENT_DATE.toFormat('s');
}
```

That difference meant that the `DateTime` was being initialized before any code in the test had the chance to mock/override/provide a specific value for the current time.

Anyway, thanks for your help – it was also good to know how the `Settings` class is expected to be used in the context of tests.

**Comment by Lucas-Geitner** [comment]
Thanks @icambron for the help 🔥

I think it could be more explicit on the docs !

**Comment by lsbyerley** [comment]
Is it possible to mock luxon in one line, like in this article https://medium.com/front-end-weekly/mocking-moment-js-in-jest-a-simple-one-line-solution-61259ffaaa2

I'm trying it but keep receiving a `TypeError: Cannot read property 'fromMillis' of undefined` when trying to mock `fromMillis`

```
jest.mock('luxon', () => () => ({ fromMillis: (date) => `passed date was ${date}` }));
```

**Comment by nigfasa** [comment]
Does this method alter other files too? 

 I did an `Settings.now = () => new Date().valueOf())` just in case it did

**Comment by att14** [comment]
> Does this method alter other files too?

It appears the answer is yes. It would be cool if we could have some wrapper to set and unset this setting, e.g.

```js
Settings.withNow(new Date(2018, 4, 25).valueOf(), () => {
  expect(DateTime.now()).to.eql(new Date(2018, 4, 25).valueOf())
})

expect(DateTime.now()).not.to.eql(new Date(2018, 4, 25).valueOf())
```

**Comment by icambron** [comment]
I think it's easy enough for people to make their own wrappers. I don't want to add it to Luxon because there are a few variations (e.g. for handing async tests). For reference here's how Luxon's own test suite implements it: 
​

**Comment by theliuk** [comment]
Do I need to restore `Settings.now` after the test finished? How about parallel tests? Are there side effects
