### ISSUE TITLE
DateTime instance from javascript Date instance

### ISSUE THREAD

**Issue by damianobarbati** [moment/luxon#255]
Is it possible to convert a native Date instance to DateTime instance?
Something like.
```
const date = new Date(); //somehow I have a date instance
const datetime = DateTime.fromDate(date); //I want to convert it to a Luxon DateTime instance
```

**Comment by icambron** [comment]
https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromJSDate

**Comment by xinthose** [comment]
I do not see `fromJSDate` anywhere in the manual.  I had to search google to find this.

**Comment by GillesDebunne** [comment]
Indeed, it should probably be part of `docs/manual/parsing.html`. Added in #789

**Comment by mayrsascha** [comment]
I was looking for this on Google even after you guys added it to the parsing docs page. IMO it would be nice to have this on the "A quick tour" page [where you also describe how to create a `DateTime` from an ISO8601 String](https://moment.github.io/luxon/docs/manual/tour.html#parse-from-iso-8601), as it seems to be a common use case to me.

**Comment by revington** [comment]
all links are broken

**Comment by AwesomeDevDen** [comment]
@revington https://moment.github.io/luxon/api-docs/index.html

**Comment by revington** [comment]
thx @AwesomeDevDen

**Comment by LarsFlieger** [comment]
It has to be:
```ts
const date = new Date();
const datetime = DateTime.fromJSDate(date); 
```
Docs: https://moment.github.io/luxon/#/parsing?id=js-date-object

**Comment by srwaggon** [comment]
This is such a common usecase that I can't believe it isn't featured at the top of the "A quick tour/Creating a DateTime" section.
