### ISSUE TITLE
fromIso is very slow

### ISSUE THREAD

**Issue by jnizet** [moment/luxon#259]
I've had a performance issue, both in Chrome and Firefox (French locale), due to a design error on my side, but which surprised me anyway. 

It was caused by a high number of calls to `Datetime.fromIso()`, where the passed strings were in the form 'yyyy-MM-dd`. I expected these calls to be fast enough, but they weren't.

So I just measured the time it takes to execute this loop:

    for (let i = 0; i < 1000; i++) {
      DateTime.fromISO('2018-03-10');
    }

it takes 740 milliseconds, which is quite a lot (replacing the content of the loop by `moment('2018-03-10')`) reduces the time to 50 milliseconds. So Luxon is one order of magnitude slower than moment here.

Most of the time seems to be spent in Intl, inside the DateTimeFormat constructor, called from Locale.supportsFastNumbers().

Here's a screenshot of the bottom-up view of the chrome console:
<img width="742" alt="capture d ecran 2018-05-18 a 22 11 36" src="https://user-images.githubusercontent.com/1608223/40256144-d4b7921c-5ae9-11e8-971b-16b662542965.png">

**Comment by icambron** [comment]
That does look like a bug. The way Luxon works is that it figures out if it needs to use the Intl library (which is very slow) or whether it can use its own much faster code. fromISO should never need the Intl library, but maybe it's getting confused by the fr locale and thinks it has to use it anyway. Just a guess.

**Comment by icambron** [comment]
Ah, nevermind that. Bad analysis.

The problem here is that the locale object is expensive to create with a non-English locale. I think we could solve this by either lazy-loading `supportsFastNumbers` or by caching the locale. I'll give it some thought.

**Comment by icambron** [comment]
That was easy enough. See 8cde0bc3, which speeds up DateTime creation 222x on my machine for non-en locales. `toFormat()` will pay that price instead, but you may not need that. Released in Luxon 1.2.1.

**Comment by jnizet** [comment]
Thanks for the quick fix Isaac. You rock.
