### ISSUE TITLE
Introduce toUnix() and fromUnix()

### ISSUE THREAD

**Issue by mingchuno** [moment/luxon#260]
Should we introduce the following functions?

```js
// ts is UNIX timestamp in second
DateTime.fromMillis(ts * 1000) === DateTime.fromUnix(ts)
Math.round(dt.toMillis() / 1000) === dt.toUnix()
```

**Comment by icambron** [comment]
No, I'd prefer not to. I know it's a feature of Moment, but I want to keep conveniences like that out of Luxon.

**Comment by mingchuno** [comment]
@icambron May I know why?

**Comment by icambron** [comment]
Because for the caller, it's just the addition of `/ 1000` or `* 1000`, but for Luxon, it's file size, testing, and maintenance. Yes, that's all small, but so is the cost for the caller, and for Luxon there are lots of things at this level of convenience, and including them all would bloat Luxon without creating much value.

You can always define your own helpers for this. It's even safe to monkey patch, because it only uses public APIs:

```js
DateTime.prototype.toMillis = (ts) => ....
```

**Comment by mingchuno** [comment]
@icambron Thx very much for the explanation

**Comment by damianobarbati** [comment]
@icambron what's the proper way to create a DateTime object from a unix timestamp with current API?

**Comment by damianobarbati** [comment]
Never mind I just found it digging in Google (`fromMillis`).

In the whole https://moment.github.io/luxon/docs/manual/parsing.html there's no mention to "unix" or "timestamp" words! xD

**Comment by mingchuno** [comment]
@damianobarbati so what is the way?

**Comment by damianobarbati** [comment]
It's fromMillis and toMillis as you said, https://codesandbox.io/s/lyj0qp979l

**Comment by richardscarrott** [comment]
Isn't this just `DateTime.fromSeconds` and `DateTime.prototype.toSeconds`?

**Comment by icambron** [comment]
yes, we did eventually add those, since this was a popular request

**Comment by jpike88** [comment]
> I want to keep conveniences like that out of Luxon

You want to make using Luxon more painful for people moving from moment? Instead of a simple ```unix()``` equivalent, I now need to floor/ceil, or monkey patch DateTime across all my projects? How is that supposed to be ergonomic for people looking to 'upgrade' from moment?

**Comment by thoroc** [comment]
For anyone looking and not finding where in the docs this is as of Feb 2025:

https://moment.github.io/luxon/api-docs/index.html#datetimetomillis for milliseconds
https://moment.github.io/luxon/api-docs/index.html#datetimevalueof for Unix epich
