### ISSUE TITLE
Contributing Guide extensions

### ISSUE THREAD

**Issue by bogdanpolak** [moment/luxon#263]
During my first contribution to luxon I found that some information are not emphasized or even lacking in the contributing.md

1. If you are not on the America/New_York time zone then you have to run tests with
```./scripts/test``` not with ```npm run test```. IMHO guide should suggest second one on the OS X and first one as an option.
2. There should be separate "Project Testing" section in this guide with all testing commands (unit tests, linter tests, doc generation, tests doc coverage). This section should be described before requesting fixes, in my opinion.
3. There lack of the: ```npm run check-doc-coverage```
4. There is no info about path to Full-ICU (on OS X adding line in the .bash_profile: export NODE_ICU_DATA). If someone wasn't familiar with ICU this could be an issue (for me it was).
5. ```npm run check-doc-coverage``` Should print something like 100% coverage when all coverage tests are passed.
6. Short comment about signing CLA during first PR would be nice.

**Comment by icambron** [comment]
Cool, will do

**Comment by icambron** [comment]
I did a bunch of those in c16ce71. I didn't understand 4 though; you shouldn't have needed that for OSX.
