### ISSUE TITLE
Implement proper Moment formatting spec

### ISSUE THREAD

**Issue by BlackHoleFox** [moment/luxon#264]
Upon some in depth research we discovered that Luxon does not contain the same formatting spec as Moment does. It contains some of them, some are different, and others don't even exist.

We tried to use this from Moment's homepage: `MMMM Do YYYY` due to dedicated Luxon documentation for it not existing and found that it does not return what is expected. It returned `Do = 5/30/2018150`. Its mostly the nonexistence of `Do` that is odd.

In the process we ran an array function to check every possible combination and noticed it doesn't exist in the code. Would it be possible to just use the exact formatting system as Moment or better off to properly document the formatting that Luxon uses?

**Comment by BlackHoleFox** [comment]
Here is the code we used for testing and its results: https://gist.github.com/BlackHoleFox/d30bb0f58efe3e42398b9a9670f99db7

**Comment by icambron** [comment]
The tokens Luxon supports are documented [here](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens). They are designed to be closer to the CLDR tokens, and make no effort to be the same as Moment's.

**Comment by BlackHoleFox** [comment]
So no chance of being able to get the date like this?  `May 31st 2018`?

**Comment by icambron** [comment]
No, unfortunately, the Intl library on which Luxon depends doesn't have support for ordinals.

If this output string is meant to be read by a human, I also really encourage you not to use a format like that, regardless of which library you use to generate it. Instead, use `toLocaleString()`, which will provide standardized and internationalizable date formats.
