### ISSUE TITLE
Invalid examples in docs for quarter format tokens?

### ISSUE THREAD

**Issue by benmccann** [moment/luxon#265]
I'm confused by https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens

There are only 4 quarters, so how are `9` and `13` example quarters? Also, how can you pad a quarter to 2 digits given that there are only 4 quarters in a year?

**Comment by icambron** [comment]
Yeah, that is confusing and at the very least a doc bug

**Comment by benmccann** [comment]
Thanks for updating https://github.com/moment/luxon/commit/57d6989e74a97c672dbc437b04f3e9b690a619a8
