### ISSUE TITLE
startOf('quarter') returns the wrong date

### ISSUE THREAD

**Issue by leahaense** [moment/luxon#271]
When running `DateTime.local().startOf('quarter')` today, June 8th 18, it returns July 1st. We use version `1.0.0`

**Comment by leahaense** [comment]
same happens with current version `1.2.1`

**Comment by icambron** [comment]
Yikes. Yeah, would definitely accept a fix for that

**Comment by leahaense** [comment]
I'm just trying to reproduce the bug in the tests, but cannot. Were you able to?

**Comment by leahaense** [comment]
Ok, never mind, it seems it was fixed in April and released with version 1.2.1. Somehow the library was not properly upgraded in our project. sorry for that.
