### ISSUE TITLE
DateTime.toISODate() typerror

### ISSUE THREAD

**Issue by Sufiane** [moment/luxon#272]
When I want to use the `toISODate()` function I get a `TypeError: DateTime.toISODate is not a function`

In the doc I saw that it was a `DateTime` function , am I mistaken?

snipet: https://runkit.com/sufiane/luxon-test-error

Thanks in advance !

**Comment by icambron** [comment]
`DateTime` is a class and `toISODate` is an instance method, so you need to create an instance of a DateTime. Assuming what you're trying to do is get the *current* ISO Date, the easiest way to do that is with `local()`:

```js
DateTime.local().toISODate()
```

**Comment by Sufiane** [comment]
Thanks !
