### ISSUE TITLE
Some time ago-like examples? 

### ISSUE THREAD

**Issue by bologer** [moment/luxon#274]
Hey, 

Was looking through documentation but did not find any examples of making time ago-like duration.

For example, `2 hours ago`.

Could anybody point me if it exists or give an example! 
Really appreciate it, thanks in advance.

**Comment by icambron** [comment]
Well, it depends what you mean. Are you trying to make something that will print that string?

**Comment by bologer** [comment]
@icambron for example I have `time` tags on the page with `datatime` attribute which contains date & time something like the following format: `2018-06-14 11:33:56`, the content of the tag is empty and I would like to render for example "2 months ago". I was trying to find the solution in `Duration` class, but no luck.

**Comment by icambron** [comment]
Unfortunately, Luxon doesn't have that because the Intl API doesn't support it. See [here](https://github.com/tc39/proposal-intl-relative-time) for the proposal. Luxon will support that as soon as the first browser does.

In the meantime, you should be able to fake it with a little code if you're only supporting one language.

**Comment by acomito** [comment]
There's no way to do something like this with luxon? 

```
import moment from 'moment';

const timeAgo = (date) => {
  const now = new Date();
  const nowMoment = moment(now);
  const pastMoment = moment(date);
  const timeAgoString = pastMoment.from(nowMoment); // 2 hours ago
  return timeAgoString;
};
```

**Comment by OzzieOrca** [comment]
Looks like we have https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format now 🎉 

Here's my shot at it. It just finds the biggest unit in the diff that isn't 0 and passes that unit and value to the relative time formatter. It rounds toward 0 with `Math.trunc` (1 min and 38 sec is "1 minute ago"). You could probably round away from 0 with something like [this](https://stackoverflow.com/a/26335164/665224) if desired. I have it hard coded to English but that would be trivial to add as an arg or pull from context somewhere.
```ts
import { DateTime } from 'luxon';

const units: Intl.RelativeTimeFormatUnit[] = [
  'year',
  'month',
  'week',
  'day',
  'hour',
  'minute',
  'second',
];

export const timeAgo = (dateTime: DateTime) => {
  const diff = dateTime.diffNow().shiftTo(...units);
  const unit = units.find((unit) => diff.get(unit) !== 0) || 'second';

  const relativeFormatter = new Intl.RelativeTimeFormat('en', {
    numeric: 'auto',
  });
  return relativeFormatter.format(Math.trunc(diff.as(unit)), unit);
};
```

**Comment by DmitryOlkhovoi** [comment]
.toRelative()

**Comment by OzzieOrca** [comment]
Cool :)

Here's the docs link for that: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toRelative

**Comment by mylastore** [comment]
@OzzieOrca 


> Looks like we have https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format now tada
> 
> Here's my shot at it. It just finds the biggest unit in the diff that isn't 0 and passes that unit and value to the relative time formatter. It rounds toward 0 with `Math.trunc` (1 min and 38 sec is "1 minute ago"). You could probably round away from 0 with something like [this](https://stackoverflow.com/a/26335164/665224) if desired. I have it hard coded to English but that would be trivial to add as an arg or pull from context somewhere.
> 
> ```ts
> import { DateTime } from 'luxon';
> 
> const units: Intl.RelativeTimeFormatUnit[] = [
>   'year',
>   'month',
>   'week',
>   'day',
>   'hour',
>   'minute',
>   'second',
> ];
> 
> export const timeAgo = (dateTime: DateTime) => {
>   const diff = dateTime.diffNow().shiftTo(...units);
>   const unit = units.find((unit) => diff.get(unit) !== 0) || 'second';
> 
>   const relativeFormatter = new Intl.RelativeTimeFormat('en', {
>     numeric: 'auto',
>   });
>   return relativeFormatter.format(Math.trunc(diff.as(unit)), unit);
> };
> ```

That did not worked for me, now sure where do you pass the date? And don't see the DateTime from luxon either. What am I missing?

**Comment by mylastore** [comment]
I figure it out, I believe this is correct 
```
const units = [
  'year',
  'month',
  'week',
  'day',
  'hour',
  'minute',
  'second',
];

const timeAgo = (date) => {
  let dateTime = DateTime.fromISO(date)
  const diff = dateTime.diffNow().shiftTo(...units);
  const unit = units.find((unit) => diff.get(unit) !== 0) || 'second';

  const relativeFormatter = new Intl.RelativeTimeFormat('en', {
    numeric: 'auto',
  });
  return relativeFormatter.format(Math.trunc(diff.as(unit)), unit);
};
```

**Comment by BALEHOK** [comment]
Here is the update link to the doc [DateTime.toRelative()](https://moment.github.io/luxon/api-docs/index.html#datetimetorelative)
