### ISSUE TITLE
Improve JSDoc in TypeDefinition

### ISSUE THREAD

**Issue by balazser** [moment/luxon#277]
I really like this moment concept and I added it to my typescript project with the @types/luxon type definition.
Because I'm a new user of luxon I'd like to get help using the IntelliSense but unfortunately, there is no jsdoc generated for the type definition of the project.
Could you generate it into that to help us use the methods correctly?

**Comment by icambron** [comment]
The type definitions are maintained externally [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/luxon), so I think the changes you seek would have to go there.
