### ISSUE TITLE
Docs: Add pointers to CDNs

### ISSUE THREAD

**Issue by networkimprov** [moment/luxon#282]
*Edited for unpkg.com*

Most open source JS libraries can be loaded at runtime from a CDN. Cloudflare's https://cdnjs.com is the most popular, but the only ones I found for Luxon were these that automatically mirror npm:

https://www.jsdelivr.com/package/npm/luxon  
https://unpkg.com/luxon@1.3.0/

May I suggest you...
- mention this method in the docs (it's an easy way to evaluate a lib, and often the best way to ship it)
- submit the project to cdnjs

**Comment by icambron** [comment]
I would accept a pull request doing whatever is required to Luxon to make cdnjs auto-update, and for docs pointing users to the CDN options.

**Comment by networkimprov** [comment]
See also: https://cdnjs.com/libraries/moment.js/

**Comment by thewizarodofoz** [comment]
@icambron I saw that I you had some [discussion](https://github.com/cdnjs/cdnjs/issues/12220) with the cdnjs crew. Is it related? Can you share the status?

**Comment by icambron** [comment]
@thewizarodofoz No status beyond what you see there. I'm taking a very hands-off approach to CDNs. I'm happy to do work to support them (like adding config files or whatever), but I'm not going to put any time into wrangling CDNs to do stuff. So I'll leave figuring out that stuff to y'all.

**Comment by icambron** [comment]
Fixed in dee55a8

**Comment by networkimprov** [comment]
Hi, I think there's a typo in that commit...
>Yout can also load ...

**Comment by icambron** [comment]
oops, thanks! Fixed in 5eb9ad3
