### ISSUE TITLE
Locale kk-KZ not supported?

### ISSUE THREAD

**Issue by Yarisrespect** [moment/luxon#289]
Why do the locale kk-KZ not supported?

**Comment by icambron** [comment]
The support (or lack of support) for a locale is provided by the browser. In my version of Chrome, it doesn't seem to have real month names:

```js
DateTime.local().setLocale("kk-KZ").toLocaleString(DateTime.DATETIME_HUGE)
"2018 M07 10, Tue 12:40 Eastern Daylight Time"
```

You can see the same behavior by playing with the options to `Intl.DateTimeFormat`
