### ISSUE TITLE
Making Luxon available in the console on https://moment.github.io/luxon/

### ISSUE THREAD

**Issue by wegry** [moment/luxon#290]
One of my favorite things about http://momentjs.com/ is moment being available on `window`.

Would the maintainers be open to doing the same with Luxon?

**Comment by icambron** [comment]
It's there. `window.luxon` returns an object with all the Luxon classes on it, so like `window.luxon.DateTime`, etc

**Comment by wegry** [comment]
@icambron Thank you for the quick response. My mistake, I was trying to use the code at the top of the landing page `DateTime.local().setZone('America/New_York').minus({ weeks: 1 }).endOf('day').toISO();` and wasn't using `luxon` directly.
