### ISSUE TITLE
It is not clear from the documentation what formats are possible in DateTime::toFormat

### ISSUE THREAD

**Issue by jleeothon** [moment/luxon#293]
The documentation for `DateTime`'s `toFormat` method does not specify what are the formats that can be used for e.g. year, month, day etc.

https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toFormat

From the examples it can be inferred that `yyyy LLL dd` is a 4-digit year, long month name, and day of the month (but not clear if it's padded to two digits or not).

The documentation suggests to use `toLocalString` instead, but documentation for that method does also suggest what the format string can look like.

**Comment by jleeothon** [comment]
The list of tokens can be found at https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens

Should we consider adding a link to that other page?

**Comment by icambron** [comment]
Sure, would take a PR linking them.

**Comment by icambron** [comment]
Fixed in 9963917
