### ISSUE TITLE
Internationalized toFormat not working on Edge

### ISSUE THREAD

**Issue by JCKodel** [moment/luxon#294]
No matter what `setLocale` I use, it always shows english text in format:
(http://jsbin.com/bagaqoqada)

Chrome (OK):
![image](https://user-images.githubusercontent.com/379339/42665602-b5481b88-8616-11e8-954e-2955540d7c64.png)

Firefox (OK):
![image](https://user-images.githubusercontent.com/379339/42665616-ccaaa796-8616-11e8-90fe-f9c0fb4b4418.png)

Edge (Son of a IE!):
![image](https://user-images.githubusercontent.com/379339/42665631-e2b2eaa8-8616-11e8-8915-78bd8f814564.png)

Internet Exploder 11 - The Nightmare Continues - Jason Resurrects Again (with polyfills):
![image](https://user-images.githubusercontent.com/379339/42665676-193bdefe-8617-11e8-9fcf-4ae973f32fa0.png)

**Comment by icambron** [comment]
Weird. I was able to reproduce this. It's just `toFormat`; `toLocaleString` works fine, which is confusing.

**Comment by steabert** [comment]
I also found an issue with `toLocaleString`, e.g.:

```
DateTime.local().setLocale('pt-BR').toLocaleString(luxon.DateTime.DATETIME_MED_WITH_SECONDS);
```

in Chromium (68.0.3440.75): "30 de jul de 2018 11:07:41"
in Edge (42.17134.1.0): "30.jul.2018 11:07:12"

**Comment by steabert** [comment]
Does it have to do with the fact that Edge doesn't support `.formatToParts` ?

**Comment by icambron** [comment]
@steabert re: `toLocaleString`; that's not really an issue; that's just how Edge's Intl implementation wants to format that:

```js
new Intl.DateTimeFormat("pt-BR", { year: 'numeric',  month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', second: '2-digit'}).format()

"‎30‎.‎jul‎.‎2018‎ ‎10‎:‎39‎:‎51"
```

Re: `formatToParts`: that *is* the cause of the OP's issue. I'd somehow missed that `formatToParts` isn't available on edge.

Switching this to a documentation issue.

**Comment by JCKodel** [comment]
I've also noticed this behavior on iOS 10 on Cordova. The same code works
only on Chrome and Cordova Android.
For now, I gave up and migrate my code to MomentJS and all platforms are
working just fine.

**Comment by nicostem** [comment]
Did someone found a solution ?

**Comment by erback** [comment]
can confirm the same issue with ie11, any progress on this?

**Comment by icambron** [comment]
It looks like this is getting confused with a general discussion of Intl and ftp availability. For everyone not talking about Edge, go here: https://moment.github.io/luxon/docs/manual/matrix.html

On the Edge issue: looks like Edge 15-17 fits the "No Intl tokens" caveat on that page. Edge 18 adds the needed feature, though I haven't tested it. I'm going to update that matrix accordingly.
