### ISSUE TITLE
Docs- links in duration point to datetime

### ISSUE THREAD

**Issue by tzachshabtay** [moment/luxon#303]
In: https://moment.github.io/luxon/docs/class/src/duration.js~Duration.html
Some of the links in the overview section send you to the functions in the datetime page instead of staying in the duration page.
For example, take a look at the "toFormat" link in the output sub-section.

**Comment by icambron** [comment]
Yeah, I noticed that too. I believe it's a bug in ESDoc itself.

**Comment by icambron** [comment]
Fixed in 967703f
