### ISSUE TITLE
Typo in Documentation for Public Member DATETIME_FULL_WITH_SECONDS

### ISSUE THREAD

**Issue by prof3ssorSt3v3** [moment/luxon#308]
https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-get-DATETIME_FULL_WITH_SECONDS

In the comments for this member you are missing the colon and the prefixed zero in front of the seconds.

Just a typo.
The actual library functions fine.

**Comment by icambron** [comment]
thanks for the report

**Comment by icambron** [comment]
Fixed in 117233f
