### ISSUE TITLE
[BUG] Formatting date from ISO and setZone problem with date less than 1910

### ISSUE THREAD

**Issue by bloodf** [moment/luxon#312]
When using the Luxon library to converte a date yyyy-mm-dd, set a timezone to America/Sao_Paulo.
```DateTime.fromISO(dateString).setZone('America/Sao_Paulo').toISO();```

If I try to pass a date ```1910-01-01``` it gives a response ```1909-12-31T23:59:32.000-03:6.466666666666669```

**Comment by icambron** [comment]
That's the correct behavior. It looks like you're expecting `setZone` to reinterpret the string to be in that zone and change the underlying time accordingly. But what you're actually doing is parsing the string in the system's local zone, which creates a DateTime object representing a specific moment in time. Setting the zone doesn't change that time, but merely considers that time from the perspective of people in Sao Paulo, where it was still 1909 when it was Jan 1, 1910 where your computer is running. The string you generate with `toISO()` is thus in 1909.

What you wanted to say was "I have a string representation of a time and want Luxon to interpret it as having been expressed in Sao Paulo's local time. Here's how you do that:

```js
DateTime.fromISO("1910-01-01", {zone: 'America/Sao_Paulo'}).toISO()
```

Also, man, they had some weird offsets back then.
