### ISSUE TITLE
Checking if a DateTime is the current date...

### ISSUE THREAD

**Issue by Busti** [moment/luxon#313]
date-fns has the convenient isToday function. How can I achieve the same in luxon?

**Comment by icambron** [comment]
This should do the trick:

```js
someDateTimeInstance.hasSame(DateTime.now(), "day");
```

**Comment by Amirault** [comment]
> This should do the trick:
> 
> ```js
> someDateTimeInstance.hasSame(DateTime.local(), "day");
> ```

```someDateTimeInstance.hasSame(DateTime.local(), "day"); ```

work if you do 

```someDateTimeInstance.hasSame(DateTime.local().minus(1, "year"), "day");```

So I do not think it's correct : isToday != isSameDay

**Comment by standup75** [comment]
```
  isToday(date: DateTime): boolean {
    return date.toISODate() === DateTime.local().toISODate();
  }
```

**Comment by AntonyTsygankov** [comment]
```ts
import {DateTime} from 'luxon'
const isToday = (unixDate: number) => DateTime.fromISO(unixDate) >=  DateTime.now().startOf('day')
```

**Comment by thinhnt-cystack** [comment]
from Luxon's docs: https://moment.github.io/luxon/api-docs/index.html#datetimehassame
```
DateTime.now().hasSame(otherDT, 'day'); //~> true if otherDT is in the same current calendar day
```

Think this should be the easy and legit answer.
