### ISSUE TITLE
Formatting to Zulu time

### ISSUE THREAD

**Issue by mschipperheyn** [moment/luxon#316]
I'm missing the option to format to Zulu time. E.g. `2018-03-01T13:00:00Z`. Is that supported?

**Comment by icambron** [comment]
Yup, that's just a UTC time in expressed in ISO 8601. For example, either of these:

```js
DateTime.local().toUTC().toISO(); //=> "2018-08-14T21:24:56.957Z"
DateTime.utc().toISO(); //=> "2018-08-14T21:25:09.732Z"
```
