### ISSUE TITLE
Cannot parse locale aware form tokens, e.g. D or F

### ISSUE THREAD

**Issue by DrNiels** [moment/luxon#317]
Consider the following code snippet:

            let dateString= DateTime.local().setLocale('de').toFormat('D tt');
            console.log(dateString);
            console.log(DateTime.fromFormat(dateString, 'D tt', {locale: 'de'}));

As expected, the string generated by toFormat returns a nicely formatted German string, e.g., 14.8.2018 16:54:34. Now, when I try to parse it back into a DateTime via fromFormat, it does not work. The object states that the string is unparsable, even though it was just generated with the same format.
The same occurs with other locales, e.g., 'fr'. Other locale aware formats, e.g., 'F' are affected as well. Locale independent formats, e.g., 'y-L-d-H-m-s' work fine.

**Comment by icambron** [comment]
Fixed docs in 873de15c0034d4cc687bcb5feba5a600f830c827, will publish them soon
