### ISSUE TITLE
Removing Weekends When Using Diff()

### ISSUE THREAD

**Issue by seivad** [moment/luxon#322]
Hey is there a way to remove the weekends when performing a diff() on two dates like Carbon\Carbon does in PHP? 

Luxon
```"luxon": "^1.3.3"```

Right now I have a total duration between 2 dates, but to make it complete it would be best if Luxon could provide me those dates minus weekends and/or allow me to count the number of weekends during the time period and I'll just minus that from the final number.

**Comment by icambron** [comment]
No, Luxon doesn't have that feature. I suspect there's a relatively short closed-form solution for computing that. Would require a bit of thought, but I bet that's like four lines of code:

 * Compute the weekend before `date1` (and take note of the days between then and `date1`)
 * Compute the weekend before `date2` (and take note of the days between then and `date2`)
 * Compute the difference and remove two-sevenths of it
 * Add back in the remainder days
 * Make sure you do the right things in the corner cases where `date1` and/or `date2` are in the weekend

This is the sort of thing I'd like Luxon *not* to do. I get that it's convenient and useful, but the library would be pretty bloated if it included issues at this level of granularity. But please tell me the solution you come up with! It might be useful to others.
