### ISSUE TITLE
Parsing of partial ISO weekdates

### ISSUE THREAD

**Issue by Cliff122** [moment/luxon#330]
According to both the [documentation ](https://moment.github.io/luxon/docs/manual/parsing.html#iso-8601)and my own tests the `DateTime.fromISO` function doesn't seem to parse partial ISO week dates, such as `2018-W39` even though they are valid ISO dates according to this [Wikipedia ](https://en.wikipedia.org/wiki/ISO_8601#Week_dates) page.

What makes this even more strange is that the function does support other types of partial dates, such as `2016-05`.

Is there any particular reason for not supporting partial ISO week dates that I'm not seeing?

**Comment by icambron** [comment]
Just an oversight, I think

**Comment by icambron** [comment]
Fixed in b2a5fba, will release in 1.4.2 soon
