### ISSUE TITLE
Setting defaultTimeZone affects DateTime.local()

### ISSUE THREAD

**Issue by kevindetry** [moment/luxon#333]
```js
import { DateTime, Settings } from "luxon";

console.log(DateTime.local().zoneName); // prints "Europe/Kiev"
Settings.defaultZoneName = "utc";
console.log(DateTime.local().zoneName); // prints 'UTC"
```
I thought it should only affect `DateTime.from*`.
Or does it work as expected?

**Comment by icambron** [comment]
This works for me. I suspect you're operating this somewhere with no zone support? Try

```js
import { Info } from "luxon";
Info.features().zones
```

and see what it returns?

**Comment by icambron** [comment]
Oh, I must have completely misread this the first time. Sorry about that.

Yeah, that is expected behavior. The idea is that you're putting the whole env into that zone, like Luxon doesn't know that isn't your system's time zone. Perhaps that needs cleared up in the docs?

**Comment by abhikp** [comment]
For testing purposes, it would be great to be able to have some way of setting the zone for `local()`and `toLocal()`. An example would be in-browser tests or showing component state that's dependent on time in something like Storybook.

**Comment by icambron** [comment]
@abhikp Yeah, I think I agree that `toLocal` should respect `Settings.defaultTimeZone`. Can you open a separate issue for that?

**Comment by abhikp** [comment]
@icambron done #377

**Comment by massic80** [comment]
By the way, as far as I know, the canonical timezone for `Europe/Kiev` should be `Europe/Kyiv`.
