### ISSUE TITLE
TypeError: DateTime.isAfter is not a function

### ISSUE THREAD

**Issue by sahibjotsaggu** [moment/luxon#335]
After reading the docs for the `isAfter` method: https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html#instance-method-isAfter

I'm not sure if I'm using it correctly:

Luxon version: 1.3.3

```javascript
const a = DateTime.local();
// wait a couple seconds
const b = DateTime.local();
b.isAfter(a); // should return true but returns:
TypeError: b.isAfter is not a function
```

What is the right way to use the `isAfter` method?

**Comment by sahibjotsaggu** [comment]
After reading the docs a bit more, it looks like the `isAfter` method works only on `Interval` objects.

**Comment by icambron** [comment]
http://moment.github.io/luxon/docs/manual/math.html#comparing-datetimes

**Comment by jjarcik** [comment]
@icambron the link is broken. Here is the correct one https://moment.github.io/luxon/#/math?id=comparing-datetimes
