### ISSUE TITLE
Luxon feedback for ECMA402 `Intl.Locale`

### ISSUE THREAD

**Issue by zbraniecki** [moment/luxon#336]
Hi!

We (ECMA TC39) are working on a new low-level API called `Intl.Locale`[0] that seems to fit perfectly into what Luxon project decided to shortcut through[1].

It would be awesome to get this projects feedback on our API since we aim to help in exactly the kind of scenarios as you're facing.

[0] https://github.com/tc39/proposal-intl-locale/
[1] https://github.com/moment/luxon/blob/master/src/impl/locale.js#L23

**Comment by zbraniecki** [comment]
CC @littledan

**Comment by icambron** [comment]
@zbraniecki Holy crap that is awesome awesome. It's funny, I just added that code you referenced, so this is top-of-mind for me, and I absolutely love the idea of having a built-in parser like that (and formatter! Luxon does that too).

What's even more important to Luxon is the locale list (and I love that I can get them as Locale objects). Just being able to tell a caller "here's what I can do" comes up all the time.

I'm going to dig into some specifics, but just to make sure I understand the API (I am bad at reading specs and it seems to have drifted from your original proposal), is the following the behavior?

```js
var l1 = Intl.Locale("de", { calendar: "coptic" });
l1.locale //=> de
l1.calendar //=> coptic
l1.numberingSystem //=> null
l1.toString() //=> de-u-ca-coptic

var l2 = l1.maximize();
l2.locale //=> de
l2.calendar //=> coptic
l2.numberingSystem //=> latn
l2.toString() => de-u-ca-coptic-nu-latn-etc

l2.minimize(); //=> same as l1

Intl.Locale("de-u-ca-coptic") //=> also the same as l1
Intl.Locale("de-u-ca-buddhist", { calendar: "coptic" }) //=> also the same as l1
```

If so, that's a totally great API.

**Comment by zbraniecki** [comment]
You're reading it correctly!

Thanks for the feedback. Glad to hear it fits your needs! If you have more time, feel free to scan through the issues as we're trying to iron out remaining details.

Also, other active proposals may be interesting for your use case:
 - https://github.com/tc39/proposals/blob/master/ecma402/README.md
 - https://github.com/tc39/proposals/blob/master/ecma402/stage-0-proposals.md

(esp. Shane's NumberFormat revision is a pretty major rewrite :))

**Comment by icambron** [comment]
@zbraniecki I looked through the issues and most of them seemed to be about the details of the spec, not exactly the supported features, so I don't think I have much to add besides cheerleading.

**Comment by icambron** [comment]
@littledan Yeah, I'd be in down for that.
