### ISSUE TITLE
Luxon version 1.2 does not work on IE

### ISSUE THREAD

**Issue by dmngu9** [moment/luxon#337]
Hi, I use babel-polyfill 6.26.0 with Luxon 1.2. All browsers works fine except IE 11. Datetime is always returned as Invalid DateTime. 

No error or anything. I am not sure why

**Comment by dmngu9** [comment]
It worked if I upgrade to latest version of Luxon which is 1.4 but this will pull babel 7 as dependency. How babel polyfill 7 make it works? Thoughts?

**Comment by icambron** [comment]
Which build are you using?

**Comment by dmngu9** [comment]
I dont get your questions

**Comment by dmngu9** [comment]
i can make a demo repo to show the issue if you want. When you are saying about the build, what are you referring to? So sorry, i dont understand your question

**Comment by icambron** [comment]
There are different builds of Luxon, like the different files available here: http://moment.github.io/luxon/. Which one are you using?

**Comment by dmngu9** [comment]
@icambron ES6 and node please. I noticed on server side rendering it works fine. But when React kicks in , luxon Date time return Invalid DAte

**Comment by icambron** [comment]
Well, yeah, the ES6 build doesn't pull in Babel as a dependency, so if you use that one, you need to polyfill it yourself. If you have a more specific issue, you'll need to provide more specific information.
