### ISSUE TITLE
Luxon does not format (DATE_MED) localized date in Safari

### ISSUE THREAD

**Issue by grzegorztomasiak** [moment/luxon#338]
Given `DateTime.local().setLocale('pl').toLocaleString(DateTime.DATE_MED)`  returns e.g. `03.10.2018` instead of `3 paź 2018`.

The problem occurs only in Safari (I am using version 11.1.1) and only with `DATE_MED`.
Other formatters works fine. Probably a bug?

**Comment by grzegorztomasiak** [comment]
hello? anyone there?

**Comment by icambron** [comment]
I finally got a chance to test this in Safari. It is a bug in Safari 11. You can see it without Luxon like this:

```js
new Intl.DateTimeFormat("pl", DateTime.DATE_MED).format() //=> "19.01.2019"
```

It does not appear to be fixed in Safari 12 either. I think we'll need to file a bug with Apple.
