### ISSUE TITLE
Question: setting an fixed offset

### ISSUE THREAD

**Issue by babeal** [moment/luxon#339]
Our application is sensitive to the time of the server so we apply an offset to the creation of DateTime.now with moment by overriding the now method().  Can I do the same thing with Settings.now()?  Is there anything that I should know.

**Comment by icambron** [comment]
You mean that there's skew between your client and server, but you know that skew and want to build it into your DateTime creation? If so, yes, I think `Settings.now` fits the bill nicely.

**Comment by babeal** [comment]
@icambron exactly.  Thanks for the quick response

**Comment by icambron** [comment]
I suspect that will work well, but let me know if that does anything unexpected
