### ISSUE TITLE
Interval.fromISO does not allow a duration relative to a start or end.

### ISSUE THREAD

**Issue by mastermatt** [moment/luxon#340]
[ISO 8601 allows for intervals to be defined](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) as 
 - `<start>/<end>`
 - `<start>/<duration>`
 - `<duration>/<end>`

But only `<start>/<end>` is currently supported.

```js
const i = luxon.Interval.fromISO("2007-03-01T13:00:00Z/P1Y2M10DT2H30M")
i.isValid // false
```

If there is interest in adding this support I'd be happy to open a PR updating this block to check if both `DateTime`s are valid and calling `Duartion.fromISO` then combining.
https://github.com/moment/luxon/blob/747d32719042d7ff05716e83372a902b41e229b6/src/interval.js#L109-L111

It's unclear if this goes against [# 3 of the design philosophy](https://github.com/moment/luxon/blob/master/contributing.md), my code could do the work of splitting on `/` and call `DateTime`, `Duration`, and `Interval.fromDateTimes` manually. But my understanding of ISO 8601 is that a value like `2007-03-01T13:00:00Z/P1Y2M10DT2H30M` is a single interval value and in that case having this library do the work seems reasonable.

**Comment by icambron** [comment]
I agree it's a reasonable addition, because it more fully supports the ISO features. So sure, I'll take a pull request.
