### ISSUE TITLE
Cross-context usage support

### ISSUE THREAD

**Issue by NirpE** [moment/luxon#343]
Is there a way to use luxon between JS contexts?

In my setup I have React web-application and JS library using luxon and application passes `DateTime` and `Duration` to function which is exported by library and uses `Interval.after` with those arguments.

This function eventually doesn't work due to `instanceof` checks performed by luxon in `friendlyDateTime` and `friendlyDuration ` functions.

Running app locally and using `yarn link` for linking the local library.

**Comment by NirpE** [comment]
Running node server which uses the same library seems to work. Could this be only browser application related or something totally different?

**Comment by icambron** [comment]
Yes, this is a fair request. I will think about it a bit.

**Comment by icambron** [comment]
@nirpe, I pulled in your changes into #359 and then grafted some of my own onto them. Can you fill out the CLA there?

**Comment by NirpE** [comment]
@icambron filled the CLA
