### ISSUE TITLE
Proposal for dayOf .. API extension

### ISSUE THREAD

**Issue by zlatinejc** [moment/luxon#347]
I would like to propose for the date object's API to include additional day info:
- dayOfYear
- dayOfQuarter
- dayOfHalfYear

These API s could be presented as a result of aggregated data:

_dayOfYear_ = ```this.weekNumber * 7 - (7-this.weekday)```

**Comment by icambron** [comment]
Hi. My thoughts:

 * `dayOfYear` exists and is called `ordinal`. Your example is really `dayOfWeekYear`
 * `dayOfQuarter` sounds OK, but also so easy to implement in userspace that I don't think it needs to be in the library (see below)
 * `dayOfHalfYear` doesn't seem very useful?

```js
// untested, but something like:
DateTime.prototype.dayOfQuarter = () => this.ordinal - this.startOf("quarter").ordinal + 1;
```

I think if you can persuade me that `dayOfQuarter` and `dayOfHalfYear` are widely used concepts, I will reopen this ticket add it. But I suspect they aren't.

**Comment by ericmorand** [comment]
I have the feeling most of these functions fall under the #3 act of the Luxon's design philosophy:

> Luxon shouldn't contain simple conveniences that bloat the library to save callers a couple lines of code. Write those lines in your own code.

@zlatinejc, what could be super cool is an npm lib that contains Luxon's helpers like the one you propose. We could all benefit from them - and I have some too like a formatter function fully compliant with PHP date formatting that could fit that helpers library perfectly.

**Comment by zlatinejc** [comment]
@ericmorand I completely agree, this is what I was looking for.
