### ISSUE TITLE
force offset

### ISSUE THREAD

**Issue by henriquecustodia** [moment/luxon#350]
Hey there.

I need to force a offset for all datetimes in my app, because my country has updated when DST starts and some OS/browsers were not updated, causing wrong datetimes. 

Looking the docs I don't found anyway to set (force) a offset specific, like `-3` . I think [`Settings.now`](https://moment.github.io/luxon/docs/class/src/settings.js~Settings.html#static-set-now) can help me to set an offset, but I'm not sure. 

Can somebody help me? 

Thanks!

**Comment by icambron** [comment]
If you're doing this quick and dirty, you can do this:

```js
var inYourForcedZone = dt.setZone("UTC-3")
```

Of course, you'll need to know when to do it, so a more elegant way is to just implement a custom zone. You just need to implement this [interface](https://github.com/moment/luxon/blob/master/src/zone.js). You can pass instances of your custom zone to `setZone()`. Most of the implementation is trivial, and you can cop most of it from [this implementation](https://github.com/moment/luxon/blob/master/src/zones/fixedOffsetZone.js). You just need to change the `offset(ts)` implementation to obey your rules, namely that sometimes the offset is `-3*60` and sometimes it's something else.

You definitely do not want to mess with Settings.now; that will give you an actually different time, which you don't want.

I hope that helps!
