### ISSUE TITLE
Performance of toLocaleString is slow, due to lack of caching.

### ISSUE THREAD

**Issue by thomas-darling** [moment/luxon#352]
#### Problem
The performance cost of `toLocaleString` becomes a significant bottleneck when formatting hundreds of dates, e.g. for presentation in a list or grid view. In our case, which is a react app that continously polls for data, this is resulting in significant jank when scrolling.

#### Root cause
Profiling the code, the root cause seem to be that Luxon instantiates a new `Intl.DateTimeFormat` every time `toLocaleString` is called, which has a relatively high cost.

#### Suggested solution
Since there will only ever be a very limited number of formats, those format instances should be cached after creation. This reduces the runtime of `toLocaleString` cost by a factor of 10.

**Comment by thomas-darling** [comment]
While not directly related, any performance improvements to `fromISO` would also be very welcome, for the same reasons. I've looked into that too, but didn't see any obvious ways to improve that one...

**Comment by icambron** [comment]
Yeah, the thing to cache here is the Locale object, which wraps the DateTimeFormat object.

**Comment by pandameister** [comment]
@icambron we ran into this at salesforce which resulted in a 1000x performance degradation for non en-US locales, and had to do quick caching fix on our version of the library.

Caching the Intl api calls as done below should provide a quick fix this issue. Has that been considered?

https://github.com/yahoo/intl-format-cache

**Comment by icambron** [comment]
@pandameister Funny you mention that; I'm in the middle of implementing this. I don't want to add any dependencies though, so not such a quick fix.

**Comment by icambron** [comment]
See bb77d5e. I'll release this soon.

**Comment by icambron** [comment]
Released in 1.4.6. I got an 85x speedup on `toLocaleString()`

**Comment by pandameister** [comment]
awesome, thanks a bunch!
