### ISSUE TITLE
Luxon latest release bug

### ISSUE THREAD

**Issue by korrio** [moment/luxon#354]
I've been using luxon on github repo for awhile with no problem.
https://moment.github.io/luxon/global/luxon.min.js

Since 3-4 days ago, it's no longer work with this sample code

`var start = luxon.DateTime.fromISO('2018-12-25T01:00:00.000z', {zone: 'utc+7'}).toLocaleString(luxon.DateTime.TIME_SIMPLE); `

Result:
`Invalid Datetime`

Please check.

**Comment by icambron** [comment]
The "Z" has to be capitalized, as I understand the ISO 8601 spec. If that's not true, we can fix the parser.
