### ISSUE TITLE
Invalid input following A quick Tour

### ISSUE THREAD

**Issue by mnelson4** [moment/luxon#355]
I'm just getting started with Luxon and am getting an error.
I just do
```
var d = luxon.DateTime.fromISO("2017-05-15");
```

(like in the "A Quick Tour" https://moment.github.io/luxon/docs/manual/tour.html)
and `d.invalid` is `invalid input`. :weary: It sure looks valid to me!

Maybe this is a hint: I'm getting another error too, when I do

```
luxon.DateTime.local().toString();
```

Instead of getting the current time nicely printed out, I see `shortTshort`. `luxon.DateTime.local().toISO()` returns the same thing too.  

Any idea where I'm going wrong? I'm just including the script from https://moment.github.io/luxon/global/luxon.min.js

**Comment by mnelson4** [comment]
I can work around it by doing 

```
luxon.DateTime.local().toLocaleString()
```

prints out the date ok, like `"10/24/2018"`

**Comment by mnelson4** [comment]
this also creates a valid `luxon.DateTime`:

```
luxon.DateTime.fromJSDate(new Date("2018-01-01"));
```

**Comment by icambron** [comment]
See #357 - looks like there's a bad build up. So nothing you're doing, just bad timing. In the meantime, if you use the non-minified version, you should be ok.

Let's track the issue over at #357.

**Comment by Clearmist** [comment]
This problem has popped up again in version 3.4.4. I tested the full version.

## Works

```javascript
luxon.DateTime.fromJSDate(Date.now());
```

## Not working

These commands result in the invalid reason "invalid input".

```javascript
luxon.DateTime.now();
luxon.DateTime.local();
```
