### ISSUE TITLE
same date via fromFormat gives different UTC outputs

### ISSUE THREAD

**Issue by sgilligan** [moment/luxon#356]
Hi,

I'm finding the same date read using fromFormat gives different UTC  results depending on whether my local machine is in DST or not.

Steps to reproduce:

1. Set your pc/mac system date to 25/10/2018, Australia/Sydney
2. open javascript console from https://moment.github.io/luxon/
3. observe `luxon.DateTime.fromFormat('01-04-2018 2:12','dd-MM-yyyy H:mm',{zone:'Australia/Sydney'}).toISO()` generates `2018-04-01T02:12:00.000+11:00`
4. set your pc/mac system date to 25/9/2018, Australia/Sydney
5. observe `luxon.DateTime.fromFormat('01-04-2018 2:12','dd-MM-yyyy H:mm',{zone:'Australia/Sydney'}).toISO()` generates `2018-04-01T02:12:00.000+10:00`

Notice the UTC date/time is different depending on the local time of the machine (which in our case is with and without DST).

Repeat the same process from https://momentjs.com/ with `moment.tz('2018-04-01 02:12', 'Australia/Sydney').format()` and observe the UTC generated is always `2018-04-01T02:12:00+11:00`

Is this expected?

**Comment by icambron** [comment]
Yes, this is expected. See the section of the docs about ambiguous times here: https://moment.github.io/luxon/docs/manual/zones.html#ambiguous-times
