### ISSUE TITLE
Do we have fromNow like we have in luxon?

### ISSUE THREAD

**Issue by pnaika** [moment/luxon#364]
fromNow in momentJS is really cool and powerful, many developers use it in their application. Is there anything equivalent in Luxon to use, where we get sentences like, "5 minutes ago", "3 hours ago"

**Comment by icambron** [comment]
No, we can't, basically because Luxon doesn't have access to internationalized strings for this. See here: https://moment.github.io/luxon/docs/manual/moment.html#humanization

**Comment by taylorgoolsby** [comment]
If you're already locked into using Luxon: https://www.npmjs.com/package/from-now

**Comment by icambron** [comment]
@taylorgoolsby I'm editing your comment to make it irritate me less.

**Comment by taylorgoolsby** [comment]
@icambron Oh sorry, that was not my intention. I was thinking in terms of people who are trying out luxon versus those who aren't.

**Comment by sgywzy** [comment]
Currently this is the top result for _luxon fromNow()_ and it contains outdated information.
Many migrating from moment.js which got deprecated.
I suggest everyone with the same problem to read the [migration guide from moment.js to luxon].(https://moment.github.io/luxon/docs/manual/moment.html)

For the lazy people out there, luxon uses `.toRelative()`

**Comment by adamreisnz** [comment]
Broken link in post above. New link: https://moment.github.io/luxon/api-docs/index.html#datetimetorelative
