### ISSUE TITLE
Math functions (plus, minus) are currently broken for object arguments in 1.6.1

### ISSUE THREAD

**Issue by cheapsteak** [moment/luxon#365]
Typing this in the console in the documentation page: 
```
luxon.DateTime.local().plus({ days: 1 })
```

Results in: 
```
duration.js:757 Uncaught InvalidArgumentError: Unknown duration argument [object Object] of type object
    at friendlyDuration (https://moment.github.io/luxon/global/luxon.js:3625:13)
    at DateTime.plus (https://moment.github.io/luxon/global/luxon.js:6212:17)
    at <anonymous>:1:24
```

![image](https://user-images.githubusercontent.com/743976/48298376-4ed7c100-e471-11e8-95f0-372a88fdcf12.png)

The same error is thrown when using in node with 1.6.1. 
1.6.0 doesn't have this problem

**Comment by icambron** [comment]
Gah, I royally screwed that one up. Just pushed 1.6.2 with a fix.
