### ISSUE TITLE
"the zone "US/Alaska" is not supported"

### ISSUE THREAD

**Issue by klase** [moment/luxon#367]
```
DateTime.local().setZone('America/Alaska');
```
gives the error "the zone "US/Alaska" is not supported".

Is this due to US/Alaska being deprecated?

**Comment by icambron** [comment]
That's up to your browser. You can see Chrome not recognizing it like this:

```js
new Intl.DateTimeFormat("en", { timeZone: "America/Alaska", hour: "numeric"}).format()
```

I've never heard of "America/Alaska", but "America/Anchorage" works fine.
