### ISSUE TITLE
Docs: lack of punctuation due to ESDoc conversion

### ISSUE THREAD

**Issue by dandv** [moment/luxon#381]
At https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromFormat, one can see the lack of punctuation in

> Create a DateTime from an input string and format string Defaults to en-US if no locale has been specified, regardless of the system's locale

In [the source](https://moment.github.io/luxon/docs/file/src/datetime.js.html#lineNumber732), the comments are separated by a newline, but that doesn't translate well to the doc site.

**Comment by icambron** [comment]
I'd accepted a pull request adding some punctuation.

**Comment by icambron** [comment]
Fixed in f32c127b0d494d91b1dd30832e6a49880a8473d1
