### ISSUE TITLE
Intl. RelativeTimeFormat API Support

### ISSUE THREAD

**Issue by mrgrauel** [moment/luxon#385]
Hey 👋 Guys,

I'd like to ask if there are currently any news regarding the relative time format? Chrome v71 shipped support for the [Intl.RelativeTimeFormat API Specification](https://github.com/tc39/proposal-intl-relative-time). It's interesting to know if you already plan to ship support in an upcoming version or wait for better support in the browsers.

Regards,
Andreas

**Comment by icambron** [comment]
There's no reason to wait, it's just that I haven't gotten to it. I'd normally ask for a pull request, bit I can already hear myself being frustratingly picky about naming and implementaftion.

**Comment by mrgrauel** [comment]
I thought about implementing it, but during the Christmas season I won't have any time. I am very sorry for the lazy approach 😢 am looking forward to see it coming.

**Comment by icambron** [comment]
Oh, I guess there is one reason to wait, which is that practically speaking, Node support makes development and testing much easier

**Comment by icambron** [comment]
For the curious, here is the branch where I'm slowly working on this: https://github.com/moment/luxon/tree/relative-time-formatting

**Comment by icambron** [comment]
Work in progress: https://github.com/moment/luxon/pull/390

**Comment by icambron** [comment]
Implemented in #390
