### ISSUE TITLE
Interval.difference(...) does not return the expected result

### ISSUE THREAD

**Issue by mfruhner** [moment/luxon#388]
Hello everyone,
I was in need of finding a fitting time interval inside of a bigger interval with some blocking intervals in between. I found this library to be useful before and found that it contains just the correct function for this use case.

But as I implemented it, it does not give the expected result. More specific, it always returns an array of size 1 containing the interval the function is called on. I then looked at the source and copied it into my code. Strangely, using this code locally gives exactly the expected result.

I did some testing with jest and found, that manually applying xor, map and filter works, while calling '.difference' on my interval does not:

    const minDate = DateTime.fromISO('2018-12-24T09:00:00.000');
    const maxDate = DateTime.fromISO('2018-12-31T18:00:00.000');

    const blocker1Start = minDate.plus({ hours: 1 });
    const blocker1End = blocker1Start.plus({ hours: 3 });
    const blocker2Start = blocker1End.plus({ hours: 8 });
    const blocker2End = blocker2Start.plus({ hours: 11 });
    const blocker3Start = blocker2End.minus({ hours: 1 });
    const blocker3End = blocker3Start.plus({ hours: 2 });

    const blockedTimeIntervals = [
      Interval.fromDateTimes(blocker1Start, blocker1End),
      Interval.fromDateTimes(blocker2Start, blocker2End),
      Interval.fromDateTimes(blocker3Start, blocker3End),
    ];

    const fullInterval = Interval.fromDateTimes(minDate, maxDate);

    // == exactly the built in diff function.
    // this somehow works, built in does not.
    const xors = Interval.xor([fullInterval].concat(blockedTimeIntervals));
    const free = xors.map(i => fullInterval.intersection(i)).filter(i => i && !i.isEmpty());

    expect(free.length).toBe(3);
    expect(free[0].start).toEqual(minDate);
    expect(free[0].end).toEqual(blocker1Start);
    expect(free[1].start).toEqual(blocker1End);
    expect(free[1].end).toEqual(blocker2Start);
    expect(free[2].start).toEqual(blocker3End);
    expect(free[2].end).toEqual(defaultMaxDate); // everything fine

    // but then:
    const diff = fullInterval.difference(blockedTimeIntervals);

    expect(diff.length).toBe(3); // Expected: 3, Received: 1

I am looking forward to a discussion,
Thanks!

**Comment by icambron** [comment]
```js
fullInterval.difference(blockedTimeIntervals)
```

should be

```js
fullInterval.difference(...blockedTimeIntervals)
````

because the method expects each interval as its own arg.

I went back and forth on whether to make that varargs or just take an array. I'm not sure why I chose varargs and certainly it's awkward for this use case.
