### ISSUE TITLE
How to differentiate date and time? 

### ISSUE THREAD

**Issue by mz4577** [moment/luxon#389]
Hi I wonder if there's a way to differentiate date-only type (i.e. doesn't contain time component) from date time (has both date and time)? 

This comes down to be important in what I'm implementing. Currently from what I understand Luxon only provides DateTime, which is hard to distinguish between the two once the class is constructed (although the string I provide could be different initially). 

I could implement a sub-class to add these fields (but that mess up the type as well since I'm using typescript and the static factory methods all return the initial type not the new one)

**Comment by icambron** [comment]
Luxon doesn’t have any support for that but it’s easy to do through composition: create a Date class that wraps DateTime and exposes the subset of methods you need. You can decide how pure of abstraction you need to provide to your application (ie how much work you want to do to make your wrapper full featured and pure)

I’ve considered many times adding a date class to Luxon but have decided it just isn’t worth the complexity
