### ISSUE TITLE
Time/Date Diff is Inaccurate.

### ISSUE THREAD

**Issue by marbuser** [moment/luxon#393]
So we are using ISO Strings to log timestamps in our DB for various different things, and one thing we need to do is take the local server date/time, and then a date/time from our database and differentiate it and get the time between them.

So we did something like this;
```
const getTimeRemaining = enddate => {
  const end = DateTime.fromISO(enddate);
  const start = DateTime.local();
  const finalDate = end.diff(start, ['days', 'hours']).toObject();

  if (finalDate.days !== 0) {
    return `${finalDate.days} Days Left`;
  }
  return `${finalDate.hours} Hours Left`;
};
```

Now this is functional, but the time returned will always be 1 hour ahead.
For example, our server time is; `Dec 29 03:55:23`
The end date in our database is; `2018-12-29T03:50:00.000Z`.

So this should now be returning a negative since the duration has gone past the end date, but for some odd reason we instead get this `0.9165527777777778 Hours Left`, so it's adding an additional hour for no reason. (That I can see at least).

If we swap the diff around so it's `const finalDate = start.diff(end, ['days', 'hours']).toObject();`

This fixes the issue, but then obviously all values are negative. I can just strip the negative value from the strings I suppose, but this doesn't feel like the best way I should be doing things.

Hopefully you guys can let me know what is going wrong here.

**Comment by icambron** [comment]
I'm not a able to reproduce this. I used an enddate that was a few minutes ago and got `-0.09445222222222223 Hours Left`, which seems right.

When you say it's `Dec 29 03:55:23`, is that the *local* time on the server? What zone is the server set to using?

**Comment by maggiepint** [comment]
Hi,

If I were guessing, I would say you are somewhere just east of GMT - perhaps Amsterdam, Berlin, Paris or Lagos, where there is a 1 hour offset from UTC right now :-). The problem you have here is that your database has a UTC date (as designated by the `Z` at the end of the value), but you are comparing it to a local date. Having switched my computer to Berlin time for fun, I can break your problem down a bit.

Your end date is 2018-12-29T03:50:00.000Z, but `DateTime.fromISO()` will change dates it parses from UTC to local by default. Thus, upon parse you get this:
```
luxon.DateTime.fromISO('2018-12-29T03:50:00.000Z').toString()
"2018-12-29T04:50:00.000+01:00"
```
If that date really is in UTC, then once converted to local time, it is in fact .91 hours AHEAD of your start time, which is presumably also in local time - as you are using `.local()` to generate it.

**Comment by marbuser** [comment]
> I'm not a able to reproduce this. I used an enddate that was a few minutes ago and got `-0.09445222222222223 Hours Left`, which seems right.
> 
> When you say it's `Dec 29 03:55:23`, is that the _local_ time on the server? What zone is the server set to?

Hey @icambron Uh it's just local but if I set a zone it also is still broken. The server is Paris.

> Hi,
> 
> If I were guessing, I would say you are somewhere just east of GMT - perhaps Amsterdam, Berlin, Paris or Lagos, where there is a 1 hour offset from UTC right now :-). The problem you have here is that your database has a UTC date (as designated by the `Z` at the end of the value), but you are comparing it to a local date. Having switched my computer to Berlin time for fun, I can break your problem down a bit.
> 
> Your end date is 2018-12-29T03:50:00.000Z, but `DateTime.fromISO()` will change dates it parses from UTC to local by default. Thus, upon parse you get this:
> 
> ```
> luxon.DateTime.fromISO('2018-12-29T03:50:00.000Z').toString()
> "2018-12-29T04:50:00.000+01:00"
> ```
> If that date really is in UTC, then once converted to local time, it is in fact .91 hours AHEAD of your start time, which is presumably also in local time - as you are using `.local()` to generate it.

Hey @maggiepint 
Yeah our server is located in Paris. So what would be the best way to fix this then? I'm not too great with timezones and such so this is actually pretty confusing. :/

If we just no longer use UTC, will that fix the issue?

**Comment by icambron** [comment]
@marbuser there are two possibilities:

 1. The time in the database is right. In this case, there's no bug! 2018-12-29T03:50:00.000Z (which unambiguously means 3:50 UTC) is 2:50 Paris time, so everything is working as expected. It *really is* 0.94 hours past due. You are just misunderstanding the time in the database, assuming it's expressing a Paris time when it's expressing a UTC time.
 2. The time in the database is wrong, and when it says 3:50 UTC it really means 3:50 Paris time because the code for inserting that time does the wrong thing, telling the DB that the 3:50 local time is actually 3:50 UTC. In that case, you have two choices: a) fix the database code so that it stores the right underlying time (this is definitely the way to go!), or b) hack off the Z from the string you get from the databsae before handing it to `fromISO` (this is a hack but will cause Luxon to interpret the database time as a local time).

> If we just no longer use UTC, will that fix the issue?

Do the opposite: always use UTC. Having servers configured in local time will just confuse you.

**Comment by marbuser** [comment]
@icambron So what should I be storing the date as in the database? Do I just use the .local() to store it as Paris (server) time?

**Comment by marbuser** [comment]
> For most use cases, storing the date in UTC is the right thing to do. I'm suggesting you set your server to UTC too. But more immediately, I'll just repeat that if the database time is right, your code is working as expected.

Perhaps working as intended for the package but definitely not intended in my use-case.
I'm currently testing storing the values with the offset like so; `2018-12-30T16:00:27.425+01:00`

Hopefully this fixes it.
