### ISSUE TITLE
.plus() over DST has varying results depending on client machine

### ISSUE THREAD

**Issue by ricardobanegas** [moment/luxon#403]
Stumbled on this while migrating from `date-fns` and writing unit tests.

### Description

Operations with `.plus()` gives different results over DST depending on client machine timezone settings

### Specifics

* luxon `"^1.9.0"`
* `America/Los_Angeles` DST occurs on **2019-03-10T02:00:00** https://www.timeanddate.com/time/change/usa/los-angeles
* Add 1 hour from 1 AM should result in 3 AM (works when client is on LA-time)
* Add 1 hour from 1 AM results in 2 AM (doesn't work when client is on Stockholm-time)

### Code

```javascript
// Default timezone is UTC
/**
 * Add hours to date
 * @param {*} date 
 * @param {*} minutes 
 */
function hoursAdd (date, hours, format = config.TIME.FORMAT.RAW_DATE) {
    return toDateTime(date)
        .plus({ hours: hours })
        .toFormat(format)
}

/**
 * Convert local time to ISO-valid format 
 * @param {*} date 
 */
function toDateTime (date) {
    return DateTime
        .fromSQL(date, { tz })
        .setLocale('en-US')
}

/**
 * Timezone in IANA format
 * @param {*} timezone 
 */
function setTimezone (timezone) {
    tz = new IANAZone(timezone)
    return timezone
}
```

### Unit tests

```javascript
describe('should handle timezones properly', () => {
    it('should handle DST in Los Angeles 2019', () => {
        setTimezone('America/Los_Angeles')

        const actual = hoursAdd('2019-03-10 01:00:00', 1)
        expect(actual).to.equal('2019-03-10 03:00:00')
    })
})
```

### Unit tests running from Europe/Stockholm on Mac OS 10.14.2

```
  48 passing (2s)
  1 failing

  1) should handle timezones properly
       should handle DST in Los Angeles 2019:

      AssertionError: expected '2019-03-10 02:00:00' to equal '2019-03-10 03:00:00'
      + expected - actual

      -2019-03-10 02:00:00
      +2019-03-10 03:00:00
```

### Unit tests running from USA/Los Angeles on Mac OS 10.14.2

```
  should handle timezones properly
    ✓ should handle DST in Los Angeles 2019
```

Ideas?

Thanks in advance & for an awesome library! 👍

**Comment by icambron** [comment]
This works for me:

```js
> DateTime.fromSQL("2019-03-10 01:00:00", { zone: "America/Los_Angeles" }).plus({ hours: 1 }).toFormat("yyyy-MM-dd HH:mm:ss") // (I assume that's your format)
'2019-03-10 03:00:00'
```

I suspect the problem is here: `{ tz }`; the key in Luxon is `zone`. So Luxon is ignoring your zone setting and using the local zone. That's consistent with it working in LA but not Sweden, which presumably doesn't have a DST then.

**Comment by ricardobanegas** [comment]
Ah, you're absolutely right. 

I was looking at this PR & comment to optimise speed, and there zone wasn't specified for the options object.

https://github.com/moment/luxon/issues/89#issuecomment-378826414

Hmm, does that mean that this test in the #89 is invalid since it was the same mistake as me?

**Comment by icambron** [comment]
@ricardobanegas I am confused. It looks like it's specified correctly there?

**Comment by ricardobanegas** [comment]
See `iANAZone()`

```javascript
function stringZone() {
  DateTime.fromFormat('1982/05/25 09:10:11.445', 'yyyy/MM/dd HH:mm:ss.SSS', {
    zone: 'America/Los_Angeles'
  });
}

function iANAZone() {
  DateTime.fromFormat('1982/05/25 09:10:11.445', 'yyyy/MM/dd HH:mm:ss.SSS', {
    zone
  });
}
```

The same mistake can be found in his speed test repository: 
https://github.com/woozyking/test-datetime/blob/master/handler.js

Which means test results are not valid, right?

**Comment by icambron** [comment]
`zone` is right though. `tz` is wrong

**Comment by woozyking** [comment]
Just saw this. Any thing to correct from the test repo?

**Comment by icambron** [comment]
@woozyking not as far as I can tell

**Comment by woozyking** [comment]
👍 cool thx.
