### ISSUE TITLE
[Question]: How to update to change timezone information.

### ISSUE THREAD

**Issue by grapgrapMMT** [moment/luxon#406]
Hi, luxon.
I have question, I have to control timezone with luxon.
I want to know "How to update timezone in luxon.".
If timezone change suddenly, how can i do for luxon? have to update luxon? or have to be changed automately?

**Comment by icambron** [comment]
Luxon uses your browser's native capabilities to provide timezone info. So if a timezone is changed, it's up to the user's OS or browser to update it.
