### ISSUE TITLE
Documentation rendering bug

### ISSUE THREAD

**Issue by benmccann** [moment/luxon#411]
On https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html the description of `fromMillis` is truncated the first place it appears on the page. If you click that link to take you further down then you can see the whole description

**Comment by icambron** [comment]
Yes, this is a bug in ESDoc, as far as I can tell.

**Comment by WretchedDade** [comment]
Hi @icambron, looks like the the reason that message and other messages get truncated is because of the 'i.e.'. When playing around with the text I found that the summary messages gets truncated after the second period. We could resolve this by removing the use of 'i.e.', thoughts?

**Comment by icambron** [comment]
Yeah, that seems reasonable. Could be changed from "i.e." to "meaning"

**Comment by WretchedDade** [comment]
@icambron, I opened a PR where I replaced i.e. with meaning. I went ahead and made the change in overall rather than just the summary of fromMillis.
