### ISSUE TITLE
Date not formatting with .toLocaleString()

### ISSUE THREAD

**Issue by toymachiner62** [moment/luxon#412]
This code is not formatting `data.end` as it should.

```js
const { DateTime } = require('luxon')

const data = {}
const end = DateTime.local().toISO()
const start = DateTime.fromISO(end).minus({ years: 10 })
data.end = end.toLocaleString()
data.start = start.toLocaleString()
console.log('data = ', data)
```
produces
```
data =  { end: '2019-01-21T15:23:30.615-07:00', start: '1/21/2009' }
```

Is this a bug or why is `data.end` not formatted?

I'm on version 1.10.0 of luxon

**Comment by icambron** [comment]
Not a bug. Your `end` var is a string, which you obtained by calling `toISO` on a DateTime. The localeString of a string is just that string, so you end up with your ISO string. Remove `toISO` and your code should work
