### ISSUE TITLE
Why does luxon use Intl.DateTimeForamt ?

### ISSUE THREAD

**Issue by moonformeli** [moment/luxon#416]
* **describe the issue**
I was using ```moment-timezone``` to obtain global timezone in which I live, but for some reason, I switched the library to ```luxon``` and used like this.

```javascript
import * as luxon from 'luxon';

const getTime = time => {
  return time ? luxon.DateTime.fromISO(time, {zone: 'Asia/Seoul'}) : luxon.DateTime.local().setZone('Asia/Seoul');
}
```
and I couldn't get the result from this function in iOS 8 since ```Intl.DateTimeFormat```, which luxon uses, does not support the some old versions of iOS lower than 8. 

* **describe how you resolve it**
So I had to use ```moment-timezone``` again, I had no choice because my application has to support the old browsers too.
So the changed code is below:

```javascript
import * as moment from 'moment-timezone';

const getTime = time => {
  time ? moment(time).tz('Asia/Seoul') : moment.tz('Asia/Seoul');
}
```

* **conclusion**
Could you tell me why luxon takes ```Intl.DateTimeFormat``` which does not support many browers specs? I wonder its development history.
Thank you for your time 👍

**Comment by icambron** [comment]
Luxon uses Intl.DateTimeFormat so that it doesn't have to include its own timezone data files or locale files. If you need to support zones on old browsers, you'll need to use a different library.
