### ISSUE TITLE
add .js extension to import statements

### ISSUE THREAD

**Issue by m0ose** [moment/luxon#417]
I get an error on certain webservers when trying to import luxon using the es6 import statement. Some webservers are configured to add the `.js` file extension but It is the exception. 
```GET ../node_modules/luxon/src/datetime net::ERR_ABORTED 404 (Not Found)```
Seriously, does dropping the extension really save that much space or make the code more readable?
I dont mind making a pull request if it is ok.

**Comment by icambron** [comment]
Fixed in #419
