### ISSUE TITLE
toRelative language in spanish

### ISSUE THREAD

**Issue by pablocarreraest** [moment/luxon#426]
Hi guys, first of all this is an amazing work. Thanks for it.

Just I found a bug in 

> toRelative({locale: 'es'})

it seems that there is no support for spanish at all.

I try to:

```typescript
const release = DateTime
    .fromFormat(value.releaseDate.substring(0, 10), 'yyyy-LL-dd')
    .setLocale('es')
    .setZone('America/Guayaquil');

const res = `${release.toRelative()} para el gran estreno`;
// OR
const res = `${release.toRelative({locale: 'es'})} para el gran estreno`;
```

I get: 

> "IN 2 MONTHS"

**Comment by icambron** [comment]
I should probably put a bigger disclaimer on the docs for this. It currently says this:

>  Can only internationalize if your platform supports Intl.RelativeDateFormat

But what I should add is:

> And your platform probably doesn't yet. As of right now, the feature is brand new and Intl only works in Chrome.

I will make that change.

**Comment by moiseshp** [comment]
```js
import { Settings, DateTime } from 'luxon'

// Global
Settings.defaultLocale = 'es-ES'

// Or
const date = '2020-01-01T12:00:00'
DateTime.fromISO(date).setLocale('es-ES').toLocaleString(DateTime.DATETIME_FULL) // 01 de ene de 2020 12:00 CET

```
