### ISSUE TITLE
relativeTo output doesn't make sense when calculated between 2 dates that are not today

### ISSUE THREAD

**Issue by rsolomon** [moment/luxon#429]
Say you call `relativeTo` like so:

```
DateTime.fromISO(timeStamp).relativeTo({ base: relativeFrom });
```

where `timeStamp` is 8 months ago and `relativeFrom` is 2 years ago. It will say something like:

```
in 14 months
```

or, conversely,

```
14 months ago
```

Both make sense if we were calculating relative to *today*, but no sense at all when calculating between 2 dates. Take, for example, calculating the time between when 2 users signed up. You would say something like, "user x signed up 14 months after user y." `moment.from` allowed a `short` option which would output `14 months`. It would be great if there was some flag that removed the `in` and `ago` and just returned the humanized time in between. `style: 'short'` only abbreviates `months` to `mo.`, which doesn't cut it here.

**Comment by icambron** [comment]
This is a totally fair criticism of it's behavior, but that's just not how the relative time tools we have from the browser work. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat There just isn't a way to do it.

The way to think of `a.toRelative({ base: b})` is not as a `a.diff(b).toFormat()` but instead as "pretend b is now and give me the relative time".
