### ISSUE TITLE
Math.sign and Math.trunc

### ISSUE THREAD

**Issue by rinu** [moment/luxon#438]
Using `Math.sign` or `Math.trunc` on old versions of Chrome will cause an error. Please consider replacing usage of these functions in your source code with tiny ployfills by Mozilla.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

Old versions of Chrome are unfortunately still in use on older Android phones which are not getting updates.

**Comment by rinu** [comment]
I see `Math.sign` is already fixed by https://github.com/moment/luxon/pull/436
`Math.trunc` has the exact same issue, fix is probably the same as well.

**Comment by icambron** [comment]
Todo:

 - [ ] Make sure the docs reflect all the polyfills needed
 - [ ] Make sure the polyfilled build includes them
