### ISSUE TITLE
isDateTime should handle null/undefined input.

### ISSUE THREAD

**Issue by cbchenoweth** [moment/luxon#441]
calling `DateTime.isDateTime(null)` or `DateTime.isDateTime(undefined)` throws an exception.
I would expect this function to just return `false` in this case.

seems like it would be a simple check to add inside the function:

    static isDateTime(o) {
      return o && o.isLuxonDateTime || false;
    }

**Comment by icambron** [comment]
Fixed in 4c4f9021362432e1406a3a147a916122b676affb
