### ISSUE TITLE
Luxon CDN pollutes window

### ISSUE THREAD

**Issue by noelheesen** [moment/luxon#443]
When including luxon from CDN it set's the module's properties to the window object directly instead of scoping it like for example lodash does under `_`.

This behavior does not only pollute the window object but also makes it hard to define it as an [external](https://webpack.js.org/configuration/externals/#externals) in webpack for production builds.

when including luxon from https://cdn.jsdelivr.net/npm/luxon@1.11.2/build/cjs-browser/luxon.min.js
the following happens to the window object:

![luxon-global-scope](https://user-images.githubusercontent.com/18031130/52905007-e2b8e600-3233-11e9-8123-8f65e9db9f5f.png)

**Comment by icambron** [comment]
Hmm, this must be a problem with the CJS build. I basically just thew Luxon at Rollup and said "make this a CJS module". Will take some investigation to figure out why it does that.
