### ISSUE TITLE
Expose DateTime globally in documentation

### ISSUE THREAD

**Issue by intellix** [moment/luxon#445]
When reading documentation I like to open the console and start exploring and playing with the API to get a feel and see the methods rather than read about them.

Think it'd be good if it was exposed on window in the documentation to do so

**Comment by icambron** [comment]
It is! The global is `luxon`, so e.g. `luxon.DateTime`

**Comment by icambron** [comment]
I couldn't think of how to document that at the ttim, but it occurs to me now that I should output instructions via console.log.

**Comment by icambron** [comment]
Done in a4379c3b7cfccb65497a0a44482a683c5975e9de

**Comment by intellix** [comment]
Ah, I tried `new DateTime`. Thanks :)
