### ISSUE TITLE
Updates required in zoneName.

### ISSUE THREAD

**Issue by patelhr** [moment/luxon#450]
Hello,
According to latest IANA database, Indian standard time have zone value 'Asia/Kolkata' while luxon giving old zoneName 'Asia/Calcutta' which create an issue for comparing latest IANA zoneName with luxon zoneName because we are maintaining latest zoneName name only. So requested you to update zoneNames to latest names if it is not updated.
We are comparing zoneName of luxon with this library which maintains the latest IANA zoneNames https://github.com/dmfilipenko/timezones.json/blob/master/timezones.json

FYI according to a world timezones map of http://momentjs.com/timezone/ is showing Asia/Kolkata which is proper. Also according to http://momentjs.com/downloads/moment-timezone-with-data-2012-2022.js records it maintain both "Asia/Kolkata|Asia/Calcutta" so here I think I should get the latest zoneName or array of zoneNames in DateTime zoneName. An array will be helpful for applications which maintain latest or old zoneNames in the application DB.

**Comment by icambron** [comment]
I think you are misunderstanding how Luxon works. Unlike, Moment, it doesn't maintain its own database of zones. Instead, it manipulates the Intl library built into the browser (or Node) to synthesize zone support. So what you're seeing is that your browser thinks your zone is "Asia/Calcutta" and Luxon is inheriting that fact. I'm not sure what browser you're testing in, but you should file a ticket with their bug tracking system.
