### ISSUE TITLE
Throw an error on invalid dates

### ISSUE THREAD

**Issue by maghis** [moment/luxon#455]
Is there a way to have `luxon` throw Errors when parsing invalid dates?

**Comment by icambron** [comment]
yes: https://moment.github.io/luxon/docs/manual/validity.html#throwoninvalid

**Comment by maghis** [comment]
thanks @icambron!

**Comment by ghuser** [comment]
link update: https://moment.github.io/luxon/api-docs/index.html#settingsthrowoninvalid
