### ISSUE TITLE
Drop the "in" prefix from the output of toRelative()

### ISSUE THREAD

**Issue by pronebird** [moment/luxon#460]
Hi,

Currently when using `DateTime.toRelative()`, it returns `in 2 days` for example. Is there any way to drop the `in` prefix and just have it report the duration, i.e `2 days`? 

Previously when using `moment.js`, `moment.fromNow(true)` was used to do that kind of thing.

**Comment by icambron** [comment]
Unfortunately, no, because the "in" is part of the response we get from the `Intl` API.
