### ISSUE TITLE
DateTime equality bug?

### ISSUE THREAD

**Issue by josephValentine** [moment/luxon#461]
Im a beginner to Luxon, but so far great library! I've noticed something a little odd though and i wanted to ask if this was intended behavior.

```
const DateTime = luxon.DateTime;
const Duration = luxon.Duration;
const Interval = luxon.Interval;

const now = DateTime.local();
const nextMonth = now.plus({months: 1});
const thisMonth = nextMonth.minus({months: 1});
console.log(now === thisMonth) // false?
console.log(now.ts === thisMonth.ts) // true
```

Shouldn't the first equality be true? Especially if the timestamps are the same?

**Comment by icambron** [comment]
`===` for objects checks if the two objects are the same object. See docs at https://moment.github.io/luxon/docs/manual/math.html#comparing-datetimes
