### ISSUE TITLE
DateTime.fromIso() producing invalid DateTime on iOS 9 Safari

### ISSUE THREAD

**Issue by nikwen** [moment/luxon#466]
# Description

The following code snippet creates an invalid DateTime in Safari on iOS 9 and a valid DateTime in every other browser:

```
var dateTime = luxon.DateTime.fromISO("2019-03-13", {
    zone: "Europe/Berlin"
});
```

It should return a valid DateTime in Safari on iOS 9, too.

# Reproduction link

Reproduction: https://0126kq78v0.codesandbox.io/ (open in iOS 9 Safari)
Code: https://codesandbox.io/s/0126kq78v0.

# Versions

Luxon: 1.11.4
Browser: Safari on iOS 9

**Comment by nikwen** [comment]
The following **does** return a valid DateTime on iOS 9 Safari:

```
var dateTime = luxon.DateTime.fromISO("2019-03-13");
```

It seems to be the `zone` option which is broken.

**Comment by nikwen** [comment]
Screenshot from BrowserStack using a real device:

![Screenshot](https://user-images.githubusercontent.com/3309657/54300898-1e8a6580-45be-11e9-8e4c-66d45feca1f7.png)

**Comment by icambron** [comment]
I've never tried iOS Safari 9 so I don't have it the support matrix. Can you check Luxon's `Info.features` on it?

**Comment by nikwen** [comment]
@icambron Thank you very, very much for your helpful reply!

[`Info.features()`](https://codesandbox.io/s/qxxkpr6yo6) returns the following:

```
{"intl":false,"intlTokens":false,"zones":false,"relative":false}
```

Is there any easy way to polyfill this?

Apart from that, is it safe to assume that whenever the resulting date of an operation is valid, only supported features were used? Or the other way round, that whenever an unsupported feature is used, the resulting date of an operation is invalid?

Thank you very much for your time! :blush:

**Comment by nikwen** [comment]
To give back to the project, I'd like to contribute `Info.features()` results for various iOS versions:

**iOS 9**

```
{"intl":false,"intlTokens":false,"zones":false,"relative":false}
```


**iOS 10**

```
{"intl":true,"intlTokens":false,"zones":true,"relative":false}
```

**iOS 11**

```
{"intl":true,"intlTokens":true,"zones":true,"relative":false}
```

**iOS 12**

```
{"intl":true,"intlTokens":true,"zones":true,"relative":false}
```
-----------------

**Thank you so much for creating `luxon`! :blush:**

**Comment by icambron** [comment]
Thank you. I'll get that added to the support matrix

**Comment by nikwen** [comment]
Awesome. Thanks for being such a great maintainer!

**Comment by xumix** [comment]
wouldn't it be better to throw if there is no support for corresponding features?

**Comment by icambron** [comment]
I updated the support matrix to reflect this.

@xumix I go back and forth on this. I mostly don't throw for consistency with other behaviors. You can make it throw using `Settings.throwOnInvalid`

**Comment by nikwen** [comment]
Thank you, Isaac! :)
