### ISSUE TITLE
RFC3339 and RFC3339Nano

### ISSUE THREAD

**Issue by mbana** [moment/luxon#474]
How does one parse the formats below. Golang defines `RFC3339` and `RFC3339Nano`, see https://golang.org/pkg/time/#pkg-constants for the documentation and `/usr/local/go/src/time/format.go` for the definition.

```go
...
	RFC3339     = "2006-01-02T15:04:05Z07:00"
	RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"
...
```

---

I am doing something wrong because the below isn't working for me:

```javascript
> luxon.DateTime.fromISO("2006-01-02T15:04:05Z07:00").toString()
"Invalid DateTime"
```

**Comment by GillesDebunne** [comment]
`Z07:00` is not a valid ISO8601 or RFC3339 format. 

From your link: _RFC3339 is useful for formatting; when used with time.Parse it does not accept all the time formats permitted by the RFCs_.

This string format means display a `Z` for UTC dates, and use `[+-]HH:MM` if there's an offset. It is however not a valid input string.

If you expand the 'Example' section in [https://golang.org/pkg/time/#pkg-constants](https://golang.org/pkg/time/#pkg-constants):

```
         // Some valid layouts are invalid time values, due to format specifiers
	// such as _ for space padding and Z for zone information.
	// For example the RFC3339 layout 2006-01-02T15:04:05Z07:00
	// contains both Z and a time zone offset in order to handle both valid options:
	// 2006-01-02T15:04:05Z
	// 2006-01-02T15:04:05+07:00
```

and indeed, `t, _ = time.Parse(time.RFC3339, "2006-01-02T15:04:05Z07:00")` displays `error parsing time "2006-01-02T15:04:05Z07:00": extra text: 07:00` and returns an invalid date.

**Comment by icambron** [comment]
@GillesDebunne's explanation is right.

I'll add that we don't support any nano formats because the underlying JS dates don't either; there's no way to represent a date with more precision than milliseconds.
