### ISSUE TITLE
Relative time shows `in 0 seconds`

### ISSUE THREAD

**Issue by mschipperheyn** [moment/luxon#478]
Relative time shows `in 0 seconds` for "now" dates. Instead it should display: 'Just now'

**Comment by icambron** [comment]
Unfortunately this is determined by the Intl API, not Luxon, so there’s no way to change that. I can’t override it because Luxon doesn’t have that string in every language

**Comment by heruan** [comment]
I have the same issue and I understand @icambron statement, but can we discuss at least a workaround? Is this being discussed for Intl API somewhere?

**Comment by KevinBatdorf** [comment]
Workaround:
```js
const relativeTime = DateTime.fromISO(time).toRelative()
return relativeTime === 'in 0 seconds' ? 'Just now' : relativeTime
```

**Comment by seavan** [comment]
locale-agnostic workaround:

```typescript
export function toRelative(date: Date) {
  if (DateTime.fromJSDate(date).diffNow().as('seconds') > -30) return 'just now';
  return DateTime.fromJSDate(date).toRelative();
}
```

**Comment by icambron** [comment]
@seavan That's not locale-agnostic, though, because "just now" is an English string

**Comment by seavan** [comment]
i am saying "locale-agnostic" because it will not break if locale is not 'en' (and toRelative returns something which doesn't have a string 'in 0 seconds there') it is still useful - but you do need to localize 'just now' within your own app, that's true.

**Comment by UziTech** [comment]
If luxon is going to use the Intl API and not try to work around some of its shortcomings then it should at least keep issues like this open until it is resolved in the API so it has a better chance of being found by anyone who needs a work around.

**Comment by icambron** [comment]
@UziTech no, the list of issues is the only tool I have to manage the things I actually can fix, and I'm arguably not even able to keep up with that. I can't have a big list of tickets sitting around waiting for browsers to update.

**Comment by nicholaszuccarelli** [comment]
I have a nicer solution 

```
DateTime.prototype.fromNow = function (capitalise = false) {
  const relativeTime = this.toRelative()
  if (relativeTime.includes('0 second')) {
    return `${capitalise ? 'J' : 'j'}ust now`
  }
  return relativeTime
}
```
Implemented a "fromNow" method into the DateTime object.
So you can do dateObj.fromNow() and it will return 'Just now' (with or without capitalisation)
