### ISSUE TITLE
Add convenience getters for month and weekday names

### ISSUE THREAD

**Issue by icambron** [moment/luxon#48]
These are analogous to `offsetNameShort` and `offsetNameLong`:

 * `dateTime.weekdayShort`
 * `dateTime.weekdayLong`
 * `dateTime.monthShort`
 * `dateTime.monthLong`

**Comment by mslooten** [comment]
You mean like a convenience wrapper for `DateTime.local().toLocaleString({ weekday: 'short' })` or `DateTime.local().toFormat('ccc')` (and the likes)? I'm happy to take a stab at this.

**Comment by icambron** [comment]
@mslooten Yup, that's right. Though I think it might be better implemented as `Info.monthsShort[this.month - 1]`

**Comment by icambron** [comment]
Fixed in #49
