### ISSUE TITLE
Issue with DateTime.plus documentation

### ISSUE THREAD

**Issue by pedro-pedrosa** [moment/luxon#480]
[In the docs](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-plus), it looks like there is an issue with the `DateTime.plus()` function.

Shouldn't the comments in the last two examples read `//~> in 3 hr, 13 min`?

**Comment by icambron** [comment]
Correct

**Comment by icambron** [comment]
Fixed in be1696c
