### ISSUE TITLE
document: navigation area is transparent

### ISSUE THREAD

**Issue by munierujp** [moment/luxon#483]
## Problem
![スクリーンショット 2019-03-30 19 05 46](https://user-images.githubusercontent.com/20086673/55274726-f8cfc100-531e-11e9-8194-7c413aa57edc.png)

navigation area (`.navigation`) does not have any background color.
So, content area (`.content`) is seen through when scroll page horizontally.

## How to fix
![スクリーンショット 2019-03-30 19 05 53](https://user-images.githubusercontent.com/20086673/55274723-f40b0d00-531e-11e9-8b33-91ec51deb971.png)

Add background color to navigation area (`.navigation`).

```css
.navigation {
    background-color: #fff;
}
```

**Comment by icambron** [comment]
This appears to be a bug in ESDoc. While technically I could use a plugin to inject that CSS into it, I'd prefer to do as little of that as possible, and instead wait for it to get fixed in https://github.com/esdoc/esdoc
