### ISSUE TITLE
toISODate()/toISOTime() for Intervals

### ISSUE THREAD

**Issue by seanfisher** [moment/luxon#492]
I noticed that DateTime has [`toISODate`](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toISODate) while Interval does not. In my case I don't want the time component (my use case is to store on the server an interval between the same dates regardless of the time zone it is considered in). Any possibility of having that method added? Currently my workaround is to do a:

    `${dt.start.toISODate()}/${dt.end.toISODate()}`

but that requires the calling code to know about/understand the [ISO 8601 interval format](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals), which responsibility should rest with the date library IMO.

Similarly the [`toISOTime()`](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toISOTime) method could be added.

**Comment by icambron** [comment]
Sure, that's a reasonable request.

**Comment by arusak** [comment]
I'd like to implement this. Is it ok?

**Comment by icambron** [comment]
Go for it
