### ISSUE TITLE
Setting Zone as UTC on Interval throws error when using Duration component

### ISSUE THREAD

**Issue by seanfisher** [moment/luxon#493]
Hi, when I do this it works and parses the dates as UTC:

    Interval.fromISO("2016-01-01/2016-12-31", { zone: 'utc' });

However, when I do this it throws an error:

    Interval.fromISO("2016-01-01/P1Y", { zone: 'utc' });

> Invalid unit zone

Tracing it through the code it appears that when the Duration portion of the interval is parsed it can't handle the `zone` option in the `Duration.fromObject` method.

There are a couple of options to resolve:

1. There appears to be some sort of [whitelist of non-unit keys](https://github.com/moment/luxon/blob/df9e439e2c1966142972940eadcd5582b09e1827/src/duration.js#L233) - perhaps this could be modified to include `zone` and potentially other options that would apply?
2. The signature of `Interval.fromISO` could be adjusted to take separate options for DateTime and Duration components of the Interval
3. Only allow and document specific Interval-relevant options in the `Interval.fromISO` function, and then require the caller to make any adjustments via `mapEndpoints`. Right now the documentation states that that `opts` means: `options to pass DateTime.fromISO and optionally Duration.fromISO`, which currently implies that all the options from those two methods are supported.
4. Others...?

For now I'll do the following:

    let i = Interval.fromISO("2016-01-01/P1Y");
    i.mapEndpoints(d => d.setZone('utc', {keepLocalTime: true}));

**Comment by icambron** [comment]
Yeah, we definitely should support something here.

**Comment by icambron** [comment]
I went with your first suggestion in 2fa3d6d. Released in 1.14.0. I have also created #513 to clean this up in 2.0, so that we don't need a whitelist.
