### ISSUE TITLE
Implement appropriate fantasy-land interfaces (or at least `Ord`)

### ISSUE THREAD

**Issue by futpib** [moment/luxon#495]
For instance, if `DateTime` implemented [`Ord`](https://github.com/fantasyland/fantasy-land#ord), one could use [`R.clamp`](https://ramdajs.com/docs/#clamp) to clamp the date.

```js
const clampedTarget = R.clamp(firstSeen, lastSeen, target);
```

I will submit a PR if this feature is accepted.

**Comment by icambron** [comment]
Forgive my ignorance, but does this just mean adding something like this?

```js
lte(other) {
  if (DateTime.isDateTime(other) {
    return this <= other;
  } else return false;
}
```

If so, sure.

**Comment by icambron** [comment]
Actually, before you do anything, are you sure that `R.clamp` doesn't just work? If you can clamp integers (which presumably also don't implement Ord), it seems like you could clamp DateTimes because they both implement `valueOf`

**Comment by icambron** [comment]
Deleted my previous comments because I did more poking.

You can use `R.clamp` now because it relies on `<` and `>`, which `DateTime` supports by implementing `valueOf`.

What would be the additional benefits of implementing fantasy-land interfaces?

**Comment by futpib** [comment]
Awesome! I haven't even thought to check it :man_facepalming:.

Another instance that would make sense is a [`Group`](https://github.com/fantasyland/fantasy-land#group) for `Duration`, but I don't have a good motivational example.

```js
const durations = map(Duration.fromObject, [{ minute: 1 }, { hour: 1 }, { day: 1 }]);
const total = reduce(concat, empty(Duration), durations);
// total.values === { days: 1, hours: 1, minutes: 1 }
```

**Comment by icambron** [comment]
Hmm, think I'll pass on that for now. Would need a compelling use case
