### ISSUE TITLE
2 DateTimes created back to back with different timezones?

### ISSUE THREAD

**Issue by zocheyado** [moment/luxon#496]
I cannot for the life of me figure out what is wrong here. I am making 2 dates back to back, and luxon is just assigning them some random offset, so my difference check is wrong ( I am trying to get a difference of 105)
Here is my code
```
    const beginDate = ‘2018-01-05’;
    const endDate = ‘2019-04-20’;
    const start = DateTime.fromSQL(beginDate);
    const end = DateTime.fromSQL(endDate);
    const difference = end.diff(start).as('days');
    console.log(beginDate);
    console.log(endDate);
    console.log(start);
    console.log(end);
    console.log(difference);
```

Here is my output
```
2019-01-05
2019-04-20
DateTime {
 ts: 2019-01-05T00:00:00.000-05:00,
zone: America/Toronto,
 locale: en-US } 
DateTime {
ts: 2019-04-20T00:00:00.000-04:00,
zone: America/Toronto,
 locale: en-US }
104.95833333333333
```

I am importing like this
```
import { DateTime } from 'luxon';
```
Version in Package.json
```
    "luxon": "^0.5.8",
```

**Comment by zocheyado** [comment]
For more info, I tested this on 1.12.0 as well, and the results are different but not exactly the same. I no longer get the weird -04:00 on my TS. I do however still get partial days when checking the difference between 2 whole dates.

**Comment by zocheyado** [comment]
I found a workaround for my instance, but I still think something is wrong. If I update to 1.12.0 AND change my code into the following.
```
    const difference = end.diff(start, 'days').toObject().days;
```
It seems to work, however one or the other still fails.

**Comment by icambron** [comment]
That offset isn't random. Canada has a DST from March 10 to Nov 3; the offset really is -4 on April 20.

If you want to keep that out of your diff, do the diff computation in days, like this:

```js
 end.diff(start, "days")
```

Otherwise you are doing it in milliseconds and converting to days and the missing hour--which, again, really is missing--is leaving its mark.

**Comment by zocheyado** [comment]
Is this still not unexpected behavior? I expect diff to give me the difference between my 2 inputs, not my 2 inputs and then those inputs adjusted for DST or MST etc. I have no hour associated with my timestamp and thus I would not expect any hour adjustment on my date. I guess my bigger problem is that if I put in a date of 2019-04-20 you should not assume it is -4 it should be 0.

**Comment by icambron** [comment]
DateTimes are always specific times. "2019-04-20" is interpreted as "2019-04-20T00:00:00" which has an offset of -4 in your zone. I don't know what you mean by "adjusting"; you sent a string, the string encodes a time, and at that time has an offset. Perhaps you want to interpret those strings as specifying a UTC time. In that case, you can tell Luxon that with the `zone` argument, like `DateTime.fromSQL(s, {zone: "UTC"})`.
