### ISSUE TITLE
Feature Request: add a method to Zone returning `+05:00`

### ISSUE THREAD

**Issue by ycmjason** [moment/luxon#504]
`Zone` currently has a method `offsetName(ts, opts)` which returns `AST` or its long form.

I suggest having an equivalent function (or extend `offsetName`'s `opts`) which can retrieve the formatted offset `+05:00`.

**Comment by icambron** [comment]
This would be a new method called `formatOffset(ts, format)`, where the `format` parameter with allowed values "short", "narrow", and "techie". The implementation should get moved from [here](https://github.com/moment/luxon/blob/236f2badea297ee73421aa39a83e06177c1be6d0/src/impl/formatter.js#L130) to Zone.js, documented, and of course called from the formatter.

**Comment by icambron** [comment]
Fixed in #509
