### ISSUE TITLE
Safety of using "s' and "e" values?

### ISSUE THREAD

**Issue by Anthropic** [moment/luxon#508]
I am creating an interval and when the error is "missing or invalid start", "missing or invalid end" or "end before start" the start and end value are null so I have been using `Interval.s` and `Interval.e` to create a new Interval that is valid.

The DefinitelyTyped version `@types/luxon` doesn't have the "s" and "e" values so I wanted to check if they should be added to the type definition (happy to do that) or if there was a reason they weren't and should not be?

**Comment by mastermatt** [comment]
I am by no way a maintainer of this project, but I've contributed here and to the types.
I remember not explicitly adding those attributes to the `Interval` class type because they are [marked as private](https://github.com/moment/luxon/blob/4c4f9021362432e1406a3a147a916122b676affb/src/interval.js#L42-L49). My two cents.
The design philosophy of whether they should or shouldn't be private is something I can't speak to.

**Comment by Anthropic** [comment]
@mastermatt thanks for the info, I appreciate your time, hopefully a maintainer can chime in with how safe it is to keep using it or if there is an alternative I could try if it should remain considered private and potentially disposable at some point.

**Comment by icambron** [comment]
Yeah, this is a good question. They are private, though I have no plans to change them. But note that in the next version, we're going to not have invalid and instead throw or return null, depending on the settings. Therefore, I would recommend wrapping the creation function to take `start` and `end` and check the validity there, where you have access to the input `start` and `end` as locals.

**Comment by Anthropic** [comment]
@icambron in my case I don't get access to the original values, that is handled by another system/component package that triggers an event passed to mine directly as the output object you provide. I then need to validate that and send back to an observer any changes required.

**Comment by icambron** [comment]
I can't officially support it, but if I were you I'd just use e and s until 2.0

**Comment by Anthropic** [comment]
Thanks for the info, appreciate your time!
