### ISSUE TITLE
React Native (Android) can't find variable Intl

### ISSUE THREAD

**Issue by SamMatthewsIsACommonName** [moment/luxon#51]
<img width="350" alt="screen shot 2017-11-01 at 21 14 46" src="https://user-images.githubusercontent.com/21329063/32295497-c541a188-bf49-11e7-8100-a05d997c93ae.png">
Is it possible to use this library in React Native? I'm getting this error on Android.
Thanks
code causing problem is below:

````
  const clockInDate = DateTime.fromMillis(shift.clockIn).toLocaleString({
    day: "numeric",
    month: "short",
    weekday: "short"
  });

  const clockOutDate = shift.clockOut
    ? DateTime.fromMillis(shift.clockOut).toLocaleString({
        day: "numeric",
        month: "short",
        weekday: "short"
      })
    : "-";
````

Edit:
I've found this can be fixed by using this library which seems excellent:
https://github.com/SoftwareMansion/jsc-android-buildscripts

**Comment by icambron** [comment]
Yikes. A few thoughts:

 1. I'm glad you found a solution. I will add it to the documentation.
 2. I've been slowly fixing places where the absence of Intl breaks things. I currently *do* expect `toLocaleString` to not break without Intl. See [http://moment.github.io/luxon/docs/manual/faq/matrix.html](this doc) for the caveats. Basically, you might not get exactly the strings you expect but it shouldn't have thrown either. I'll look into it. Are you sure you were on the latest version of Luxon? I have been pretty actively fixing this stuff and there are some (not terribly thorough) tests for it.
 3. I would like to support React Native but I don't know much about it. It surprises me that it doesn't provide `Intl`.

**Comment by SamMatthewsIsACommonName** [comment]
hmm I was on version 0.0.10. I'll try taking the build scripts out and trying again with 0.0.12, however I imagine the need for those scripts is real given they exist at all 
I'm just basing this on what they say: "An obvious benefit for everyone using React Native is that this will allow us to update JSC for React Native on Android much more often than before (note that facebook/android-jsc uses JSC version from Nov 2014), which is especially helpful since React Native on iOS uses the built-in copy of JSC that is updated with each major iOS release")
I will say that I had been using moment.format() earlier and it was causing some really strange and inconsistent results on our android version, so I'm wondering if that is related to the need for this

**Comment by icambron** [comment]
Right, it looks like the RN environment is missing the Intl API but that library provides it. And to get the full features of Luxon you definitely need that. What I'm saying is that Luxon should at least not break so horribly and I'd be surprised if it the latest version did. But I could be wrong!

**Comment by icambron** [comment]
I added some docs

**Comment by SamMatthewsIsACommonName** [comment]
Great thanks. Amazingly I still don't really know how to create a pull request (I know I know...)
But I made this gist to give a bit of an overview and point out that it only is a problem on Android 
https://gist.github.com/SamMatthewsIsACommonName/906dcbfdb1d3582948d4878bc2790aff

**Comment by icambron** [comment]
Loudly failing makes sense for RN, but it's really painful in browsers, where the browser the developer is using is not the same one their users use. Anyway, I did track the root issue down and fix it.

I've also updated the documents to clarify that the build script thing is only needed for Android.

**Comment by SamMatthewsIsACommonName** [comment]
Of course, I didn't even think of that! Thanks

**Comment by kbrandwijk** [comment]
The weird thing is, it's working for me in development mode on Android without any error, but as soon as I go into production mode, it doesn't work anymore. I'll try the solution mentioned above though...

**Comment by kopax** [comment]
I have the same error. is there a solution?

**Comment by hsuan1117** [comment]
Run
```shell
npm install intl
```
and put these code into ```index.js```
```javascript
import 'intl';
import 'intl/locale-data/jsonp/en';
```
