### ISSUE TITLE
Documentation typo mistake

### ISSUE THREAD

**Issue by cre-mer** [moment/luxon#510]
On the following page [https://moment.github.io/luxon/docs/manual/math.html](https://moment.github.io/luxon/docs/manual/math.html)
![Bildschirmfoto 2019-05-16 um 11 24 09](https://user-images.githubusercontent.com/33655900/57842761-723b4a00-77cd-11e9-83b4-772eb7ad84de.png)

it should be `d2 < d1` not `d2 < d2` on line 4.

**Comment by icambron** [comment]
Fixed in #511. Thanks for the report
