### ISSUE TITLE
TIME_SIMPLE giving different output for Windows 10 and Windows 7 in Chrome

### ISSUE THREAD

**Issue by arunkgopal** [moment/luxon#515]
In Google Chrome on Windows 7 the TIME_SIMPLE works perfectly fine with the output of 5:30 PM. (expected output)
**In Google Chrome on Windows 10 the TIME_SIMPLE doesn't works as expected with an output of 17:30. instead of 5:30 PM**
Code snippet:
var a= "2019-05-18"+" "+"17:30:00"
var b= new Date(a.replace(/-/g, '/'));
var timeZone = "Australia/Melbourne"
var c= DateTime.fromJSDate(b).setZone(timeZone, {keepCalendarTime: true});
b = c.toISO();
var d= c.toLocaleString(DateTime.TIME_SIMPLE);

Is there any configuration that I am missing or is this an issue. I couldn't find anything related in the Luxon manuals. Any help would be much appreciated.

**Comment by icambron** [comment]
Can you run this on Chrome on Windows 7 and tell me what it produces?

```js
new Intl.DateTimeFormat("en", Object.assign({ zone: "Australia/Melbourne"}, DateTime.TIME_SIMPLE)).format(new Date("2019-05-18T17:30:00"))
```

**Comment by arunkgopal** [comment]
Thanks Mate! That works perfectly fine on Windows 10 and Windows 7.
