### ISSUE TITLE
Inconclusive error message: Duration.fromObject: argument expected to be an object, got object

### ISSUE THREAD

**Issue by shaedrich** [moment/luxon#516]
If you pass `null` to `Duration.fromObject()` you'll get the following error message:

> Duration.fromObject: argument expected to be an object, got object

this happens in the following lines of code ([duration.js:272](https://github.com/moment/luxon/blob/master/src/duration.js#L227,L231)):

```
if (obj == null || typeof obj !== "object") {
      throw new InvalidArgumentError("Duration.fromObject: argument expected to be an object, got " + typeof obj);
}
```

The code is not incorrect but the error message inconclusive. This is because of the not using a strict comparison operator and using typeof which doesn't always have the desirable result.

Maybe this could be a bit improved…

**Comment by shaedrich** [comment]
I made that more clear using a ternary operator for the "null case". Are you OK with that?

**Comment by icambron** [comment]
yup, thanks

**Comment by shaedrich** [comment]
Cool, you're welcome
