### ISSUE TITLE
DateTime.local().toISO()

### ISSUE THREAD

**Issue by 3boysdad** [moment/luxon#518]
Getting an odd situation running on Lambda - similar to #257 - running lambda in the us-west-2 zone.  The code is pretty simple.

procoess.env.COMPANY_TZ is defined as -> America/Los_Angeles

```
    DateTime.local().setZone(process.env.COMPANY_TZ);
    console.log(DateTime.local().zone.name + " - " + process.env.COMPANY_TZ);
    console.log(DateTime.utc().toISO() + " / " +  DateTime.utc().plus({ day: 1}).toISO());
    console.log(DateTime.local().toISO() + " / " +  DateTime.local().plus({ day: 1}).toISO());
```
The output from the logs:

UTC - America/Los_Angeles (this looks funny, shouldn't they both just be LA?)
2019-05-28T15:43:00.531Z / 2019-05-29T15:43:00.532Z (looks good)
2019-05-28T15:43:00.534+00:00 / 2019-05-29T15:43:00.534+00:00 (shouldn't this be -07:00?)

So I simplified even more.

```
    let localDate:DateTime = DateTime.local();
    localDate.setZone("America/Los_Angeles");
    console.log(localDate.zone.name + " - " + process.env.COMPANY_TZ);
    console.log(localDate.toISO() + " / " +  localDate.plus({ day: 1}).toISO());
```
My output:

UTC - America/Los_Angeles
2019-05-28T15:55:10.731+00:00 / 2019-05-29T15:55:10.731+00:00

So...any thoughts on what I am doing wrong here?  My package.json file is telling me i'm using version -> "luxon": "^1.15.0",

**Comment by 3boysdad** [comment]
Anyone that happens to trip across this - I did find a work around...doing this ->

```
    let localDate:DateTime = DateTime.local();
    let rezoned:DateTime = localDate.setZone("America/Los_Angeles");
    console.log(localDate.zone.name + " - " + process.env.COMPANY_TZ);
    console.log(localDate.toISO() + " / " +  localDate.plus({ day: 1}).toISO());
    console.log(rezoned.toString() + " / " +  rezoned.plus({ day: 1}).toString());

```
Will cause the rezoned output to be as you'd expect:

2019-05-28T09:02:44.564-07:00 / 2019-05-29T09:02:44.564-07:00

But I am still curious why my original code didn't work as expected.

**Comment by icambron** [comment]
The basic problem is this:

```js
DateTime.local().setZone(process.env.COMPANY_TZ);
```

That creates an instance and sets its zone. It doesn't set the default zone for the creation of future instances, so those all turn out to be UTC, because that's your system's zone. Your new code actually sets it on the instance you output to the console, so that works as expected.

You might be interested in the default zone setting: https://moment.github.io/luxon/docs/manual/zones.html#changing-the-default-zone

**Comment by 3boysdad** [comment]
thanks Issac...this makes more sense...back to sling code after a few minor changes on my end..
