### ISSUE TITLE
Support plus operator for intervals

### ISSUE THREAD

**Issue by fenixsolorzano** [moment/luxon#519]
Would be awesome to support the `plus` operator so that we could have add weeks, days etc, in intervals.

**Comment by icambron** [comment]
Hmm, I think this is pretty well-handled:

```js
interval.mapEndpoints(start => start, end => end.plus({ days: 1 }))
```

One reason to do it this way is that I don't know whether you want to add to the beginning or end of the interval.

But maybe this could use better documentation. Probably a section in the Math docs would be a good addition.
