### ISSUE TITLE
If Interval is invalid due to Start Date coming after end date, it should throw if Settings.throwOnInvalid is true

### ISSUE THREAD

**Issue by DanielJoyce** [moment/luxon#521]
https://github.com/moment/luxon/blob/6c7d84d3e5f08b7115a3a1ab31cdf093bc3fbf5e/src/interval.js#L16

It should check Settings.throwOnInvalid here, and throw if true.

It currently doesn't.

**Comment by DanielJoyce** [comment]
https://codesandbox.io/embed/luxon-playground-50osl  

Playground repro

**Comment by icambron** [comment]
Sure, would take a fix

**Comment by StheffanyHadlich** [comment]
I can work on it

**Comment by icambron** [comment]
Right

**Comment by icambron** [comment]
Fixed in that PR, released in 1.17.0
