### ISSUE TITLE
toLocaleString is not returning correct date format in arabic locale in angular application

### ISSUE THREAD

**Issue by sriharsha566** [moment/luxon#525]
toLocaleString() method is not returning correct date format in arabic locale in angular application.
If i execute the same in npm runkit, it is working as expected.

**Comment by icambron** [comment]
You're going to need to give me a reproduceable scenario. Also, can you confirm that using the Intl API in the browser you're testing with produces the results you expect?

**Comment by sriharsha566** [comment]
https://codesandbox.io/s/angular-ndv55
It is reproduced here with latin numbering system.
Please check

**Comment by icambron** [comment]
I need something that looks more like this:

```js
DateTime.local().setLocale("ar").toLocaleString()

// received [some value]
// expected [some value]
```

**Comment by al4str** [comment]
Seems like I have kind of the same problem on my nodejs app

```js
const { DateTime } = require('luxon');

console.info(DateTime
  .fromSQL('2019-07-08 13:35:00')
  .setZone('Asia/Dubai')
  .setLocale('ar')
  .toRelative());

// received "1 day ago"
// expected "قبل يوم واحد"

// node -v
// v10.15.1

// luxon version
// 1.16.0
```

**Comment by icambron** [comment]
@al4str that's node not yet supporting intl relative time. 

You can see the support matrix here: https://twitter.com/reflected_sky/status/1148669928792346624?s=19

It's also useful to check `Info.features()` to(https://moment.github.io/luxon/docs/class/src/info.js~Info.html#static-method-features) to check your environment's support.

But the gist here is that internationalized relative time requires the Intl.RelativeTime API, which is new to v8 and thus not in Node 10

**Comment by al4str** [comment]
@icambron thank you for quick reply!

To be honest, I didn't know that `luxon` uses node's `Intl.RelativeTime` API for it's `toRelative` method under the hood. Even more, I got confused by correct result for `en` locale.

For the future, wouldn't it be better to put that info in your docs?

**Comment by icambron** [comment]
oops, pasted the wrong link. Fixed
