### ISSUE TITLE
"Intl not available" errors in some IE11 settings for recent Windows updates

### ISSUE THREAD

**Issue by phinch** [moment/luxon#528]
Hi! I'm working on an enterprise project that consumes Luxon. We're getting reports of an "Intl not available" bug that seems to be present on IE11 in certain settings (like a nonexistent manifest file) for some recent (March 2019) updates of Windows. (relevant: [Microsoft forum thread](https://social.msdn.microsoft.com/Forums/en-US/1c1b0af6-47a9-45a4-85b9-d8944ed886c9/typeerror-intl-is-not-available?forum=iewebdevelopment); [StackOverflow thread](https://stackoverflow.com/questions/55467744/ie11-typeerror-intl-is-not-available).) Our stacktrace goes back to the `hasIntl` function - it appears that the very act of referencing Intl to check if it exists is throwing this error. 

I think a workaround could be as simple as adding a try/catch block surrounding `hasIntl`'s logic. The catch block would swallow the error return `false` to any consumers of `hasIntl`. [This thread](https://github.com/angular/components/issues/15687) has some links to PRs with alternative solutions, like conditional polyfills, but given that Luxon already has robust workarounds for Intl not being defined, it seems like adding some more hardening to the `hasIntl` function would be a satisfactory solution here. This bug also seems relatively rare on our end, so I don't expect many people to travel the `catch` path anyway. I forked Luxon to experiment with this change and it fixes the bug in our case.

**Comment by icambron** [comment]
Thanks for the report and the analysis. I agree that's probably the best approach.

**Comment by gokulsiva** [comment]
Can I take this ?

**Comment by icambron** [comment]
Sure

**Comment by phinch** [comment]
@gokulsiva yay, thank you so much! If you want a reference, [this](https://github.com/blend/luxon/blob/master/src/impl/util.js#L34) is what we did in our forked luxon project to get it to work for our project. I'm excited to see this patch go in!

**Comment by gokulsiva** [comment]
@icambron Submitted a [PR](https://github.com/moment/luxon/pull/536) for this issue.

**Comment by gokulsiva** [comment]
> @gokulsiva yay, thank you so much! If you want a reference, [this](https://github.com/blend/luxon/blob/master/src/impl/util.js#L34) is what we did in our forked luxon project to get it to work for our project. I'm excited to see this patch go in!

@phinch thank you for your reference.
