### ISSUE TITLE
Environment for testing?

### ISSUE THREAD

**Issue by gbirke** [moment/luxon#53]
My platform (Mac OS X, node 7 and icu4c installed with brew) threw errors when running `gulp test`, probably due to missing or outdated `icu-full` (most failing tests were due to missing translations).  I've since updated to node 8 and installed icu-full and now all the tests are passing. However, I'm wondering if this environment should be documented somewhere (e.g. `contributing.md`) or if the repo should contain a Dockerfile that contains all the necessary environment setup (including gulp-cli and a US timezone that would fix issue #52) and a script to run the ci/tests in the Docker environment.

I'd be happy to provide such a file if needed, maybe even change `.travis.yml` to use the Docker environment. Or to update the documentation if you don't like Docker.

**Comment by icambron** [comment]
Yeah, it should definitely be documented that it needs Node 8 and full-ICU and also, yeah, setting the TZ needs documented. I think with osx it's just `brew install node --with-full-icu`. 

I'm all for Docker (both as an option for local dev and as a CI thing), but think we should also provide instructions for people running it directly too. I have plenty of Docker experience but none with using it for testing an OSS project. What's the simple way to make the commands accessible in a way that runs them in a docker container?

**Comment by gbirke** [comment]
> What's the simple way to make the commands accessible in a way that runs them in a docker container?

Assuming the Dockerfile is for development only and a front end for `gulp`, we could add

    ENTRYPOINT gulp
    CMD ["test"]

After that the issue is that a simple command like `gulp test` needs to be prepended with Docker "boilerplate" like 

    docker run -it --rm -v $(pwd):/app -w /app moment/luxon test

If we leave out `ENTRYPOINT` and `CMD`, the command gets only slightly longer and reveals more intent:

    docker run -it --rm -v $(pwd):/app -w /app moment/luxon gulp test

The most common ways to provide the command line syntax I've used in different project are:
1. Write the docker run command in the readme or other docs.
2. Create a makefile that contains a target for each gulp command
3. Adopt the "[scripts to rule them all](https://github.com/github/scripts-to-rule-them-all)" and put the commands in the `scripts` directory.

**Comment by icambron** [comment]
OK, how is this?

 1. A Dockerfile with Node 8 that installs full-icu and sets the env vars
 2. `scripts/gulp` runs gulp inside the container, passing its arguments through

I gave this a shot and it works fine.

**Comment by icambron** [comment]
@gbirke Can you take a look at the `use-docker` branch I just pushed?

**Comment by gbirke** [comment]
🎉 Worked fine. I like it!

**Comment by icambron** [comment]
I reorganized it a little and merged it. So this is good to go.
