### ISSUE TITLE
DateTime is valid for object with null fields

### ISSUE THREAD

**Issue by nexen505** [moment/luxon#530]
Hello to all!

When I worked with validation, found some strange behavior:

`DateTime.fromMillis(-6e2422).isValid = true`, but `DateTime.fromMillis(-6e2422).toObject()` is `{"year":null,"month":null,"day":null,"hour":null,"minute":null,"second":null,"millisecond":null}`.

Is it correct?

**Comment by icambron** [comment]
hmm, yeah, that does seem quite wrong

**Comment by icambron** [comment]
Fixed in 6e19fd8
