### ISSUE TITLE
setZone('America/New_York') producing 'Invalid DateTime' on ReactNative 0.59 (Android)

### ISSUE THREAD

**Issue by bramski** [moment/luxon#541]
Version: `1.8.2`
ReactNative: `0.59`
Platform: `Android`

Trying to dig deeper... 
The following code: `DateTime.fromISO('2020-09-17T16:00:00-04:00')` returns `Invalid DateTime`. Not sure if something changes in the javascript runtime or something...

**Comment by icambron** [comment]
That is pretty weird. Unfortunately I have no idea. Can you check `invalidReason` and `invalidExplanation` on that invalid instance?

**Comment by bramski** [comment]
I'm baffled as well... If I do the following:
`import { parseISODate } from 'luxon/src/impl/regexParser';`
and then `parseISODate('2020-09-17T16:00:00-04:00')' I get back the date parts.

**Comment by icambron** [comment]
Do you have any settings overrides, particularly `defaultZone`?

**Comment by bramski** [comment]
No settings overrides.
Dug a bit deeper this morning (we have a side library that takes dates and produces standard time strings for us from our API)
It seems that `DateTime.fromISO` is actually succeeding, but calling `toFormat('h:mm a ZZZ')` is causing the 'Invalid DateTime' to be returned.

**Comment by bramski** [comment]
Ah wait... it seems like there is an additional call in here that is failing:
`setZone('America/New_York')` is returning the 'Invalid DateTime'.

**Comment by bramski** [comment]
So it seems this isn't Luxon's issue, but Intl no longer accepts 'America/New_York' as a valid timezone on the latest upgrade of React-Native.

**Comment by bramski** [comment]
Solved by: https://github.com/andyearnshaw/Intl.js/issues/19
Installing a second polyfill: https://github.com/yahoo/date-time-format-timezone
Fixes this.

**Comment by santiagofm** [comment]
Thank you @bramski for the thorough investigation! 🥇
