### ISSUE TITLE
fomISO may not work

### ISSUE THREAD

**Issue by amit-gshe** [moment/luxon#543]
when I parsing date form ISO string: `2019-07-13T01:01:01.123-07:00`, it complains `the input "‎2019-07-13T01:01:01.123-07:00" can't be parsed as ISO 8601`

**Comment by icambron** [comment]
Works fine for me. Are you sure your input is really a string? That error message will automatically `toString()` your input, so you should double check that it's not secretly a `Date` or a `DateTime` or something.

**Comment by amit-gshe** [comment]
I have found an invisible symbol after the first quotation mark and you are right.
