### ISSUE TITLE
Rename setZone option in DateTime constructors

### ISSUE THREAD

**Issue by GillesDebunne** [moment/luxon#546]
This is a suggestion, open for discussion, for v2.0.

I find the name of the `opts.setZone` used as a parameter in several DateTime `from` methods confusing.

What about renaming it `keepZone` instead?

The documentation could be:

```
opts.keepZone=false: if true, set the time zone from what is parsed in the input string. If not parsed, or if this option is false (default), use opts.zone instead.

opts.zone=local: the time zone where this DateTime is set. The time will be converted to this zone if a zone is parsed in the input string.
```

**Comment by icambron** [comment]
Yes, I'm ok with this, yeah. I'd switched it from `keepZone` (which we used in Moment), but now I can't remember why...
