### ISSUE TITLE
Duration multiply method

### ISSUE THREAD

**Issue by LandonSchropp** [moment/luxon#557]
In our app, we ran into a case where we need to multiply a Luxon `Duration` object by a number before adding it to another number. It would be awesome if there were a multiply method that took in a number and returned the duration multiplied by that number. Here's a simplified example of what we'd like:

``` javascript
Duration.fromObject({ hour: 1 }).multiply(5);
```

I realize in this example you could put the 5 in the object, but in our case, it makes sense to have this behavior.

**Comment by GillesDebunne** [comment]
This looks like a valid request with practical use cases. The implementation seems straightforward (simply multiply all units by the coefficient).

**Comment by icambron** [comment]
Could also have a `unitMap` method that lets you do `dt.mapUnits(u => u * 5)`

**Comment by icambron** [comment]
Fixed by #592
