### ISSUE TITLE
Wrong long name when different locale

### ISSUE THREAD

**Issue by arxeiss** [moment/luxon#559]
**System**: Ubuntu 19.04
**Luxon**: v1.17.2

On my computer, Luxon probably takes locale from my computer settings, because it is set to `cs-CZ`. However there is no translation, and then long names doesn't work as expected.

```javascript
// By default locale is cs-CZ because of my computer settings
DateTime.local(2017, 10, 30).weekdayLong // Mon
DateTime.local(2017, 10, 30).setLocale('en-US').weekdayLong // Monday
```

**Comment by arxeiss** [comment]
Sorry, I'm using NodeJS, not browser.
**node -v**: v12.9.0

Here is what I did now:
```bash
npm init
npm install --save luxon
node
> const { DateTime } = require("luxon");
> DateTime.local().locale
'cs-CZ'
> DateTime.local(2017, 10, 30).weekdayLong
'Mon'
```

I don't understand it..

**Comment by arxeiss** [comment]
So I did some digging and found out it is probably problem of Node/my computer.

```js
new Intl.DateTimeFormat('cs-CZ', { weekday: 'long', timeZone: 'UTC' }).formatToParts(new Date('2017-10-30'))[0].value; // Mon
```
If I did the same in Google Chrome console, it returned Pondělí correctly
So you can close this as this is not relative to Luxon..

**Comment by arxeiss** [comment]
I understand it doesn't know Czech word, but I don't understand why I'm asking for long name and it gives me short name. The fact, it is in English is OK.

I asked already in Node issues(nodejs/help#2150), but they said it is behaviour of ICU module.
I don't think it is acting correctly, but I have no idea where to report this, so I have to get used to it...

**Comment by icambron** [comment]
Oh, yeah, the "Mon" vs "Monday" thing is weird. Unfortunately, I have no idea how to report that either
