### ISSUE TITLE
plus function not updating DateTime object for seconds (or due to referencing the object)

### ISSUE THREAD

**Issue by RealHandy** [moment/luxon#569]
I use plus() to add minutes in various places -- it works fine. But I had to debug through the code to understand why this line to update the DateTime to 0 seconds of the next minute didn't work for me:
`startTime.plus({seconds:60 - startTime.second});`

There's enough going on in there that I'm not sure what exactly is up, but I did confirm that the addition is happening, but somehow the object isn't getting updated. So I went with this, which worked:
`startTime = startTime.plus({seconds:60 - startTime.second});`

I don't think it could be related to my referencing startTime.second in the param of plus(), so I guess it's just an issue with seconds?

DateTime is great, btw -- it really takes the pain out of a lot of date/time work!

**Comment by GillesDebunne** [comment]
Hello,

Every object in luxon is **immutable**, and all the mutation operations (such as `plus`) indeed *return a modified object*, without altering the object on which they are applied.

This means that you must *always* use this pattern `d = d.plus(...)`. This has nothing to do with `seconds` in that case.

BTW, you can achieve the same result in your case with `startTime = startTime.startOf('minute')`.

**Comment by RealHandy** [comment]
Uh, yeah. I knew that. I must've been really tired. Sorry to have wasted your time!
