### ISSUE TITLE
Errors on FB App Windows 10

### ISSUE THREAD

**Issue by chaffeqa** [moment/luxon#571]
Hard for me to know about support, but we are consistently getting windows10 issues with this report:

https://sentry.io/share/issue/feea7007054f41b5954623ba1a09caf8/

Let me know if you need more info to reproduce, on our end unfortunately we don't have enough time to debug it, sorry :(

**Comment by GillesDebunne** [comment]
Thanks a lot for this feedback. I love sentry's reports, I think I found a possible problem.

Can you run `new Intl.DateTimeFormat().resolvedOptions().locale` on this system? My guess is that it returns `undefined`, which is not handled properly in the code.

**Comment by chaffeqa** [comment]
I'll try, I have a windows10 VM ill try it on, hopefully its not Facebook App specific which will be harder for me to replicate.

I may also try to add the polyfill (just read about it: https://moment.github.io/luxon/docs/manual/matrix.html#internet-explorer-and-platform-polyfills)

Think that may help?

**Comment by chaffeqa** [comment]
user agent:
```Mozilla/5.0 (Windows NT 10.0.17134.523; osmeta 10.3.31799) AppleWebKit/602.1.1 (KHTML, like Gecko) Version/9.0 Safari/602.1.1 osmeta/10.3.31799 Build/31799 [FBAN/FBW;FBAV/186.0.0.83.783;FBBV/143636256;FBDV/HPNotebookX0H94UA#ABA;FBMD/HP Notebook;FBSN/Windows;FBSV/10.0.18362.329;FBSS/1;FBCR/;FBID/desktop;FBLC/en_US;FBOP/45;FBRV/0]```

**Comment by chaffeqa** [comment]
Looks like its fine on non-fb app possibly:
<img width="732" alt="Screenshot 2019-09-13 07 58 54" src="https://user-images.githubusercontent.com/287640/64860837-5c635780-d5fc-11e9-9dc8-d081639fcf1e.png">

**Comment by GillesDebunne** [comment]
It may depend on the browser version.
Can you reproduce the issue on this VM?
I may try to fix the potential problem, even if there are no repro cases, since it depends on the browser's config.

**Comment by chaffeqa** [comment]
I have a repro!!! It **is** the facebook app only! but that probably also means most other apps on IE10 / 11 because they all use the same browser I am guessing.

Unfortunately I cannot open the developer tools in the app browser (dangit FB!) but i was able to see the error that didnt occur in the regular system browser:

<img width="1237" alt="Screenshot 2019-09-13 08 27 30" src="https://user-images.githubusercontent.com/287640/64862465-959dc680-d600-11e9-9ba7-2f2e20604957.png">

**Comment by GillesDebunne** [comment]
Ok. I guess I'll try to blindly fix this.

**Comment by chaffeqa** [comment]
Confirmed! that fixed everything on the site!

Thanks a ton @GillesDebunne  🎉
