### ISSUE TITLE
Default locale doesn't work in jest tests

### ISSUE THREAD

**Issue by RakhmatovR** [moment/luxon#573]
I'm writing tests to see an expected time from a particular component, but tests don't recognize default locale.

Example:
```ts
import { DateTime, Settings } from 'luxon';

test('locale is de -> should return time in correct format', () => {
    Settings.defaultLocale = 'de';

    const time = DateTime.fromMillis(13 * 60 * 60 * 1000, { zone: 'utc' })
                         .toLocaleString({ hour: '2-digit', minute: '2-digit' });

    expect(time).toEqual('01:00 PM'); // Should be 13:00
});
```

What am I doing wrong?

**Comment by icambron** [comment]
My guess is that your node env doesn't have the ICU data and is falling back to en-US

**Comment by RakhmatovR** [comment]
@icambron Seems like, you're right. Fixed it with:
1. `npm i -D full-icu`
2. `node --icu-data-dir=node_modules/full-icu node_modules/jest/bin/jest.js`
