### ISSUE TITLE
toJSDate is wrong for years before 1884

### ISSUE THREAD

**Issue by taylorgoolsby** [moment/luxon#575]
![image](https://user-images.githubusercontent.com/14286600/65355720-6dd1d400-dba7-11e9-9281-5fef373fc7b6.png)

It's expected that `luxon.DateTime.fromObject({year: 1883}).toJSDate()` return something like `Jan 01 1883 00:00:00`.

**Comment by icambron** [comment]
Yeah, there is a known issue here. Historical timezones with seconds in their offsets confuse Luxon.  In this example, in your timezone, in 1882, your UTC offset was 7 hours, 52 minutes, and 58 seconds, which was then changed in 1884 to the standard 8 hours, as you can see in the screenshot below.

<img width="809" alt="Screen Shot 2019-09-20 at 22 10 33" src="https://user-images.githubusercontent.com/244988/65366568-a7303100-dbf3-11e9-9871-9c017be3ad82.png">

See also #401, which is the same issue, but for 19th century Spain. Unfortunately, we just aren't going to be able to fix this until there's a way to ask a local time to tell us its offset with second precision.
