### ISSUE TITLE
Wrong interval divideEqually type definition or behaviour

### ISSUE THREAD

**Issue by ianbytchek** [moment/luxon#582]
Apparently type definitions allow skipping the value, but [the lib doesn't](https://github.com/moment/luxon/blob/bc407f8b0488b766c81769cac473ae0e53175d28/src/interval.js#L349):

```ts
divideEqually(numberOfParts?: number): Interval[];
```

Perhaps it should? After all, dividing equally without the number of parts implies the outcome.

**Comment by GillesDebunne** [comment]
This is a typo in the current `.d.ts`, the parameter is mandatory. This is fixed in the 2.0 branch.
