### ISSUE TITLE
hasSame order matters / timezones are not working with hasSame

### ISSUE THREAD

**Issue by Absor** [moment/luxon#584]
I noticed that when I compared two DateTime objects with hasSame the ordering of the objects returned different results. It seems to only happen when at least one of the objects has a timezone defined.

I managed to reproduce it, let the code speak for itself:

```
// With zones
const first = DateTime.fromISO("2019-10-02T07:24:04.339+03:00", {
  zone: "Europe/Helsinki"
});
const second = DateTime.fromISO("2019-10-02T00:00:00.000-05:00", {
  zone: "America/Chicago"
});

console.log(first.hasSame(second, "day")); // true
console.log(second.hasSame(first, "day")); // false
console.log(first.toISO()); // 2019-10-02T07:24:04.339+03:00
console.log(second.toISO()); // 2019-10-02T00:00:00.000-05:00

// No zones
const third = DateTime.fromISO("2019-10-02T07:24:04.339+03:00");
const fourth = DateTime.fromISO("2019-10-02T00:00:00.000-05:00");

console.log(third.hasSame(fourth, "day")); // true
console.log(fourth.hasSame(third, "day")); // true
console.log(first.toISO()); // 2019-10-02T07:24:04.339+03:00
console.log(second.toISO()); // 2019-10-02T08:00:00.000+03:00
```

**Comment by icambron** [comment]
Yeah, this is definitely a bug. It's doing this:

```js
      const inputMs = otherDateTime.valueOf();
      return this.startOf(unit) <= inputMs && inputMs <= this.endOf(unit);
```

which is asymmetrical because `startOf` and `endOf` work on the dates time zone but milliseconds are absolute. Clearly it should be symmetrical,  but I need to figure out how it _should_ work.

**Comment by icambron** [comment]
Ok, so with a little bit of time to think this through: the question is, what should be behavior be when `hasSame` is run across time zones? There are two options:

1. Does the other time have the same [unit] when translated to this zone?
2. Does the other time have the same [unit] in its zone as this one does in *its* zone?

Neither answer is wrong, but I believe 2 is more useful, because:

A. if you want the behavior from 1, you need only change zone
B. for non-hour-aligned offsets (e.g. IST), the comparison is awkward in 1

I'm open to feedback on that reasoning. I'd especially love to hear appeals as to why 1 is more useful for various use cases. But at any rate, assuming we go with option 2, the fix is simply to check that they have the same value for that unit.

**Comment by Absor** [comment]
I also agree that 2. is more useful. Does checking for the same unit mean that only that unit is checked, e.g. if comparing days it only checks that the day are the same and not months and years? If that is the case I think it would be necessary to add at least hasSame "date" comparison which would check year, month and day.

**Comment by icambron** [comment]
> e.g. if comparing days it only checks that the day are the same and not months and years?

No, good point, will need to check everything higher-order too. I guess we could also rezone the other datetime and startOf() both sides and then compare the timestamps

**Comment by Absor** [comment]
I checked moment's `isSame` comparison and it works the similarly to Luxon's `hasSame` "If the two moments have different timezones, the timezone of the first moment will be used for the comparison." Luxon's asymmetry is just undocumented.

I'm not sure if asymmetry is the right way to go in a comparison method like this as does not feel natural, `hasSame` sounds like equality check. I think that both options should be supported in some way as there is probably a case where you want the timezones adjusted before comparison and a case where you don't.

**Comment by sebastianvoss** [comment]
We recently got bitten by this in the context of daylight saving. We were filtering a list of items by `item.date.hasSame(today, 'day')`. We changed the filter condition to `item.date.toISODate() === today.toISODate()` for now to avoid the problem. But it would be great if this could be somehow improved.

**Comment by icambron** [comment]
It could be! I just need a PR.
