### ISSUE TITLE
TIME_24_SIMPLE constant not defined as expected

### ISSUE THREAD

**Issue by gothill** [moment/luxon#585]
The project [documentation](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html) states that the `TIME_24_SIMPLE` constant 

> defines a toLocaleString format like '09:30', always 24-hour.

In reality, `TIME_24_SAMPLE` is defined differently (`impl/formats.js`):

```
export const TIME_24_SIMPLE = {
  hour: n,
  minute: d2,
  hour12: false
};
```

The hour has `n` for format, i.e., it is numeric ('9:30'), not double-digit ('09:30') as defined by [Date.prototype.toLocaleString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#Syntax)

Unless I'm wrong, either the documentation or `TIME_24_SIMPLE` is incorrect. Personally, I would prefer to have two digit hours as the documentation leads me to expect.

Codesandbox [here](https://codesandbox.io/s/luxon-playground-xwgg7)
Tested with Google Chrome 77 and luxon 1.19.3
Note: I couldn't reproduce this in node.js

**Comment by icambron** [comment]
Yeah, what's happening is that it's supposed to be "9:30" but older versions of v8 produced "09:30" (both Chrome and Node) so that's what I documented. Looks like Chrome fixed it and Node will inherit the fix eventually. We should go ahead and update the docs.

As for what it should _actually_ do, it's obviously a matter of opinion, but I tend to prefer "9:30" for this.

**Comment by gothill** [comment]
You might want to reconsider your preference here. The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) actually requires leading zeros for a 24 hour date format. I think there is a good reason for that, namely that 2:34 can easily be misinterpreted as 2:34pm but 02:34 cannot. It's also the standard format for 24 hour time on digital clocks.

If you do decide to keep the format as it is, would you consider adding a new 24 hour constant with leading zeros for users who need it?

**Comment by icambron** [comment]
The ISO standard isn't relevant here; it's not a localized string. And in general, we should always use "numeric" and let the locale decide how it wants to display it, which may or may not pad.

But I do take back the part about Chrome fixing things. In fact its behavior here is just weird:

```js
new Intl.DateTimeFormat("en", { hour: "numeric", minute: "numeric", hour12: false } ).format() //=> 04:22

new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit", hour12: false } ).format() //=> 04:23

new Intl.DateTimeFormat("fr", { hour: "numeric", minute: "numeric", hour12: false } ).format() //=> 04:25

new Intl.DateTimeFormat("fr", { hour: "numeric", minute: "2-digit", hour12: false } ).format() //=>
4:24
```

So what's happening there is that in some locales the *minute* settings is affecting what the hour does. Using "numeric" for the minute setting is proper, which would in fact get you 04:24, at least in French. So I would take _that_ change.

Note that in many locales (such as `es`) it will still use a single-digit hour

**Comment by icambron** [comment]
I made that "2-digit" -> "numeric" change in #593. You may be particularly interested in the test cases: https://github.com/moment/luxon/pull/593/files#diff-3fa15d157860d1e582b70e7a84714c28R291
