### ISSUE TITLE
Why are there extra commas in the pre-defined formats?

### ISSUE THREAD

**Issue by deepakanand** [moment/luxon#586]
I noticed that that formatted datetime strings have commas where i did not expect and also diverges from moment.js. I am curious to understand the rationale of this design
Example: 
DATETIME_MED From the documentation
https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-get-DATETIME_MED
formats like so:
`Oct 14, 1983, 9:30 AM`

Whats the reason for the comma after 1983 ? I did not expect that

**Comment by icambron** [comment]
It's debateable in general, but it's not up to Luxon anyway. That's just what Intl does:

```
new Intl.DateTimeFormat("en", { year: "numeric", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format()

//=> "Oct 2, 2019, 1:07 PM"
```

**Comment by deepakanand** [comment]
Thanks for the quick response. I understand better now.
