### ISSUE TITLE
Cannot compare  DateTime to  DateTime with flow

### ISSUE THREAD

**Issue by serkankaracasulu** [moment/luxon#587]
` var d1 = DateTime.fromISO("2017-04-30");
  var d2 = DateTime.fromISO("2017-04-01");
  if (d2 < d1) {
    //something
  }`

flow gives this error :

> Cannot compare  `DateTime` [1] to  `DateTime` [1].

**Comment by icambron** [comment]
I don't know Flow, but in JS, < automatically casts both sides to numbers by calling `valueOf`. You can do that cast manually like this:

```
+d2 < +d1 //shorthand

d2.valueOf() < d1.valueOf() // longhand
```

Presumably, Flow will understand that those operations return numbers and allow the comparison.

**Comment by serkankaracasulu** [comment]
> `d2.valueOf() < d1.valueOf()`

it works, thanx
