### ISSUE TITLE
.toLocaleString() output different on Android than on iOS

### ISSUE THREAD

**Issue by rdewolff** [moment/luxon#588]
When using `myDateTime.toLocaleString({ weekday: 'short', day: 'numeric', month: 'short' })` I get two different output on Android on iOS.

1. On iOS 10.3.1, I get : `Mon, Sep 30`.
2. On Android Pixel 2 API 29 I get : `Monday, September 30, 2019, 12:00 AM`.

To fix this different behaviour on the 2 platforms, I use the alternate `.toFormat('ccc, LLL M')`

I wish to understand why this is happening.

We are using Luxon version 1.13.0.

**Comment by icambron** [comment]
Can you try this on each of those platforms?

```js
new Intl.DateTimeFormat("en", { weekday: 'short', day: 'numeric', month: 'short' }).format()
```

and tell me what you get?

**Comment by icambron** [comment]
Closing for age. If you end up answering that question, I'll reopen.

**Comment by Aryk** [comment]
@icambron I'm getting this exact issue. Wonder if @rdewolff solved it somehow.

**Comment by rdewolff** [comment]
Ended up using `DateTime.DATETIME_MED` or any other constants provided by `DateTime`.

**Comment by MrSnoozles** [comment]
Same issue here with Android  API 29.
Using `.toLocaleString({month: 'short', day: 'numeric'});`  returns `Thurday, November 19, 2020, 12:00 AM`

**Comment by NilsBaumgartner1994** [comment]
Same problem still having
