### ISSUE TITLE
Drop support for Node 6 and IE 11

### ISSUE THREAD

**Issue by icambron** [moment/luxon#594]
In 2.0 we should formally drop support for Node 6 and IE 11. Some notes:

  1. I have lost track of which polyfills are needed where. Generally, I would like to eliminate the scenarios in which Intl is available but `formatToParts` is not. This includes Node 6 and IE 11, but possibly also Safari 10?
  2. I am not against creating some take-it-or-leave-it documentation for getting IE 11 or Node 6 to work (e.g. here are some polyfills). I just want to a) remove any code specifically built to support them and b) remove it from the mainline documentation and build tooling
 3. We can bump a bunch of the babel targeting for Node

**Comment by dhuang612** [comment]
I want to work on this
