### ISSUE TITLE
I confuse to set string date to luxon object

### ISSUE THREAD

**Issue by zeing** [moment/luxon#598]
I confuse to set string date to luxon when I have date string (22/10/2019) which has "DD/MM/YYYY" format.
So I use
 ```
DateTime.fromFormat(start, "DD/MM/YYYY")
```
for convert string date to luxon object then I get an error `` the input "22/10/2019" can't be parsed as SQL ``

How to handle the problem? 

Thank you.

**Comment by icambron** [comment]
I don't know how you get an error about SQL (are you sure that's really the error message you got?), but "DD/MM/YYYY" is wrong; you want "dd/MM/yyyy":

```js
DateTime.fromFormat("22/10/2019", "dd/MM/yyyy").toISO() //=> "2019-10-22T00:00:00.000-04:00"
```

**Comment by zeing** [comment]
thank you
