### ISSUE TITLE
Datetime toFormat with weekday changes the luxon object

### ISSUE THREAD

**Issue by hadrian625** [moment/luxon#601]
I used in our code luxon date objects kept in vuex store.
Using the "en" locale, when trying to do date.toFormat("cccc, dd.LL.yyyy"), vuex started to complain that objects in store are modified outside use of mutations.
![image](https://user-images.githubusercontent.com/37671580/67557245-64df9f80-f71d-11e9-87d8-8e77b5e1251b.png)

I think the problem resides in this piece of code from datetime.js
function possiblyCachedWeekData(dt) {
  if (dt.weekData === null) {
    dt.weekData = gregorianToWeek(dt.c);
  }
  return dt.weekData;
}

Here the datetime object is modified by setting the weekData on it. Should this be fixed, or people should no use the luxon objects from vuex store?

Regards

**Comment by icambron** [comment]
See #323. The outcome there is still right:

> If there's some way I can modify this library to make tools like Vuex ignore private state, I'd be happy to make them. In the meantime, Luxon has to keep private caches to make perf tolerable.

**Comment by hadrian625** [comment]
I understand your point. As I am not very good at javascript, I can't provide a suggestion for a fix. I can say that in order to bypass the problem I had to change the luxon date in the vue template (I used date.plus({ day: 0 }) ) so that the toFormat is not applied to the object in vuex store. But, I guess, this way I gave up to using the cache.
Maybe there was a way to keep that cache outside the Luxon datetime object. Don't have any other idea.

**Comment by icambron** [comment]
I'm going to close this. I'll reiterate that if anyone knows Vuex's privacy conventions, I'd be happy to implement them, but there's nothing to do here until I know what to do there.

**Comment by dm-CaT** [comment]
The same situation in Angular NGRX. :(

**Comment by dm-CaT** [comment]
Here is the workaround I used in Angular with NGRX but it could be used anywhere.

```TypeScript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import * as lx from 'luxon';
import * as lxt from '../node_modules/luxon/src/impl/conversions.js';


if (environment.production) {
  enableProdMode();
} else {

  // Dirty hack to pass strictStateImmutability check from ngrx (https://ngrx.io/guide/store/configuration/runtime-checks).
  // Remove when the https://github.com/moment/luxon/issues/601 or similiar will be fixed.
  Object.defineProperty(lx.DateTime.prototype, 'weekData', {
    enumerable: false,
    get(this: lx.DateTime) {
      return lxt.gregorianToWeek(this);
    },
    set() { }
  });

}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));


```
