### ISSUE TITLE
open-ended intervals

### ISSUE THREAD

**Issue by RobMayer** [moment/luxon#606]
Potentially a hassle, but it'd be useful to be able to construct an interval with only one endpoint.

**Comment by icambron** [comment]
It definitely sounds useful, but I'm afraid it's out of scope for Luxon.

**Comment by sedx** [comment]
Have same need. I read source code and found some hacky solution:
```js
const interval = new Interval({
    start: DateTime.local(),
    end: DateTime.invalid("has no end"),
})

```
But it produce the valid range with bunch of unexpected behaviour during interval's operation.

@icambron Can we back to this question?

In my case I want to keep values of ranged DatePicker as Interval. I used `[DateTime, DateTime]` tuple before, but now I need to merge selected ranges (`Interval.merge` is very helpful there). In some cases (for example when user pick only one date, or we have not information about interval's end or start on server) I can't create valid interval, so I still need to use tuple and each time (when interval is valid) coerce it to Interval for manipulation.

I can create tests and make PR with some changes (based on sandbox draft) if you give a chance. As marker of endless we can use invalid DateTime and invalid Duration so public API will not changed. Just aded new member `isFinite` to track has interval start and end or not.

Sandbox code is not tested and just as sample of PR vector 😉

[![Edit luxon-interval-patch](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-bhaskara-pvbno?fontsize=14&hidenavigation=1&module=%2Fsrc%2Findex.js)

**Comment by GillesDebunne** [comment]
I can see the point for open-ended intervals, but the entire source code should thoroughly be checked with those in mind...

We need to make sure that at least one boundary is always set, and that ALL operations preserve this invariant. Also note that the notion of `invalid` is removed in the upcoming version 2. Using `null` or a specific constant might be a replacement.

**Comment by RobMayer** [comment]
I don't mind putting in the effort, but I can't say that I know what the heck I'm doing. Still, if the leaders say there's no point, then I'm not going to bother and work around it locally, so if this has merit enough to alter the scope, then I'm down.

**Comment by LosD** [comment]
@icambron Im sorry, but that was not much of an explanation, how is it "out of scope"? Luxon represents intervals, ISO 8601:2019 has open-ended intervals (true, as an extension, but still), so I don't see why it would be out of scope.
