### ISSUE TITLE
How to get the current UTC time even if your browser timezone is different?

### ISSUE THREAD

**Issue by peteringram0** [moment/luxon#613]
Everything i seem to try seems to be wrong when i put my browser into a different timezone and call DateTime.local().toUTC()

I would expect the value to be the exact same regardless of timezone the browser is in?

**Comment by GillesDebunne** [comment]
Changing the timeZone, as `toUTC()` does, does not change the instant in the history of the universe. So unless your system's time zone happens to be synced with UTC, calling `toUTC()` will change the displayed hour.

`DateTime.local().toUTC()` is indeed the way to know the current time, expressed in UTC.

```
luxon.DateTime.local().toISO() // "2019-11-04T20:17:39.706+01:00"
luxon.DateTime.local().toUTC().toISO()  // "2019-11-04T19:17:40.529Z"

// Change system TimeZone to Kazastan

luxon.DateTime.local().toISO() // "2019-11-05T01:20:26.533+06:00"
luxon.DateTime.local().toUTC().toISO() // "2019-11-04T19:20:31.267Z"
```

As you can see, the UTC time (around 19:20 in my case) does not depend on the TZ of my system.

**Comment by icambron** [comment]
@peteringram0 You'll need to provide us a reproduceable example

**Comment by peteringram0** [comment]
@GillesDebunne Thanks you are correct, i was using a chrome plugin to mock a timezone which i think it was wrong and throwing me off, if i set the timezone at OS level this does seem to work and gives me the same UTC time as per your example above. Thanks
