### ISSUE TITLE
Wrong timezone America/Sao_Paulo

### ISSUE THREAD

**Issue by itreinei** [moment/luxon#614]
I'm getting -02:00. The correct timezone is -03:00.

**Comment by icambron** [comment]
You need to upgrade your browser and/or operating system, which still thinks there's a DST in Brazil. Luxon only knows what the browser knows.

**Comment by un-versed** [comment]
That's still wrong when I'm deploying to Heroku.

When I run `heroku run date +"%Z %z"`, the answer is  `-03 -0300`, but `DateTime.local()` returns `'2019-11-20 19:11:10.430 -02:00'`

There's an issue with Node.js itself?

My node version is `v12.13.1`

**Comment by icambron** [comment]
@un-versed Probably so. I haven't tried that specific version of Node, but you can test it directly like this:

```js
> new Intl.DateTimeFormat("en", { timeZone: "America/Sao_Paulo", timeZoneName: "short" }).format(new Date())
'11/21/2019, GMT-2'
```

You can see I get -2 there, where you expect -3. That's what Luxon sees too.
