### ISSUE TITLE
Different results in toDuration calculations

### ISSUE THREAD

**Issue by gonzofish** [moment/luxon#618]
I'm getting different output when calculating a `Duration` from an `Interval` created from two `DateTime`s

Here's the example (tested in-console from the Luxon docs):

```javascript
var date1 = luxon.DateTime.local(2018, 11, 12);
var date2 = luxon.DateTime.local(2019, 11, 11);
var interval = luxon.Interval.fromDateTimes(date1, date2);
var dur1 = interval.toDuration(['days', 'months', 'years']);
var dur2 = interval.toDuration(['days', 'weeks', 'months', 'years']);

// outputs: 365
console.info(dur1.as('days'));
// outputs: 367
console.info(dur2.as('days'));
```

Here it is in Codepen: https://codepen.io/gonzofish/pen/LYYJZPJ

I also tried using `.normalize()` off each of those durations, which gave the same output. Not sure if I'm doing something wrong or misunderstanding some concept, but just adding `weeks` seems to cause an issue.

If there's more info or anything I can do to help, let me know.

**Comment by icambron** [comment]
Please see https://moment.github.io/luxon/docs/manual/math.html#losing-information. You may also find the section above it about conversion accuracy to be relevant. I think the docs address the issue pretty directly, but lmk if it's not adequately clear why you're seeing this behavior and what to do about it.

**Comment by gonzofish** [comment]
Ah thanks @icambron my bad. Thanks for the clarification!
