### ISSUE TITLE
Possibly reversed +/- sign in toHTTP function for time zone calculation ?

### ISSUE THREAD

**Issue by felixunivers** [moment/luxon#620]
I understand that functions fromHTTP and toHTTP always represent UTC zone.
But I would argue that the output still misrepresents the provided time value.

Lets run some tests on local time zone: America/Vancouver, offset: -480 ( minus -8 hours)

```

    // UTC time:
    dtU = DateTime.utc(1970, 1, 1);
    console.log('-- 1:  dtU = DateTime.utc(1970, 1, 1);         ' + dtU.toRFC2822());    
    console.log('-- 2:  dtU = DateTime.utc(1970, 1, 1);         ' + dtU.toHTTP());

    // local time
    dtL = DateTime.local(1970, 1, 1);
    console.log('-- 3:  dtL = DateTime.local(1970, 1, 1);       ' + dtL.toRFC2822());
    console.log('-- 4:  dtL = DateTime.local(1970, 1, 1);       ' + dtL.toHTTP());

```

will output:
-- 1:  dtU = DateTime.utc(1970, 1, 1);         Thu, 01 Jan 1970 00:00:00 +0000
-- 2:  dtU = DateTime.utc(1970, 1, 1);         Thu, 01 Jan 1970 00:00:00 GMT

-- 3:  dtL = DateTime.local(1970, 1, 1);       Thu, 01 Jan 1970 00:00:00 -0800
-- 4:  dtL = DateTime.local(1970, 1, 1);       Thu, 01 Jan 1970 08:00:00 GMT

In case of output 3: the function .toRFC2822() correctly indicates minus  -0800 hours offset.

In case of output 4: the function .toHTTP() increments the date / time by 8 hours.
This, in my opinion is incorrect. The offset should be subtracted and output should be:

    Wed, 31 Dec 1969 16:00:00 GMT

**Comment by icambron** [comment]
No, the offset answers "with what offset is this time expressed?", not "what should we add to the current time?" Vancouver is 8 hours *behind* GMT, so when it's some particular local time in Vancouver, the local time in England is 8 hours later. So when Luxon converts to GMT to provide the HTTP date, it advances the hours by 8.

**Comment by felixunivers** [comment]
I get it. Thanks for the explanation. Perhaps something similar in to the documentation of the functions ... ?

**Comment by icambron** [comment]
Unfortunately, can't explain everything in every method. It's not really about those methods anyway; it's just how offsets work.
