### ISSUE TITLE
Add Duration.fromHTMLTime()

### ISSUE THREAD

**Issue by munierujp** [moment/luxon#625]
Value of HTML's `<input type="time">` have below patterns:

- `hh:mm`
- `hh:mm:ss`
- `hh:mm:ss.S`
- `hh:mm:ss.SS`
- `hh:mm:ss.SSS`

These are expressed as below regular expression:

```
/^(\d{2}):(\d{2})(:(\d{2}))?(\.(\d{1,3}))?$/
```

cf. https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#times

## My idea
*Not tested*

### Implemention

```js
function fromHTMLTime (text) {
  const matched = text.match(/^(\d{2}):(\d{2})(:(\d{2}))?(\.(\d{1,3}))?$/)

  if (!matched) {
    return Duration.invalid('unparsable', `the input "${text}" can't be parsed as HTML time`)
  }

  const getValue = index => matched[index] ? Number(matched[index]) : 0
  const hours = getValue(1)
  const minutes = getValue(2)
  const seconds = getValue(4)
  const milliseconds = getValue(6)
  return Duration.fromObject({
    hours,
    minutes,
    seconds,
    milliseconds
  })
}
```

### Usage example

```html
<input type="time" id="time" value="13:30">
```

```js
const timeElement = document.getElementById('time')
const value = timeElement.value  // "13:30"
const duration = Duration.fromHTMLTime(value)
```

**Comment by icambron** [comment]
A couple thoughts on this:

 * It's not clear to me that HTML time is meant to specify a duration, as opposed to a specific time on some (externally-provided) date, i.e. it seems like `13:30` means the time, as opposed to a period of 13 hours and 30 minutes.
 * As a *time*, it's just an ISO time and the `fromISO` method handles, though of course it returns a `DateTime`, not a `Duration`

I'm not against providing ISO-like parsing for durations, I just don't think it really has much to do with HTML Time.

**Comment by icambron** [comment]
Let's do this:

```
Duration.fromISOTime("13:30");
Duration.fromISOTime("13:30:30");
Duration.fromISOTime("13:30:30.1");
Duration.fromISOTime("13:30:30.12");

**Comment by thomas-darling** [comment]
@icambron We'd _really_ like this too. Do you have any idea when support for this might land?

Also, I'm not sure we need a new method name for this - I'd suggest just adding support for this to the existing `fromISO` method. The time format is just as much part of ISO-8601 as the duration format, and they are easy to distinguish, as the duration format always begins with a `P`.

**Comment by thomas-darling** [comment]
@munierujp Why would you call the method that?
The format pattern is defined in ISO-8601 and has nothing to do with HTML - the time input just follows the ISO spec 🙂

**Comment by thomas-darling** [comment]
Hmm, on a second thought, I actually agree with @icambron regarding the name.

The best name for this would be `fromISOTime(...)` - and then I'd suggest we also add a corresponding `toISOTime()`, so we can do a full roundtrip in this format.

This does raise a question though:
While all ISO times can be represented as durations, not all durations can be represented as ISO times, as that format is limited to 24 hours. I think the solution here is to simply throw an error if `toISOTime()` is called on a duration that is longer than 24 hours...

Also note that according to https://en.wikipedia.org/wiki/ISO_8601#Times, the time format has changed slightly in the latest version of the spec. Basically, it may now start with a `T` - and if the value could be confused with a date, the `T` is required.

So, the format is essentially `Thh[mm][ss][.sss]` in the short form and `[T]hh[:mm][:ss][.sss]` in the extended form.
Maybe `toISOTime()` should accept options for whether to omit the `T` when possible, and whether to use the short or extended form - but on the other hand, the pragmatic choice might be to just always use the form `hh:mm[:ss][.sss]`
