### ISSUE TITLE
Start/end of X

### ISSUE THREAD

**Issue by TomasHubelbauer** [moment/luxon#626]
> Luxon lacks the relative time features of Moment and won't support it until the required facilities are provided by the browser.

*Relative time features* includes what, specifically? Is `startOf` and `endOf` available in Luxon? Reading through the documentation would have me believe so, but I'd like to double-check.

**Comment by icambron** [comment]
Yes, startOf and endOf are available.

Relative time is stuff like formatting a date as "next week". Luxon does now have some limited support for that too, at least in newer browsers.
