### ISSUE TITLE
Is it normal that difference between time results in 59 minutes rather than 1 hour? 

### ISSUE THREAD

**Issue by paufar** [moment/luxon#631]
I am using the following code to get the difference between two times.
```
var end = DateTime.fromISO(endTime.toISOString());
        var start = DateTime.fromISO(startTime.toISOString());
        const diff = end.diff(start, ['hours', 'minutes']);
        console.log(diff.values.hours, diff.values.minutes);
```

For some reason the first time i inputted the two values 5:00 PM and 6:00 PM, the answer was: 

```
hours: 0  minutes: 59.9922
```

When i tried it again the answer was 1 hour as expected. Is this something normal when dealing with difference between time? Is there a way to avoid it eg using a round function that works with all answers?

**Comment by icambron** [comment]
I can't reproduce this:

```js
var end = DateTime.fromISO("2019-12-19T06:00:00");
        var start = DateTime.fromISO("2019-12-19T05:00:00");
        var diff = end.diff(start, ['hours', 'minutes']);
        console.log(diff.values.hours, diff.values.minutes); //=> prints 1 0
```

Are you sure you're establishing the end time and start time correctly?

**Comment by paufar** [comment]
@icambron I am using this time picker to obtain the time https://reactdatepicker.com/
and when printing out the start and end time These are the results: 

```
1. start:  Fri Dec 20 2019 08:00:00 GMT+0100 (Central European Standard Time)   end:  Fri Dec 20 2019 09:00:00 GMT+0100 (Central European Standard Time)   hours:  1  minutes:  0.006216666666666666

2. start:  Fri Dec 20 2019 08:30:00 GMT+0100 (Central European Standard Time)   end:  Fri Dec 20 2019 09:30:00 GMT+0100 (Central European Standard Time)   hours:  1  minutes:  0.006216666666666666

3. start:  Fri Dec 20 2019 14:00:00 GMT+0100 (Central European Standard Time)   end:  Fri Dec 20 2019 15:00:00 GMT+0100 (Central European Standard Time)   hours:  0  minutes:  59.98558333333333
```

And the time in the date does not have any seconds listed so not sure what the problem could be ?

**Comment by Atema** [comment]
The seconds in the ISO format are in decimal format with three decimals; the three digits are a number of milliseconds after the hours entered in the datepicker.

So it seems like the issue is with react-datepicker. I found a similar bug in that project(Hacker0x01/react-datepicker#1991), but I'm not sure it's the same one, since the milliseconds in your example are nearly half a second apart.

**Comment by icambron** [comment]
I'm not sure why some of your test results are in the default js date `toString()` format and some are in ISO. For the ones in the tostring format, it isn't showing you the milliseconds, but that doesn't mean they're not there. For the ones you printed in ISO, like @Atema said, you can see extra chunks of milliseconds in there:

start:  2019-12-20T08:30:00.**448**Z   end:  2019-12-20T10:00:00.**439**Z 

In that example there, the start time has 9 more milliseconds than the end, resulting in very slightly less than a 1.5 hour diff. So Luxon is doing what it's supposed to.

Why is the date picker giving you dates that look like that? I don't know. I suspect it's the same issue that Atema linked to.

If you want to use Luxon to work around the issue by stripping the extra milliseconds off the time, you can use

```js
start = start.startOf("second");
end = end.startOf("second");
```
