### ISSUE TITLE
defaultZoneName not changing

### ISSUE THREAD

**Issue by valmack** [moment/luxon#634]
I have this function that I am using in React 16.12 with Luxon 1.21.3

```js
export const setSystemTimezone = (timezone) => {
  Settings.defaultZoneName = timezone;
  console.log(DateTime.local().zoneName);
}
```

When the function is called with any valid timezone ("utc", "America/Los_Angeles", etc.) I always get my system timezone logged `America/New_York`.

Also, my other datetimes are still `America/New_York` when being displayed with

```js
export const formatDatetime = (datetime) => {
  return datetime.toFormat("fff");
}
```

My expectation is that `setSystemTimezone("Europe/Berlin")` would log `Europe/Berlin` and that the other datetimes in my app would have their timestamps changed and display in `GMT+1` upon re-render.

Am I doing something wrong or is this expectation incorrect?

**Comment by icambron** [comment]
The first issue--that the default zone doesn't seem to take for new DateTimes-- is unexpected. In fact, I can't reproduce it. Here is a fiddle of it: https://jsfiddle.net/wemdo92r/. Maybe you have something weird in your environment where Settings is being imported from a separate place from DateTime? I'm just guessing, but it has to be something.

On the second issue, that depends: are you recreating the instances? Changing the default timezone will *not* update existing instances. It only determines the zone for new instances.

**Comment by valmack** [comment]
@icambron I am importing like this
```js
import { DateTime } from 'luxon'
import Settings from 'luxon/src/settings.js'
```

I copied from the top of this page: https://moment.github.io/luxon/docs/class/src/settings.js~Settings.html

**Comment by valmack** [comment]
> On the second issue, that depends: are you recreating the instances? Changing the default timezone will _not_ update existing instances. It only determines the zone for new instances.

Yes I saw the note about not updating existing instances so that makes sense to me now.

**Comment by valmack** [comment]
Changing the import to below worked! Thanks. Gonna close this out.

```js
import { Settings } from 'luxon' // this works
// import Settings from 'luxon/src/settings.js' // this does not work
```

**Comment by icambron** [comment]
Yeah, you were effectively importing from two different Luxons, setting the setting in one and using it from the other.
