### ISSUE TITLE
different values returned between using .as('years') and Duration.years

### ISSUE THREAD

**Issue by leonged** [moment/luxon#636]
import { DateTime } from 'luxon'

const TODAY = DateTime.local() // 12/30/2019 (day of this post)
var d = new Date(`1/1/2004`)
var age1 = TODAY.diff(DateTime.fromJSDate(d), 'years').years //returns 15.996094939592846 (correct)
var age2 = TODAY.diff(DateTime.fromJSDate(d)).as('years') // returns 16.007027299816084 (incorrect)

even though they should be doing the same calculation

**Comment by icambron** [comment]
No, they are not doing the same calculation. See the "losing information" section here: https://moment.github.io/luxon/docs/manual/math.html#losing-information
