### ISSUE TITLE
DateTime.plus(...) with mixed algebraic signs works incorrectly

### ISSUE THREAD

**Issue by PerfectPixel** [moment/luxon#645]
## Description
If doing a calculation on `DateTime` with mixed algebraic signs leads to incorrect results. This is true for example when modifying dates in a way that the target month does not have 30 days or the target year is a leap-year.

## Example
```
// should be 2019-12-09, but is 2019-12-10
DateTime.fromISO('2020-01-08').plus({months: -1, days: 1})
```

## Analysis
Internally, the duration `{months: -1, days: 1}` is shifted to `months, days, milliseconds` and during that it is normalized. During normalization, the algebraic signs are changed and the resulting duration is `{months: 0, days: -29}`. It would be correct if the target month has 30 days, but December has 31 days.

Same issue for leap-years: `{years: -4, days: 1}` is converted to `{years: -3, days: -364}`, should be `days: -365` if the resulting year is a leap year.

## Reproducible example
https://codesandbox.io/s/sleepy-diffie-x761e

## Version
Tested with latest Luxon version (1.21.3)

## Workaround
Add units one by one in the right order: `DateTime.fromISO('2020-01-08').plus({months: -1}).plus({days: 1})`

**Comment by icambron** [comment]
Yeah, I agree that's a bug. We probably just shouldn't normalize there
