### ISSUE TITLE
Request: Allow a variable number of digits for fractions of a second in DateTime.fromISO

### ISSUE THREAD

**Issue by snocorp** [moment/luxon#65]
I'm having an issue where I'm using Go to encode my JSON and it outputs dates in ISO format like `"2017-12-02T05:26:01.302911182Z"` with 9 decimal places but your parser will only allow exactly 3. According to the wikipedia page on ISO8601:

> There is no limit on the number of decimal places for the decimal fraction. However, the number of decimal places needs to be agreed to by the communicating parties. For example, in Microsoft SQL Server, the precision of a decimal fraction is 3, i.e., "yyyy-mm-ddThh:mm:ss[.mmm]".

That being said a generic parser like luxon would be more useful if it were more flexible in its ability to parse ISO-formatted dates. I'm curious if you would be open to adjusting the regex to allow for 1-9 digits.

Here's a version that works for my use case:
```js
const isoTimeRegex = /(?:T(\d\d)(?::?(\d\d)(?::?(\d\d)(?:[.,](\d{1,9}))?)?)?(?:(Z)|([+-]\d\d)(?::?(\d\d))?)?)?$/
```

Happy to submit a PR if that helps.

**Comment by icambron** [comment]
Yeah, I agree. PR welcome
