### ISSUE TITLE
Feature request - function to quickly create ISO8601 stamp without milliseconds

### ISSUE THREAD

**Issue by cyberwombat** [moment/luxon#651]
Unless I am missing something this is how one gets the DateTime without milliseconds:
```
DateTime.utc()
        .startOf('second')
        .toISO({ suppressMilliseconds: true }),
```
Which is rather verbose. So many systems use the ISO8601 format without milliseconds (ex: 2020-01-21T23:03:23Z) that it would be nice to have a faster way to crank these out? maybe a `trimMilliseconds` option or something.

And thanks for the lib - I've tried them all and love this one by far the most.

**Comment by icambron** [comment]
I'd accept a PR for this

**Comment by cyberwombat** [comment]
Coo.. What do you think of creating a dedicated function `toISODateTime()`. ? else I think it would be an option like `trimMilliseconds` though that could create a bit of confusion between that and `suppressMuliseconds'

**Comment by icambron** [comment]
I like the option better. If it's confusing, perhaps `suppressMilliseconds` needs a better name

**Comment by ahmetzambak** [comment]
I'm missing that feature too

**Comment by EzeGmnz** [comment]
The following PR solves this by adding a new parameter https://github.com/moment/luxon/pull/1412

**Comment by TheArKaID** [comment]
@EzeGmnz  Is this not accepted, or am I missing a docs that mentions it?

**Comment by cyberwombat** [comment]
@TheArKaID  its in there. Perhaps not documented - is an option for `toISO` and `toISOTime` on DateTime as well as in Duration methods. See code: https://github.com/search?q=repo%3Amoment%2Fluxon+suppressMilliseconds&type=code

**Comment by TheArKaID** [comment]
> @TheArKaID its in there. Perhaps not documented - is an option for `toISO` and `toISOTime` on DateTime as well as in Duration methods. See code: https://github.com/search?q=repo%3Amoment%2Fluxon+suppressMilliseconds&type=code

Thanks for mentioning it. But, it can only be suppressed if it is zero, isn't?
![image](https://github.com/moment/luxon/assets/35050722/8c83d44b-4d01-47a2-abec-cabe301a39d7)

**Comment by cyberwombat** [comment]
I can’t remember for sure, but you can certainly round down or upOn Jun 2, 2024, at 9:52 AM, Arifia Kasastra R ***@***.***> wrote:﻿

@TheArKaID its in there. Perhaps not documented - is an option for toISO and toISOTime on DateTime as well as in Duration methods. See code: https://github.com/search?q=repo%3Amoment%2Fluxon+suppressMilliseconds&type=code

Thanks for mentioning it. But, it can only be suppressed if it is zero, isn't?
image.png (view on web)

**Comment by cyberwombat** [comment]
@TheArKaID this is how I use it:
```
 DateTime.utc()
    .startOf('second')
    .toISO({ suppressMilliseconds: true })
```

**Comment by diesieben07** [comment]
Closing this, as ti has been implemented as shown above. It's also in the JSDoc for the relevant methods.

@TheArKaID Correct, Luxon will not hide information. If you want to output a timestamp without milliseconds, you have to have a timestamp without milliseconds.

**Comment by FabianoLothor** [comment]
It's weird, but this flag doesn't work for me without `.set({ millisecond: 0 })`, is it derided behavior?

**Comment by cyberwombat** [comment]
@FabianoLothor  been a while but sounds right as this [comment](https://github.com/moment/luxon/issues/651#issuecomment-2143940437) does so. I used ` .startOf('second')` which may do something similar. But been a while!
