### ISSUE TITLE
Feature Request: Duration toString with locale

### ISSUE THREAD

**Issue by Aryk** [moment/luxon#653]
I could also be missing this, but I looked through the documentation. Is there a way to output a written duration in the local language?

So for example you have {hours: 1, minutes: 30} and you set the locale to russian and it will output "полтора часа" russian for 1 and 1/2 hours.

**Comment by icambron** [comment]
There is not. Luxon relies on browser Intl APIs for this sort of thing, and there isn't one for durations. If the standards folks add one, we'll definitely add it to Luxon's durations!
