### ISSUE TITLE
Add support for ISO 8601 basic format to DateTime.toISO()

### ISSUE THREAD

**Issue by mohd-akram** [moment/luxon#656]
From [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601):

> Representations can be done in one of two formats – a basic format with a minimal number of separators or an extended format with separators added to enhance human readability. The standard notes that "The basic format should be avoided in plain text." The separator used between date values (year, month, week, and day) is the hyphen, while the colon is used as the separator between time values (hours, minutes, and seconds). For example, the 6th day of the 1st month of the year 2009 may be written as "2009-01-06" in the extended format or simply as "20090106" in the basic format without ambiguity.

This could be done as a `{ format: 'basic' }` option with the default being `{ format: 'extended' }`. This format is useful when used in a URL.

**Comment by icambron** [comment]
I guess I'm not against it, but what's the use case for this?

**Comment by mohd-akram** [comment]
My current use case is using them in a hyphen-separated path in a URL, like `/foobar-20201201T1234Z`. This makes it easy to separate the datetime and other information in the path. I can also see them being used in filenames where the colon is problematic. Lastly, they can be used in data stores to provide a readable alternative to timestamps while taking less space than the extended version.

**Comment by icambron** [comment]
ok, I'd accept a PR for this
