### ISSUE TITLE
Locale handling

### ISSUE THREAD

**Issue by dkazmer** [moment/luxon#658]
Just wondering why locale is handled locally (Object level) rather than globally as in Moment?
Is it to be able to set one DT object with one locale and another with another? If so why?

**Comment by icambron** [comment]
Moment and Luxon work exactly the same way in this regard. Here is Moment:

```js
m1 = moment().locale("it"); // create a moment and set just its locale. Does not affect other instances
m1.format("ddd") //=> "gio"
moment.locale("fr") //=> Set it globally, affects future instances
moment().format("ddd") //=> "jeu."
m1.format("ddd") //=> "gio", previously created instances unaffected
```

Here is Luxon:

```js
dt = DateTime.local().setLocale("it") // create a moment and set just its locale. Does not affect other instances
dt.toFormat("ccc") //=> "gio"
Settings.defaultLocale = "fr"; //=> Set it globally, affects future instances
DateTime.local().toFormat("ccc") //=> "jeu."
dt.toFormat("ccc") //=> "gio", previously created instances unaffected
```

As for why it allows that -- not everyone is writing a web application

**Comment by MonstraG** [comment]
Hmm, but I am writing a web front end. Can I please have a plugin or a setting, or a guide on how to have the locale handled globally?

**Comment by diesieben07** [comment]
Set `Settings.defaultLocale` to the users locale. Then any DateTime created without an explicitly specified locale will use that locale.

**Comment by MonstraG** [comment]
The thing is that user can change the locale, and time table should be updated, which is cached.

So for now, I guess I'd be sticking with extending prototypes to add formatting function that always uses default locale instead:

```tsx
import { DateTime, DateTimeFormatOptions, Settings } from "luxon";

declare module "luxon/src/datetime" {
	export interface DateTime {
		toLocaleStringGlobal: (formatOpts?: DateTimeFormatOptions) => string;
	}
}

/**
 * Custom ToLocaleString for Luxon, that uses Settings.defaultLocale for localization instead of
 * local value of this variable.
 */
if (!DateTime.prototype.toLocaleStringGlobal) {
	DateTime.prototype.toLocaleStringGlobal = function toLocaleStringGlobal<T>(
		formatOpts?: DateTimeFormatOptions
	) {
		return this.toLocaleString(formatOpts, { locale: Settings.defaultLocale });
	};
}

export {};
```
