### ISSUE TITLE
Wrong date calculation for Asia/Saigon timezone in Chrome

### ISSUE THREAD

**Issue by quanla** [moment/luxon#659]
This code:
```
    const millis = 1581008400000;
    const tz = "Asia/Saigon";
    console.log(new Date(millis));
    console.log(DateTime.fromMillis(millis, {zone: tz}).toObject());
```

Will show in Chrome:
```
Fri Feb 07 2020 00:00:00 GMT+0700 (Indochina Time)
{year: 2020, month: 2, day: 8, hour: 0, minute: 0, …}
```

Which is wrong, day should be 7, not 8

It works correctly in NodeJS or other browsers (Firefox, Safari):
```
2020-02-06T17:00:00.000Z
{
  year: 2020,
  month: 2,
  day: 7,
  hour: 0,
  minute: 0,
  second: 0,
  millisecond: 0
}
```

**Comment by icambron** [comment]
It produces 7 for me in Chrome. What version of Chrome are you in?

Additionally, what does this code return for you?

```js
new Intl.DateTimeFormat("en", { month: "numeric", day: "numeric", timeZone: tz }).format(new Date(millis))
```

**Comment by quanla** [comment]
Chrome Version:
Version 80.0.3987.87 (Official Build) (64-bit)

I use Mac OS, but my customers using Windows is having same issue

Your code returns:
2/7

And the issue is still happening while I execute your code (Intl ...)

Thanks

**Comment by icambron** [comment]
Ah, you probably need to upgrade to the latest Luxon. See #619

**Comment by quanla** [comment]
It's working now. Thanks a lot
