### ISSUE TITLE
How to compare two duration objects?

### ISSUE THREAD

**Issue by kesavkolla** [moment/luxon#663]
I've two duration objects is there any way to compare two durations are same or greater or less.

Eg:

```JS
d1 = Duration.fromObject({hours: 8});
d2 = Duration.fromObject({hours: 7, minutes: 60});
```

How to tell these two are same?

Even let's say I've an array of duration objects and I want to sort them is it possible?

```JS
durations = [Durations.fromObject({minutes: 1000}), Duration.fromObject({hours: 10}), Duration.fromObject({days: 1})];
```
Is it possible to do a natural sorting of them?

**Comment by icambron** [comment]
Just use `Array#sort`. Durations support autocasting to integers, so the sort system handles them just fine. Note that the sort will use the Duration's [conversion accuracy setting](https://moment.github.io/luxon/docs/manual/math.html#casual-vs-longterm-conversion-accuracy) to do the conversion, so for stable results, every duration in the array should use the same accuracy setting.
