### ISSUE TITLE
DateTime#toISO() of local time can result in invalid format (offset "-00:00")

### ISSUE THREAD

**Issue by iStefo** [moment/luxon#665]
I noticed a bug in our application only users in Portugal encountered when sending requests to our server containing ISO formatted dates. We were only able to reproduce it by setting our computer's time zones to GMT (e.g. "Europe/London").

The issue is that luxon (v 1.22.0) formats the current date as follows:

```js
> luxon.DateTime.local().toISO()
'2020-02-17T10:02:14.703-00:00'
```

According to the Wikipedia entry on ISO 8601:

> An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00". However, **it is not permitted to state it numerically with a negative sign, as "−00:00", "−0000", or "−00"**. The section dictating sign usage (section 3.4.2 in the 2004 edition of the standard) states that a plus sign must be used for a positive or zero value, and a minus sign for a negative value. Contrary to this rule, RFC 3339, which is otherwise a profile of ISO 8601, permits the use of "-00", with the same denotation as "+00" but a differing connotation.[29]

Funny enough, the following works:

```js
> luxon.DateTime.local().setZone(luxon.DateTime.local().zoneName).toISO()
'2020-02-17T10:08:04.416+00:00'
```
(Note: this does not work around the problem if a `Zone` object is given to `setZone`, it only works for the zone name, i.e. `Europe/London`)

As this shows there is a workaround that we will include in our application to fix the issue for our British and Portuguese users.

Since I'm not familiar with the luxon code base, I have not yet started working on a fix/PR. Please tell me whether this seems like an easy fix and you'll be able to do it. Otherwise please point me in some direction and I'll see what I can come up with.

**Comment by icambron** [comment]
It seems like it should be an easy fix, but I won't get to it for a bit

**Comment by iStefo** [comment]
Ok, I tried to work on a fix by adding a failing test case. Unfortuantely, I was only able to reproduce the issue when running `jest` with `TS="Europe/London"` instead of `America/New_York`, which causes two other tests to fail:

<details>

```
Summary of all failing tests
 FAIL  test/datetime/diff.test.js
  ● DateTime#diff handles fractional days as fractions of those specific days

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Object {
    -   "days": 1.96,
    +   "days": 1.9583333333333335,
      }

      213 |       "days"
      214 |     )
    > 215 |   ).toEqual({ days: 1 + 24 / 25 });
          |     ^
      216 | });
      217 | 
      218 | test("DateTime#diff is precise for lower order units", () => {

      at Object.<anonymous> (test/datetime/diff.test.js:215:5)

 FAIL  test/zones/local.test.js
  ● LocalZone.instance provides valid ...

    expect(received).toBe(expected) // Object.is equality

    Expected: "America/New_York"
    Received: "Europe/London"

      14 | 
      15 |   // todo: figure out how to test these without inadvertently testing IANAZone
    > 16 |   expect(LocalZone.instance.name).toBe("America/New_York"); // this is true for the provided Docker container, what's the right way to test it?
         |                                   ^
      17 |   // expect(LocalZone.instance.offsetName()).toBe("UTC");
      18 |   // expect(LocalZone.instance.formatOffset(0, "short")).toBe("+00:00");
      19 |   // expect(LocalZone.instance.offset()).toBe(0);

      at Object.<anonymous> (test/zones/local.test.js:16:35)
```

</detail>

I tried to set the default zone for my test only (both using `Settings.defaultZoneName` and `process.env.TZ`) but the first approach resulted in the *correct*  ouput (`+00:00`)  and the second approach had no effect.
The only way to reproduce seems to be setting the time zone when starting the tests, and I don't really like that.

How should be proceed?

**Comment by icambron** [comment]
Yeah, that's a tricky one, when the system timezone is what matters. I think practically speaking we'll just have to skip the test case.
