### ISSUE TITLE
set({weekday: 6}) sometims creates invalid DateTime

### ISSUE THREAD

**Issue by fbialek** [moment/luxon#666]
When I try to `DateTime.fromISO("2027-12-31").set({ weekday: 6 })` it returns Invalid DateTime. I noticed that it happens for the last week of a year before leap year once per 28 years. 

So DateTime.fromISO("2055-12-27").set({ weekday: 6 })` also returns invalid output. 

https://codesandbox.io/s/luxon-playground-1wkdk?fontsize=14&hidenavigation=1&theme=dark

**Comment by icambron** [comment]
Interesting. I'll take a look when I get a chance. In the meantime, I'd welcome a fix

**Comment by fbialek** [comment]
Sorry, I just checked it once more time. Current version of Luxon doesn't have that bug. I was using 1.2.0 version.

**Comment by icambron** [comment]
Ah, ok, yeah. The changelog has this item in it for 1.6.0:

> Fix handling weekdays at the end of leap week years

That's probably it. Always good to try the latest version
