### ISSUE TITLE
Include support for numbers

### ISSUE THREAD

**Issue by wijnsema** [moment/luxon#67]
Would be really nice to include numeral support in this library. Feels like in de same domain somehow. Many of the concepts (parse, formating, localization) apply to numbers as well!

**Comment by icambron** [comment]
I do think someone should write a convenience wrapper around the [Intl.NumberFormat library](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) that has the features you describe. But Luxon is going to focus exclusively on dates and times.
