### ISSUE TITLE
How to use a new IANA TZDB file

### ISSUE THREAD

**Issue by guyisra** [moment/luxon#670]
IANA releases new TZ information every now and then.
In case luxon creators are busy, how can I take the tzdb files and update luxon with this information?

**Comment by icambron** [comment]
There are no TZ info files. We use the one built into the browser's (or Node's) Intl API.

**Comment by casper5822** [comment]
Sorry if i write on a closed issue. So how it works? 
Because we have a web app for booking. So it is very important the timezone changes.

Do we have to wait that users will update the browser?
