### ISSUE TITLE
Feature request: toRelative multiple units

### ISSUE THREAD

**Issue by proteriax** [moment/luxon#672]
I searched the docs but there doesn’t seem to be a way to do this.

```js
DateTime.local().plus({ hours: 2, minutes: 16 }).toRelative({ round: false })
```

currently outputs `in 2.26 hours`, which is correct but less readable than, say `in 2 hours and 16 minutes`.

**Comment by GillesDebunne** [comment]
This is a limitation of the underlying [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat).

Its `format` method which is used by `toRelative` only accepts a value and a single unit, to create texts such as _one day ago_. Rounding (default) the time difference before `format` is probably the best option for such a coarse method.

See also #743
