### ISSUE TITLE
toRelative days ago instead of weeks

### ISSUE THREAD

**Issue by rightaway** [moment/luxon#674]
`DateTime.local().minus({days:8}).toRelative()` says `8 days ago` but it should be `1 week ago`.

Also the documentation says a unit can be `quarters`, but `DateTime.local().minus({months:8}).toRelative()` shows months not quarters. Why is this?

Actually this is how I'd like it to be, because people think in terms of months not quarters. Can we have an option to disable quarters from the possible units?

**Comment by Allcharles** [comment]
This may help you understand whats going on: https://github.com/moment/luxon/issues/687

**Comment by abhijit945** [comment]
Encountered this issue as well. 
Is there a way to enforce `week` instead of `days`? Specifically the following scenario: 

```
luxon.DateTime.local().setLocale('en').plus({ 'days': -7}).toRelative('days')
// Expected and Actual are both correct -> 7 days ago
```
But 
```
luxon.DateTime.local().setLocale('en').plus({ 'week': -1}).toRelative('week')
// Expected -> 1 week ago
// Actual -> 7 days ago
```

**Comment by GillesDebunne** [comment]
Use `.toRelative({unit:'weeks'})`.

When `unit` is not specified, luxon picks the larger unit of `"years", "months", "days", "hours", "minutes", "seconds"` which is not zero when rounded.

Adding `weeks` to this list would display _one week ago_ for all dates between 7 and 13 days ago, which is not very precise and probably explains why it is not included. Note that `quarters` in not in this list either.
