### ISSUE TITLE
Luxon DateTime fromISO off by one hour versus moment.js

### ISSUE THREAD

**Issue by springandangular** [moment/luxon#677]
Trying to replace moment.js in my Angular application with Luxon to reduce bundle size.

I have come across a case where the two libraries produce a different output, and I am not sure why.

moment.js produces a date that is one hour ahead.

```
const activeToDateTimeString = '2014-08-06T13:07:04';

let foo1 = moment(activeToDateTimeString).utcOffset(-5, true);
let foo2 = DateTime.fromISO(activeToDateTimeString, {zone: 'America/New_York'}).setZone('America/New_York', { keepLocalTime: true });
let foo3 = DateTime.fromJSDate(new Date(activeToDateTimeString)).setZone('America/New_York', { keepLocalTime: true });
let foo4 = DateTime.fromISO(activeToDateTimeString).setZone('America/New_York', { keepLocalTime: true });

console.log(foo1.toDate());
console.log(foo2.toJSDate());
console.log(foo3.toJSDate());
console.log(foo4.toJSDate());
```

Output:
```
Wed Aug 06 2014 14:07:04 GMT-0400 (Eastern Daylight Time)
Wed Aug 06 2014 13:07:04 GMT-0400 (Eastern Daylight Time)
Wed Aug 06 2014 13:07:04 GMT-0400 (Eastern Daylight Time)
Wed Aug 06 2014 13:07:04 GMT-0400 (Eastern Daylight Time)
```

Why does Luxon produce a different output in this case?

**Comment by icambron** [comment]
`America/New_York` is in -4 on August 6, not -5. So what's happening in the Moment case is that you're parsing the string as being in -5 and then converting it to eastern time (happens automatically as part of the `toDate()` conversion, which adds an hour to it. This is the incorrect result, just the result of assuming the wrong offset.

In the Luxon cases, you're either parsing it as being `America/New_York` (foo2) or forcing it to be reinterpreted as `America/New_York` (foo3 and foo4). But in both cases, Luxon knows that's -4, no extra math happens. So you get a difference of an hour.
