### ISSUE TITLE
Error message suggestion

### ISSUE THREAD

**Issue by benmccann** [moment/luxon#678]
I got the error below:
```
Uncaught Error: fromMillis requires a numerical input
    at Function.fromMillis (luxon.js:6399)
```

I would have expected my code was passing a numerical input, so I'm curious what it's passing instead. It might be nice if the error message contained the given input. E.g. if it said something like `fromMillis requires a numerical input, but received foobar`

**Comment by icambron** [comment]
Sure, makes sense. I'd accept a PR spelling that out
