### ISSUE TITLE
"Why?" page seems to be outdated about relative times

### ISSUE THREAD

**Issue by Razican** [moment/luxon#679]
Hello, checking the "Why does Luxon exist?" [page][why_luxon], I've noticed that it says Luxon doesn't support relative times, but it seems this has been supported for more than a year, since #390 was merged.

[why_luxon]: https://moment.github.io/luxon/docs/manual/why.html

**Comment by icambron** [comment]
True, that can be updated.

**Comment by cmitz** [comment]
This is still true for the "For Moment users" [page](https://moment.github.io/luxon/docs/manual/moment.html)
