### ISSUE TITLE
DateTime.fromISO change time zone to my local zone

### ISSUE THREAD

**Issue by stroiman** [moment/luxon#685]
I don't know if this is a bug, or by design, but I find the behavior odd.

When I parse an ISO string with time zone information, the result is converted to my local time zome (Western Europe). I would have expected that the DateTime instance should have kept the offset specified in the input string:

Observed

```
> luxon.DateTime.fromISO("2019-01-01T12:00:00.000Z").toISO()
'2019-01-01T13:00:00.000+01:00'
> luxon.DateTime.fromISO("2019-01-01T12:00:00.000+00:00").toISO()
'2019-01-01T13:00:00.000+01:00'
```

Expected that the representation 

```
> luxon.DateTime.fromISO("2019-01-01T12:00:00.000Z").toISO()
'2019-01-01T12:00:00.000Z'
```

Node version: v12.16.1
Luxon version: 1.23.0

**Comment by GillesDebunne** [comment]
Hello Peter,

This is the expected behavior. There is a `{setZone: true}` extra option you can use to keep the zone specified in the string.

**Comment by stroiman** [comment]
Thanks a bunch for the speedy reply

**Comment by icambron** [comment]
You can see [here](https://moment.github.io/luxon/docs/manual/zones.html#strings-that-specify-an-offset) for more info.
