### ISSUE TITLE
Duration normalize is buggy

### ISSUE THREAD

**Issue by sechel** [moment/luxon#687]
```typescript
Duration.fromObject({ minutes: 120 }).normalize().toObject();
// => { minutes: 120 }
```
Does not change anything, however when I put in `hours: 0` then I get
```typescript
Duration.fromObject({ hours: 0, minutes: 120 }).normalize().toObject();
// => { hours: 2, minutes: 0 };
```
Looking at this function from the luxon code seems to reveal the issue
```javascript
function normalizeValues(matrix, vals) {
  reverseUnits.reduce(function (previous, current) {
    if (!isUndefined(vals[current])) {
      if (previous) {
        convert(matrix, vals, previous, vals, current);
      }

      return current;
    } else {
      return previous;
    }
  }, null);
}
```

**Comment by icambron** [comment]
Right, normalization doesn't expand the set of units; it just balance the ones you have in there.

**Comment by sechel** [comment]
Hmm, this is counterintuitive IMHO. Is this by definition? I mean if I think about a vector space analogy then then it makes sense to not add new dimensions through normalization.

**Comment by icambron** [comment]
I'm not sure about the analogy, but yes, Luxon's durations are just like that. It seemed too confusing for Luxon to add new keys without you telling it to (e.g. via `shiftTo`). You can of course add all the keys and later filter out the zeros.

**Comment by icambron** [comment]
Actually, let me motivate this a little better, since it's probably not that obvious why introducing new units is so weird. With hours and minutes it seems fine, but Luxon supports quarters, weeks, and months. Do you really want to roll months into quarters? Weeks into months, which fit very poorly? Maybe not, depends on the application. Luxon doesn't want to have an opinion about which units are "good" to normalize into, so it doesn't have an opinion at all. You just tell it what units you're interested in and it does the work.

**Comment by atruskie** [comment]
This just threw me through a loop. Intuitively, every log line here was not expected by me:

```
var example = Duration.fromObject({ minutes: 525600 }).normalize();
console.log("years: " + example.years) // years: 0
console.log("days: " + example.days) // days: 0
console.log("seconds: " + example.seconds) // seconds: 0

console.log("years: " + example.get("years")) // years: 0
console.log("days: " + example.get("days")) // days: 0
console.log("seconds: " + example.get("seconds")) // seconds: 0
```

I appreciate you might be trying to something novel with non-standard size units but I'd find it confusing that these example would fail _before_ `normalize` was called, and even more so afterwards.

Perhaps a distinction between the input units (`values` in the codebase) and computed values would be useful?

**Comment by sechel** [comment]
My use case was to generate a human readable version of the duration at hand. But the normalize method is not meant for this, I understand this now. I ended up using https://www.npmjs.com/package/humanize-duration for this purpose.

**Comment by icambron** [comment]
@atruskie that's a different problem. I think you mean `example.as("years")`. `get` is just a getter for the unit
