### ISSUE TITLE
Date "0001-01-01T00:00:00Z" treated differently in different browsers

### ISSUE THREAD

**Issue by adiherzog** [moment/luxon#689]
`console.log(DateTime.fromISO('0001-01-01T00:00:00Z').toISO());`

leads to different outputs in different browsers:

```
Chrome:    0001-01-01T00:34:00.000+00:34
IE / Edge: 0001-01-01T01:00:00.000+01:00
Firefox:   0001-01-01T00:34:08.000+00:34.13333333333333
```

Is this a bug or expected behavior?

This particular date has some relevance because it's the default value of the C# `DateTime` type. But it's also easily avoidable if it's not supported by luxon.

**Comment by icambron** [comment]
For some reason Firefox thinks that the offset way back then was odd. Here's what it looks like for me (`America/New_York`):

```js
DateTime.fromISO('0001-01-01T00:00:00Z').offset
-296.03333333333336
```

Why does it think that? I'm not sure. Browsers have a lot of historic time zone data baked into them and historic time zones are wack. So it's weird, but that's just what Firefox thinks the local time for your zone is back in AD 1.

However, note that this is insensitive to the local offset:

```js
DateTime.fromISO('0001-01-01T00:00:00Z').toUTC().toISO();
"0001-01-01T00:00:00.000Z"
```
