### ISSUE TITLE
Add isWeekend metadata

### ISSUE THREAD

**Issue by wkeese** [moment/luxon#690]
This library looks awesome.  I wonder if it's possible to add a method or property to tell which days are considered weekends (normally, but apparently not always, Saturday and Sunday).  (This is for a calendar app that shades the weekends differently.)

But I'm not sure if/how you could get that metadata by using/introspecting Intl.  The data is available in the CLDR, but of course, you are trying to avoid pulling in data files.

For simplicity, dojo handled ` isWeekend()` by lifting the data from the CLDR, see https://github.com/dojo/dojo/blob/1.16.2/date/locale.js#L679 and https://github.com/dojo/dojo/blob/1.16.2/cldr/supplemental.js#L97.

**Comment by icambron** [comment]
Unfortunately, Luxon doesn't have direct access to CLDR data; it only has access to Javascript's Intl API, which is based on ICU/CLDR data, but as far as I know, doesn't provide an API for this

**Comment by wkeese** [comment]
OK that's what I was guessing.   Too bad.  Luckily it's easy to make a standalone function to do it, without pulling in all the CLDR data.  (With the caveat that the function needs to be updated if any country changes their definition of "weekend".)
