### ISSUE TITLE
Start of day relative to a IANA-zone

### ISSUE THREAD

**Issue by joekaiser** [moment/luxon#696]
Is it possible to get the start of a day relative to an IANA specified zone?

example: given an ISO string of `2020-04-22T01:00:00:000Z`.  Is there a way to convert it to the `startOf(day)` but relative to an IANA zone? (let's use America/Los_Angeles)? It can still be represented as am ISO standard, but what I am looking for is `2020-04-21T07:00:00:000Z`.

Here is my thought process.  `April 22 1AM GMT` is `April 21 6PM PDT` and I need to get midnight relative to the user's timezone

**Comment by icambron** [comment]
Sure, like so:

```js
DateTime
  .fromISO("2020-04-22T01:00:00.000Z")
   .setZone("America/Los_Angeles")
  .startOf("day").toISO()
"2020-04-21T00:00:00.000-07:00"
```

Note I had to replace the last `:` in your time strings with a `.`
