### ISSUE TITLE
polyfill.io feature list is missing Object.is in documentation

### ISSUE THREAD

**Issue by iddings** [moment/luxon#697]
It appears that an Object.is polyfill is also required for IE, but this is missing from the suggested polyfill URI in the [documentation](https://moment.github.io/luxon/docs/manual/install.html#internet-explorer).

Happy to submit a PR for this.

**Comment by icambron** [comment]
Yes, would take that PR

**Comment by iddings** [comment]
Should the polyfill.io version bump to v3 as well?

**Comment by icambron** [comment]
sure
