### ISSUE TITLE
Question: DateTime.fromISO({ setZone: true })

### ISSUE THREAD

**Issue by clicktravel-tim** [moment/luxon#699]
Why is setZone defaulted to false when using "fromISO" on DateTime? Especially because it says "will use zone if one is provided". We use data from flights around the world all the time, and timeZone being kept is incredibly important, I'm currently struggling to think of a use case where I wouldn't want setZone: true

**Comment by icambron** [comment]
From https://github.com/moment/luxon/issues/621#issuecomment-554799609: 

> Two reasons: a) it would be confusing to developers if important things like zone are determined by the string, and would lead to bugs where formatted-back-out strings were in all different zones without the developer realizing it and b) since it's a fixed-offset zone, it loses DST information (e.g. which country's +1 is meant here?) so this forces people to think about what information they really have instead of hoping that the "zone" is really the originator's zone. For example, that set() call could easily cross a DST boundary in wherever this string came from, but Luxon doesn't know that because all it knows is +1.
