### ISSUE TITLE
Some toFormat tokens are not localized until locale is set explicitly

### ISSUE THREAD

**Issue by downace** [moment/luxon#701]
Luxon version: 1.23.0

Let me explain this through example:

```javascript
console.clear();

const d = luxon.DateTime.local();

console.log("Current locale:", d.locale);
console.log("                     toFormat('DDD'):", d.toFormat('DDD'));
console.log("                toFormat('d MMMM y'):", d.toFormat('d MMMM y'));
console.log("toFormat('d MMMM y') after setLocale:", d.setLocale(d.locale).toFormat('d MMMM y'));
```

Output:
```
"Current locale:" "ru"
"                     toFormat('DDD'):" "30 апреля 2020 г."
"                toFormat('d MMMM y'):" "30 April 2020"
"toFormat('d MMMM y') after setLocale:" "30 апреля 2020"
```

Codepen: https://codepen.io/downace/pen/xxwLzZd?editors=0012

As we can see, `MMMM` token is not localized. But explicit call to `setLocale` somehow fixes it, despite  that correct locale is already set

I can use `d.setLocale(d.locale)` as a workaround, but it looks strange...

**Comment by icambron** [comment]
That's documented here: https://moment.github.io/luxon/docs/manual/intl.html#using-the-system-locale-in-string-parsing. The typical use case for `toFormat` is to match some system-interpreted format, so we don't localize by default. Otherwise, the developer ends up trying to make the string match some date RFC and it only works in English locales.

**Comment by downace** [comment]
Ah, sorry, haven't found this... Got the point, thanks

But why it only applies to some tokens, not all of them?

[Docs says](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toFormat):

> Defaults to en-US if no locale has been specified, regardless of the system's locale

But `DateTime.local().toFormat('DDD')` outputs localized string, like I mentioned in example. Maybe I'm missing something else?
