### ISSUE TITLE
Converting timezone for some valid IANA timezone returning null

### ISSUE THREAD

**Issue by dexcell** [moment/luxon#702]
Example:
````
console.log(IANAZone.isValidSpecifier("US/Hawaii")); // true
console.log(DateTime.fromISO('2020-05-04T08:00:00.000+07:00').setZone('US/Hawaii').toISO()); // null
````

Thanks

**Comment by dexcell** [comment]
It turns out because `US/Hawaii` is deprecated IANA timezone according to wikipedia. An information to state deprecated IANA timezone is not supported in the docs would be helpful.

**Comment by icambron** [comment]
Unfortunately Luxon only knows whether the IANA specifier was recognized by the browser’s Intl library, so I doesn’t know anything about why. In v2, an invalid zone will throw so it will be more clear what’s happening. In the meantime, you can check invalidReason on the instance

**Comment by dexcell** [comment]
@icambron Thank you for the info.
