### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by EvtK** [moment/luxon#703]
Hi there,

Working on performance improvements for a library. It uses luxon and as it turns out, it's eating a few kb's

![image](https://user-images.githubusercontent.com/1754392/80979008-14ad6c80-8e27-11ea-9f88-ac737f2ac0e1.png)

I'm wondering:

1) is it normal for luxon to have this size, or did I import it not in the right way?
2) is there a way to remove all localizations from the bundle?

Thanks!

**Comment by sesam** [comment]
I just arrived here, so can only offer a guesstimate: I think luxon has all locales integrated (from an old ticket about luxon's design making it hard to trim size by making translations optional) and that luxon supports also some very old browsers, so the babel transpilation is likely adding quite a bit of cruft. Building a library, if it's used in browsers, one smart choice is to use something that is already included in the dependencies for most of your users. That probably means you should just use moment instead. (Though if you just want to trim down the library's apparent size, maybe move luxon from dependencies to peerDependencies 😬)

Do you have a public issue tracker link for this work for your library?
What platforms does your library need to support?
Are you measuring the performance metrics you want to improve? Maybe size shouldn't be your primary metric.

**Comment by icambron** [comment]
Luxon doesn't have locale files.

That bundle size is quite big because we don't minify in the Node build, since we expect you'll probably do it in your own build. It's quite a lot smaller minified; for example Luxon directly publishes a browser global build, which is about 70K.

That said, bundle size is definitely an area where Luxon could use more improvement. Future versions will better support tree-shaking.

**Comment by justingolden21** [comment]
@evtk (or someone else who knows), what's the utility you used for the visual on the space used per package?

Also, is luxon still this large currently? How is tree shaking? Can I just import/use what I want and remove/purge everything else with my bundler, like postcss is to tailwindcss?
