### ISSUE TITLE
Luxon toFormat is giving a time stuck at 05 minutes

### ISSUE THREAD

**Issue by hfzvc** [moment/luxon#707]
You can easily test this out even on the main LuxonJS page: https://moment.github.io/luxon/index.html

Open the console and paste in: luxon.DateTime.local().toFormat('h:MM')

The result returns the hours properly. The minutes are stuck at 05.

If you output second they work fine as well. It was working fine yesterday (May 10, 2020) but today (May 11, 2020) it just stopped.

The same is true if you use the CDN, or download the luxon.js file.

I have tested this across two standard devices and mobile phone.

Edit: The standard JS Date() object works fine.

**Comment by GillesDebunne** [comment]
Hello,

The `MM` you are using in your format string corresponds to the [_month_ token](https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens). Hence the `05`for May.

Use 'h:mm' instead to solve your problem.

**Comment by hfzvc** [comment]
Thanks!
