### ISSUE TITLE
[wishlist] generic modifier combining plus and minus

### ISSUE THREAD

**Issue by wsw70** [moment/luxon#71]
It would be useful to have a modifier (date/time  shift) which would accept a positive or negative offset (effectively offering the `plus` and `minus` functionality).

The idea is borrowed from the functionality of the Python's `arrow` (very useful when the offset sign is not predictable)

**Comment by icambron** [comment]
This actually does work; it just isn't documented:

```js
> d = DateTime.local().setZone(-480)
> d.offset
-480
> d.zone
FixedOffsetZone { fixed: -480 }
```

It could use some tests and documentation (in the `setZone` method docs), so I'll leave this open as a reminder to do that.

**Comment by icambron** [comment]
(Deleting earlier comment; I misunderstood the request)

`plus()` accepts negative values:

```js
DateTime.local().plus({ seconds: -500 })
```

IOW, think of `plus` as a mathematical plus, where adding negatives effectively subtracts. I've added an example to `plus`'s docs to make this more obvious (see ebe07d8).

You can also pass milliseconds (negative or positive) directly:

```js
DateTime.local().plus(-500 * 1000)
```

**Comment by wsw70** [comment]
Thank you, this is super helpful to have this functionality. I assume that `minus` works the same. 

If so, it would maybe be worth considering something as `offset()` (or another offset-neutral name, like `shift()`) which would combine both `plus` and `minus` (as they are effectively the same).

**Comment by icambron** [comment]
Yup, `minus` with a negative should result in a later time
