### ISSUE TITLE
Specify { "sideEffects": false } in package.json to encourage tree shaking?

### ISSUE THREAD

**Issue by ryota-ka** [moment/luxon#710]
Hello,

Since Webpack 4, it checks `sideEffects` field in `package.json` for tree shaking.

Here the term "side effect" is defined as below in [this page](https://webpack.js.org/guides/tree-shaking/).

> A "side effect" is defined as code that performs a special behavior when imported, other than exposing one or more exports. An example of this are polyfills, which affect the global scope and usually do not provide an export.

I looked around the code base and noticed no side effects will happen just by importing a file (right?)

Is it worth considering?

related link: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by icambron** [comment]
Yeah, that sounds right to me

**Comment by ryota-ka** [comment]
closing as #713 has been merged
