### ISSUE TITLE
Timezone offsets are output with long decimals from floating point rounding errors in Firefox 

### ISSUE THREAD

**Issue by jonknowles** [moment/luxon#724]
This issue is present in Firefox 77. Timezone offsets, whether output by the format string token "ZZZ" or the toISO() method, have long floating point rounding errors in the minutes portion of the offset (i.e. `50.6000000000000002` rather than `50`)

Here are two examples:

```
> DateTime.fromJSDate(new Date(-62090696591000)).toFormat(`yyyy-MM-dd'T'HH:mm:ss.SSSZZ`)
 "0002-06-04T10:26:13.000-05:50.60000000000002"
```

```
> DateTime.fromJSDate(new Date(-62090696591000)).toISO()
"0002-06-04T10:26:13.000-05:50.60000000000002"
```

I believe that the root of the problem is that for this particular timestamp, Firefox returns 350.6 as the timezone offset:
```
> new Date(-62090696591000).getTimezoneOffset()
350.6
```

Then in src/impl/util.js `formatOffset`, the `minutes` value (which presumably should always be an integer) is not rounded.

**Comment by jonknowles** [comment]
Just to follow up on this, I've learned that Firefox does not consider this the value returned from getTimezoneOffset to be bug. Apparently it can be valid to have floating point values for some old timezone offsets: https://bugzilla.mozilla.org/show_bug.cgi?id=1643387

**Comment by icambron** [comment]
Yeah, I think we should round that to a reasonable number of digits
