### ISSUE TITLE
Settings.throwOnInvalid = true breaks Interval.fromISO for <start>/<duration> ISO input

### ISSUE THREAD

**Issue by JStonevalley** [moment/luxon#728]
When ```Settings.throwOnInvalid = true``` is set the following code in Interval.js static fromISO
```js
const start = DateTime.fromISO(s, opts),
        end = DateTime.fromISO(e, opts);
```

throws which means that the subsequent handling of duration ISO is never reached.

Reproduction:
```js
Settings.throwOnInvalid = true
const interval = Interval.fromISO('2020-06-22T17:30:00.000+02:00/PT5H30M')
```
Throws:
```
InvalidDateTimeError: Invalid DateTime: unparsable: the input "PT5H30M" can't be parsed as ISO 8601
```

**Comment by icambron** [comment]
@JStonevalley Can you provide a full reproduction of the issue?

**Comment by JStonevalley** [comment]
> @JStonevalley Can you provide a full reproduction of the issue?

Added to the description
