### ISSUE TITLE
toFormat() will print "24" for hour instead of "00"

### ISSUE THREAD

**Issue by koitsu** [moment/luxon#733]
Example of bug:

```javascript
let a = luxon.DateTime.fromSQL('2007-09-12 07:20:50', { zone: 'utc' });

console.log(a.toString());
console.log(a.setZone('America/Los_Angeles').toFormat('yyyy-MM-dd TT ZZZ'));
```
Result:
```
2007-09-12T07:20:50.000Z
2007-09-12 24:20:50 -0700
```
Note `24:20:50`, not `00:20:50`.  The year, month, and day are correct, as is the offset at that moment in time (-0700 / PDT / Pacific Time with DST in effect).  This is not specific to `TT` either, `HH` returns `24` as well.

**Comment by koitsu** [comment]
It looks like https://github.com/moment/luxon/issues/726 is reporting the same thing.

**Comment by jasonswearingen** [comment]
probably #749 is related also.

**Comment by GillesDebunne** [comment]
I'm unable to reproduce this problem. On which browser(s) or node version(s) does it happen?

**Comment by thomas-darling** [comment]
@GillesDebunne, I posted some details about this here: https://github.com/moment/luxon/issues/726#issuecomment-674581122

**Comment by GillesDebunne** [comment]
I'm closing this bug as a duplicate of #726
