### ISSUE TITLE
Is there a way to get the raw offset (not DST) of a time zone?

### ISSUE THREAD

**Issue by vvo** [moment/luxon#735]
Hi there, I am trying to get the raw offset of a time zone (when not in DST) but I am not sure there's a reliable way to do so using Luxon or just JavaScript in general.

If you have any idea, let me know!

**Comment by icambron** [comment]
Luxon doesn't really "know" the non-DST offset, just the offsets for specific times. However, you can create two DateTimes, one in January and one in May, and take the greater of the two offsets you find on those instances:

```js
function nonDSTOffsetForZone(zone) {
    const jan = DateTime.fromObject({ year: 2020, month: 1, zone }).offset;
    const may = luxon.DateTime.fromObject({ year: 2020, month: 5, zone }).offset;
    return Math.min(jan, may);
}
```

Hacky, but I suspect it works in practice.
