### ISSUE TITLE
keepLocalTime: true

### ISSUE THREAD

**Issue by drmrbrewer** [moment/luxon#738]
I like the `keepLocalTime: true` option (see [here](https://moment.github.io/luxon/docs/manual/zones.html#keeplocaltime)).  It is *exactly* what I'd be looking for (but couldn't find) in moment.  It is [suggested in the docs](https://moment.github.io/luxon/docs/manual/zones.html#keeplocaltime) that if you're using this option a lot then you're "probably doing something wrong"... well I think I might end up using it a lot but for good reason... I just fear that, because it might be seen as "bad practice", this option might be deprecated/removed/changed in future... I vote in favour of keeping it **forever**!

Specifically, I am using it as follows to get a timestamp that "fakes" UTC:

    var local = DateTime.fromObject({ zone: 'Europe/Stockholm' });
    var rezonedToUtc = local.setZone('utc', { keepLocalTime: true });
    console.log(local.valueOf());
    console.log(rezonedToUtc.valueOf());

Let's say it is 09:00 in UTC time.  And let's say Stockholm is currently 2 hours ahead of UTC, so it is 11:00 in Stockholm.  And let's say the UTC timestamp is currently `ts` (eg. `1594393735304`).  The above will create a timestamp of `ts + 2 * 36e5` (e.g. `1594400935304`), which (when viewed as if in UTC world) is 11:00... i.e. we can get a UTC timestamp equivalent to the local time in Stockholm.

This is very useful for my use-case.

Another example:

    // 'now' in UTC...
    var dt = DateTime.utc();
    console.log(dt.valueOf());
    // move over to Stockholm timezone...
    dt = dt.setZone('Europe/Stockholm');
    // do some datetime arithmetic in Stockholm (midnight tomorrow in Stockholm)...
    dt = dt.plus({ days: 1 }).endOf('day');
    console.log(dt.valueOf());
    // get an equivalent timestamp for that time as if we were in UTC world...
    var dtUtc = dt.setZone('utc', { keepLocalTime: true });
    console.log(dtUtc.valueOf());

And **now a question** about a possibly missing functionality in this library...  

If we start with the timestamp of `1594400935304` (see above), and we know that this is a timestamp in the context of *Stockholm time* (which is two hours ahead of *UTC time*), is there a way of getting back to an actual UTC timestamp (i.e. `1594393735304` as above)?  My feeling is that this should be possible with [`DateTime.fromObject()`](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-method-fromObject), passing in the assumed timezone (`Europe/Stockholm`) and the timestamp (`1594400935304`), and then we can call `dt.setZone('utc', { keepLocalTime: true })`... but it only seems to be possible to pass in datetime in terms of year, month, etc, rather than a single timestamp.

**Comment by icambron** [comment]
Thanks for the kind words. I am certainly never going to remove the feature; it's one of those things I don't think should get used much, but when you need it, you really need it. And yes, it is exactly for "as if it were..." use cases.

FWIW, Moment does have this feature too, but it is in the form of an optional argument:

```js
moment().utcOffset(-6, true) // the true means keepLocalTime
```

**Comment by drmrbrewer** [comment]
Thanks @icambron.  Glad that the option is here to stay, and I'll also check out the equivalent in moment... thanks.

Regarding the question part of my (long and rambly post), regarding starting with a "faked" UTC timestamp, is this the best way to do it...?

    var dateLocal = new Date(1594400935304);
    var dtLocal = DateTime.fromObject({
        year: dateLocal.getUTCFullYear(),
        month: dateLocal.getUTCMonth() + 1,
        day: dateLocal.getUTCDate(),
        hour: dateLocal.getUTCHours(),
        minute: dateLocal.getUTCMinutes(),
        second: dateLocal.getUTCSeconds(),
        millisecond: dateLocal.getUTCMilliseconds(),
        zone: 'Europe/Stockholm'
    });
    var dtUtc = dtLocal.setZone('utc', { keepLocalTime: true });
    console.log(dtLocal.valueOf());
    console.log(dtUtc.valueOf());

I feel that it would be nice to be able to pass a timestamp to `DateTime.fromObject()` rather than having to split it up manually, like:

    var dtLocal = DateTime.fromObject({
        timestamp: 1594400935304,
        zone: 'Europe/Stockholm'
    });

**Comment by icambron** [comment]
@drmrbrewer The easiest way is to not use `fromObject()` at all:

```js
luxon.DateTime.fromJSDate(date).setZone("Europe/Stockholm", { keepLocalTime: true }).valueOf()
1594379335304
```

Or similarly:

```js
luxon.DateTime.fromMillis(1594400935304).setZone("Europe/Stockholm", { keepLocalTime: true }).valueOf()
1594379335304
```

Both those methods take a `zone` option, but unlike `fromObject()`, those methods don't use the `zone` argument to _interpret_ the input, only to set the zone on the resulting object. (This makes sense -- JS dates aren't in a zone, and "local" timestamps aren't really a thing). So instead, we read them in faithfully, then reinterpret them as having been in a specific zone all along, and then spit out the "real" timestamps.

**Comment by drmrbrewer** [comment]
Thanks @icambron... I'm liking luxon more and more!
