### ISSUE TITLE
Luxon setZone throws exceptions on IE edge 38+

### ISSUE THREAD

**Issue by samyue** [moment/luxon#74]
Our company has been using Luxon on our Angular 4 project, but recently we found when we use timezone related api, the luxon throws exception on IE edge 38 or later version. 

For example, the following code will cause exception: 
DateTime.local().setZone('Australia/Sydney');

Exception details:
```
ERROR Error: Uncaught (in promise): TypeError: Invalid attempt to destructure non-iterable instance
TypeError: Invalid attempt to destructure non-iterable instance
   at Anonymous function (http://localhost:4000/vendor.bundle.js:53138:7)
   at hackyOffset (http://localhost:4000/vendor.bundle.js:55272:7)
   at offset (http://localhost:4000/vendor.bundle.js:55354:11)
   at DateTime (http://localhost:4000/vendor.bundle.js:59826:11)
   at clone (http://localhost:4000/vendor.bundle.js:59594:3)
   at setZone (http://localhost:4000/vendor.bundle.js:59959:9)
   at DateHelper.getSydneyDateToday (http://localhost:4000/main.bundle.js:2033:9)
   at GettingStartedComponent (http://localhost:4000/0.chunk.js:1839:9)
   at createClass (http://localhost:4000/vendor.bundle.js:11133:13)
   at createDirectiveInstance (http://localhost:4000/vendor.bundle.js:10951:5)
core.es5.js (1020,1)
 ....
```

This is a quite serious issue which break the code. Can you pls help on that? Thanks.

**Comment by icambron** [comment]
Yikes. I'll try to see if I can figure that out.

**Comment by samyue** [comment]
Thank you!

- sent from my mobile

On 20 Nov 2017 12:23 pm, "Isaac Cambron" <notifications@github.com> wrote:

Yikes. I'll try to see if I can figure that out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/moment/luxon/issues/74#issuecomment-345568195>, or mute
the thread

**Comment by icambron** [comment]
Which build are you using?

**Comment by samyue** [comment]
19 or 20

- sent from my mobile

**Comment by icambron** [comment]
Sorry, meant which build of Luxon, e.g. the browser global one, etc.

**Comment by samyue** [comment]
I tried the latest Luxon release, same issue. the browser is IE edge 38 or
later version

- sent from my mobile

**Comment by samyue** [comment]
Just back to office from lunch break. The exact version I tried with Luxon is: 0.0.4, 0.0.19 and 0.0.20.

**Comment by samyue** [comment]
As mentioned, we are using Angular 4, which uses webpack for bundling/importing different libraries. We install and use Luxon like this:

npm install --save luxon
import { DateTime } from 'luxon';

**Comment by samyue** [comment]
You can check the demo page on IE edge, the errors appear for examples with zone setting:
https://moment.github.io/luxon/demo/global.html

![image](https://user-images.githubusercontent.com/2274976/32999709-a87a88e6-cdf7-11e7-9c53-953296d044b1.png)

**Comment by icambron** [comment]
Fixed in 0.0.21. Thanks for the report

**Comment by samyue** [comment]
great, awesome

- sent from my mobile

**Comment by tomtom94** [comment]
I encoutered the same issue. `.setZone('Europe/Paris')` not working on IE 11.

I know it is written zones are not supported by IE https://moment.github.io/luxon/docs/manual/matrix.html#official-support

But we all use the babel polyfill 
```
import "core-js/stable";
import "regenerator-runtime/runtime";
```

Is there a specific polyfill to add to counter this issue ?

**Comment by tomtom94** [comment]
Ok I got it !!!!

https://moment.github.io/luxon/docs/manual/matrix.html#polyfills

`npm i date-time-format-timezone`

and in your webpack

```
  entry: {
    bundle: [
      require.resolve('core-js/stable'),
      require.resolve('regenerator-runtime/runtime'),
      require.resolve('date-time-format-timezone'),
      paths.srcClient
    ]
  },
```

It works setZone on IE now !!! (I now have other IE issue to take care of ... lol)
