### ISSUE TITLE
isLuxonDateTime not documented or typed

### ISSUE THREAD

**Issue by RWOverdijk** [moment/luxon#741]
First: really having a lot of fun with luxon. It works very intuitively.

I am looking for a way to identify an argument as either a regular Date, a regular object or a DateTime instance without having luxon as a dependency (I support it, but don't include it). Now, I found that using isLuxonDateTime works great, but it's not documented or available in the typescript typings.

This is probably on purpose, so I wanted to ask what method is recommended, and if I can safely use isLuxonDateTime even though it's not typed.

**Comment by icambron** [comment]
It's hidden on purpose, because we encourage you to use `DateTime. isDateTime(object)` instead of `object.isLuxonDateTime()`. That way it can handle `null` and `undefined`

**Comment by RWOverdijk** [comment]
Okay but I think you missed the part where I said that I don't have luxon as a dependency.

Anyway thanks I'll just use `.isLuxonDateTime`

**Comment by icambron** [comment]
Yup, I saw that, was just explaining why it's not public. I think it's fine if you use it; it's not technically supported but it's very unlikely to change

**Comment by RWOverdijk** [comment]
Ah okay, thanks for clearing that up. Communication is a sport. 😄
