### ISSUE TITLE
[Feature Request] Allow showing multiple units with .toRelative

### ISSUE THREAD

**Issue by wyqydsyq** [moment/luxon#743]
`toRelative` should allow specifying multiple units like so:

```ts
 DateTime.fromJSDate(new Date(order.createdAt)).toRelative({
    unit: ['hours', 'minutes', 'seconds'],
  })
```
Giving something like:
```
3 hours, 23 minutes, 45 seconds ago
```

I feel this could be a common use-case (I've needed it in two of my own projects) and it seems like something `toRelative` should be capable of doing out of the box.

**Comment by GillesDebunne** [comment]
`toRelative` is using [Intl.RelativeTimeFormat.format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/format), which is meant for coarse localized approximations (as in _2 days ago_) and accepts a single unit.

If you are looking for a precise date difference, use `diff` instead:

```
const d = luxon.DateTime.fromISO('2020-01-01')
const diff = d.diffNow(['days', 'hours', 'minutes'])
// Since `d` is in the past, all diff unit are negative
const str = `${-diff.days} days, ${-diff.hours} hours and ${Math.round(-diff.minutes)} minutes ago`
// "230 days, 15 hours and 19 minutes ago"
```
