### ISSUE TITLE
returning `null` for invalid date times?

### ISSUE THREAD

**Issue by studds** [moment/luxon#760]
First of all, love luxon, it's a great library, indispensable.

I just want to ask whether returning null from `toISODate` for invalid datetimes is the most ergonomic approach? Having an invalid date strikes me as being an exceptional case, and at least for my applications, it makes more sense to throw an error in this case.

Would you accept a PR to either:

- always throw an error when calling `toISODate` on an invalid date, or
- add a `strict` option to `toISODate` to optionally throw?

**Comment by GillesDebunne** [comment]
Thanks for this feedback. This is actually already supported in version
2.0, where invalid objects are no longer an option (constructors throw or
return null instead).

**Comment by studds** [comment]
Oh, awesome. I'll look forward to that, then.

**Comment by slaesh** [comment]
did it came back in V3.3.0?

**Comment by slaesh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/65161
