### ISSUE TITLE
Recurring dates?

### ISSUE THREAD

**Issue by wwahammy** [moment/luxon#763]
I just looked at Luxon and I really like what I see. So, first off, bravo.

I was curious about whether Luxon was going to add support for recurring schedules. As an example, let's say someone wanted to describe a calendar event that happens on the first Tuesday of every month.I don't see a way to describe that exactly in Luxon right now. There is a Moment [plugin](https://github.com/c-trimm/moment-recur) but I haven't found anything similar for Luxon.

Is this a feature that Luxon would want or is this something you'd prefer external to Luxon, like a plugin?

**Comment by icambron** [comment]
Thanks!

Definitely external. I don't think such a plugin exists right now, but it would be a welcome addition to the ecosystem.
