### ISSUE TITLE
Add alternative to native function "startsWith" for old browsers

### ISSUE THREAD

**Issue by DarckBlezzer** [moment/luxon#769]
## Versions
- vue: 2.6.11
- luxon: 1.24.1
- Android: 4.4

### Description:
I was testing my app in an old Android (4.4) and It has an old browser version(Version/4.0 Chrome/39.0.0.0 Mobile), I found that isn't a native function "startsWith"

I use [this](https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales/String/startsWith) to get out of errors:

```
if (!String.prototype.startsWith) {
  String.prototype.startsWith = function(stringBuscada, posicion) {
    posicion = posicion || 0;
    return this.indexOf(stringBuscada, posicion) === posicion;
  };
}
```

**Comment by icambron** [comment]
Luxon provides a pollyfilled build that includes `startsWith`, and several other methods missing from old browsers: https://github.com/moment/luxon/blob/master/src/luxonFilled.js#L8. You can find it built for browser globals [here](https://moment.github.io/luxon/global-filled/luxon.min.js). You might consider using that instead.

Alternatively, providing your own polyfills is perfectly reasonable. One way to do that is how you did it, which is definitely fine, another is to use a polyfill service, like this: https://moment.github.io/luxon/docs/manual/matrix.html#internet-explorer-and-platform-polyfills (though I seem to have not added `startsWith` to the example there).

At any rate, thanks for the feedback. I think the options we have for applying fills are sufficient, so I'm going to close this.
