### ISSUE TITLE
URL broken in install instructions

### ISSUE THREAD

**Issue by AdaRoseCannon** [moment/luxon#771]
It links to here which is 404: `https://moment.github.io/luxon/es6/luxon.min.js`

https://moment.github.io/luxon/docs/manual/install.html#es6

**Comment by icambron** [comment]
I think we stopped building that, just need to remove the link. Almost everyone using es6 wants the unminified one so that they can do their own build.

**Comment by AdaRoseCannon** [comment]
I was mostly after it for using ESModules in the browser so modified es6
would be ideal.

**Comment by icambron** [comment]
@AdaRoseCannon I took a quick look. It turns out that uglify is choking on the es6 syntax trying to minify it. I probably took it out rather than figure out the tooling issue. In general, Luxon is overdue for a tooling overhaul, but if you're game to give a shot, you can enable it by adding `minify: true` to the es6 part of `tasks/build.js`. It gives me this error:

```
Building es6
Error uglifying JS_Parse_Error [SyntaxError]: Unexpected token: name «LuxonError», expected: punc «;»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/isaaccambron/code/luxon/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
```

**Comment by AdaRoseCannon** [comment]
Yeah, uglify can't handle ES6. I believe Terser is the modern minifier à la
mode.

**Comment by icambron** [comment]
Thanks, always catching up on tools around here...

**Comment by pgcalixto** [comment]
While a tooling overhaul is not done, as @icambron mentioned, I quickly fixed it changing uglify-js to uglify-es.
It would be a quick way to restore that 404 link.

I also run `npm run build` and it built all the Luxon versions correctly.

What do you all think? Should I submit a PR?

**Comment by icambron** [comment]
Yeah, if that worked, I'll take a PR
