### ISSUE TITLE
Localized presets without year needed

### ISSUE THREAD

**Issue by juiceo** [moment/luxon#772]
I have a pretty simple request which oddly does not really seem to be supported by any of the major date libraries. I would need to display a date as e.g. "October 16th", and have it localized. The correct order of the day/month depends on the locale so this is not really something that can be done properly without it being a preset. 

The `DATE_FULL` preset for `.toLocaleString` already _almost_ does this, but it adds the year at the end. Not sure what the ideal solution here would be in terms of the API but I can think of two suggestions: 

- Add xxx_WITHOUT_YEAR or similar variants of the existing presets
- Add an option to `.toLocaleString` to not display year in the output

In any case, the heavy lifting here is already done as this feature would only require trimming existing outputs. There are tons of use cases for this sort of format, as in many cases it is completely redundant to display the year of a date as it is obvious from context or communicated elsewhere.

If there is already a way to achieve this, would be happy to know! (and it could be mentioned in the documentation as well)

**Comment by icambron** [comment]
hmm, a few things:

>  The correct order of the day/month depends on the locale so this is not really something that can be done properly without it being a preset.

I don't follow that. A preset has no power beyond what just providing your own set of parameters does. The Intl API determines the order. This should work fine:

```js
var monthAndDay = { month: "long", day: "numeric" };
DateTime.local().toLocaleString(monthAndDay) //=> "September 19"
DateTime.local().setLocale("fr").toLocaleString(monthAndDay) //=> "19 septembre"
```

> "October 16th"

This might be a minor point, but there's no way to make "16th". In theory, an Intl implementation could decided that "st", "nd", and "th" endings go on those, but in practice, I don't think they ever do.

With those aside, should we still add a preset? I'm inclined to say no. My reasoning as follows:

 1. It's very easy to do in userland (see above)
 2. It doesn't seem to be very common (haven't heard many requests for it)
 3. We're having bloat trouble with presets

I would certainly reconsider if there's a groundswell of support for the preset

**Comment by juiceo** [comment]
Ok cool! Not all too familiar with this library so did not know that was a possibility - thanks!

**Comment by juiceo** [comment]
>This might be a minor point, but there's no way to make "16th". In theory, an Intl implementation could decided that "st", "nd", and "th" endings go on those, but in practice, I don't think they ever do.

Don't really understand the reasoning here - what do you mean it's not possible? I'm not at all familiar with the inner workings of Intl implementations, is it something controlled by the browser or?

**Comment by icambron** [comment]
Localizations are provided by the browser, yes. Luxon uses the browser-provided Intl API to build your strings. What I'm saying is that I don't think any of the browser implementations provide strings like that, and the Intl API doesn't, as far as I know, provide any switch to tell it you want them.
