### ISSUE TITLE
Duration doesn't work as expected

### ISSUE THREAD

**Issue by AjaySewradj** [moment/luxon#781]
I'm trying to use the Duration object to create a countdown clock by using the minus function to subtract a second. But it seems that the minus function operates on the units (e.g. seconds) independently.

Steps to reproduce

```
var duration = Duration.fromObject({minutes: 1, seconds: 0})
var time = `${duration.minutes} : ${duration.seconds.toString().padStart(2, '0')}`

var newDuration = duration.minus({seconds: 1});
var newTime = `${duration.minutes} : ${duration.seconds.toString().padStart(2, '0')}`

```
**Expected:**
time:              1:00
newTime:       0:59

**Actual:**
time:              1:00
newTime:       1:-1

**Comment by icambron** [comment]
Yes, each unit is independent. Switch your third line to this in order to "reshuffle" the units:

```js
var newDuration = duration.minus({seconds: 1}).normalize();
```

**Comment by RemyMachado** [comment]
@icambron 
It seems the behavior is inconsistent. If I had to guess I would say that if the upper unit is present, then it's automatically subtracting from it, if not, then it goes into negative.
Please, check this [codesandbox](https://codesandbox.io/s/luxon-countdown-not-normalized-yqhmx?file=/src/App.js).
