### ISSUE TITLE
Can we use luxon in google apps scripts?

### ISSUE THREAD

**Issue by naoya7076** [moment/luxon#783]
Unfortunately, Moment.js is in maintenance mode. https://momentjs.com/docs/#/-project-status/
We could use Moment.js in google apps scripts.
If we can use luxon in gas, I would like to know library ID and how to use.
We can't use it, I want to know alternatives.

**Comment by icambron** [comment]
Yes, please give it a try. You might find StackOverflow more helpful for these kinds of questions, since I'm not a GAS expert

**Comment by ianhyzy** [comment]
I'm trying to do this now and failing — `eval(UrlFetchApp.fetch('https://cdn.jsdelivr.net/npm/luxon@3.0.3/build/global/luxon.min.js').getContentText());`
 doesn't work, but it did for moment. I get `ReferenceError: DateTime is not defined`
