### ISSUE TITLE
DateTime.toLocaleString with TIME_24_SIMPLE Results in Invalid Time

### ISSUE THREAD

**Issue by DeanPoulin** [moment/luxon#787]
The below code results in a string value of "24:49" instead of "00:49" for a time that's equal to 12:49 AM Sept 30th.

```javascript
import { DateTime } from 'luxon';

const twelve49AmSept30th = DateTime.fromMillis(1601441350107);
const timeIn24Simple = twelve49AmSept30th.toLocaleString(DateTime.TIME_24_SIMPLE);

console.log(timeIn24Simple);   // timeIn24Simple = "24:49" instead of "00:49"
```

This code is running in the browser, Google Chrome - Version 85.0.4183.121 (Official Build) (64-bit) and I'm using version 1.25.0 imported as an ES6 module. I'm on macOS Catalina 10.15.2, my timezone is set by macOS as Eastern.

I would expect the above code to result in printing out 00:49

See attached screen shot of me debugging in Google Chrome on a breakpoint where you can see the value of timeNow is not valid.

<img width="1078" alt="Screen Shot 2020-09-30 at 1 00 25 AM" src="https://user-images.githubusercontent.com/246410/94647118-d3c66080-02bd-11eb-8349-803a6c949c97.png">

I also put this sample out on codesandbox.io with a simplified example of what I'm seeing.

[![Edit kind-rubin-l02mp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-rubin-l02mp?fontsize=14&hidenavigation=1&theme=dark)

Chromium Version 86.0.4197.0 (Developer Build) (64-bit) has the same issue as Chrome.

<img width="1312" alt="Screen Shot 2020-09-30 at 1 32 17 AM" src="https://user-images.githubusercontent.com/246410/94646704-d1afd200-02bc-11eb-98cb-c7b5dcc9c301.png">

Google Chrome Canary Version 87.0.4277.0 (Official Build) canary (x86_64) has the same issue:

<img width="1230" alt="Screen Shot 2020-09-30 at 1 35 25 AM" src="https://user-images.githubusercontent.com/246410/94647207-fb1d2d80-02bd-11eb-9252-ff91f3801459.png">

It looks ok in Safari and Firefox

<img width="1369" alt="Screen Shot 2020-09-30 at 1 29 22 AM" src="https://user-images.githubusercontent.com/246410/94646552-72ea5880-02bc-11eb-9402-84d1016957d4.png">

**Comment by GillesDebunne** [comment]
Thanks for this feedback. This is already tracked in #726
