### ISSUE TITLE
Parse/format SQL dates, times, and datetimes

### ISSUE THREAD

**Issue by icambron** [moment/luxon#79]
Luxon should support SQL times with a new static method called `fromSQL` and instances methods `toSQL`, `toSQLDate`, and `toSQLTime`:

 * `fromSQL` accepts strings like '2016-05-14', '04:12:00.123', and ‘2016-05-14 10:23:54.234’ and should be implemented in the regex parser (see the ISO equivalent method)
 * `toSQLDate`, `toSQLTime`, and `toSQL` should output strings like '2016-05-14', '04:12:00.123', '2016-05-14 10:23:54.234`, respectively. There are analogous ISO-outputting methods to refer to.
 * Times and Datetimes should output up to milliseconds but parse up to nanoseconds

**Comment by tuananh** [comment]
@icambron i'll bite. can you help review it https://github.com/moment/luxon/pull/83

**Comment by dobromyslov** [comment]
What about fromNanoseconds()?

For exampre Google Firestore can return timestamp only in seconds and nanoseconds.

**Comment by icambron** [comment]
No, two reasons we won't do that:

 * It would imply to many people that we support nanosecond precision, which we do not

 * It's easy enough to multiply by 1e6. We always need to trade-off usefulness vs bloat. I don't think that makes the cut

**Comment by benj5378** [comment]
Please add this to the documentation
