### ISSUE TITLE
Unexpected `weekNumber` behaviour

### ISSUE THREAD

**Issue by gurki** [moment/luxon#790]
**version:** 1.25.0

Hi there!

I'm trying to get the date of the first day of the first iso week of a certain year (can be in the previous year).
However, there seems to be an issue, where `set( { weekNumber: 1 } )` does not yield the expected result of some date in WN1, which is from `2005-01-03` to `2005-01-09`.
The year is set falsely, looks like an off-by-one error.

```js
const date = luxon.DateTime.local( 2005 )
const weekDate = date.set( { weekNumber: 1 } )

console.log( date.toISODate(), weekDate.toISODate() )

/*  output: "2005-01-01" "2004-01-03" */
```

You can check it out in [codepen](https://codepen.io/gurki/pen/abNgzOr).
Thanks and cheers.

**Comment by gurki** [comment]
Looked through the code and might have found an issue in `weekToGregorian` conversion. Opened draft PR for you guys, maybe it's the right track.

**Comment by icambron** [comment]
You're confusing week years and Gregorian years. `local` works with the Gregorian calendar, but you're expecting the result to be in the 2005 week year:

```js
const date = luxon.DateTime.local( 2005 ) // => January 1, 2005
date.weekYear // => 2004, because Jan 1, 2005 is at the end of the 2004 ISO week year
const weekDate = date.set( { weekNumber: 1 } ) // => the first week of the 2004 week year
```

Instead, try this:

```js
luxon.DateTime.fromObject({ weekYear: 2005}) //=> Jan 3, 2005
```

**Comment by gurki** [comment]
Ah, I see, the conversion is based on `weekYear` which is set implicitly. Thanks a bunch! 
The ghost I saw in code was just a different form of the conversion and of course totally correct as is.
Appreciate the quick help, cheers :).
