### ISSUE TITLE
add extension point for hard-coded limit in 1960 

### ISSUE THREAD

**Issue by olmobrutall** [moment/luxon#792]
Hi @icambron, 

first of all thanks for building such a great library. After reading [this Hacker News post](https://news.ycombinator.com/item?id=24477941), I followed the advice and moved [Signum Framework from moment.js to luxon](https://github.com/signumsoftware/framework/commit/b2096177de9f84c91d226e1a6080386c55566d2a#commitcomment-42575134). The process was relatively smooth thanks to [the migration guide](https://moment.github.io/luxon/docs/manual/moment.html). The API looks simple and well designed. Great work!

I've successfully migrated the Framework and a few projects, but now I'm stuck in one project where I had this override: 

```JS 
(moment as any).parseTwoDigitYear = (yearString: string) => {
  var date = parseInt(yearString) + 2000;

  var limit = new Date().getFullYear() + 10;

  if (date > limit)
    date -= 100;

  return date;
}

```

Moment.js has a method `parseTwoDigitYear` that **can be overriden**. The equivalent in luxon is [`untruncateYear`](https://github.com/moment/luxon/search?q=untruncateYear) but I don't see how could I override it. 

This is a very important feature in this application. Most of the dates are birth dates from people going to hospital, many of them born before 1960, so not having this feature means the workers can not parse dates in the format ddMMyy that they are used to.

A great yet simple solution would be to have something like: 

```C#
luxon.Settings.maxTwoDigitYear = 2030; 
```

**Comment by icambron** [comment]
Yeah, I think we'd accept a PR along the lines of what you proposed

**Comment by olmobrutall** [comment]
At the end I realized that Luxon has no relaxed parse functionality line `moment.js` does, so I had to implement it myself and as part of it was very easy to make the 2 digit year consideration: 

I can imagine that his relaxed parsing feature is quite dependent on each particular use case so I'm happy implementing it myself. 

About the twoDigit year, will be better to have it in Luxon but I can not justify a full "clone repo / make changes / test / documentation / PR / wait for it to get accepted / maybe made changes again / wait for it to be published" workflow for luxon and for @types/luxon. 

Still, maybe the snippet I'm using is usefull to someone: 


```
   var maxTwoDigitYearDefault = maxTwoDigitYear ?? DateTime.local().year + 10;
    (...)
    parse: function parse(value: string, format: string, culture: string) {
      debugger;
      if (value == undefined || value == "")
        return undefined;

      let t = DateTime.fromFormat(value, format ?? "F", { locale: culture })
      if (t.isValid)
        return t.toJSDate();

      t = DateTime.fromFormat(value, "D", { locale: culture })
      if (t.isValid)
        return t.toJSDate();

      t = DateTime.fromFormat(value, "ddMMyy", { locale: culture })
      if (t.isValid) {
        if (value.length == 6) {
          var twoDigitYear = parseInt(value.substr(4, 2));
          t = t.set({ year: twoDigitYear > maxTwoDigitYearDefault ? 1900 + twoDigitYear : 2000 + twoDigitYear });
        }
        return t.toJSDate();
      }

      return undefined;
    },
```
