### ISSUE TITLE
Moments isBetween analog

### ISSUE THREAD

**Issue by AlexZd** [moment/luxon#793]
Hi, I can see in your docs that analog of `m1.isBetween(m2, m3)` is `Interval.fromDateTimes(dt2, dt3).contains(dt1)`, but in moments there is also nice thing that I can pass inclusivity as `[]`, `(]` and etc, to not include start or end in comparing.

Is there any way to do similar thing:
```
time.isBetween(from, to, undefined, "[)");
```

**Comment by icambron** [comment]
There isn't a special method, but IMO this is pretty good:

```js
time >= from && time < to
```
