### ISSUE TITLE
[Feature Request] Provide method to accept the format presets for parsing

### ISSUE THREAD

**Issue by cutterbl** [moment/luxon#805]
Not sure what the actual implementation would be here, but would be helpful if the formatting Presets were also available for parsing. Something like:

```js
const dateObj = DateTime.fromPreset('10/08/2020', DateTime.DATE_SHORT, options);
```
Would be extremely helpful for those of us who have to manage two way conversions.

**Comment by icambron** [comment]
This is probably possible, yeah. We already have a lot of this logic, in fact; the way this code works:

```js
const dateObj = DateTime.fromFormat("10/08/2020", "D")
```

... is to turn `D` into `DateTime.DATE_SHORT` and then do some cleverness to convert that into a more granular token format, then feed that back into the parser as the format. With a little refactoring, you could make it use that cleverness directly. I'd take a sufficiently compact PR.

**Comment by diesieben07** [comment]
I believe this has been implemented in the form of `DateTime.parseFormatForOpts`:
```js
const format = DateTime.parseFormatForOpts(DateTime.DATE_SHORT); // M/d/yyyyy
const dt = DateTime.fromFormat('3/4/2023', format); // 2023-03-04
```

Let me know if there are other use-cases not covered by this method.
