### ISSUE TITLE
forrmat the date with format with escape characters

### ISSUE THREAD

**Issue by sanket-bhalerao** [moment/luxon#814]
i want to format the date to format like 'YYYY-MM-DDTHH:mm:ss', (i am moving from moment)
here 'T' is a format specifier and i can not seem to escape it. if i want to set the date to the datetime_local html field it needs the string to be in the format. 
is there a way to escape the 'T' charater?

**Comment by GillesDebunne** [comment]
It looks like you are looking for the `toISO()` method.

Special characters are otherwise escape using single quotes using `toFormat()`, as in `yyyy-MM-dd'T'hh:mm:ss`
