### ISSUE TITLE
Warning in manual for "Comparing Dates"

### ISSUE THREAD

**Issue by fforw** [moment/luxon#815]
"Comparing Dates" in the manual contains the following code example

```js
d1.toMillis() === d2.toMillis() // are d1 and d2 the same instant in time?
+d1 === +d2 // same test, using object coercion
```

with the latter having some questionable Properties. It's kinda cute that `+null === +Date.fromMillis(0)`, it's maybe not something that is obvious or wanted in all cases.

Even more puzzling then is the fact that two undefined Dates are not equal.

Shouldn't people be made aware of these issues?

**Comment by icambron** [comment]
Those are not questionable properties of Luxon, though. They are questionable properties of Javascript numbers. For example, `+undefined == +undefined` means `NaN == NaN` which is false. I agree that stuff really is quite puzzling! But it's not really the place of Luxon's guide to explore the wackiness of Javascript comparisons. If we had to walk though every pitfall in JS, we'd end up with a book.

**Comment by fforw** [comment]
But you are advertising the questionable method in your docs.
