### ISSUE TITLE
Only milliseconds property set on `Duration`

### ISSUE THREAD

**Issue by wozzo** [moment/luxon#816]
The `Duration` object always returns 0 for the years, months, days,... properties.
The only one that works is the milliseconds.

I've reproduced on [code sandbox](https://codesandbox.io/s/eloquent-gates-5ffdq?file=/src/index.js)

```javascript
import "./styles.css";
import { DateTime, Duration } from "luxon";

const a = DateTime.fromISO("2020-01-01");
const b = DateTime.fromISO("2010-10-15");

const d = a.diff(b);

console.log({
  years: d.years,
  months: d.months,
  days: d.days,
  hours: d.hours,
  minutes: d.minutes,
  seconds: d.seconds,
  ms: d.milliseconds
});
```

Produces an output of

```
{
  years: 0,
  months: 0,
  days: 0,
  hours: 0,
  minutes: 0,
  seconds: 0,
  ms: 290739600000
}
```

Am I missing a step?

**Comment by pgcalixto** [comment]
Hi there @wozzo, from inspecting the code and reading the documentation I believe it is intended to be this way (one of the maintainers please correct me if I'm wrong). When you call the diff of a DateTime with just 1 argument like you've done, the default behavior is to create a Duration with only the milliseconds property set, while the others properties are 0.

You can, however, use other alternatives to obtain the units you want.

One of them is by Duration's [toFormat](https://moment.github.io/luxon/docs/class/src/duration.js~Duration.html#instance-method-toFormat), then splitting the string.
The other one is by passing the desired units when using DateTime's [diff](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-diff).

There is an example using the second alternative:

```ts
import { DateTime, Duration } from "luxon";
const { DateTime, Duration } = require("luxon");

const a = DateTime.fromISO("2020-01-01");
const b = DateTime.fromISO("2010-10-15");

const diffUnits = ['years', 'months', 'days', 'hours', 'minutes', 'seconds', 'milliseconds'];
const d = a.diff(b, diffUnits);

console.log({
  years: d.years,
  months: d.months,
  days: d.days,
  hours: d.hours,
  minutes: d.minutes,
  seconds: d.seconds,
  ms: d.milliseconds
});
```

```js
// =>
{
  years: 9,
  months: 2,
  days: 17,
  hours: 0,
  minutes: 0,
  seconds: 0,
  ms: 0
}
```

**Comment by icambron** [comment]
yes, @pgcalixto is correct. Luxon doesn't know what units you want (e.g. that example excluded `weeks` which you often wouldn't want!). `milliseconds` is just the default unit. Just set the units you want to work in when you do the diff (you can also use `shiftTo` but you need to be careful about [losing information](https://moment.github.io/luxon/docs/manual/math.html#losing-information)

**Comment by wozzo** [comment]
Cheers @pgcalixto. The `diffUnits` is what I was missing.
