### ISSUE TITLE
Custom INTL for non en-US locales

### ISSUE THREAD

**Issue by hottehead** [moment/luxon#818]
**Is your feature request related to a problem? Please describe.**
Im frustrated after seeing that the native INTL is terribly slow for non-en locales. 

**Describe the solution you'd like**
I'd like to add the INTL for some languages myself. I read that luxon uses its internal INTL if possible. I'd like to enhance the internal INTL with my own language set, so I dont need native INTL.

**Describe alternatives you've considered**
* Going back to moment
* Not using localised strings
* Using a date lib not based on native INTL

**Additional context**
Im totally stunned about how bad the native INTL is. In fact it's unusable. Thus I think it might be desirable to give the possibility to add own custom INTL sets.

**Comment by icambron** [comment]
I agree the native Intl is unconscionably slow. It's baffling.

But the best way to handle this would be to simply override the native intl features. That keeps the API consistent for Luxon, allows other libraries used by your app to use the same customizations, and just generally simplifies things. Luxon doesn't know it's using something "native"; it only knows that it's using `Int.*`

**Comment by hottehead** [comment]
I have never worked with native INTL. But in fact I want to prevent this slow INTL code from executing. I dont mind in which layer I add my custom INTL. 
Could you give me a hint where to start with this? I've searched for 'nodejs custom INTL'  but no luck.

**Comment by icambron** [comment]
The easiest way to start is probably by forcing in an Intl polyfill, such as this one: https://github.com/andyearnshaw/Intl.js/, basically by just say `Intl = thatPolyfill`. Then you can customize the locales inside of it.

On reflection, that might not be such a good idea, depending on your needs. Luxon also uses Intl to do time zone calculations, which would create a significant burden on your implementation (e.g. that ashaw polyfill doesn't support zones, iirc).

And that's sort of the rub: Intl is slow and cumbersome, but it does provide a lot of features. Those features are hard to replicate

**Comment by icambron** [comment]
Though it is true that I implemented en-US in code for Luxon, mostly as an optimization. We can consider if it's possible to make that pluggable.

**Comment by hottehead** [comment]
Thanks for the starting points. As I understand there are 2 layers to implement and solve this

1. Polyfilling all locale aware functions in the `INTL.*` namespace
2. Enhancing the custom en-US locale implementation in luxon and making it pluggable to allow for other locales, too

Sadly I cant provide any of them as I dont have the time/knowledge for it. As far as Im concerned this issue can be closed.
