### ISSUE TITLE
Timezone "Poland" is invalid

### ISSUE THREAD

**Issue by alfredvaa** [moment/luxon#825]
The timezone "Poland" is not working, but it is [listed](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) as a timezone, although deprecated. I am not sure if Luxon is supposed to support deprecated timezones or not, is there a complete list? Luxon is not working well with the timezone-selector from [blueprint](https://github.com/palantir/blueprint/issues/4394) as "Poland" is listed there.

**Comment by icambron** [comment]
Luxon supports whatever the browser supports in Intl. The browser uses ICU data to drive that, though I don't know what subset of that they include or how often they update it. Unfortunately, there's no way to generate a list directly our of the browser, but it doesn't seem to ever support zones of the form`Poland` as compared to, e.g. `Europe/Warsaw`, and you can't typically find zones like that in other zone tables either.

**Comment by alfredvaa** [comment]
It looks like blueprint is getting its list from [moment-timezone](https://github.com/palantir/blueprint/issues/4394#issuecomment-718846176) and moment is related to Luxon I guess 😅. But I guess it could be that moment-timezone is also getting it from Intl in the browser? I am getting Poland in the list of timezones within an Electron app, and I use Luxon in nodejs 10.16.3. I'll dig further into this in someway, thanks anyway!

**Comment by icambron** [comment]
moment-timezone has its own list, periodically imported from external sources. So it's completely separate
