### ISSUE TITLE
parsing 24:00 is now illegal in ISO 8601

### ISSUE THREAD

**Issue by ericsnap** [moment/luxon#826]
It appears that the newer version of ISO 8601 does not allow `24:00` as a value. According to [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601):

> As of ISO 8601-1:2019 midnight may only be referred to as "00:00", corresponding to the beginning of a calendar day. Earlier versions of the standard allowed "24:00" corresponding to the end of a day, but this is explicitly disallowed by the 2019 revision.

code sample:
```typescript
const date = DateTime.fromFormat('24:00', 'HH:mm');
// date is set to today+24h or "end of day today"
```

With the new ISO 8601, I would expect the parsing to fail.

- OS: MacOS Catalina 10.15.7
- Browser Chrome Version 86.0.4240.111, Edge Version 86.0.622.58
- Luxon version 1.25.0 (in my NodeJS app) but also on the latest version or whatever is on the website

**Comment by icambron** [comment]
Unfortunately, the standard updating last year doesn't mean all the software using it has been updated accordingly. So while I agree in spirit and also hate that 24:00 was ever part of the standard, Luxon can't really just drop support for it. That would result in broken applications and needless pain. 


Besides saving a few bytes, there seems little upside to dropping it. Which has me curious: do you have an application in which returning an invalid date for this is desired behavior?

**Comment by ericsnap** [comment]
@icambron that makes sense. I ran into this as I was implementing an input box that allows users to enter a time (of day). In the end, for my use case `24:00` gets parsed to 0 hour and 0 minute, which is just fine as I don't use the date part of the object.
