### ISSUE TITLE
Wrong german date format

### ISSUE THREAD

**Issue by mbeckenbach** [moment/luxon#828]
**Describe the bug**
DATE_SHORT gives wrong format with locale "de"

**To Reproduce**
dateTime.setLocale('de').toLocaleString(DateTime.DATE_SHORT)

**Actual vs Expected behavior**
Actual: 1.1.2020 (d.M.yyyy)
Expected: 01.01.2020 (dd.MM.yyyy)

**Desktop (please complete the following information):**
- OS: [Windows]
- Browser [Chome (86)]
- Luxon version [1.25.0]

**Additional context**
In Date and Time formats, Germans keep the leading 0.
So we would always write something like: 01.01.2021 01:01:01:001

Even the Year 2005 would be displayed as short 05

**Comment by GillesDebunne** [comment]
The internationalisation part of Luxon is handled by the Intl implementation in the browser.

Try this in your browser's console:
```
console.log(new Intl.DateTimeFormat('de-DE').format(new Date(Date.UTC(2020, 0, 1))));
// 1.1.2020
```

Chromium 88, Firefox 82 and Safari 14 all give the same result.

However, `DATETIME_SHORT` asks for "numeric" values, which may not depend on the locale (and at least seem incorrect for German).

Asking for [`2-digit`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Intl/DateTimeFormat) instead gives the correct result:
```
console.log(new Intl.DateTimeFormat('de-DE', {year: "numeric",  month: "2-digit",  day: "2-digit" }).format(new Date(Date.UTC(2020, 0, 1))));
// 01.01.2020
```

which translates to:
```
const MY_FORMAT = {year: "numeric",  month: "2-digit",  day: "2-digit" }
dateTime.setLocale('de').toLocaleString(MY_FORMAT)
```

Note that the locale is taken into account for the number separator, which translates to `"/"` for `en-US`.

**Comment by mbeckenbach** [comment]
Thanks, that worked so I could add some workaround for it.
If this is a problem in Intl that might affect a lot of browsers, it might be worth to report this somewhere. 
Can you tell where?

```typescript
if ((culture) === 'de') {
   format.day = format.day === 'numeric' ? '2-digit' : format.day;
   format.month = format.month === 'numeric' ? '2-digit' : format.month;
   format.hour = format.hour === 'numeric' ? '2-digit' : format.hour;
   format.minute = format.minute === 'numeric' ? '2-digit' : format.minute;
   format.second = format.second === 'numeric' ? '2-digit' : format.second;
}

return dateTime.setLocale(culture).toLocaleString(format);
```

**Comment by icambron** [comment]
I would think this complaint would go to [cldr](https://github.com/unicode-org/cldr), from which these formats are eventually imported to the browser. That said, I'm far from an expert on the process
