### ISSUE TITLE
Parsing Islamic calendar string to luxon gregory DateTime

### ISSUE THREAD

**Issue by Cassini2K20** [moment/luxon#830]
Hi,

How can I parse an Islamic calendar string like ("1442/03/23") to its equivalent luxon Gregory DateTime object (2020/11/09)?

best regards,

**Comment by icambron** [comment]
Luxon doesn't support this. It can _format_ dates in the Islamic calendar, but it can't parse them. This is a limitation of the Intl API Luxon uses to do this. See [calendars](https://moment.github.io/luxon/docs/manual/calendars.html)
