### ISSUE TITLE
toLocaleString returns incorrect FixedOffsetZone abbreviation

### ISSUE THREAD

**Issue by jonathanberger** [moment/luxon#834]
**Describe the bug**
toLocaleString returns "UTC" instead of "UTC+1" as expected, when called on a DateTime with the "UTC+1" timezone.

**To Reproduce**
var hours = 1;
var min_ph = 60;
DateTime.local().setZone(FixedOffsetZone.instance(hours * min_ph)).toLocaleString({timeZoneName:'short'});

**Actual vs Expected behavior**
Actual: returns "11/19/2020, UTC"
Expected: return "11/19/2020, UTC+1"

**Desktop:**
- OS: Mac
- Browser: Safari 14.0
- Luxon version: Sorry, I don't know how to figure this out.

**Comment by icambron** [comment]
Yeah, this is an unfortunate bug. If you print more than the date, you'll see it actually converts the time to UTC. This is the comment in the code corresponding to it:

```js
      // Chromium doesn't support fixed-offset zones like Etc/GMT+8 in its formatter,
      // See https://bugs.chromium.org/p/chromium/issues/detail?id=364374.
      // So we have to make do. Two cases:
      // 1. The format options tell us to show the zone. We can't do that, so the best
      // we can do is format the date in UTC.
      // 2. The format options don't tell us to show the zone. Then we can adjust them
      // the time and tell the formatter to show it to us in UTC, so that the time is right
      // and the bad zone doesn't show up.
      // We can clean all this up when Chrome fixes this.
```

You are in case 1. I would love to fix this; it would simplify the code and remove this ugly gotcha. I just tried it, though, and the Chrome bug still seems to be there:

<img width="620" alt="364374_-_Some_official_time_zone_IDs_are_not_accepted_by_Intl_DateTimeFormat__-_chromium" src="https://user-images.githubusercontent.com/244988/99753828-0a964700-2ab5-11eb-9e38-e516391c2f38.png">

If any of those worked, I could (and would) fix this. I haven't had time to thoroughly review the Chrome upstream bug (which is marked as "fixed") so I'm not sure what's up there

**Comment by jonathanberger** [comment]
Wow, thanks so much for the quick and detailed reply! No problem about the next steps - hope the report was helpful as feedback.
