### ISSUE TITLE
What is the correct way to get the DateTime value from the database?

### ISSUE THREAD

**Issue by leandromatos-hotmart** [moment/luxon#835]
For write in MySQL database I used:

```js
DateTime.local().setLocale('pt-BR').toSQL({
    includeOffset: false,
 })
```

Now I need to do some mathematical operations with the record that has a date.

First I tried to get the value with the code below to try to perform the mathematical operation, but I got an error.

```js
// syncedAt is an variable that's return the DateTime value from database: 2020-11-19 12:00:00
DateTime.fromSQL(syncedAt)
// .plus({
//   hours: 6,
// })
// .toSQL({
//   includeOffset: false,
// })
```

```sh
DateTime {
  ts: 1605814564165,
  _zone: LocalZone {},
  loc: Locale {
    locale: 'en-US',
    numberingSystem: null,
    outputCalendar: null,
    intl: 'en-US',
    weekdaysCache: { format: {}, standalone: {} },
    monthsCache: { format: {}, standalone: {} },
    meridiemCache: null,
    eraCache: {},
    specifiedLocale: null,
    fastNumbersCached: null
  },
  invalid: Invalid {
    reason: 'unparsable',
    explanation: `the input "Thu Nov 19 2020 12:00:00 GMT-0300 (Brasilia Standard Time)" can't be parsed as SQL`
  },
  weekData: null,
  c: null,
  o: null,
  isLuxonDateTime: true
}
```

What is the correct way to get the DateTime value from the database, so that I can continue performing the desired operation?

**Comment by icambron** [comment]
The type of `syncedAt` is expected to be a string like `2020-11-19 12:00:00` but according to that result, it's a string like `"Thu Nov 19 2020 12:00:00 GMT-0300 (Brasilia Standard Time)"`, which obviously `fromSql` can't parse. So I think the code you have is just not doing what you think it's doing. I recommend playing with it a bit in the dev console to see what `syncedAt` really is.

**Comment by leandromatos-hotmart** [comment]
Thanks for responding @icambron.

The trouble was in the Sequelize connection config. After adding the dialect options below for MySQL, everything works perfectly.

```js
module.exports = {
  dialect: 'mysql',
  ...
  dialectOptions: {
    dateStrings: true,
    typeCast: true,
  },
  timezone: '-03:00',
  ...
}
```
