### ISSUE TITLE
Add getFirstDayOfWeek functionality to support angular material date adapter

### ISSUE THREAD

**Issue by IbrahimElkhatib** [moment/luxon#836]
Community is trying to add date adapters to be used in angular material instead of the MatMomentDateModule, Material DateAdapter needs getFirstDayOfWeek functionality: 
    /**
     * Gets the first day of the week.
     * @returns The first day of the week (0-indexed, 0 = Sunday).
     */
    abstract getFirstDayOfWeek(): number;

So we need equivalent to the moment functionality: moment.localeData().firstDayOfWeek()

**Comment by icambron** [comment]
Luxon doesn't support localized week numbering; the only week calendar in Luxon is the ISO one, where the week starts on Monday. So I suppose you could just make it return `1`?
