### ISSUE TITLE
Subtracting dates in UTC not returning expected value

### ISSUE THREAD

**Issue by mboekhold** [moment/luxon#837]
**Describe the bug**
Subtracting two datetime objects to return the difference is not returning the expected value. every result is being returned with + 1 hour

**To Reproduce**
Note: Incoming date is UTC
`const activityDate = DateTime.fromISO(isoDate)`
 `const now = DateTime.local().toUTC()`
 `const secondsPast = (now - activityDate) / 1000`

**Actual vs Expected behavior**
dubbing the two dates, I can conclude that the difference between the two was about ~2 minutes
but calculating the difference returns 1 hour and 2 minutes. (in milliseconds ofcourse)

**Desktop (please complete the following information):**

- OS: Ubuntu 18.04.4 LTS
- Browser: Chrome 80
- Luxon version: 1.25.0

**Additional context**

**Comment by icambron** [comment]
Can you fill your example out with real values? Like what is the string, and what is your current time, and what does `DateTime.utc().toISO()` return? I can't reproduce this and I'm very confident this works as expected. I suspect you might have something mixed up, but you didn't provide me much info!

**Comment by mboekhold** [comment]
`const activityDate = DateTime.fromISO('2020-11-30T17:44:58.910211')` 

`const now = DateTime.local().toUTC()` 
returns a DateTime object with the values `{ year: 2020, month: 11, day: 30, hour: 17, minute: 50, second: 4, millisecond: 602}`

and `const secondsPassed = (now - activityDate)` returns 4507607 milliseconds

I would expect it to return ~450000 milliseconds since it is actually about 7 minutes difference, it seems like it is adding ^10 to the result of the calculation?

Maybe I'm doing something wrong here but I'll be glad to be corrected about it.

Thanks

**Comment by icambron** [comment]
The problem is that while *you* know that `2020-11-30T17:44:58.910211` is a UTC time, Luxon does not, because the string doesn't specify that. It thus interprets it as a local time. Then when you subtract, it computes the epoch milliseconds by converting to UTC. That's where you're gaining the hour.

So you need to tell Luxon that the time is in UTC:

```js
activityDate = DateTime.fromISO('2020-11-30T17:44:58.910211', {zone: "utc"})

// or add a Z

activityDate = DateTime.fromISO('2020-11-30T17:44:58.910211Z').toUTC() // toUTC() unnecessary, but here for symmetry
```

**Comment by mboekhold** [comment]
Thank you for clearing things up
