### ISSUE TITLE
How to get localized format string

### ISSUE THREAD

**Issue by thedavidhoffman** [moment/luxon#839]
Sorry if this doesn't belong here, wasn't sure how else to ask this question.

I need to get the localized string format from Luxon. Examples: If we're in english MM/DD/YYYY or if we're in french DD/MM/YYYY.

I need this to set as placeholder text for input fields. Previously I could get this from moment, but I'm not sure if it's available in Luxon and I didn't see it anywhere in the documentation. Did I miss it?

**Comment by icambron** [comment]
Good question. We don't have anything like that available. But obviously a lot of the pieces are there, more a matter of exposing them in API.

**Comment by stinachen** [comment]
Is there any update on this?

**Comment by diesieben07** [comment]
I believe this has been implemented in the form of `DateTime.parseFormatForOpts`:
```js
const format = DateTime.parseFormatForOpts(DateTime.DATE_SHORT); // M/d/yyyyy
```

Let me know if there are other use-cases not covered by this method.
