### ISSUE TITLE
Failed to parse string to DateTime object: yyyy-LL-DD H:mm:ss

### ISSUE THREAD

**Issue by mythjuha** [moment/luxon#842]
**Describe the bug**
I'm trying to parse a string formatted like '2020-12-13 22:12:00' using the format code 'yyyy-LL-DD H:mm:ss'. I've also tried using MM instead of LL as those 'format options' seem to have a 'standalone token' and a 'formatting token', but neither works. Not sure what that means. What am I doing wrong?

**To Reproduce**
let t = DateTime.fromFormat('2020-12-13 22:12:00', 'yyyy-LL-DD H:mm:ss', { zone: 'utc' })

**Comment by icambron** [comment]
`dd`, not `DD`. `DD` is the whole localized date, like "Aug 6, 2014", so it was expecting that whole thing in the string. See [here](https://moment.github.io/luxon/docs/manual/parsing.html). You can usually track these down using `fromFormatExplain`:

<img width="1342" alt="Luxon" src="https://user-images.githubusercontent.com/244988/102030436-ca0eae00-3d80-11eb-9dbd-24c61b60a246.png">

So you can see from the regex it gets translated to...

**Comment by mythjuha** [comment]
I tried it and saw the jan/feb/mar, etc .... so that's why I was focussing on the LL / MM thing. Thanks for the response!

**Comment by icambron** [comment]
The LL and MM are the `(\d{2})` toward the beginning

**Comment by Landys18** [comment]
Isaac did you make this? I'm new and have questions Mr Cambron
