### ISSUE TITLE
Standalone weekday is lowercase for Spanish locale

### ISSUE THREAD

**Issue by germanfr** [moment/luxon#844]
**Describe the bug**
Using the standalone token for getting the week day ("cccc") does not return a correct value for the Spanish locale. 

In Spanish, week days and months are expected to start with an upper case letter if they appear standalone (like in a calendar UI or a schedule header) or at the start of a sentence.

**To Reproduce**

```js
import { DateTime, Settings } from 'luxon';

Settings.defaultLocale = 'es'
const dt = DateTime.local();

// Format token
console.log(dt.toFormat('EEEE')); // "lunes"


// Standalone token
console.log(dt.toFormat('cccc')); // Also "lunes", expecting "Lunes"
```

**Actual vs Expected behavior**
The standalone version should be capitalized ("Lunes" instead of "lunes").

This is what should be like, but instead they are all lowecase:
```
Lunes - viernes: 9:00 - 20:00 <-- Start of sentence and normal
Sábado: 9:00 - 14:00 <-- Standalone
Domingo: cerrado <-- Standalone
```

Of course I could manipulate the strings to make them look like what I want, but I don't know if the same rule applies to all other languages or languages with non-latin characters.

**Desktop:**

- OS: Windows 10
- Browser: Chrome 87
- Luxon version: 1.25.0

**Comment by icambron** [comment]
Unfortunately, this is what your browser is returning when asked for the Spanish weekday, not a decision Luxon is making. Trying to capitalize it in Luxon has the same problem you're describing: making sure it's really correct across all languages. Generally, Luxon's role is to manipulate the Intl library into giving good localized tokens; it isn't the source of the data itself.

**Comment by germanfr** [comment]
I understand. Do you know if there is any place where this bug to be reported?

**Comment by icambron** [comment]
It's probably ultimately the CLDR: http://cldr.unicode.org/.

But I'd start with Chrome, reporting that this should result in a capitalized string:

```js
new Intl.DateTimeFormat("es", { month: "long"}).format() //=> "diciembre"
```
