### ISSUE TITLE
startOf('day') returns wrong timestamp

### ISSUE THREAD

**Issue by Lucria** [moment/luxon#847]
**Describe the bug**
`.startof("day")` seems to add an additional 24 hours offset to a timestamp's timezone.

**To Reproduce**
```
const timezone = "Asia/Singapore";
const timestamp = 1609818520001;
const test = DateTime.fromMillis(timestamp).setZone(timezone);
console.log(test.zoneName);  // Returns "Singapore Standard Time"
console.log(test.offset); // Returns 480. This corresponds to timezone being GMT+8
const test2 = DateTime.fromMillis(timestamp).setZone(timezone).startOf("day");
console.log(test2.zoneName); // Returns "Singapore Standard Time"
console.log(test2.offset); // Returns 1920. This should return 480 instead
```

**Actual vs Expected behavior**
Using `.startOf("day")` should still retain the same timezone and offset as the original DateTime object, but in this case it pushes it back by 24 hours for some strange reason.
I wish to get the timestamp representing the start of a certain day within a specific timezone. 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Microsoft Chromium Edge Version 87.0.664.66 (Official build) (64-bit)
- Luxon version 1.8.3 and 1.3.2

**Comment by icambron** [comment]
I wasn't able to reproduce this in Chrome. I suspect it's an Edge bug, but I'll have to wait until I'm at Windows computer

**Comment by Lucria** [comment]
I was able to replicate this issue on jsfiddle as well, but it seems that updating the package to 1.22.0 solves the issue 🤔

**Comment by icambron** [comment]
Oh, I was using latest version when I tested, didn't see the version number.

So it's fixed?

**Comment by Lucria** [comment]
Yeap I believe it is fixed! Thanks
