### ISSUE TITLE
Interval split by

### ISSUE THREAD

**Issue by ijosh** [moment/luxon#848]
I have an interval that is a year and a bit worth of date ranges - from 30 Dec 2019 - 01 Jan 2021. I was looking to use the splitBy to break it up into monthly energy consumption values.

Looks like things get off to a good start - then hits Feb 2020, correctly adjusting for leap year. March 2020 then ends on the 29th which I would guess the correct behaviour should be 31 March.

```javascript
const { DateTime, Duration, Interval, Info }  = require('luxon');


let start = DateTime.fromMillis(1577664000000);
let end = DateTime.fromMillis(1609630200000);

let intervalConsumption = Interval.fromDateTimes(start, end);

// Interval {
//     s: DateTime {
//       ts: 1577664000000,
//       _zone: LocalZone {},
//       loc: Locale {
//         locale: 'en-GB',
//         numberingSystem: null,
//         outputCalendar: null,
//         intl: 'en-GB',
//         weekdaysCache: [Object],
//         monthsCache: [Object],
//         meridiemCache: null,
//         eraCache: {},
//         specifiedLocale: null,
//         fastNumbersCached: null
//       },
//       invalid: null,
//       weekData: null,
//       c: {
//         year: 2019,
//         month: 12,
//         day: 30,
//         hour: 0,
//         minute: 0,
//         second: 0,
//         millisecond: 0
//       },
//       o: -0,
//       isLuxonDateTime: true
//     },
//     e: DateTime {
//       ts: 1609630200000,
//       _zone: LocalZone {},
//       loc: Locale {
//         locale: 'en-GB',
//         numberingSystem: null,
//         outputCalendar: null,
//         intl: 'en-GB',
//         weekdaysCache: [Object],
//         monthsCache: [Object],
//         meridiemCache: null,
//         eraCache: {},
//         specifiedLocale: null,
//         fastNumbersCached: null
//       },
//       invalid: null,
//       weekData: null,
//       c: {
//         year: 2021,
//         month: 1,
//         day: 2,
//         hour: 23,
//         minute: 30,
//         second: 0,
//         millisecond: 0
//       },
//       o: -0,
//       isLuxonDateTime: true
//     },
//     invalid: null,
//     isLuxonInterval: true
//   }

console.log(intervalConsumption.splitBy(Duration.fromISO('P1M')));

// [
//     Interval {
//       s: DateTime {
//         ts: 1577664000000,
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       e: DateTime {
//         ts: 1580342400000,
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       invalid: null,
//       isLuxonInterval: true
//     },
//     Interval {
//       s: DateTime {
//         ts: 1580342400000,
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       e: DateTime {
//         ts: 1582934400000,
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       invalid: null,
//       isLuxonInterval: true
//     },
//     Interval {
//       s: DateTime {
//         ts: 1582934400000,
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       e: DateTime {
//         ts: 1585440000000, <-- NOT AS EXPECTED (29 March 2020)
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       invalid: null,
//       isLuxonInterval: true
//     },
//     Interval {
//       s: DateTime {
//         ts: 1585440000000, <-- NOT AS EXPECTED (29 March 2020)
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: -0,
//         isLuxonDateTime: true
//       },
//       e: DateTime {
//         ts: 1588114800000, <-- THEN THINGS GO WRONG INCREMENTING MONTHS
//         _zone: LocalZone {},
//         loc: [Locale],
//         invalid: null,
//         weekData: null,
//         c: [Object],
//         o: 60,
//         isLuxonDateTime: true
//       },
//       invalid: null,
//       isLuxonInterval: true
//     },

```

**Comment by icambron** [comment]
Yeah, I agree, that seems wrong.

**Comment by dan-overton** [comment]
I've taken a look at this and opened a PR. 

The main change is using the start date of the original duration as the basis for each split period, rather than the end of the previous period which keeps things consistent across the shorter month.

For the example given in the bug report this leads to the following splits:

0: 2019-12-30T00:00:00.000+00:00 - 2020-01-30T00:00:00.000+00:00
1: 2020-01-30T00:00:00.000+00:00 - 2020-02-29T00:00:00.000+00:00
2: 2020-02-29T00:00:00.000+00:00 - 2020-03-30T00:00:00.000+01:00
3: 2020-03-30T00:00:00.000+01:00 - 2020-04-30T00:00:00.000+01:00
4: 2020-04-30T00:00:00.000+01:00 - 2020-05-30T00:00:00.000+01:00
5: 2020-05-30T00:00:00.000+01:00 - 2020-06-30T00:00:00.000+01:00
6: 2020-06-30T00:00:00.000+01:00 - 2020-07-30T00:00:00.000+01:00
7: 2020-07-30T00:00:00.000+01:00 - 2020-08-30T00:00:00.000+01:00
8: 2020-08-30T00:00:00.000+01:00 - 2020-09-30T00:00:00.000+01:00
9: 2020-09-30T00:00:00.000+01:00 - 2020-10-30T00:00:00.000+00:00
10: 2020-10-30T00:00:00.000+00:00 - 2020-11-30T00:00:00.000+00:00
11: 2020-11-30T00:00:00.000+00:00 - 2020-12-30T00:00:00.000+00:00
12: 2020-12-30T00:00:00.000+00:00 - 2021-01-02T23:30:00.000+00:00

Is that how you were expecting it to work?

**Comment by icambron** [comment]
@dan-overton yeah, that looks right to me. I merged your PR

**Comment by ijosh** [comment]
Hi, sorry for the delay in seeing this. I guess if you are splitting on month P1M in particular, then it should align with start and end of month for my application. But there are different opinions about this.

https://stackoverflow.com/questions/26265751/what-is-the-value-of-the-iso-8601-duration-p1m-in-seconds

Has some worthwhile discussion.

From page 6 of the standard (specifically regarding durations)
month: a time-unit of 28, 29, 30 or 31 days.
NOTE In certain applications a month is regarded as a unit of time of 30 days

I would say the library would be useful to automatically determine the number of days in a month when that month/year combination is present.

On that basis, I'm not sure the solution fixes the issue, but it is very nice to see you guys on top of addressing it and working to get resolution. A thank you is in order!
