### ISSUE TITLE
Inconsistent invalid date [expo/react native]

### ISSUE THREAD

**Issue by RodrigoNovais** [moment/luxon#850]
**Describe the bug**
Whenever executing the following expression:
```js
import { DateTime } from 'luxon'

export default function formatDate (date: Date, format: string) {
    const formattedDate = DateTime.fromJSDate(date)
        .setLocale('pt-BR')
        .toFormat(format)

    return formattedDate
}
```
The output keeps getting invalid date at times
```bash
2007-01-24T16:08:39.000Z dd-MM-yyyy Invalid DateTime
2007-01-24T16:08:39.000Z dd-MM-yyyy 24-01-2007
2007-01-24T16:08:39.000Z dd-MM-yyyy 24-01-2007
2007-01-24T16:08:39.000Z dd-MM-yyyy Invalid DateTime
```
> To reproduce use a react native expo application

**Actual vs Expected behavior**
When executed on luxon's website, the output is consistent and correct:

![](https://cdn.discordapp.com/attachments/293931621101338626/796926402627895386/unknown.png)

- Luxon version: 1.25.0

**Comment by icambron** [comment]
I'm not sure how to help here. I'll need a reproduceable example...

Perhaps your inputs aren't what you think they are?

**Comment by RodrigoNovais** [comment]
Sorry, I don't think I explained the outputs I put in the example

The output values in sequence represents the date, the format and formattedDate variables
As you can see, dates and formats are constant but the formatted date is not

```bash
2007-01-24T16:08:39.000Z dd-MM-yyyy Invalid DateTime
2007-01-24T16:08:39.000Z dd-MM-yyyy 24-01-2007
2007-01-24T16:08:39.000Z dd-MM-yyyy 24-01-2007
2007-01-24T16:08:39.000Z dd-MM-yyyy Invalid DateTime
```

In no time I had passed invalid dates or formats and it had only occurred in the app
I'm very confused with this behaviour

Im not allowed to share the app itself as it is a client's job...

**Comment by RodrigoNovais** [comment]
After several hours of debugging I have found out the problem was lack of serialization of the data coming from redux
Sorry for taking your time
