### ISSUE TITLE
Changing "Settings.defaultLocale" doesn't have any effect

### ISSUE THREAD

**Issue by lephro** [moment/luxon#851]
**Describe the bug**
After changing the locale through the Settings class, the default locale of the next instance (or any) doesn't get affected.

**To Reproduce**
In my locale-switcher component I set the `Settings.defaultLocale` to a 2 letter language code.
On each rendering (just for testing) I give out the `Settings.defaultLocale` (to see if my change takes effect) and the `DateTime.local().locale`. 
```
<template>
  <div>{{ testOut() }}</div>
</template>

<script>
import { DateTime } from 'luxon';
import Settings from 'luxon/src/settings.js'

export default {
  methods: {
    testOut() {
      return Settings.defaultLocale + " " + DateTime.local().locale;
    }
  }
}
</script>
```

**Output:**
Initial: `de de`
After changing the locale:  `en de`

The defaultLocale is set correctly but the locale of the DateTime instance is still the initial default one.

**Actual vs Expected behavior**
The locale of the default language should change, according to the value in the `Settings.defaultLocale` class.

**Desktop (please complete the following information):**

- OS: Any
- Browser FireFox 84
- Luxon version 1.25.0 (@latest)

**Additional context**
Laravel 8, Vue 2.4

**Comment by fabiofdsantos** [comment]
Try `import { DateTime, Settings } from 'luxon';`

**Comment by lephro** [comment]
It works. Thank you a lot. 

This should probably go into the documentation.

**Comment by icambron** [comment]
The problem is that you imported `Settings` and `DateTime` from two different places, so naturally the DateTime didn't "see" the settings change.
