### ISSUE TITLE
Interval.fromISO([ISO String], [ISO String]) creates invalid start/end, but Interval.fromDateTimes(DateTime.fromISO([ISO String]), DateTime.fromISO([ISO String])) works fine.

### ISSUE THREAD

**Issue by mia-z** [moment/luxon#853]
**Describe the bug**
I have a set of ISO DateTimes fetched from Microsoft Graph API. When I parse them with DateTime.fromISO, they're valid and work as intended. However, when I try to parse them into an interval via 

```
Interval.fromISO([ISO String], [ISO String])
```
it returns the following object

![image](https://user-images.githubusercontent.com/1094070/104280786-bc963200-54ac-11eb-99ed-58957a34dc72.png)

But If I parse them as DateTime using fromDateTimes(), the interval works just fine, eg
`Interval.fromDateTimes(DateTime.fromISO([ISO String]), DateTime.fromISO([ISO String]))`

**To Reproduce**
Create a luxon.Interval using fromISO() with two ISO Strings
`Interval.fromISO([ISO String], [ISO String])`

**Actual vs Expected behavior**
Expected behaviour: Should successfully parse the two valid ISO Strings as start and end times for the interval.
Actual Behaviour: Returns invalid, stating that the strings cannot be parsed.

**Desktop (please complete the following information):**

- Windows 10
- Browser Chrome 87
- Luxon version 1.25

**Additional context**
The DateTimes are ISO Strings from Microsoft's Graph API.

**Comment by icambron** [comment]
`Interval.fromISO()` takes an ISO _interval_ string, not two ISO datetime strings. Reading the [docs](https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html#static-method-fromISO) that's not 100% clear, so we could use some tweaks there; shouldn't imply that it passes the options to `DateTime.fromISO()` and should give an example.

**Comment by mia-z** [comment]
Thanks for the clarification -- yeah, it does seem a little ambiguous, or I'm just a little naive. Either way, it wouldn't hurt to clarify.
