### ISSUE TITLE
Flow typing (idea)

### ISSUE THREAD

**Issue by jpolo** [moment/luxon#86]
Hi !

We are thinking about migrating our project from moment to this one (because of the immutability, better debuggable code, better API). At the moment, only one thing would require some work : Flow type definition.
I was just wondering if you thought of using flow annotation in your source (or at least provide a flow definition in the published package) ?

PS: if I may give you a raw feedback from our team about the naming : we did not understand the relation between a luxon and datetime/calendar. It might be an obstacle for the adoption of this package that is theorically better than moment.js on almost every subject...

Thanks!

**Comment by tuananh** [comment]
partially related: https://github.com/moment/luxon/issues/73

**Comment by icambron** [comment]
Yeah, see my comment in #73. I'm partial to Flow but only if it's done "for real"

**Comment by icambron** [comment]
I'm going to close this in preference for #73.
