### ISSUE TITLE
Question - how luxon handle the world wide time zones changes?

### ISSUE THREAD

**Issue by casper5822** [moment/luxon#860]
Hello,
We have a booking platform so it's important to have updated timezones and we use moment and moment-timezone in the project.
We want to switch to luxon but we have a question:

I read that luxon uses Intl API, but, how the timezones update process work? Is it related to the user browser ? Do we have to wait for  luxon release?

Thank you.

**Comment by icambron** [comment]
@casper5822 the data is in the browser; Luxon is just using it via the Intl API. So you get the TZ updates whenever the browser gets them

**Comment by casper5822** [comment]
@icambron thank you for response.
So if a user has a not updated browser, the timezone definition can be obsolete, is it right?

**Comment by icambron** [comment]
Correct

**Comment by casper5822** [comment]
ok thank you for the response.
