### ISSUE TITLE
How to remove milliseconds from ISO formatted  date using luxon

### ISSUE THREAD

**Issue by Deepads** [moment/luxon#862]
How to remove milliseconds from ISO formatted  date using luxon

Using moment :
moment().tz( 'America/New_York').format(); - o/p = **2021-02-04T07:06:52-05:00**

Using Luxon:
DateTime.fromJSDate(new Date(), { zone: 'America/New_York' }).toISO({ suppressMilliseconds: true })- o/p - **2021-02-04T07:06:52.914-05:00**

how to remove milliseconds or any alternative to get the ISO date in the above format without millisecond in luxon

**Comment by Deepads** [comment]
As per the document { suppressMilliseconds: true } will only work if the value is 0

**Comment by EzeGmnz** [comment]
The following PR solves this by adding a new parameter https://github.com/moment/luxon/pull/1412

**Comment by Ericlm** [comment]
Maybe this issue could be closed if it's solved ?

**Comment by Deepads** [comment]
Thank you !!!

**Comment by Deepads** [comment]
Issue is fixed

**Comment by razvanioan** [comment]
Is it possible to add the same parameter to other format methods, like toSQL for example ?
