### ISSUE TITLE
Remove fixed-offset TZ formatting workaround

### ISSUE THREAD

**Issue by durasj** [moment/luxon#866]
The workaround I'm talking about: https://github.com/moment/luxon/blob/6934632be3d1003b48a4f43178d6ac1f36bd6911/src/impl/locale.js#L186-L200

I've quickly tried what I've proposed in https://github.com/moment/luxon/issues/201#issuecomment-776784273 and it seems to be working, so I'm opening this issue.

The problem is there are no UTC+X entries in `tzdata` and there are only whole hours from `Etc/GMT-14` to `Etc/GMT+12`.

Here is the list of time zones under `Etc/` on my Linux:

```
[jakub@localhost ~]$ ls /usr/share/zoneinfo/Etc/
GMT    GMT+1   GMT+11  GMT-13  GMT+3  GMT+5  GMT+7  GMT+9      Universal
GMT+0  GMT-1   GMT-11  GMT-14  GMT-3  GMT-5  GMT-7  GMT-9      UTC
GMT-0  GMT+10  GMT+12  GMT+2   GMT+4  GMT+6  GMT+8  Greenwich  Zulu
GMT0   GMT-10  GMT-12  GMT-2   GMT-4  GMT-6  GMT-8  UCT
```

A "good enough" solution could be to still fall back to that workaround for anything outside of the supported range?
EDIT: I've opened #867 that does exactly that.

This should fix issues like #201 and #834

**Comment by icambron** [comment]
Oh nice. Yeah, let's remove it.

**Comment by human33** [comment]
@durasj @icambron I receive an error without this workaround:  

```
 console.error

    RangeError: Expected Area/Location(/Location)* for time zone, got Etc/GMT-3
        at new DateTimeFormat (native)
        at getCachedDTF (node_modules/luxon/src/impl/locale.js:12:11)
        at new PolyDateFormatter (node_modules/luxon/src/impl/locale.js:221:18)
        at Locale.dtFormatter (node_modules/luxon/src/impl/locale.js:455:12)
        at Formatter [as formatDateTime] (node_modules/luxon/src/impl/formatter.js:102:16)
        at DateTime.toLocaleString (node_modules/luxon/src/datetime.js:1505:9)
```

Rollback to luxon@1.25.0 helps with it.
I run it on Node.js in tests.

**Comment by durasj** [comment]
@human33 What version of node are you using?

**Comment by human33** [comment]
> @human33 What version of node are you using?

v10.19.0

**Comment by durasj** [comment]
It sounds like the same issue as #912 and #883. Node.js v10 is likely on V8 that doesn't even properly handle anything in `Etc`. This could be tested in a half-hacky way (if there isn't a better way to do this I'm not aware of) by trying to catch it. Then, if it is not supported, it can also fall back to the old behaviour.

However, I have personally no motivation to solve this as it works correctly on the last two versions of the most used browsers and the last two Node.js LTS versions.

**Comment by human33** [comment]
@durasj thanks for help! I will update luxon after new Node.js version releases for Ubuntu
