### ISSUE TITLE
Minus function gives incorrect result when passing year zero

### ISSUE THREAD

**Issue by dan-overton** [moment/luxon#868]
**Describe the bug**
When minus is used to cross year zero, the result appears to be incorrect.

**To Reproduce**

https://codesandbox.io/s/luxon-playground-forked-ivl7f?file=/src/index.js
(compares moment and Luxon behaviour)

`DateTime.fromISO("+000000-01-01T00:00Z").minus({ years: 1 }).toISO()`

**Actual vs Expected behavior**

Expected result: -000001-01-01T00:00:00.000Z
Actual result: 00-2-12-31T23:59:00.000-00:01

**Desktop (please complete the following information):**

- MacOS
- Browser Chrome 88
- Luxon version 1.25.0

**Additional context**
Not sure if a bug or this just isn't supported.

**Comment by icambron** [comment]
There are two things going on here:

1. A bug in the extended formatter. It means to say `-0002-12-31` but it put the minus sign in the wrong place
2. Your local offset is 1 minute. That's some weird historic thing in the data. You probably want to say `DateTime.fromISO("+000000-01-01T00:00Z").toUTC()`. The `Z` tells the parser that the time is expressed in UTC, but not to do math and formatting in UTC, so the it's using local settings. Anyway, that's what's taking off the additional minute.

**Comment by dan-overton** [comment]
Thanks for taking a look at it. I've updated the codesandbox with `toUTC` like you mentioned and the minute is now gone. The result is now `00-1-01-01T00:00:00.000Z`, as per the bug you identified.

**Comment by dan-overton** [comment]
I wrote a test for this and came down to it being an issue with [`padStart`](https://github.com/moment/luxon/blob/ff17eeac8081753c5a2629a17c3fce6d622d88b3/src/impl/util.js#L101) not correctly padding minus numbers.

This version passes (but might need some optimising)

```
export function padStart(input, n = 2) {
  const minus = input < 0 ? '-' : '';
  const target = minus ? input * -1 : input;
  let result;

  if (target.toString().length < n) {
    result = ("0".repeat(n) + target).slice(-n);
  } else {
    result = target.toString();
  }

  return `${minus}${result}`;
}
```

Would you accept a PR?

**Comment by icambron** [comment]
Yup, thanks
