### ISSUE TITLE
Documentation > Moment

### ISSUE THREAD

**Issue by danielskeeled** [moment/luxon#869]
**Is your feature request related to a problem? Please describe.**
In "Major functional differences" of the documentation page for Moment users it's said that no relative time features are available (point 4).

**Describe the solution you'd like**
Remove point 4.
https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toRelative

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/47665730/107667173-3c1f4880-6c87-11eb-92a5-a2d71c12ffc9.png)

**Comment by icambron** [comment]
Yup, will do

**Comment by icambron** [comment]
This seems to have been done a while ago.
