### ISSUE TITLE
DateTime.toFormat('D') and default locale

### ISSUE THREAD

**Issue by Roseidon** [moment/luxon#87]
Hey everybody,

I tried to use `.toFormat('D')` on a DateTime-object to get a string in locale-Settings (in my case locale: "de").
The result was `11/22/2017` instead of `22.11.2017` (which would be my locale). Am I using it wrong, or is it a bug?

**Comment by icambron** [comment]
This isn't a bug, exactly, it's just not very obvious. This is how I wrote about it in the [docs](http://moment.github.io/luxon/docs/manual/usage/intl.html):

> By default the locale property of a new DateTime or Duration is null. This means different things in different contexts:

> * DateTime#toLocaleString, DateTime#toLocaleParts, and other human-readable-string methods like Info.months will fall back on the system locale. On a browser, that means whatever the user has their browser or OS language set to. On Node, that usually means en-US.
> * DateTime.fromString and DateTime#toFormat fall back on en-US. That's because these methods are often used to parse or format strings for consumption by APIs that don't care about the user's locale. So we need to pick a locale and stick with it, or the code will break depending on whose browser it runs in

That makes sense for many uses of `toFormat` but it is super confusing for the macro formats like 'D'. But basically, you should see this:

```js
dt.toLocaleString(DateTime.DATE_SHORT) //=> does what you want
dt.toLocale('de').toFormat('D') //=> also does what you want
dt.toFormat('D') //=> does NOT do what you want
```

You can change this behavior. Also from the doc:

> You generally don't want DateTime#fromString and DateTime#toFormat to use the system's locale, since your format won't be sensitive to the locale's string ordering. That's why Luxon doesn't behave that way by default. But if you really want that behavior, you can always do this:

> `Settings.defaultLocale = DateTime.local().resolvedLocaleOpts().locale;`

I'm open to suggestions on how to improve all this. I agree it's sort of dumb for 'D' to work like this, but I also know that a) having most formatting tokens sensitive to an implicitly specified locale will lead to all sorts of bugs, b) it would be at least weird to have the macro formats follow a different set of default locale rules than, say, 'MMMM'. But maybe (b) is actually less confusing than the current behavior.

**Comment by icambron** [comment]
I decided to go with (b). It makes things more complicated but it just doesn't seem reasonable that the macro formats wouldn't be sensitive to the system locale. The patch is 19b095f. I'll deploy it soon.
