### ISSUE TITLE
DateTime#set({ year }) modifying timezone

### ISSUE THREAD

**Issue by simonfan** [moment/luxon#870]
**Describe the bug**
When using `DateTime#set({ year })` to change only the year of the date, I've noticed that the timezone is modified as well in some years.

Don't really know if this is a bug or if it is a feature (such as taking into account daylight saving time, etc.), just wanted to clarify.

**To Reproduce**
```js
const ISO_DATE = '2021-02-12T12:34:15.020-03:00'

DateTime.fromISO(ISO_DATE).set({ year: 2020 }).toISO()
// 2020-02-12T12:34:15.020-03:00

DateTime.fromISO(ISO_DATE).set({ year: 2019 }).toISO()
// 2019-02-12T12:34:15.020-02:00 -> Timezone became -02:00

[2030, 2021, 2020, 2019, 1990, 1980, 1970, 1940, 1800, 1].reduce((acc, year) => ({
  ...acc,
  [year]: DateTime.fromISO(ISO_DATE).set({ year }).toISO()
}), {})
// {
//  "1": "0001-02-12T12:34:15.020-03:06",    -> -03:06
//  "1800": "1800-02-12T12:34:15.020-03:06", -> -03:06
//  "1940": "1940-02-12T12:34:15.020-03:00",
//  "1970": "1970-02-12T12:34:15.020-03:00",
//  "1980": "1980-02-12T12:34:15.020-03:00",
//  "1990": "1990-02-12T12:34:15.020-03:00",
//  "2019": "2019-02-12T12:34:15.020-02:00", -> -02:00
//  "2020": "2020-02-12T12:34:15.020-03:00",
//  "2021": "2021-02-12T12:34:15.020-03:00",
//  "2030": "2030-02-12T12:34:15.020-03:00"
// }

```
**Actual vs Expected behavior**
Again, it might just be my misunderstanding: I expected timezone to be constant

**Desktop (please complete the following information):**
- Tested on Luxon docs website in the console, through `luxon.DateTime` (https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html)
- Node.js v14.15.4
- Luxon version: luxon@1.25.0

**Comment by icambron** [comment]
Yeah, time zones change over time. A zone might do daylight savings one year, and not the next, or change the date when the shift happens from year to year, or just change offsets altogether one year. Very old dates have some truly wild offsets (hence the weird 6 minutes). The specifics depend on your zone, but at any rate, it just isn't the case that the offset is constant for any given time. You may find this website helpful: https://www.timeanddate.com/time/map/

The way Luxon handles this is that it figures out the right local time (setting a year means "make it the same local date and time, but with the year changed). It then figures out what underlying epoch time and offset corresponds to, and builds an instance out of it.

**Comment by simonfan** [comment]
Ok, thank you very much for the clarification!
