### ISSUE TITLE
DateTime.now() in documentation but actually does not exist

### ISSUE THREAD

**Issue by DaSchTour** [moment/luxon#875]
**Describe the bug**
In the documentation there is a method described that is called `now()` but when using it I get the error `luxon__WEBPACK_IMPORTED_MODULE_1__.DateTime.now` 

Actually the typescript typings also do not have this method

**To Reproduce**
use `DateTime.now()`

**Actual vs Expected behavior**
Either the documentation should not contain the method or it should actually exist.

**Comment by ethanmick** [comment]
Hello, running into this as well. What did you do to resolve it?

**Comment by DaSchTour** [comment]
@ethanmick
Update. It's like luxon released a 2.0
DateTime.now() is very new function

**Comment by luixaviles** [comment]
Looks like the current documentation doesn't match the implementation. I got the same issue too.
Solved it replacing the `DateTime.now()` function call to `DateTime.local()`.

**Comment by ebisbe** [comment]
@DaSchTour Upgrading worked for me. It should be an indicator on the docs that's from v2 onwards

**Comment by icambron** [comment]
I'd take a PR adding version indicators to the docs
