### ISSUE TITLE
toFormat('ttt') returns GMT instead of UTC

### ISSUE THREAD

**Issue by ericdowell** [moment/luxon#878]
**Describe the bug**
When calling DateTime.fromISO with zone `utc`, then `toFormat('ttt')` previous versions output `UTC`. Starting in v1.26.0 `GMT` is now returned instead.

**To Reproduce**
Please share a minimal code example that triggers the problem:
v1.26.0
```js
const luxon = require('luxon');
const dateTime = luxon.DateTime.fromISO('2019-07-12T02:45:03.000Z', { zone: 'utc' });
console.log(dateTime.toFormat('MM/dd/yyyy ttt'));
// 07/12/2019 2:45:03 AM GMT
```

v1.25.0
```js
const luxon = require('luxon');
const dateTime = luxon.DateTime.fromISO('2019-07-12T02:45:03.000Z', { zone: 'utc' });
console.log(dateTime.toFormat('MM/dd/yyyy ttt'));
// 07/12/2019 2:45:03 AM UTC
```

**Actual vs Expected behavior**
Expected is to return `UTC` as v1.25.0 did, actual return is `GMT` in v1.26.0.

**Desktop (please complete the following information):**

- OS: macOS 10.15.7
- Browser: n/a, Node v14.15.0
- Luxon version: 1.26.0

**Additional context**
Looks like this change may have created the bug: https://github.com/moment/luxon/issues/866 (PR https://github.com/moment/luxon/pull/867), did not see anything else in the release notes that had to do with Offset/TZ.

**Comment by parkr** [comment]
We are seeing this with format `'fff'` as well:

```javascript
export const EnglishDateTimeWithZoneFormat = 'fff'
const val = DateTimeFromISO('2020-03-05T15:13:10Z')
expect(val.toFormat(EnglishDateTimeWithZoneFormat)).toEqual('March 5, 2020, 3:13 PM UTC')
// FAILS: 
// Expected: "March 5, 2020, 3:13 PM UTC"
// Received: "March 5, 2020, 3:13 PM GMT"
```

**Comment by SeemaHejazi** [comment]
We are seeing this with format 'TTT' as well.
`DateTime.fromISO(timestamp).toUTC().toFormat("DDD TTT")

// Expected: "January 1, 2020 18:53:46 UTC"
// Received: "January 1, 2020 18:53:46 GMT"
`

My short-term workaround in the meantime:
` DateTime.fromISO(timestamp).toUTC().toFormat("DDD TT' UTC'")`

**Comment by ericdowell** [comment]
As of v1.27.0 this has reverted back to returning `UTC`:
```js
const luxon = require('luxon');
const dateTime = luxon.DateTime.fromISO('2019-07-12T02:45:03.000Z', { zone: 'utc' });
console.log(dateTime.toFormat('MM/dd/yyyy ttt'));
// 07/12/2019 2:45:03 AM UTC
```
