### ISSUE TITLE
fromFormat() claims dates with slashes are unparsable when they shouldn't be

### ISSUE THREAD

**Issue by Nickersoft** [moment/luxon#879]
**Describe the bug**
`DateTime.fromFormat()` will claim a parsed date is invalid if it contains slashes, apparently.

**To Reproduce**
I attempted to parse the exact date used as an example in the [tokens table](https://moment.github.io/luxon/docs/manual/parsing.html#table-of-tokens):

```js
console.log(DateTime.fromFormat('8/6/2014 1:07 PM', 'f'));
```

and received:

```
DateTime {
      ts: 1614023496842,
      _zone: LocalZone {},
      loc:
       Locale {
         locale: 'en',
         numberingSystem: null,
         outputCalendar: null,
         intl: 'en',
         weekdaysCache: { format: {}, standalone: {} },
         monthsCache: { format: {}, standalone: {} },
         meridiemCache: null,
         eraCache: {},
         specifiedLocale: null,
         fastNumbersCached: null },
      invalid:
       Invalid {
         reason: 'unparsable',
         explanation: 'the input "8/6/2014 1:07 PM" can\'t be parsed as format f' },
      weekData: null,
      c: null,
      o: null,
      isLuxonDateTime: true }
```

yet trying with the other examples in the docs (that don't have slashes), seems to work fine.

**Actual vs Expected behavior**
This date should be read in and parsed properly.

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS Catalina
- Browser [e.g. Chrome 84, safari 14.0] Node 10
- Luxon version [e.g. 1.25.0] 1.26.0

**Comment by dan-overton** [comment]
The string from the documentation has a comma after the date, making it `8/6/2014, 1:07 PM`. It seems to work if you add the comma?

**Comment by Nickersoft** [comment]
@dan-overton Hmm.. is there a reason it wouldn't be able to parse `DateTime.fromFormat('1/1/2020 13:00', 'M/D/yyyy HH:mm')` then? Can custom formats not have slashes?

**Comment by dan-overton** [comment]
They can, but I think your format has a bad identifier, it should be a lowercase d rather than uppercase, as per https://moment.github.io/luxon/docs/manual/parsing.html#table-of-tokens. `DateTime.fromFormat('1/1/2020 13:00', 'M/d/yyyy HH:mm')` seems to work ok.

**Comment by Nickersoft** [comment]
Oh! Hm.. I was certain I had got that right. Thanks for the correction. Going to close this out then!

**Comment by dan-overton** [comment]
No problem, I get my tokens wrong at least half the time 😄
