### ISSUE TITLE
Browser console support

### ISSUE THREAD

**Issue by droooney** [moment/luxon#88]
Please, can you make the whole `luxon` module available in the browser console on the website?

**Comment by icambron** [comment]
It is available in the console [here](http://moment.github.io/luxon/) as a global (open the console and type `luxon`). Do you mean in the documentation pages, like this [one](http://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html)? If so, that should be possible, though it will require some fussing with ESDoc

**Comment by droooney** [comment]
Thanks for the quick answer! Yes, I did mean those type of pages. I'd love to be able to read the docs/examples and type something in the console at the same time. Moment has that.

P.S.: [these](http://moment.github.io/luxon/docs/manual/design/tour.html) pages could have the same too.

I could take a look at that, and if I won't be able to do so I'll let you know :)

**Comment by icambron** [comment]
I appreciate the offer to help, but I realized it was pretty straightforward. Fixed in 0adf42f. Will be part of the next release.

**Comment by droooney** [comment]
Ah, ok! Thanks a lot for your work!
