### ISSUE TITLE
Random bug when using minus from 2020-11-01T01:00:00

### ISSUE THREAD

**Issue by sscots** [moment/luxon#884]
I'm been executing time series data backwards by 5 minute increments from 2021-02-24 and it all worked well until I got to 2020-11-01T01:00:00 and subtracted 5 minutes to get 01:55 instead of 00:55

Example here:
http://jsfiddle.net/16hy0jsx/

**Comment by dan-overton** [comment]
I think this might be down to a daylight savings time change in your timezone? There was one at 2am on 1st Nov 2020 as per https://www.timeanddate.com/time/change/usa/new-york?year=2020 

If you run `console.log(DateTime.local().zoneName)` in your jsfiddle, what do you get?

**Comment by sscots** [comment]
I'm in American/Chicago zone. That does appear to be my issue. How do you suggest I handle this based on subtracting 5 minutes? Should I just check that if my new time value is greater than my previous time value then subtract an hour?

**Comment by dan-overton** [comment]
I guess it depends on what you're using it for. Technically it's correct for that timezone - 5 minutes before 1 am was 1:55 am in that zone.

If you're not actually worried about the time zone you could just do the whole thing in UTC, which is not impacted by DST - e.g. `DateTime.fromISO('2020-11-01T01:00:00', {zone: 'UTC'}).minus({minutes: 5}).toISO()`. As far as I'm aware that shouldn't ever skip hours when using plus/minus.

I'm just a user though, there might be better options I haven't seen yet.

**Comment by icambron** [comment]
Agreeing with Dan here. It sounds like you don't really want the local time, which really does do that whacky thing. I don't quite know what your use case is, but if you need them to be continuous like you expect, you should switch to UTC
