### ISSUE TITLE
Comparing dst and non dst time

### ISSUE THREAD

**Issue by lueenavarro** [moment/luxon#899]
console.log( DateTime.fromISO("2021-03-14T01:00:00") >
    DateTime.fromISO("2021-03-14T12:59:00")) returns false. I believe that should return true in this case. 
    
Also:
console.log(DateTime.fromISO("2021-03-14T12:59:00").toString()) -> 2021-03-14T12:59:00.000-05:00
console.log(DateTime.fromISO("2021-03-14T01:00:00").toString()) -> 2021-03-14T01:00:00.000-06:00

I'm not sure if the change in timezone is already expected. The timezone is set to America/Chicago.

- OS: Windows, Nodejs v14.15.3
- Luxon version: ^1.26.0

**Comment by icambron** [comment]
No, I think you're confusing 12:59 with 00:59. 12:59 means 12:59 in 24-hour time, so PM not AM. With that in mind:

> console.log( DateTime.fromISO("2021-03-14T01:00:00") >
DateTime.fromISO("2021-03-14T12:59:00")) returns false. I believe that should return true in this case.

`2021-03-14T01:00:00` is just shy 11 hours before `2021-03-14T12:59:00` (would be 12 without the intervening DST). So 1:00 < 12:59.

> I'm not sure if the change in timezone is already expected. 

Same issue. The DST shifts the zone in the opposite direction, from -6 to -5. 1:00 is before the change and 12:59 is well after it.
