### ISSUE TITLE
Luxon FP?

### ISSUE THREAD

**Issue by sporto** [moment/luxon#90]
Hi, Luxon looks great.

However the chainable method syntax is not very functional programming friendly. It would be great if there could be alternative version with functions aimed at fp.

This is what I mean (using Ramda):

```
const formatted = R.pipe(
    DateTime.fromISO,
    DateTime.minus({weeks: 1}),
    DateTime.toISO,
    someOtherThing,
  )(someDate)
```

What this means is having standalond functions that are auto-curried with the data at the end. e.g.

```
minus(args)(dateTime)
```

Please consider this, thanks

**Comment by icambron** [comment]
I love FP and I'm sympathetic to this request, but Luxon is going to stick to chainable method system. That's just kind of its thing.

**Comment by sgronblo** [comment]
From what I hear, the "FP module" pattern is better for dead code elimination as well.

**Comment by TimTheToaster** [comment]
It seems these are not mutually exclusive

**Comment by icambron** [comment]
For the curious, this is a stab at FP Luxon: https://github.com/icambron/luxon-next. I will probably never finish it, though.
