### ISSUE TITLE
Strange behavior with interval

### ISSUE THREAD

**Issue by yariksav** [moment/luxon#901]
**Describe the bug**
Hi guys, I noticed some strange behavior in luxon interval with not utc timezone

As you will see in reproduction link, if we make diffs between two start dates
https://codesandbox.io/s/luxon-playground-forked-ne3bc

```
  const datec1 = DateTime.fromISO("2021-03-01T00:00:00+00");
  const datec2 = DateTime.fromISO("2021-04-01T00:00:00+00");
  const intervalc = Interval.fromDateTimes(datec1, datec2);
  // result 1.0013888888888889, little tail because of 1 hour daylight saving time

  const date1 = DateTime.fromISO("2021-03-01T00:00:00+03:00");
  const date2 = DateTime.fromISO("2021-04-01T00:00:00+03:00");
  const interval = Interval.fromDateTimes(date1, date2);
  // result 1.0981182795698925, must be the same diff, but it almost 3 days difference!!!
```

Thank you!

**Comment by icambron** [comment]
This is working as expected: it's the nasty confluence of you doing the diff in a local zone, the DST, and the fact that February has fewer days. I'm taking it that you're in Ukraine, so:

date 1 is 2021-02-28T23:00:00.000+02:00
date 2 is 2021-04-01T00:00:00.000+03:00

While that's only an hour short of the full months, Luxon says: "what's a month after 2/28? Well, that's March 28. How far away am I from my target of 4/1? Three days, plus an hour for the DST"

```js
interval.toDuration(["months", "days", "hour"]).toObject() //=> { months: 1, days: 3, hours: 1 }
```

Whereas the +00:00 is simpler:

date 1 is 2021-03-01T02:00:00.000+02:00
date 2 is 2021-04-01T03:00:00.000+03:00 

So one month and one hour in local time.
