### ISSUE TITLE
An example on Terminologies - time zone section of the manual is wrong?

### ISSUE THREAD

**Issue by chikakow** [moment/luxon#902]
A time zone is a set of rules, associated with a geographical location, that determines the local offset from UTC at any given time. The best way to identify a zone is by its IANA string, such as "America/New_York". That zone says something to the effect of **"The offset is -4, except between March and November, when it's -5"**.

Between March and November, it's -4.  The rest of the year, it's -5.  The phrase sounds flipped from actually offset during DST.

![image](https://user-images.githubusercontent.com/3085026/111798832-d4b97180-88a0-11eb-904f-16c1124ebcf4.png)

**Comment by icambron** [comment]
Ha, yes

**Comment by icambron** [comment]
Fixed in 9d4fb61d
