### ISSUE TITLE
Parsing english am/pm times

### ISSUE THREAD

**Issue by andersfly** [moment/luxon#91]
Hi, not sure if this is a bug. 

But I'm having some troubles parsing english times.

```javascript
moment.utc('12.05am', 'hh.mma').format('HH:mm')
// => 00:05 - correct (I guess)
DateTime.fromString('12.05am', 'hh.mma', {zone: 'utc'}).toFormat('HH:mm')
// => 12:00 - it should be 00:05 right?
DateTime.fromString('12.05pm', 'hh.mma', {zone: 'utc'}).toFormat('HH:mm')
// => Invalid DateTime: hour out of range
```

By reading the docs the tokens should (afaik) have the same meaning in moment and luxon.

**Comment by icambron** [comment]
Weird, I'll have a look

**Comment by icambron** [comment]
```js
DateTime.fromString('12.05am', 'hh.mma', {zone: 'utc'}).toFormat('HH:mm')
// => 12:00 - it should be 00:05 right?
```

This worked fine for me on the latest release. I got `12:05`.

```js
DateTime.fromString('12.05pm', 'hh.mma', {zone: 'utc'}).toFormat('HH:mm')
// => Invalid DateTime: hour out of range
```

That is a bug

**Comment by icambron** [comment]
Fixed in a1005ad. Going to release this today.

**Comment by andersfly** [comment]
Thx again for the quick response

It seems to work now on 0.1.0, so:

```
12.05am => 00:05 (midnight)
12.05pm => 12:05 (noon)
```

Work as expected.

**Comment by icambron** [comment]
Re: lazy meridiem: The trouble is that I can't internationalize it unless I can get the Internet API to produce it. And as far as I know it won't.
