### ISSUE TITLE
Setting the default zone name has unexpected impact on equality

### ISSUE THREAD

**Issue by sechel** [moment/luxon#910]
Setting the `Settings.defaultZoneName` impacts `Interval.equal` behavior in unexpected ways.

Execute this
```js
const isoRange = '2021-03-24/2021-03-25';
range01 = Interval.fromISO(isoRange);
range02 = Interval.fromISO(isoRange);
Settings.defaultZoneName = Settings.defaultZoneName;
range03 = Interval.fromISO(isoRange);
range01.equals(range02); // true
range01.equals(range03); // false?
```
After `Settings.defaultZoneName = Settings.defaultZoneName;` intervals are no more equal.

**Comment by icambron** [comment]
That is correct. The default zone determines how ISO strings without explicit offsets are interpreted, meaning, how they map to actual instants in time. "2021-03-24" is a different moment in the Earth's timeline if you interpret ti to refer to New York's local time or London's local time. Thus when you change the default zone, you are changing the instant in time used as the endpoints in the interval. And intervals with different times as their endpoints are not equal.

**Comment by sechel** [comment]
Right, but shouldn't this be a noop:
```ts
Settings.defaultZoneName = Settings.defaultZoneName;

```

**Comment by icambron** [comment]
oh i see. Yeah, what zones do you end up with at there?

**Comment by huilibaba** [comment]
I ran a test to check for
```
const isoRange = '2021-03-24/2021-03-25';
range01 = Interval.fromISO(isoRange);
range02 = Interval.fromISO(isoRange);
Settings.defaultZoneName = Settings.defaultZoneName;
range03 = Interval.fromISO(isoRange);
range01.equals(range02); // true
range01.equals(range03); // false?
```

and `range01.equals(range03)` appears to be `true`. 

@icambron I think this not an issue anymore.

**Comment by icambron** [comment]
@huilibaba thanks
