### ISSUE TITLE
Time zone format not supported in Node.js 10.X

### ISSUE THREAD

**Issue by salami-art** [moment/luxon#912]
The PolyDateFormatter class forces the time zone to the 'Etc/GMT+...' format but this is not meant to work in nodeJs v.10, as you can see here: https://github.com/nodejs/node/blob/v10.x/deps/v8/test/intl/date-format/timezone.js#L61

```
var { DateTime } = require('luxon');
DateTime.fromFormat("28 marzo 2021", "d LLLL yyyy", { locale: "it" }); // or just about anything that internally instantiates a PolyDateFormatter
```
expected behavior: get a workable date or at least don't break
actual behavior: throws 
```
RangeError: Expected Area/Location(/Location)* for time zone, got Etc/GMT+0
    at new DateTimeFormat (native)
```

- OS: mac os
- Node.js 10
- Luxon version [e.g. 1.26.0]

I have of course tried to set the time zone manually on the node process but it consistently gets converted. Is there a way I can access the time zone formatting that is ultimately passed to Intl.DateTimeFormat and would otherwise work?

**Comment by durasj** [comment]
Hi @salami-art, could you try #918 if it fixes the issue for you?
