### ISSUE TITLE
Deprecated IANA timezones question

### ISSUE THREAD

**Issue by Eldair** [moment/luxon#916]
Hello,

I have observed that when using DateTime.local().zone.name chrome will return Deprecated zone name (example 
America/Buenos_Aires) but firefox will return correct one (America/Argentina/Buenos_Aires). Is this something that can be fixed in library or it needs to be fixed on browser level? Also, is there a way to find correct new timezone for deprecated ones and how to know if it is deprecated?

**Comment by icambron** [comment]
All timezone support comes from the browser (or other runtime, like Node). Unfortunately, the browser doesn't provide APIs for answering questions like those, so Luxon can't really help.

**Comment by Eldair** [comment]
Thanks for the answer
