### ISSUE TITLE
Throw error when a parser method could not parse a date successfully

### ISSUE THREAD

**Issue by vansham-gortnm** [moment/luxon#921]
Whenever we parse a date using any of the parser methods, we have to check the `isValid` property manually to confirm whether the data has been successfully parsed or not. Rather it should automatically through an error which can eliminate a whole class of errors and make debugging easy.

Also using `luxon` with typeorm has some issues like when parsing ISO dates after fetching them from the database.

**Comment by icambron** [comment]
See the `throwOnInvalidOption`: https://moment.github.io/luxon/docs/manual/validity.html#throwoninvalid

You'd have to be more specific about the ISO issues
