### ISSUE TITLE
Issues with TypeORM

### ISSUE THREAD

**Issue by vanshamagg** [moment/luxon#922]
So I was working with `TypeORM` while building a ticket booking app and I encountered this strange bug.

So I fetch my entity `show` details from the database and it consists of several kinds of dates. It has an attribute `start` which is being stored as `timestamptz` in the `PostgreSQL` database. It's the start date-time of the show.

when I console `show.start` it shows me `2021-04-26T05:53:00.000Z` which is the UTC time in ISO format, right?

So I try to create a `DateTime` object using `DateTime.fromISO(show.start)`, and `luxon` implicitly throws an error.

When I console the freshly created `DateTime` object, I have the following object -

```
DateTime {
  ts: 1618517115922,
  _zone: LocalZone {},
  loc: Locale {
    locale: 'en-IN',
    numberingSystem: null,
    outputCalendar: null,
    intl: 'en-IN',
    weekdaysCache: { format: {}, standalone: {} },
    monthsCache: { format: {}, standalone: {} },
    meridiemCache: null,
    eraCache: {},
    specifiedLocale: null,
    fastNumbersCached: null
  },
  invalid: Invalid {
    reason: 'unparsable',
    explanation: `the input "Mon Apr 26 2021 11:23:00 GMT+0530 (India Standard Time)" can't be parsed as ISO 8601`
  },
  weekData: null,
  c: null,
  o: null,
  isLuxonDateTime: true
}

```

In the explanation, it is referring to the default format used by the JS `Date` object. How is this possible is beyond my comprehension. Now the only way I am able to create a `DateTime` object is by using the following code :-

`DateTime.fromJSDate(new Date(show.start))`

I am not sure if it is a bug or am I missing on some documentation?

**Comment by icambron** [comment]
It looks to me like `show.start` is just not quite what it appears to be. Certainly, Luxon isn't making up the string it thinks was input to it. Perhaps it's a different kind of object that is merely `toString()`ing to an ISO string your console. No way for me to know, but it doesn't look like a bug in Luxon.

I'm going to close this ticket. If you dig deeper and discover a Luxon issue, feel mention me here and i'll reopen
