### ISSUE TITLE
Luxon setZone throws exception with polyfilled build in IE 11

### ISSUE THREAD

**Issue by v2canopyteam** [moment/luxon#925]
I am trying to set date from object and which is working fine in Chrome but throws the exception "the zone \"America/New_York\" is not supported"  in IE 11.

I am using polyfilled build of luxon downloaded from - https://moment.github.io/luxon/global-filled/luxon.min.js

Code :
```
var luxondate = DateTime.fromObject({
   "year":"date.getFullYear()",
   "month":"parseInt(month)",
   "day":"parseInt(day)",
   "hour":0,
   "minute":0,
   "zone":"America/New_York"
})
```

**Comment by icambron** [comment]
See the feature support matrix: https://moment.github.io/luxon/docs/manual/matrix.html
