### ISSUE TITLE
Missing 1.27.0 version on NPM

### ISSUE THREAD

**Issue by RodolfoSilva** [moment/luxon#934]
**Describe the bug**
The latest version of luxon is missing from NPM

**To Reproduce**
Check the [npm][npm-url] package or this badge state [![NPM version][npm-version-image]][npm-url]

**Actual vs Expected behavior**
Version 1.27.0 should be available to install with 1.27.0

**Desktop (please complete the following information):**

- OS: OSX
- Browser Chrome
- Luxon version 1.27.0

[npm-url]: https://npmjs.org/package/luxon
[npm-version-image]: https://badge.fury.io/js/luxon.svg

**Comment by icambron** [comment]
Thanks. Fixed.
