### ISSUE TITLE
Cast to date

### ISSUE THREAD

**Issue by adamreisnz** [moment/luxon#935]
**Is your feature request related to a problem? Please describe.**
With moment, when we would pass a moment instance to our database, it would get cast to a JS Date object correctly. WIth Luxon however, it seems this doesn't work and unless we explicitly convert using `.toJSDate()` the database gets angry.

**Describe the solution you'd like**
Ideally, if a `DateTime` object is coerced to a `Date`, it would convert itself to a javascript Date object.

**Describe alternatives you've considered**
Using `.toJSDate()` in every single location where we convert DateTime to a database property, which would require us to add this in hundreds of locations.

Alternatively, the database driver also checks if objects have a converter `toBSON()`. If that could be implemented which would return a JS Date object that'd be great too.

**Comment by icambron** [comment]
I don't know how your database driver is deciding to coerce Moment objects into JS Date objects, so I don't know how to translate your request into a change to Luxon. Can you be more specific about what you want to change in Luxon?

As for BSON, Luxon does implement `toBSON`: https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#instance-method-toBSON, implementation is what you'd expect: https://github.com/moment/luxon/blob/043f2b9a217a855b760a04ea3a25015ff6d83a42/src/datetime.js#L1733

**Comment by adamreisnz** [comment]
Thank you @icambron, I must have missed the `toBSON` method in the documentation, I looked for it but couldn't find it at first glance. I had another chat with our team and the issue they had could no longer be replicated. I was also not able to replicate it myself, and casting seemed to work as expected.

I will close this off as an environmental issue, thank you.
