### ISSUE TITLE
en-GB short date's not formatted correctly in node

### ISSUE THREAD

**Issue by itsravenous** [moment/luxon#936]
**Describe the bug**
Formatting short dates during a jest test for en-GB results in `mm/dd/yyyy`. I have installed `full-icu` and provided it to node via env as described here: https://github.com/moment/luxon/issues/573#issuecomment-532952325.

**To Reproduce**
Please share a minimal code example that triggers the problem:

**test.js**
```js
it("displays the provided date in the user's locale", () => {
  Settings.defaultLocale = "en-GB";

  const date = new Date(Date.UTC(2020, 11, 20));
  const time = DateTime.fromJSDate(date).toLocaleString({
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });

  expect(time).toEqual("20/12/2020"); // This fails
});
```

I have tried passing `DateTime.DATE_SHORT` to `toLocaleString` as well, with the same result.

This works fine in my browser (Firefox)

**Actual vs Expected behavior**
**Expected:** Date to be formatted to `20/12/2020`
**Actual:** Date to be formatted to `12/20/2020`

**Desktop (please complete the following information):**

- OS: **Linux**
- Browser: **Node**
- Luxon version **1.2.6**

**Additional context**
I am sure the `full-icu` data is available to node, as setting the locale to `de-DE` gives the correct format (`20/12/2020`)

**Comment by icambron** [comment]
Works ok for me:

```js
> DateTime.fromJSDate(date).toLocaleString({
...     year: "numeric",
...     month: "2-digit",
...     day: "2-digit",
...   })
'19/12/2020' // my time zone puts this on a different date, but the point is that the format is right
```

What version of Node?

**Comment by itsravenous** [comment]
I've tested on another machine with the same version of node (12.19.0) and it works fine, so I think we can chalk this up to something funky on the settings on the first machine 🤷 

Thanks for checking it out!
