### ISSUE TITLE
StartOf('week') always return Monday

### ISSUE THREAD

**Issue by NSLog0** [moment/luxon#939]
I been creating a calendar by using date from luxon. My calendar has a feature to change the background of each date box if it `.hasSame(d, 'weeks')` return true. let say today is 18 May my expectation when I call `hasSame(d, 'weeks')` is to return true on 16 May to 22 May but actual is 17 May to 23 May have been highlighted. 

Anyone can help me to correct the result and what API should I call. I been tried `.set({{ weekday: 7})` still got a same result
<img width="331" alt="Screen Shot 2564-05-18 at 14 00 16" src="https://user-images.githubusercontent.com/1640817/118606237-6120db80-b7e1-11eb-9f04-881b2e2fa5d1.png">

**Comment by mTdev1** [comment]
Think about it for a second.
May 16 in this case would be day of a last week.
But I heard that Germany considers Sunday to be the first day of the week. So maybe try .setLocale('de') or smth.

**Comment by icambron** [comment]
Luxon uses the ISO week calendar, where weeks start on Monday.

We'd love to support local weeks, but the Intl API doesn't currently have the ability to tell us when, say, Germany starts its weeks. The relevant proposal is here: https://github.com/tc39/proposal-intl-locale-info

**Comment by NSLog0** [comment]
@mTdev1 I tried but I still got same result the orange background didn't cover to 16

**Comment by NSLog0** [comment]
@icambron thanks for the information

**Comment by Wernfried** [comment]
> Think about it for a second. May 16 in this case would be day of a last week. But I heard that Germany considers Sunday to be the first day of the week. So maybe try .setLocale('de') or smth.

That's clearly not the case. In Germany week starts on Monday, according to standard EN 28601 which is according to ISO 8601.
But it also shows, this is not a trivial topic.
