### ISSUE TITLE
week parsing should allow years (but not month and day)

### ISSUE THREAD

**Issue by jcompagner** [moment/luxon#940]
if you have a format like: 

W-yyyy

and you change the week number you get this when parsing it:

Error: Can't mix weekYear/weekNumber units with year/month/day or ordinals
    at Function.fromObject (luxon.js:6645)
    at parseDataToDateTime (luxon.js:6135)
    at Function.fromFormat (luxon.js:6841)
    at FormattingService.push.N7Z2.FormattingService.unformat (formatting.service.ts:110)
    at FormatDirective.push.bdAw.FormatDirective.input (formatcontrolvalueaccessor.directive.ts:101)
    at FormatDirective_change_HostBindingHandler (formatcontrolvalueaccessor.directive.ts:40)
    at executeListenerWithErrorHandling (core.js:15265)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:15303)
    at HTMLInputElement.<anonymous> (platform-browser.js:582)
    at ZoneDelegate.invokeTask (zone.js:434)
core.js:6210 ERROR Error: Invalid date/time value: 22-2021
    at DateConverter.push.01F2.DateConverter.fromClientToServer (date_converter.ts:17)

which is in my eyes wrong, you should be able to have a year with a week,
It would be correct that it would Error out when you have a day or month also specified, because those 2 specify the same thing
But a year doesn't dictate at all the week.

i tried in the debugger flipping the boolean containsGregor to false

 if ((containsGregor || containsOrdinal) && definiteWeekDef) {
      throw new ConflictingSpecificationError("Can't mix weekYear/weekNumber units with year/month/day or ordinals");
    }

so it jumps over that. but that doesn't really work because then it doesn't parse the year.

**Comment by jcompagner** [comment]
hmm i see now you have to use kkkk for the years if you want to use W 
thats really annoying why is there that distinction between the 2 formatting strings for years?
isn't it really displaying in the end if you use kkkk or yyyy the same thing?

**Comment by icambron** [comment]
No, ISO week years aren't the same as gregorian calendar years. https://en.wikipedia.org/wiki/ISO_week_date. The error is there to prevent just this confusion. Often the first or last week of a week year are in a different calendar year, which results in a lot of confusion

**Comment by jcompagner** [comment]
ahh didn't think of that, this is even worse.. :(

Luxon doesn't fix the 2 important things that moment did fix for us... And that is the localization around week/weekdays...

Also this case for first day of the week: 
https://github.com/moment/luxon/issues/373

in moment i could just do:

    const ld = moment.localeData();
    this.firstDayOfWeek = ld.firstDayOfWeek();

to get the actual locales first day of the week (monday for me, sunday for usa)

The same for weeks i guess?
Because yes a week is different in most of Europa (like NL) compared to for example USA
The start of the week rule is different, for us it is where the first Thursday is in (so most of the week, 4 days, need to be in this week). For USA it is where the Sunday is in.
So if 1st of Jan on a Thursday then for us that week is week 1. But for the USA the next week is week 1 because the Sunday before that Thursday is still the previous year.

i kind of expect that a date framework with localization does fix those 2 issues that are kind of the most import things to fix for people. 
In a datetime-calendar that you want to show you should be able to configure 3 things: 12 hour clock (AM/PM) or 24 hour clock, what the first day of the week is, and the week number..

That kind of info i expect to be able to get from a date framework.. But it seems that for at least 2 of them those are not really accurate to get because they both are all based on pure ISO values not actual Locale values.

**Comment by icambron** [comment]
Correct, browser don't currently provide week localization through the Intl API, so Luxon can't either. There's a proposal for it working its way through the standards process, and when it's implemented, Luxon will add it.
