### ISSUE TITLE
toSQL 'space' bug

### ISSUE THREAD

**Issue by dmitrygh** [moment/luxon#941]
toSQL outputs '2020-01-05 16:05:00 +03:00', but mySQL '2020-01-05 16:05:00+03:00' expected with no space before '+'
thank you!

**Comment by icambron** [comment]
I seem to have missed this issue earlier. Sorry about that. I'd take a PR adding an option to `toSQL` that drops the space. I don't know why DB vendors are inconsistent about this.

**Comment by sdotson** [comment]
I've taken a shot at this. See above. Open to any and all feedback!
