### ISSUE TITLE
Get Timezone Offset without creating a Date instance

### ISSUE THREAD

**Issue by binarykitchen** [moment/luxon#942]
is that possible?

Something like

```
IANAZone.create('Pacific/Auckland').getOffset()
```

If I'm displaying a list of time zones for example, there is no need to create date instances. Right?

**Comment by icambron** [comment]
No, you can't do that, and there's a good reason why: in many zones, the offset depends on date. Running with your NZ example:

```js
// NZST
DateTime.fromObject({year: 2021, month: 1, day : 2, zone: "Pacific/Auckland"}).offset // => 780

// NZDT
DateTime.fromObject({year: 2021, month: 6, day : 2, zone: "Pacific/Auckland"}).offset //=> 720
```

So you can see how the zone can't answer the question without any arguments.

The zone interface does let you ask this directly, though it's slightly awkward:

```js
// takes epoch milliseconds
IANAZone.create("Pacific/Auckland").offset(1621433759509) //=> 720

// which you can do by coercing a date time instance
IANAZone.create("Pacific/Auckland").offset(+DateTime.now()) //=> 720

// or by coercing a JS Date instance
IANAZone.create("Pacific/Auckland").offset(+new Date()) //=> 720
```

**Comment by binarykitchen** [comment]
Good points, thanks mate
