### ISSUE TITLE
toLocaleString with en-GB locale shows 12:00 pm as 00:00 pm

### ISSUE THREAD

**Issue by Acidic9** [moment/luxon#945]
**Describe the bug**
Using toLocaleString with a time in `12:xx pm`, it returns it as `00:xx pm`

**To Reproduce**
```js
const ms = 1621650844983;
const dateTime = DateTime.fromMillis(ms);
const localeString = dateTime.toLocaleString({
  hour: "2-digit",
  minute: "2-digit",
  hour12: true,
  locale: "en-GB"
});
```
Results in `00:04 pm`.

[CodeSandbox](https://codesandbox.io/s/luxon-js-invalid-time-example-q3rt2)

**Actual vs Expected behavior**
The above example prints `00:04 pm` while I expect `12:04 pm`. Changing the locale to en-US has the correct output.

**Desktop (please complete the following information):**

- OS: Mac OS Big Sur
- Browser: Chrome
- Luxon version: 1.27.0

**Comment by icambron** [comment]
Fixed in 2.0

**Comment by victorheid** [comment]
@icambron This issue is fixed on 2.0.0, but its broken from 2.0.2 ahead

**Comment by icambron** [comment]
@victorheid You now have to use `hourCycle: h12` instead of `hour12: true`. This is because the browsers actually changed how they handle this:

```js
const date = new Date(2022, 7, 1, 12, 4)
new Intl.DateTimeFormat("en-GB", { hour: "2-digit", hour12: true }).format(date) // => '00 pm'
new Intl.DateTimeFormat("en-GB", { hourCycle: "h12", hour: "2-digit" }).format(date) //=> '12 pm'
```

Luxon used to try to work around this with some logic, but the logic caused other bugs, so we decided to just let the options through to Intl.

**Comment by victorheid** [comment]
@icambron ah ok. Thanks for letting me know - That was a head-scratcher!
