### ISSUE TITLE
Double up of unit specification when trying to query a difference between two DateTime objects

### ISSUE THREAD

**Issue by adamreisnz** [moment/luxon#947]
**Is your feature request related to a problem? Please describe.**
To me, it seems like a flaw in the API if we have to double up and specify the unit for the difference between to DateTime objects twice:

Consider two DateTime objects:

```js
const earlier = DateTime.now().minus({days: 1, hours: 3}) 
const later = DateTime.now().plus({days: 5, hours: 2})
```

As far as I can tell from the documentation, this is the way to get the number of days between the two dates:

```js
const duration = later.diff(earlier, 'days')
const {days} = duration
```

So we first need to specify that we want the difference in days by passing in the `days` unit into `diff()`, and then we need to extract the days from the resulting Duration object.

I find this a bit redundant, as I've already passed in the `days` unit into the `diff()` method, so it feels like a double up having to extract the days again from a resulting object.

Moreover, if you want to get the hours or any other unit from that same duration, it won't work:

```js
const duration = later.diff(earlier, 'days')
const {hours} = duration //hours will be 0
```

This is confusing, because if a Duration object is returned, it would be assumed that that Duration object has all available units of duration available for querying, which it seems that it doesn't. Instead, a duration seems to only contain the duration of the unit that you asked for.

So if all the other values are 0, why doesn't diff just return a Number instead?

**Describe the solution you'd like**
To maintain the current API and return a Duration, I would expect the following to work:

```js
const duration = later.diff(earlier) //Not passing in a unit
const {days, hours, minutes} = duration //All units of duration are available for querying
```

Or if passing in a unit, I would expect the resulting value to be a number so I don't need to specify the unit a 2nd time:

```js
const days = later.diff(earlier, 'days')
```

**Additional context**
It could be that I'm missing something, so I'll be happy to be proven wrong if what I'm proposing is inferior to the current approach. However, I always value efficiency, and having to specify the same unit twice smells like inefficiency to me, hence why I thought I'd raise it.

**Comment by icambron** [comment]
Durations can contain more than one unit. E.g. try `later.diff(earlier, "days", "hours")`. A duration is at heart a bag of units and their values, as in "5 days, 6 hours, 2 minutes,  and 1 second". You created a duration with just one unit (which is fine), and you seem to be interpreting the other available units as *conversions*, as opposed to just values not specified in the duration.

Of course Luxon supports converting between sets of units too (via the `shiftTo()` method), but it's a complicated thing (e.g. how many days is a month?), so you have to do it explicitly.
 
This may help:

```js
const now =  DateTime.now()
const earlier = now.minus({days: 1, hours: 3}) 
const later = now.plus({days: 5, hours: 2});

const dur = later.diff(earlier, ["days", "hours"]);

// this represents the units in that diff
dur.toObject() //=> { days: 6, hours: 5 }
const {days, hours} = dur
days //=> 6
hours //=> 5

// you may want as()?
dur.as("days") //=> 6.208333333333333 
dur.as("minutes") //=> 8940

// ok, but I want to *convert* it to other units:
dur.shiftTo("months", "hours").toObject() //=> { months: 0, hours: 149 }
dur.shiftTo("minutes", "seconds").toObject() //=> { minutes: 8940, seconds: 0 }
// compare this to just pulling out the days value
dur.shiftTo("days").toObject() //=> { days: 6.208333333333333 }

// diff is not the only way to create durations:
const dur2 = Duration.fromObject({ days: 1, hours: 2});
dur2.days //=> 1
dur2.hours //=> 2
dur2.minutes //=> 0, since it's not part of it
```

**Comment by adamreisnz** [comment]
Thanks, that sheds some more light on it. So basically unless you specify what units you want a duration in, these will not be available in the resulting duration object.

Am I correct in understanding that if multiple units are provided, it will round down the higher value units accordingly?

e.g.

```js
const now =  DateTime.now()
const earlier = now.minus({days: 1, hours: 3}) 
const later = now.plus({days: 5, hours: 2});

const dur1 = later.diff(earlier, ["days", "hours"]);
const dur2 = later.diff(earlier, 'days');

dur1.toObject() //=> { days: 6, hours: 5 }
dur2.toObject() //=> { days: 6.2083333 }
```

**Comment by icambron** [comment]
Yup, the decimals go in the lowest-order slot
