### ISSUE TITLE
isValid returns true on an invalid date (0021-05-26)

### ISSUE THREAD

**Issue by AidanHak** [moment/luxon#948]
**Describe the bug**
The isValid value does not validate date strings properly.

**To Reproduce**
Please share a minimal code example that triggers the problem:
`luxon.DateTime.fromString('0020-05-28', 'yyyy-mm-dd').isValid`

**Actual vs Expected behavior**
The value of `isValid` should be false, but instead it returns true.

**Desktop (please complete the following information):**

- OS: Windows 10 21H1
- Browser: Edge Chromium 90
- Luxon version: 1.27

**Comment by icambron** [comment]
I guess I'm missing something: why is that an invalid date?

**Comment by AidanHak** [comment]
0020 is not a valid year

It's a mistake the user makes when filling out a date input field. I'm trying to validate with luxon.

**Comment by icambron** [comment]
That is a valid year: AD 20, about 2000 years ago, expressed as yyyy. That might not be a valid entry for your form but that's business logic, not date parsing.

**Comment by AidanHak** [comment]
SQL doesn't seem to like it when I try to insert that date into a field. I guess I'll figure something else out.
