### ISSUE TITLE
Node package 1.27.0 possibly missing the ES6/ESM build

### ISSUE THREAD

**Issue by lukepuplett** [moment/luxon#953]
**Describe the bug**
I think the npm package 1.27.0 is missing the ES6/ESM version.

Your "Install guide" neglects to discuss the npm package folders and how to use them, which is probably obvious to front-end developers but I'm a beginner.

In desperation I then looked to download the ES6 version as linked on the install guide and I noticed it has "es6" in its URL while the browser download has "global" and AMD has "amd" which match up with the build folders in the npm package.

So I assume there should also be an `es6` build in the package, too?!

**To Reproduce**
I have this in the top of my `.ts` file.

`import { DateTime } from "luxon";`

Which is transpiled by TypeScript and a little custom Gulp turns it into this:

`import { DateTime } from "../lib/luxon/build/cjs-browser/luxon.js";`

(I've tried also `/global/` build)

Chrome gives me this error:

> Uncaught SyntaxError: The requested module '../lib/luxon/build/cjs-browser/luxon.js' does not provide an export named 'DateTime'

TypeScript is happy to compile it, VS Code gives me intellisense.

**Actual vs Expected behavior**
Since VS Code is happy, and the path to the `.js` file is good and Chrome's module loader finds it, I expected the code to run.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Version 91.0.4472.77 (Official Build) (64-bit)
- Luxon version: 1.27.0

**Comment by icambron** [comment]
We can add the es6 build to the Node package, yeah.

**Comment by lukepuplett** [comment]
Yeah only if you agree it makes sense. I'm not a JS/front-end developer so I could be talking nonsense, but I'm guessing it would help web developers targeting modern ESM-compatible browsers if there was a single, large ES6 .js file in the package.

**Comment by icambron** [comment]
Yup, I agree. I made the change in 2.0
