### ISSUE TITLE
Add option to change start of week to Sunday

### ISSUE THREAD

**Issue by caseydriscoll** [moment/luxon#954]
I'm an American working on a personal finance project. For me personally, Sunday is the first day of the week and I'd like to have any Sunday to be `datetime.weekday == 1` instead of `datetime.weekday == 7`

This at first seemed like an obvious and simple request, but these Wiki pages shed a lot of info on 8601. Curious to know how easy this would be!

https://en.wikipedia.org/wiki/Week
https://en.wikipedia.org/wiki/ISO_week_date

**Comment by icambron** [comment]
I'm American too and find this frustrating, but the Intl API doesn't support what's-this-locale's-start-of-week, so there's no way for Luxon to look that up. See, e.g. #939.

Note that when Intl adds support for this and we implement it in Luxon, it won't likely change the behavior of `datetime.weekday`, but rather some new field, like `localWeekday`

**Comment by mdom95** [comment]
@icambron Has there been any development on this? It seems the Intl API now supports looking up start-of-week based on locale: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo

Not sure when it was added.

**Comment by icambron** [comment]
@mdom95 There isn't. I'd take a PR for it though

**Comment by DNA-PC** [comment]
This seems to be available now, although I haven't seen it documented yet
https://github.com/mui/mui-x/issues/12821#issuecomment-2061782173

**Comment by ozair-dev** [comment]
> update:
> 
> const utcDate = '2024-12-09T02:03:30.419+02:00' // Use the commented date
> 
> const now = DateTime.fromISO(utcDate, { locale: 'he' }).setZone(DEFAULT_TIMEZONE)
> 
> const startOfWeek = now.startOf('week', { useLocaleWeeks: true }).toISO()
> const endOfWeek = now.endOf('week', { useLocaleWeeks: true }).toISO()

this works on every browser except for firefox

**Comment by chiq2045** [comment]
I can confirm that this does not work on Firefox. For anyone who might want more information, or a workaround, view #1563
