### ISSUE TITLE
Documentation for toLocaleString has a buggy and misleading example

### ISSUE THREAD

**Issue by SystemParadox** [moment/luxon#955]
The [documentation for toLocaleString](https://moment.github.io/luxon/docs/manual/formatting#tolocalestring--strings-for-humans-) states that "This also means you can modify the presets as you choose", with the following example:

```
dt.toLocaleString(DateTime.DATE_SHORT); //=>  '4/20/2017'
var newFormat = Object.assign(DateTime.DATE_SHORT, { weekday: 'long' });
dt.toLocaleString(newFormat); //=>  'Thursday, 4/20/2017'
```

This example is misleading and leads to confusing bugs - the `Object.assign` is actually modifying `DateTime.DATE_SHORT`, which means that future calls using `DateTime.DATE_SHORT` also use the changed version:

```
dt.toLocaleString(DateTime.DATE_SHORT); //=>  '4/20/2017'
var newFormat = Object.assign(DateTime.DATE_SHORT, { weekday: 'long' });
dt.toLocaleString(newFormat); //=>  'Thursday, 4/20/2017'
dt.toLocaleString(DateTime.DATE_SHORT); // Expected '4/20/2017', got 'Thursday, 4/20/2017'!
```

If the example is trying to show that you can create your own formats derived from an existing format then it should be changed to assign to an empty object like this:

```
dt.toLocaleString(DateTime.DATE_SHORT); //=>  '4/20/2017'
var newFormat = Object.assign({}, DateTime.DATE_SHORT, { weekday: 'long' });
dt.toLocaleString(newFormat); //=>  'Thursday, 4/20/2017'
```

If the example is trying to show that you can customise the global formats then it should always use the global reference and not create a misleading `newFormat` variable:

```
dt.toLocaleString(DateTime.DATE_SHORT); //=>  '4/20/2017'
Object.assign(DateTime.DATE_SHORT, { weekday: 'long' });
dt.toLocaleString(DateTime.DATE_SHORT); //=>  'Thursday, 4/20/2017'
```

Thanks.

**Comment by icambron** [comment]
Yeah, I noticed that when updating to 2.0 and just switched to using spread anyway.
