### ISSUE TITLE
Easy getters to check if date is in the future or in the past

### ISSUE THREAD

**Issue by adamreisnz** [moment/luxon#957]
**Is your feature request related to a problem? Please describe.**
Most of the date comparisons we work with, deal with comparing a certain date to "now", to see if something has expired or not for example. Currently, the simplest way I can see of doing this with Luxon is something like:

```js
const isPast = DateTime.now() > DateTime.fromJSDate(date)
```

I find the need to always instantiate another date time instance to `now()` quite cumbersome.

**Describe the solution you'd like**
Would it be viable to create simple instance getters like `isPast` and `isFuture` to make this common check simpler to perform?

```js
const {isPast} = DateTime.fromJSDate(date)
```

or

```js
const date = DateTime.fromJSDate(jsDate)
if (date.isPast) {
  //...do something
}
```

**Describe alternatives you've considered**
I reviewed the documentation to see if something similar was already available but couldn't find anything.

**Comment by icambron** [comment]
This is easy to add in userspace:

```js
DateTime.prototype.isInFuture = function() { return +this > +new Date();};
DateTime.prototype.isInPast = function() { return +this < +new Date();};

DateTime.now().isInFuture() //=> false
DateTime.now().plus({minutes: 1}).isInFuture() // => true
```

You can't really do it without instantiating another date somewhere (whether hidden from you or not) because Luxon wouldn't otherwise know the current time.

In general, I'm hesitant to add little convenience features that are easy to make

**Comment by adamreisnz** [comment]
All good, I was trying to avoid hacking into the prototyped because that
might easily break and derail our app in the future. However, will do what
you suggested in this case.

**Comment by icambron** [comment]
It's mostly safe if you only use public methods, though of course if you wanted you could also just wrap it like `isInFuture(dateTime)`
