### ISSUE TITLE
Intersection and union of (arrays of arrays of) intervals

### ISSUE THREAD

**Issue by robocop6** [moment/luxon#961]
I'm having a look at the [Interval documentation](https://moment.github.io/luxon/docs/class/src/interval.js~Interval.html) to solve this problem.

Given the following array:

```
const myIntervals = [
  [
    Interval.fromDateTimes({ hour: 0 }, { hour: 10 })
  ],
  [
    Interval.fromDateTimes({ hour: 2 }, { hour: 4 }),
    Interval.fromDateTimes({ hour: 9 }, { hour: 11 }),
    Interval.fromDateTimes({ hour: 13 }, { hour: 14 }),
  ]
]
```

I'd like to compute the following:

- The intersection of those intervals, i.e. an array of intervals that contains only the intervals shared between `myIntervals[0]` and `myIntervals[1]`. In this case, the array should have two intervals that represent "from hour 2 to hour 4" and "from hour 9 to hour 10".
- The union of those intervals, i.e. the minimal array of intervals that are present either in `myIntervals[0]` or `myIntervals[1]` should be also an array of two intervals: "from hour 0 to hour 11" and "from hour 13 to hour 14". **EDIT: this corresponds to `Interval.merge(myIntervals.flat())`**

Of course, this should work for an arbitrary number of intervals (the input is of type `Interval[][]`).

Is there a simple way of doing this? I could code a solution myself, but it would be nice to use some built-in logic, if any.

**Comment by icambron** [comment]
Nothing built in for that `intersection` case, no. But it's pretty straightforward:

```js
const intersectingArrays = (arr) =>
  arr.reduce((i1, i2) =>
    i1 ?
      Interval.merge(i1.flatMap(e1 => i2.map(e2 => e1.intersection(e2))).filter(n => n)) :
      i2);

intersectingArrays(myIntervals).map(i => i.toISO()); // =>

// [
//  '2021-06-24T02:00:00.000-04:00/2021-06-24T04:00:00.000-04:00',
//  '2021-06-24T09:00:00.000-04:00/2021-06-24T10:00:00.000-04:00'
// ]

```

Probably doesn't perform well for large arrays. Also, I'm a little annoyed that I had to put in that `filter`, which is because `merge` doesn't handle nulls (it should).

Anyway, that's a little complicated, but it's a complicated use case! So I think I'm comfortable with the status quo.
