### ISSUE TITLE
Add support for Moment's fractional second tokens `S` and `SS` 

### ISSUE THREAD

**Issue by dasa** [moment/luxon#965]
**Is your feature request related to a problem? Please describe.**
I'm using Moment's fractional second [format](https://momentjs.com/docs/#/displaying/format/) tokens `S` and `SS` and looking for the equivalent in the DateTime's `toFormat` function.

**Describe the solution you'd like**
`SSS` is already supported and Luxon already supports this as either `SSS` or `u`. Maybe it can add `uu` and `uuu`, where `uu` is equivalent to `SS` and `uuu` is equivalent to `S`.

**Comment by icambron** [comment]
They are supported as `S` and `SSS`, unless I'm misunderstanding the request: https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens

**Comment by dasa** [comment]
`lux.DateTime.fromJSDate(new Date()).toFormat("S")` -> `415`, but in Moment, it's a number between 0 and 9.

`lux.DateTime.fromJSDate(new Date()).toFormat("SS")` -> `SS`, but in Moment, it's a padded number between 0 and 99.

**Comment by dasa** [comment]
This appears to be the `moment` implementation: 

https://github.com/moment/moment/blob/e96809208c9d1b1bbe22d605e76985770024de42/src/lib/units/millisecond.js#L19-L25

**Comment by dasa** [comment]
I've started a PR at #976, but I could use some advise on how to handle `fromFormat`. Please let me know if I'm on the right track or if there's any changes you'd like.

**Comment by dasa** [comment]
I've added parsing support to the PR.
