### ISSUE TITLE
Node version installs ~350 dependencies

### ISSUE THREAD

**Issue by maxnordlund** [moment/luxon#97]
It's odd as the package.json doesn't include any normal dependencies. I tried installing in a fresh directory using both npm (334) and yarn (362). I'm not sure _why_ it does that though, moment installs just fine without any dependencies.

**Comment by tuananh** [comment]
it's installing dev dependencies. try `npm install luxon --production`

**Comment by icambron** [comment]
I think this is a bug I've fixed in master. Here is the released package.json. I'm not sure how those deps got into that section https://github.com/moment/luxon/blob/37645a3f74c4d95703e6da4ba39c74e747ce47ea/package.json

**Comment by icambron** [comment]
I just released `0.2.0` and gave it a try and it doesn't seem to install any extra deps. So I think this is fixed.
