### ISSUE TITLE
Bad download links in 'Install Guide'

### ISSUE THREAD

**Issue by moon6969** [moment/luxon#971]
The download links in the 'Install Guide'→'Basic browser setup' section are broken.
https://moment.github.io/luxon/#/install?id=basic-browser-setup

The broken full/minified links are:
https://moment.github.io/luxon/#/../../global/luxon.js
https://moment.github.io/luxon/#/../../global/luxon.min.js

I found the scripts here (hope they are the current version?):
https://moment.github.io/luxon/global/luxon.js
https://moment.github.io/luxon/global/luxon.min.js

**Comment by icambron** [comment]
Thanks, I'm still working out the kinks in the new website. I've fixed this now.

Yes, those are the right URLs
