### ISSUE TITLE
Documentation Site is down since days..

### ISSUE THREAD

**Issue by SO-Eng** [moment/luxon#972]
When will the documentation available again?
Site is not reachable since yesterday for me. Maybe longer... Did not used it last week.

https://moment.github.io/luxon/docs/manual/install.html

**Comment by icambron** [comment]
Yeah, I moved around the docs as part of 2.0. The links in the readme are updated to go here: https://moment.github.io/luxon

**Comment by vially** [comment]
I think part of the problem is that [most Google searches](https://www.google.com/search?q=luxon+documentation) still point to the old documentation URLs which throw 404 errors now.

The good news is that this should only be temporary (hopefully) and once the new docs are properly indexed most of the confusion will go away.

**Comment by MikeyBurkman** [comment]
@icambron Is there a link anymore to the 1.x docs? I'm not sure when we'll be able to fully upgrade to 2.0.

**Comment by jakebiesinger-storyhealth** [comment]
Not to mention stackoverflow and lots of other sites that point to the old docs and now give 404's :(

**Comment by SO-Eng** [comment]
I guess there should be default site with forward link to new Documentation?

> Not to mention stackoverflow and lots of other sites that point to the old docs and now give 404's :(

**Comment by wiegell** [comment]
> @icambron Is there a link anymore to the 1.x docs? I'm not sure when we'll be able to fully upgrade to 2.0.

+1
Until then: https://web.archive.org/web/20210116144907/https://moment.github.io/luxon/docs/manual/tour.html

**Comment by icambron** [comment]
Sorry guys, it's impractical for me to host multiple versions of the docs, and the documentation mechanism has been totally reworked. I think Archive.org is the way to go. You can also check out the 1.x source code and build the doc site locally.
