### ISSUE TITLE
IANAZone.isValidZone(undefined) returns true

### ISSUE THREAD

**Issue by mscheper** [moment/luxon#973]
**Describe the bug**
A call to `IANAZone.isValidZone(zone)`, where `zone` is undefined, returns **`true`**. This is unexpected and undocumented.

**To Reproduce**
Please share a minimal code example that triggers the problem:

```js
const zone = undefined;
console.log(IANAZone.isValidZone(zone)); // true
```

**Actual vs Expected behavior**
I would expect this function to return `false` for an undefined zone.

**Desktop (please complete the following information):**

- OS: Mint 19
- Browser: Chrome 91
- Luxon version: 1.27.0
- Your timezone: America/New_York

**Comment by socraticDevBlog** [comment]
@icambron this open issue seems to have been fixed and ready to be closed, no?  i'm shopping for a bug to fix this morning ;)

**Comment by icambron** [comment]
Sure, thanks
