### ISSUE TITLE
fromFormat doesn't work for single digit days unless explicitly requested.

### ISSUE THREAD

**Issue by gcaseycupp** [moment/luxon#975]
fromFormat doesn't work for single digit days when format is 'dd' 

//Works
test("DateTime.fromFormat() allows literals", () => {
  const i = DateTime.fromFormat("Mar 13, 2020", "MMM dd, yyyy");
  expect(i.day).toBe(3);
});

//Works
test("DateTime.fromFormat() allows literals", () => {
  const i = DateTime.fromFormat("Mar 3, 2020", "MMM d, yyyy");
  expect(i.day).toBe(3);
});

//Does not work
test("DateTime.fromFormat() allows literals", () => {
  const i = DateTime.fromFormat("Mar 3, 2020", "MMM dd, yyyy");
  expect(i.day).toBe(3);
});

Expected behavior is 'dd' should work regardless of whether date is single digit or 2. (verified that is how it works w/ moment)

**Comment by icambron** [comment]
No, that's not the expected behavior; the expected behavior is that the input format match the format you asked it too.

If you're comparing to Moment, Luxon't behavior is closer to Moment's `strict` parsing mode:

```js

// Moment has non-strict parsing by default
moment('24 4 2019', "DD MM YYYY").isValid() //=> true

// third arg is strictness
moment('24 04 2019', "DD MM YYYY", true).isValid() // => true
moment('24 4 2019', "DD MM YYYY", true).isValid() //=> false
```
