### ISSUE TITLE
Cannot find a table of tokens and their interpretations for fromFormat 

### ISSUE THREAD

**Issue by thefertilitypartners** [moment/luxon#977]
**Describe the bug**
Cannot find a table of tokens and their interpretations for fromFormat, the link in the API docs returns a 404 as well.

**To Reproduce**
Visit https://moment.github.io/luxon/api-docs/index.html#datetimefromformat
Click **fromFormat(text, fmt, opts)** on the right
Click **Here** button in the description
get a 404 page

**Actual vs Expected behavior**
Documentation in table form for date tokens used by luxon fromFormat

**Desktop (please complete the following information):**

- OS: Kubuntu
- Browser Chrome
- Luxon version 1.27.0
- Your timezone Canada/Ontario

**Additional context**
none.

**Comment by icambron** [comment]
Thanks, fixed
