### ISSUE TITLE
2.0 not published?

### ISSUE THREAD

**Issue by ianwremmel** [moment/luxon#981]
**Describe the bug**

All documentation for 1.0 seems to be gone, but 2.0 doesn't seem to be available on npm.

**To Reproduce**

```bash
npm i luxon@latest
```

**Actual vs Expected behavior**

I expect to get luxon 2.0 but I get luxon 1.28.0.

**Desktop (please complete the following information):**

- OS: macOs
- Browser n/a
- Luxon version 1.28.0
- Your timezone "America/Los_Angeles"

**Comment by ianwremmel** [comment]
I just found https://github.com/moment/luxon/issues/974 which says it's fixed, but 2.0 is not listed at https://www.npmjs.com/package/luxon.

**Comment by ianwremmel** [comment]
wait, my apologies. 2.0 has been published, but 1.28.0 is the one that's tagged as latest.

Can either that `latest` tag be changed or can the docs make it clear that 2.0 ha to be explicitly installed and `latest` will continue to point at 1.0?

**Comment by icambron** [comment]
Ugh, yeah, it's because I had a publishing snafu and ended up publishing 1.28.0 after 2.0, and the automation tagged the most recent one with `latest`. I guess I'll just publish 2.0.1 and let that fix itself

**Comment by icambron** [comment]
Should be good now.

**Comment by ianwremmel** [comment]
Thanks! For future reference, I _think_ you can use `npm tag` to repoint latest to an existing release.
