### ISSUE TITLE
Docs: Info.features doc lists keys which were removed in 2.0

### ISSUE THREAD

**Issue by dasa** [moment/luxon#982]
**Describe the bug**
Doc https://moment.github.io/luxon/api-docs/index.html#infofeatures lists the keys as `intl`, `intlTokens`, `zones`, `relative`, but only `relative` is supported in 2.0.

**To Reproduce**

**Actual vs Expected behavior**
Expected: Doc only lists `relative`.

**Additional context**

Source:

https://github.com/moment/luxon/blob/d4fcbfc4337db0f683f86450e1f89522d94e800e/src/info.js#L158-L171

**Comment by icambron** [comment]
Yeah,, those need removed

**Comment by icambron** [comment]
done
