### ISSUE TITLE
Docs site down?

### ISSUE THREAD

**Issue by csicky** [moment/luxon#984]
In VS Code, in a documentation popup, I click on the link https://moment.github.io/luxon/docs/manual/formatting.html#table-of-tokens and points to 404.

**Comment by mceachen** [comment]
Try https://moment.github.io/luxon/ (looks like they switched to a new docs generator)

**Comment by dasa** [comment]
The URLs may need to be updated at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/datetime.d.ts

**Comment by csicky** [comment]
I just wanted to let you know, I will close this now. 
THX
