### ISSUE TITLE
Luxon equivalent to moment.tz.guess()

### ISSUE THREAD

**Issue by heath-freenome** [moment/luxon#993]
**Is your feature request related to a problem? Please describe.**
I am converting from moment to luxon and we have code that is using the `moment-timezone` package as follows to take a string and convert it to the current user's timezone:

```
  const dateTxt = date.toISOString();
  const tz = moment.tz.guess();
  return moment(dateTxt).tz(tz).format(stringFormat);
```

**Describe the solution you'd like**
Is there an analogous capability to `moment.tz.guess()` that I can use in Luxon?

**Describe alternatives you've considered**
none

**Comment by icambron** [comment]
No, there's so such capability. Luxon doesn't have access to the list of supported time zones supported in the environment, so there's not really a way to implement this. It would make a good plugin that carried a manually curated list of zones known to be widely support, built a sort of index of the offsets out of them, and then used them to implement `guess()`, but that can't really go into the core library.

**Comment by heath-freenome** [comment]
so could there be `luxon-timezone` package?

**Comment by dasa** [comment]
> Is there an analogous capability to `moment.tz.guess()` that I can use in Luxon?

I may be missing something, but this appears similar to `luxon.DateTime.local().zoneName`

Reference: https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/
