### ISSUE TITLE
Feature for startOf('week') to start from Sunday, not Monday

### ISSUE THREAD

**Issue by adelivuk** [moment/luxon#994]
Hi,

I know this is dupe of #373 but can it be possible to add a feature that can be used that `.startOf('week')` starts from Sunday?

Currently I'm using the current day in month and weekday to see if the starting week's day is Sunday.

I believe it would help a lot of people.

Thanks in front

**Comment by icambron** [comment]
Sorry, no, I'm not going to implement this until [this proposal](https://tc39.es/proposal-intl-locale-info/) is widely available

**Comment by MinSomai** [comment]
update: 
```js
const utcDate = '2024-12-09T02:03:30.419+02:00' // Use the commented date

const now = DateTime.fromISO(utcDate, { locale: 'he' }).setZone(DEFAULT_TIMEZONE)

const startOfWeek = now.startOf('week', { useLocaleWeeks: true }).toISO()
const endOfWeek = now.endOf('week', { useLocaleWeeks: true }).toISO()
```
