### ISSUE TITLE
DateTime.fromObject({ zone}) throws "Invalid unit zone" error in React with Luxon v2.0.1

### ISSUE THREAD

**Issue by jadamduff** [moment/luxon#996]
When using Luxon 2.0.1 with React,

`DateTime.fromObject({ hour: 15, zone: "America/New_York" })`

throws an 'Invalid unit zone' error.

This bug doesn't seem to exist in previous versions of Luxon.

![Screenshot 2021-07-23 134654](https://user-images.githubusercontent.com/22721175/126827690-dc78eb02-4b44-433d-8a6d-129b6f7b6f1a.png)

**Comment by icambron** [comment]
Yes, please see the upgrade guide. The zone option now goes in the second argument

**Comment by jadamduff** [comment]
@icambron thanks for the reply! Apologies, I hadn't run across that in the upgrade guide.

Moving zone to the second argument gets rid of the error, but I'm not sure that it's recognizing what is passed in.

![Screenshot 2021-07-24 172940](https://user-images.githubusercontent.com/22721175/126882446-b0c8e8c6-9511-40d3-91ac-122340b6065f.png)

Both of these output the same thing:

![Screenshot 2021-07-24 173119](https://user-images.githubusercontent.com/22721175/126882464-44f9bf18-4bd1-4d0a-830f-3aca4f7e67c6.png)

Shouldn't the second one be -06:00 ?

Also, Typescript doesn't seem to recognize the update the second parameter:

![Screenshot 2021-07-24 172453](https://user-images.githubusercontent.com/22721175/126882505-61764dd9-b65d-4803-b68f-5afbfa4954e5.png)

**Comment by icambron** [comment]
It's like

```js
DateTime.fromObject({ ...units }, { zone: "America/New_York"})
```

So the second arg is an options object, just like the second arg for `fromISO` etc

**Comment by gonzojive** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/luxon/src/datetime.d.ts is out of date - DateTime.fromObject has no second argument in that file.

**Comment by icambron** [comment]
I double-checked and this is pretty well covered by the upgrade guide. I can't help with the Typescript files, sorry.
