### ISSUE TITLE
what does this mean "Only 12-hour if the locale is. "?

### ISSUE THREAD

**Issue by mfaizan1** [moment/luxon#998]
I was working on a project and i had to reset my laptop, before reset i was able to get 12-hour format dates using `DateTime.toLocaleString(DateTime.TIME_WITH_SHORT_OFFSET) `but now it is being returned as 24-hour format, i am wondering how luxon is making this decision internally so that i can make more educated route in fixing my problem.

From docs i can see there is a condition "Only 12-hour if the locale is." to return 12-hour format, i am not sure if it has todo some thing with system date time or loc property in luxon datetime object. if it is later i can see there is loc property with locale set to `en-GB`

```
loc: Locale {
    intl: "en-GB"
    locale: "en-GB"
    .
    .
    .
    .
}

``` 
and for system i have my system time in 12-hour format so in both cases it should return 12-hour format.

if i can have clarification of above mentioned sentence i can further debug my program.

**Comment by icambron** [comment]
Luxon doesn't have direct access to the 24-hour time setting on your computer. It just gets what `Intl` gives it, using your default locale. In your case, you're getting 24-hour time because `en-GB` is set up that way:

```js
new Intl.DateTimeFormat("en-GB", { hour: "numeric"}).format() //=> "14"
new Intl.DateTimeFormat("en-US", { hour: "numeric"}).format() //=> "2 PM"
```

If you want to override the locale-specific behavior and always use 12-hour time, do this:

```js
var format = {...DateTime.TIME_WITH_SHORT_OFFSET, hourCycle: "h12" }

// i need to set the locale, but you wouldn't
DateTime.now().locale("en-GB").toLocaleString(format) // => "2:15:34 pm GMT-4"
```
